{
 "title": "Social Media Report YouTube",
 "description": "Anpassungen September 2024",
 "time": { "from": "2023-08-01T09:02:19.304Z", "to": "2023-09-02T09:02:19.304Z" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Monat",
    "query": {}
   },
   {
    "name": "Jahr",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "Month",
    "query": {}
   },
   {
    "name": "Monat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastMonat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastJahr",
    "query": {}
   },
   {
    "name": "YearFromLastMonth",
    "query": {}
   },
   {
    "name": "stichtagmonat",
    "query": {}
   },
   {
    "name": "Vergleich",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": {}
   },
   {
    "name": "profile_Zeitraum",
    "query": {}
   },
   {
    "name": "Stichtag",
    "query": {}
   },
   {
    "name": "Vormonat",
    "query": {}
   },
   {
    "name": "dataset_suffix",
    "query": {}
   },
   {
    "name": "table_suffix",
    "query": {}
   },
   {
    "name": "last_month",
    "query": {}
   },
   {
    "name": "year_from_last_month",
    "query": {}
   },
   {
    "name": "last_year",
    "query": {}
   },
   {
    "name": "month_from_last_year",
    "query": {}
   },
   {
    "name": "month_as_number",
    "query": {}
   },
   {
    "name": "LRA_mapping",
    "query": {}
   },
   {
    "name": "src_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Hinweise",
   "type": "text",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "- Durch nachträgliche Importe und Speicherung der Daten kann es im Vergleich mit anderen Stichtags-Erhebungen (z.B. den Berichten der Medienforschungen) Abweichungen bei den Daten geben."
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(DISTINCT profile) \n  FROM Quintly_frozen.profiles\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "Letzter Datenstand: </br>\n${stichtagmonat}\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [
         { "name": "total_video_10s_views", "type": "functionParameter" }
        ],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "facebookInsightsOwnVideos"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 4 },
   "options": {
    "content": "# YouTube Report | ${Month}\n\n"
   }
  },
  {
   "title": "Entwicklung: Videostarts für Videos im Zeitraum genutzt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Summe Videostarts für Videos im Zeitraum genutzt (in Mio.)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DATE(jahr,monat,1) as month, SUM(videostarts_zeitraum_genutzt)/1000000 as videoViews10sMill FROM Quintly_frozen.youtube_metrics\r\nWHERE LRA = \"$LRA_mapping\" AND \r\nCASE $month_as_number\r\nWHEN 19 THEN jahr = $Jahr AND monat <= 12\r\nELSE monat <= 12 AND DATE(jahr,monat,1) BETWEEN DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL 1 YEAR) AND DATE($Jahr,$month_as_number,1) END\r\nGROUP BY month\r\nORDER BY month ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 9, "y": 7 },
   "options": {
    "content": "### Anteil Videostarts für Videos im Zeitraum genutzt | Top 8 | $Month\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "options": {
    "content": "### Videostarts für Videos im Zeitraum genutzt (in Mio.)\n"
   }
  },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH top_8_profiles AS(\r\n  SELECT profile, videostarts_zeitraum_genutzt as Views\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY videostarts_zeitraum_genutzt DESC\r\nLIMIT 8\r\n), rest AS(\r\n  SELECT \"Rest\" as profile, SUM(videostarts_zeitraum_genutzt) as Views\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nAND profile NOT IN (SELECT profile FROM top_8_profiles)\r\n)\r\nSELECT REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\nViews FROM(\r\nSELECT profile, Views FROM top_8_profiles\r\nUNION ALL\r\nSELECT profile, Views FROM rest\r\nWHERE CASE \r\nWHEN profile = \"Rest\" THEN Views IS NOT NULL \r\nELSE TRUE END)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 9 },
   "options": {
    "content": "<img \n  src=\"${src_url}\" \n  alt=\"Tracking Pixel\" \n  width=\"1\" \n  height=\"1\" \n  style=\"display:none;\"\n/>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Summe')), 'Summe')\r\nFROM(\r\nSELECT 'Summe' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Ø Pro Tag')), 'Ø Pro Tag')\r\nFROM(\r\nSELECT 'Ø Pro Tag' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" \", $Jahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nSUM(videostarts_zeitraum_genutzt)/1000000 as videoViews10sMill,\r\n(SUM(videostarts_zeitraum_genutzt)/MAX(anzahltage))/1000000 as videoViews10sMillPerDay\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE LRA = \"$LRA_mapping\" AND monat = $month_as_number AND jahr = $Jahr"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CASE $month_as_number\r\n            WHEN 19 THEN \"\"\r\n            ELSE \"$LastMonat_abkuerzung $YearFromLastMonth\"\r\n            END As Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS(\r\n  SELECT\r\nSUM(videostarts_zeitraum_genutzt)/1000000 as past_sum_in_mil,\r\n(SUM(videostarts_zeitraum_genutzt)/MAX(anzahltage))/1000000 as past_sum_per_day\r\nFROM Quintly_frozen.youtube_metrics\r\n  WHERE LRA = \"$LRA_mapping\" AND monat = $last_month AND jahr = $year_from_last_month \r\n), current_value_in_mil AS(\r\n  SELECT\r\nSUM(videostarts_zeitraum_genutzt)/1000000 as current_sum_in_mil,\r\n(SUM(videostarts_zeitraum_genutzt)/MAX(anzahltage))/1000000 as current_sum_per_day\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE LRA = \"$LRA_mapping\" AND monat = $month_as_number AND jahr = $Jahr\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" \", $LastJahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS(\r\n  SELECT\r\nSUM(videostarts_zeitraum_genutzt)/1000000 as past_sum_in_mil,\r\n(SUM(videostarts_zeitraum_genutzt)/MAX(anzahltage))/1000000 as past_sum_per_day\r\nFROM Quintly_frozen.youtube_metrics\r\n  WHERE LRA = \"$LRA_mapping\" AND monat = $month_from_last_year AND jahr = $last_year \r\n), current_value_in_mil AS(\r\n  SELECT\r\nSUM(videostarts_zeitraum_genutzt)/1000000 as current_sum_in_mil,\r\n(SUM(videostarts_zeitraum_genutzt)/MAX(anzahltage))/1000000 as current_sum_per_day\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE LRA = \"$LRA_mapping\" AND monat = $month_as_number AND jahr = $Jahr\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil"
    }
   ]
  },
  { "title": "Abonnenten | ${Month}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Abonnements | Stichtag: $Stichtag ",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, abonnements as Abonnements\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(Abonnements,0) as Abonnements FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY Abonnements DESC"
    }
   ]
  },
  {
   "title": "Veränderung zum ${Vormonat} in %",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nlm.profile,\r\nprofileId,\r\nlm_follower,\r\n(lm_follower/llm_follower - 1)*100 as FollowerVeraenderung\r\nFROM\r\n(\r\nSELECT\r\nprofile, profileId, abonnements as lm_follower\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY abonnements desc\r\n) as lm\r\nLEFT JOIN\r\n(\r\nSELECT\r\nprofile, abonnements as llm_follower\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE \r\nCASE $month_as_number\r\nWHEN 19 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nAND LRA = \"$LRA_mapping\"\r\nORDER BY abonnements desc\r\n) as llm \r\nON llm.profile = lm.profile\r\nORDER BY lm.lm_follower DESC\r\n)\r\nSELECT all_profiles.profile as Profil, IFNULL(FollowerVeraenderung,0) as FollowerVeraenderung FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY lm_follower DESC"
    }
   ]
  },
  {
   "title": "Videostarts für Videos im Zeitraum genutzt |  ${Month}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Videostarts für Videos im Zeitraum genutzt",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, videostarts_zeitraum_genutzt as videoViews\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(videoViews,0) as videoViews FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY videoViews DESC"
    }
   ]
  },
  {
   "title": "Gesamte Wiedergabedauer für Videos im Zeitraum genutzt | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "Gesamte Wiedergabedauer in Stunden für Videos im Zeitraum genutzt",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, sehVolumen_in_std_zeitraum_genutzt as sehVolumen\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(sehVolumen,0) as sehVolumen FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY sehVolumen DESC"
    }
   ]
  },
  {
   "title": "Interaktionen für Videos im Zeitraum genutzt |  ${Month}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "Interaktionen für Videos im Zeitraum genutzt",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, interactions_zeitraum_genutzt as interactions\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(interactions,0) as interactions FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY interactions DESC"
    }
   ]
  },
  {
   "title": "Top Videos nach Videostarts (Videos im Zeitraum genutzt) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 }
  },
  {
   "title": "Top Videos im Zeitraum genutzt | ${Month}",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nProfil,\r\nDatum,\r\nDauer,\r\naverageViewTime,\r\nsehVolumen,\r\ntitle,\r\nviews, \r\nlink,\r\nlikes + dislikes + comments + shares as interactions,\r\naverageViewPercentage,\r\nabo_change,\r\nFROM Quintly_frozen.youtube_top_videos_nach_videostarts_zeitraum_genutzt\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY views DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Top One Video je Kanal (Videos im Zeitraum genutzt) |  $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }
  },
  {
   "title": "Top One Video im Zeitraum genutzt je Kanal | $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DISTINCT\r\n  Profil,\r\n  Datum,\r\n  Titel,\r\n  Wiedergaben,\r\n  link,\r\n  Dauer,\r\nsehVolumen,\r\naverageViewPercentage,\r\nFROM Quintly_frozen.youtube_top_video_je_kanal_zeitraum_genutzt\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY Wiedergaben DESC\r\n"
    }
   ]
  },
  {
   "title": "Zusammenfassung aller Kanäle (Videos im Zeitraum genutzt) | $Monat $Jahr ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 }
  },
  {
   "title": "Zusammenfassung aller Kanäle | $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), current_values AS(\r\nSELECT profile, abonnements as current_abonnements, videostarts_zeitraum_genutzt as current_videostarts_zeitraum_genutzt, sehVolumen_in_std_zeitraum_genutzt as current_sehVolumen_in_std_zeitraum_genutzt, interactions_zeitraum_genutzt as current_interactions_zeitraum_genutzt\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"),\r\npast_values AS(\r\nSELECT profile, abonnements as past_abonnements, videostarts_zeitraum_genutzt as past_videostarts_zeitraum_genutzt, sehVolumen_in_std_zeitraum_genutzt as past_sehVolumen_in_std_zeitraum_genutzt, interactions_zeitraum_genutzt as past_interactions_zeitraum_genutzt\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE CASE $month_as_number\r\nWHEN 19 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nAND LRA = \"$LRA_mapping\"\r\n), joined_data AS(\r\nSELECT * FROM all_profiles\r\nLEFT JOIN \r\ncurrent_values\r\nUSING(profile)\r\nLEFT JOIN \r\npast_values\r\nUSING(profile))\r\nSELECT profile as Profil,\r\ncurrent_abonnements as followers,\r\ncurrent_abonnements - past_abonnements as FollowerVeraenderungAbsolut,\r\n(SAFE_DIVIDE(current_abonnements,past_abonnements)-1)*100 as FollowerVeraenderung,\r\n\r\ncurrent_videostarts_zeitraum_genutzt as videoViews10s,\r\ncurrent_videostarts_zeitraum_genutzt - past_videostarts_zeitraum_genutzt as videoViews10sVeraenderungAbsolut,\r\n(SAFE_DIVIDE(current_videostarts_zeitraum_genutzt,past_videostarts_zeitraum_genutzt)-1)*100 as videoViews10sVeraenderung,\r\n\r\n\r\ncurrent_sehVolumen_in_std_zeitraum_genutzt as sehVolumenVariable,\r\ncurrent_sehVolumen_in_std_zeitraum_genutzt - past_sehVolumen_in_std_zeitraum_genutzt as sehVolumenVariableVeraenderungAbsolut,\r\n(SAFE_DIVIDE(current_sehVolumen_in_std_zeitraum_genutzt,past_sehVolumen_in_std_zeitraum_genutzt)-1)*100 as sehVolumenVariableVeraenderung,\r\n\r\n\r\ncurrent_interactions_zeitraum_genutzt as interactionenVariable,\r\ncurrent_interactions_zeitraum_genutzt - past_interactions_zeitraum_genutzt as interactionenVariableVeraenderungAbsolut,\r\n(SAFE_DIVIDE(current_interactions_zeitraum_genutzt,past_interactions_zeitraum_genutzt)-1)*100 as interactionenVariableVeraenderung,\r\n\r\n\r\nFROM joined_data\r\nORDER BY Profil DESC"
    }
   ]
  },
  {
   "title": "Videostarts für Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 }
  },
  {
   "title": "Videostarts für Videos im Zeitraum veröffentlicht",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, videostarts_zeitraum_veroeffentlicht as videoViews\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(videoViews,0) as videoViews FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY videoViews DESC"
    }
   ]
  },
  {
   "title": "Veröffentlichte Videos | $Monat $Jahr​",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, anzahlVideos_zeitraum_veroffentlicht as profileIdSum, videostarts_zeitraum_veroeffentlicht as videoViews\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(profileIdSum,0) as profileIdSum FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY videoViews DESC"
    }
   ]
  },
  {
   "title": "Gesamte Wiedergabedauer für Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 }
  },
  {
   "title": "Gesamte Wiedergabedauer in Stunden für Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat)​",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, sehVolumen_in_std_zeitraum_veroeffentlicht as sehVolumen\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(sehVolumen,0) as sehVolumen FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY sehVolumen DESC"
    }
   ]
  },
  {
   "title": "Interaktionen für Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 }
  },
  {
   "title": "Interaktionen für Videos im Zeitraum veröffentlicht",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, interactions_zeitraum_veroeffentlicht as interactions\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(interactions,0) as interactions FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY interactions DESC"
    }
   ]
  },
  {
   "title": "Top Videos nach Videostarts Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 }
  },
  {
   "title": "Top Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 196 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nProfil,\r\nDatum,\r\nDauer,\r\naverageViewTime,\r\nsehVolumen,\r\ntitle,\r\nviews,\r\nlink,\r\nlikes + dislikes + comments + shares as interactions,\r\naverageViewPercentage,\r\nabo_change,\r\nFROM Quintly_frozen.youtube_top_videos_nach_videostarts_zeitraum_veroeffentlicht\r\n\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY views DESC LIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "Top One Video  je Kanal Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 }
  },
  {
   "title": "Top One Video im Zeitraum veröffentlicht je Profil (Nutzung bis zum Stichtag $stichtagmonat) |  $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 215 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nSELECT DISTINCT\r\n  Profil,\r\n  Datum,\r\n  Titel,\r\n  Wiedergaben,\r\n  link,\r\n  Dauer,\r\n  sehVolumen,\r\n  averageViewPercentage,\r\nFROM Quintly_frozen.youtube_top_video_je_kanal_zeitraum_veroeffentlicht\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY Wiedergaben DESC\r\n"
    }
   ]
  },
  {
   "title": "Zusammenfassung aller Kanäle Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 233 }
  },
  {
   "title": "Zusammenfassung aller Kanäle Videos im Zeitraum veröffentlicht | $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 234 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, youtubeID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND youtubeID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), current_values AS(\r\nSELECT profile, abonnements as current_abonnements, videostarts_zeitraum_veroeffentlicht as current_videostarts_zeitraum_veroeffentlicht, sehVolumen_in_std_zeitraum_veroeffentlicht as current_sehVolumen_in_std_zeitraum_veroeffentlicht, interactions_zeitraum_veroeffentlicht as current_interactions_zeitraum_veroeffentlicht\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"),\r\npast_values AS(\r\nSELECT profile, abonnements as past_abonnements, videostarts_zeitraum_veroeffentlicht as past_videostarts_zeitraum_veroeffentlicht, sehVolumen_in_std_zeitraum_veroeffentlicht as past_sehVolumen_in_std_zeitraum_veroeffentlicht, interactions_zeitraum_veroeffentlicht as past_interactions_zeitraum_veroeffentlicht\r\nFROM Quintly_frozen.youtube_metrics\r\nWHERE CASE $month_as_number\r\nWHEN 19 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nAND LRA = \"$LRA_mapping\"\r\n), joined_data AS(\r\nSELECT * FROM all_profiles\r\nLEFT JOIN \r\ncurrent_values\r\nUSING(profile)\r\nLEFT JOIN \r\npast_values\r\nUSING(profile))\r\nSELECT profile as Profil,\r\nCASE current_abonnements\r\nWHEN 0 THEN NULL\r\nELSE current_abonnements END as followers,\r\nCASE current_abonnements - past_abonnements\r\nWHEN 0 THEN NULL \r\nELSE current_abonnements - past_abonnements END as FollowerVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_abonnements,past_abonnements)-1)*100 \r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_abonnements,past_abonnements)-1)*100 END as FollowerVeraenderung,\r\n\r\nCASE current_videostarts_zeitraum_veroeffentlicht\r\nWHEN 0 THEN NULL\r\nELSE current_videostarts_zeitraum_veroeffentlicht END as videoViews10s,\r\nCASE current_videostarts_zeitraum_veroeffentlicht - past_videostarts_zeitraum_veroeffentlicht\r\nWHEN 0 THEN NULL\r\nELSE current_videostarts_zeitraum_veroeffentlicht - past_videostarts_zeitraum_veroeffentlicht END as videoViews10sVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_videostarts_zeitraum_veroeffentlicht,past_videostarts_zeitraum_veroeffentlicht)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_videostarts_zeitraum_veroeffentlicht,past_videostarts_zeitraum_veroeffentlicht)-1)*100 END as videoViews10sVeraenderung,\r\n\r\n\r\nCASE current_sehVolumen_in_std_zeitraum_veroeffentlicht\r\nWHEN 0 THEN NULL \r\nELSE current_sehVolumen_in_std_zeitraum_veroeffentlicht END as sehVolumenVariable,\r\nCASE current_sehVolumen_in_std_zeitraum_veroeffentlicht - past_sehVolumen_in_std_zeitraum_veroeffentlicht\r\nWHEN 0 THEN NULL\r\nELSE current_sehVolumen_in_std_zeitraum_veroeffentlicht - past_sehVolumen_in_std_zeitraum_veroeffentlicht END as sehVolumenVariableVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_sehVolumen_in_std_zeitraum_veroeffentlicht,past_sehVolumen_in_std_zeitraum_veroeffentlicht)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_sehVolumen_in_std_zeitraum_veroeffentlicht,past_sehVolumen_in_std_zeitraum_veroeffentlicht)-1)*100 END as sehVolumenVariableVeraenderung,\r\n\r\n\r\nCASE current_interactions_zeitraum_veroeffentlicht \r\nWHEN 0 THEN NULL \r\nELSE current_interactions_zeitraum_veroeffentlicht END as interactionenVariable,\r\nCASE current_interactions_zeitraum_veroeffentlicht - past_interactions_zeitraum_veroeffentlicht \r\nWHEN 0 THEN NULL\r\nELSE current_interactions_zeitraum_veroeffentlicht - past_interactions_zeitraum_veroeffentlicht END as interactionenVariableVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_interactions_zeitraum_veroeffentlicht,past_interactions_zeitraum_veroeffentlicht)-1)*100 \r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_interactions_zeitraum_veroeffentlicht,past_interactions_zeitraum_veroeffentlicht)-1)*100 END as interactionenVariableVeraenderung,\r\n\r\n\r\nFROM joined_data\r\nORDER BY Profil DESC"
    }
   ]
  }
 ]
}