{
 "title": "Social Media Report Facebook old 20240118",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "LRA", "query": "NDR, MDR" },
   {
    "name": "lastMonth",
    "query": {}
   },
   {
    "name": "lastMonthShort",
    "query": {}
   },
   {
    "name": "earliestLastUpdate",
    "query": {}
   },
   {
    "name": "Monat",
    "query": "Januar : 1, Februar :  2, März : 3, April : 4, Mai : 5, Juni : 6, Juli : 7, August : 8, September : 9, Oktober : 10, November : 11, Dezember : 12 "
   },
   {
    "name": "Jahr",
    "query": "2022 : 2022, 2023 : 2023, 2024 : 2024"
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "profiles",
    "query": {}
   },
   {
    "name": "query0",
    "query": {}
   },
   {
    "name": "query1",
    "query": {}
   },
   {
    "name": "top_8_profiles",
    "query": {}
   },
   {
    "name": "Month",
    "query": {}
   },
   {
    "name": "top_8_profiles_impressionUnique",
    "query": {}
   },
   {
    "name": "Month_1",
    "query": {}
   },
   {
    "name": "Day_number",
    "query": {}
   },
   {
    "name": "Monat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastMonat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastJahr",
    "query": {}
   },
   {
    "name": "YearFromLastMonth",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "stichtagmonat",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# Facebook Report | ${Month} ${Jahr}\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [
         { "name": "total_video_10s_views", "type": "functionParameter" }
        ],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "facebookInsightsOwnVideos"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "Letzter Datenstand: </br>\n${stichtagmonat}\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  { "title": "Entwicklung: Aktive Nutzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "barchart",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\n\r\nDECLARE profiles STRING;\r\nSET profiles = (\"$query0\");\r\nEXECUTE IMMEDIATE format(\"\"\"WITH filter_month_profiles as (SELECT\r\n   REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n   SUM(page_engaged_users) AS engagedUsers,\r\n   CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) as month_year\r\n FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` AS facebook\r\n JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n   ON facebook.profileId = profiles.facebookID\r\n WHERE profiles.LRA = \"$LRA\"\r\n   AND EXTRACT(MONTH from time) = $Monat\r\n   AND EXTRACT(YEAR from time) = $Jahr\r\n GROUP BY profile, month_year), filter_month_top_profiles as (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers,\r\n   ROW_NUMBER() OVER (PARTITION BY month_year ORDER BY engagedUsers DESC) AS profile_rank\r\n FROM filter_month_profiles\r\n), filter_month_top_8_profiles AS (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank <= 8\r\n ), filter_month_rest AS (\r\n SELECT\r\n   month_year,\r\n   'Rest' AS profile,\r\n   SUM(engagedUsers) AS engagedUsers\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank > 8\r\n GROUP BY month_year\r\n), filter_month_top_8_rest_profiles AS (\r\n  SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM filter_month_top_8_profiles\r\n UNION ALL\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM filter_month_rest\r\n ORDER BY month_year DESC, profile\r\n),privous_months_profiles AS (\r\n SELECT\r\n   CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) as month_year,\r\n   REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n   SUM(page_engaged_users) AS engagedUsers\r\n FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` AS facebook\r\n JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n   ON facebook.profileId = profiles.facebookID\r\n WHERE profiles.LRA = \"$LRA\"\r\n   AND EXTRACT(DATE FROM time) >= DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 YEAR)\r\n   AND EXTRACT(DATE FROM time) <= LAST_DAY(DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH), MONTH)\r\n GROUP BY profile, month_year\r\n), privous_months_top_8_profiles AS (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM privous_months_profiles\r\n WHERE profile IN ($top_8_profiles)\r\n ), privous_months_rest AS (\r\n SELECT\r\n   month_year,\r\n   'Rest' AS profile,\r\n   SUM(engagedUsers) AS engagedUsers\r\n FROM privous_months_profiles\r\n WHERE profile NOT IN ($top_8_profiles )\r\n GROUP BY month_year), privous_months_top_8_rest_profiles AS (\r\n  SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM privous_months_top_8_profiles\r\n UNION ALL\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM privous_months_rest\r\n ORDER BY month_year DESC, profile)\r\n--SELECT * FROM privous_months_top_8_rest_profiles\r\nSELECT\r\n*\r\nFROM (\r\n SELECT\r\n   DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64), CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64), 1) as month_year ,\r\n   FORMAT_DATE('%%B %%Y', DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64), CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64), 1)) AS formatted_date,\r\n   profile,\r\n   ROUND(engagedUsers / (DATE_DIFF(LAST_DAY(DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64),CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64),1),MONTH),DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64),CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64),1),DAY) + 1)) as engagedUsers\r\n FROM filter_month_top_8_rest_profiles\r\n UNION ALL\r\n SELECT\r\n   DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64), CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64), 1) as month_year,\r\n   FORMAT_DATE('%%B %%Y', DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64), CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64), 1)) AS formatted_date,\r\n   profile,\r\n   ROUND(engagedUsers / (DATE_DIFF(LAST_DAY(DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64),CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64),1),MONTH),DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64),CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64),1),DAY) + 1)) as engagedUsers\r\n FROM privous_months_top_8_rest_profiles\r\n ORDER BY month_year DESC, profile\r\n)\r\nPIVOT(SUM(engagedUsers) FOR profile IN (%s))\"\"\", profiles);\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Anteil Top 8 + Rest | $Month $Jahr",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH filter_month_profiles as (SELECT\r\n   REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n   SUM(page_engaged_users) AS engagedUsers,\r\n   CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) as month_year\r\n FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` AS facebook\r\n JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n   ON facebook.profileId = profiles.facebookID\r\n WHERE profiles.LRA = \"$LRA\"\r\n   AND EXTRACT(MONTH from time) = $Monat\r\n   AND EXTRACT(YEAR from time) = $Jahr\r\n GROUP BY profile, month_year), filter_month_top_profiles as (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers,\r\n   ROW_NUMBER() OVER (PARTITION BY month_year ORDER BY engagedUsers DESC) AS profile_rank\r\n FROM filter_month_profiles\r\n), filter_month_top_8_profiles AS (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank <= 8\r\n ), filter_month_rest AS (\r\n SELECT\r\n   month_year,\r\n   'Rest' AS profile,\r\n   SUM(engagedUsers) AS engagedUsers\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank > 8\r\n GROUP BY month_year\r\n), filter_month_top_8_rest_profiles AS (\r\n  SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM filter_month_top_8_profiles\r\n UNION ALL\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   engagedUsers\r\n FROM filter_month_rest\r\n ORDER BY month_year DESC, profile\r\n)\r\nSELECT profile, ROUND(engagedUsers/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1)) as engagedUsers FROM filter_month_top_8_rest_profiles\r\n\r\n"
    }
   ]
  },
  {
   "title": "Entwicklung: Potenzielle Reichweite",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "type": "barchart",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE profiles STRING;\r\nSET profiles = (\"$query1\");\r\nEXECUTE IMMEDIATE format(\"\"\"WITH filter_month_profiles as (SELECT\r\n   REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n   SUM(page_impressions_unique) AS impressionsUnique,\r\n   CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) as month_year\r\n FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` AS facebook\r\n JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n   ON facebook.profileId = profiles.facebookID\r\n WHERE profiles.LRA = \"$LRA\"\r\n   AND EXTRACT(MONTH from time) = $Monat\r\n   AND EXTRACT(YEAR from time) = $Jahr\r\n GROUP BY profile, month_year), filter_month_top_profiles as (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique,\r\n   ROW_NUMBER() OVER (PARTITION BY month_year ORDER BY impressionsUnique DESC) AS profile_rank\r\n FROM filter_month_profiles\r\n), filter_month_top_8_profiles AS (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank <= 8\r\n ), filter_month_rest AS (\r\n SELECT\r\n   month_year,\r\n   'Rest' AS profile,\r\n   SUM(impressionsUnique) AS impressionsUnique\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank > 8\r\n GROUP BY month_year\r\n), filter_month_top_8_rest_profiles AS (\r\n  SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM filter_month_top_8_profiles\r\n UNION ALL\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM filter_month_rest\r\n ORDER BY month_year DESC, profile\r\n),privous_months_profiles AS (\r\n SELECT\r\n   CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) as month_year,\r\n   REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n   SUM(page_impressions_unique) AS impressionsUnique\r\n FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` AS facebook\r\n JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n   ON facebook.profileId = profiles.facebookID\r\n WHERE profiles.LRA = \"$LRA\"\r\n   AND True\r\n   AND EXTRACT(DATE FROM time) >= DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 YEAR)\r\n   AND EXTRACT(DATE FROM time) <= LAST_DAY(DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH), MONTH)\r\n GROUP BY profile, month_year\r\n), privous_months_top_8_profiles AS (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM privous_months_profiles\r\n WHERE profile IN ($top_8_profiles_impressionUnique)\r\n ), privous_months_rest AS (\r\n SELECT\r\n   month_year,\r\n   'Rest' AS profile,\r\n   SUM(impressionsUnique) AS impressionsUnique\r\n FROM privous_months_profiles\r\n WHERE profile NOT IN ($top_8_profiles_impressionUnique )\r\n GROUP BY month_year), privous_months_top_8_rest_profiles AS (\r\n  SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM privous_months_top_8_profiles\r\n UNION ALL\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM privous_months_rest\r\n ORDER BY month_year DESC, profile)\r\n--SELECT * FROM privous_months_top_8_rest_profiles\r\nSELECT\r\n*\r\nFROM (\r\n SELECT\r\n   DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64), CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64), 1) as month_year,\r\n   FORMAT_DATE('%%B %%Y', DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64), CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64), 1)) AS formatted_date,\r\n   profile,\r\n   ROUND(impressionsUnique / (DATE_DIFF(LAST_DAY(DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64),CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64),1),MONTH),DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64),CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64),1),DAY) + 1)) as impressionsUnique\r\n FROM filter_month_top_8_rest_profiles\r\n UNION ALL\r\n SELECT\r\n   DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64), CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64), 1) as month_year,\r\n   FORMAT_DATE('%%B %%Y', DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64), CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64), 1)) AS formatted_date,\r\n   profile,\r\n   ROUND(impressionsUnique / (DATE_DIFF(LAST_DAY(DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64),CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64),1),MONTH),DATE(CAST(SPLIT(month_year, '-')[OFFSET(1)] AS INT64),CAST(SPLIT(month_year, '-')[OFFSET(0)] AS INT64),1),DAY) + 1)) as impressionsUnique\r\n FROM privous_months_top_8_rest_profiles\r\n ORDER BY month_year DESC, profile\r\n)\r\nPIVOT(SUM(impressionsUnique) FOR profile IN (%s))\"\"\", profiles);\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Anteil Top 8 + Rest | $Month $Jahr",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH filter_month_profiles as (SELECT\r\n   REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n   SUM(page_impressions_unique) AS impressionsUnique,\r\n   CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) as month_year\r\n FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` AS facebook\r\n JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n   ON facebook.profileId = profiles.facebookID\r\n WHERE profiles.LRA = \"$LRA\"\r\n   AND EXTRACT(MONTH from time) = $Monat\r\n   AND EXTRACT(YEAR from time) = $Jahr\r\n GROUP BY profile, month_year), filter_month_top_profiles as (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique,\r\n   ROW_NUMBER() OVER (PARTITION BY month_year ORDER BY impressionsUnique DESC) AS profile_rank\r\n FROM filter_month_profiles\r\n), filter_month_top_8_profiles AS (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank <= 8\r\n ), filter_month_rest AS (\r\n SELECT\r\n   month_year,\r\n   'Rest' AS profile,\r\n   SUM(impressionsUnique) AS impressionsUnique\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank > 8\r\n GROUP BY month_year\r\n), filter_month_top_8_rest_profiles AS (\r\n  SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM filter_month_top_8_profiles\r\n UNION ALL\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   impressionsUnique\r\n FROM filter_month_rest\r\n ORDER BY month_year DESC, profile\r\n)\r\nSELECT profile, ROUND(impressionsUnique/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1)) as impressionsUnique FROM filter_month_top_8_rest_profiles"
    }
   ]
  },
  { "title": "Entwicklung: Interaktionen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Summe Interaktionen $LRA Profile in Mio.",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0))/1000000 as interactionsMill,\r\n\r\n  DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1) as month\r\n  \r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n-- Daten des ausgewählten Zeitraums minus 1 Jahr\r\nWHERE DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1) <= DATE($Jahr, $Monat, 1) AND DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1)  >= DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 12 MONTH) \r\nGROUP BY month\r\nORDER BY month ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 9, "y": 34 },
   "options": {
    "content": "### Zusammensetzung Interaktionen | ${Month}  ${Jahr} \n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 34 },
   "options": { "content": "### Interaktionen in Mio.\n" },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger,0)) as Reaktionen,\r\n\r\n  SUM(IFNULL(page_positive_feedback_by_type_comment, 0)) as Kommentare,\r\n\r\n  SUM(IFNULL(page_positive_feedback_by_type_link, 0)) as Shares, --Zählen diese als shares?,\r\n  \r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 16, "y": 36 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Summe')), 'Summe')\r\nFROM(\r\nSELECT 'Summe' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Ø Pro Tag')), 'Ø Pro Tag')\r\nFROM(\r\nSELECT 'Ø Pro Tag' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 38 },
   "options": {
    "content": "## $Monat_abkuerzung\r\n## $Jahr"
   },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nlm_interactions,\r\nlm_interactions/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1) as lm_interactionsPerDay\r\nFROM\r\n(SELECT\r\n  SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0))/1000000 as lm_interactions,\r\n  \r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n)\r\n\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 41 },
   "options": {
    "content": "## $LastMonat_abkuerzung\r\n## $YearFromLastMonth"
   },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS(\r\n  SELECT\r\n  SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0))/1000000 as past_sum_in_mil,\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\n), past_value_per_day AS(\r\n  SELECT past_sum_in_mil/(DATE_DIFF(LAST_DAY(DATE_SUB(DATE($Jahr,$Monat,1),INTERVAL 1 MONTH),MONTH),DATE_SUB(DATE($Jahr,$Monat,1),INTERVAL 1 MONTH),DAY) + 1) AS past_sum_per_day\r\n  FROM past_value_in_mil\r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0))/1000000 as current_sum_in_mil,\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n), current_value_per_day AS(\r\n  SELECT current_sum_in_mil/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1) AS current_sum_per_day\r\n  FROM current_value_in_mil\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil, current_value_per_day, past_value_per_day"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 44 },
   "options": {
    "content": "## $Monat_abkuerzung\r\n## $LastJahr"
   },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS(\r\n  SELECT\r\n  SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0))/1000000 as past_sum_in_mil,\r\n  \r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr - 1\r\n), past_value_per_day AS(\r\n  SELECT past_sum_in_mil/(DATE_DIFF(LAST_DAY(DATE_SUB(DATE($Jahr,$Monat,1),INTERVAL 1 YEAR),MONTH),DATE_SUB(DATE($Jahr,$Monat,1),INTERVAL 1 YEAR),DAY) + 1) AS past_sum_per_day\r\n  FROM past_value_in_mil\r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0))/1000000 as current_sum_in_mil,\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n), current_value_per_day AS(\r\n  SELECT current_sum_in_mil/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1) AS current_sum_per_day\r\n  FROM current_value_in_mil\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil, current_value_per_day, past_value_per_day"
    }
   ]
  },
  {
   "title": "Entwicklung: 10 Sek. Videostarts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Summe Videostarts (10 Sek.) $LRA Profile in Mio.",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(IFNULL(page_video_views_10s,0))/1000000 as videoViews10sMill,\r\n  DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1) as month,\r\n \r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1) <= DATE($Jahr, $Monat, 1) AND DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1)  >= DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 12 MONTH) \r\nGROUP BY month\r\nORDER BY month ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 9, "y": 48 },
   "options": {
    "content": "### Anteil Videostarts (10 Sek.) Top 8 | ${Month} ${Jahr}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 48 },
   "options": { "content": "### Videostarts in Mio.\n" },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH filter_month_profiles as (SELECT\r\n   REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n   SUM(IFNULL(page_video_views_10s,0)) as videoViews10s,\r\n   CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) as month_year\r\n FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` AS facebook\r\n JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n   ON facebook.profileId = profiles.facebookID\r\n WHERE profiles.LRA = \"$LRA\"\r\n   AND EXTRACT(MONTH from time) = $Monat\r\n   AND EXTRACT(YEAR from time) = $Jahr\r\n GROUP BY profile, month_year), filter_month_top_profiles as (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   videoViews10s,\r\n   ROW_NUMBER() OVER (PARTITION BY month_year ORDER BY videoViews10s DESC) AS profile_rank\r\n FROM filter_month_profiles\r\n), filter_month_top_8_profiles AS (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   videoViews10s\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank <= 8\r\n ), filter_month_rest AS (\r\n SELECT\r\n   month_year,\r\n   'Rest' AS profile,\r\n   SUM(videoViews10s) AS videoViews10s\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank > 8\r\n GROUP BY month_year\r\n), filter_month_top_8_rest_profiles AS (\r\n  SELECT\r\n   month_year,\r\n   profile,\r\n   videoViews10s\r\n FROM filter_month_top_8_profiles\r\n UNION ALL\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   videoViews10s\r\n FROM filter_month_rest\r\n ORDER BY month_year DESC, profile\r\n)\r\nSELECT profile, videoViews10s FROM filter_month_top_8_rest_profiles\r\n\r\n\r\n\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 16, "y": 50 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Summe')), 'Summe')\r\nFROM(\r\nSELECT 'Summe' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Ø Pro Tag')), 'Ø Pro Tag')\r\nFROM(\r\nSELECT 'Ø Pro Tag' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 52 },
   "options": {
    "content": "## $Monat_abkuerzung\r\n## $Jahr"
   },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nvideoViews10sMill,\r\nvideoViews10sMill/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1) as videoViews10sMillPerDay\r\nFROM\r\n(SELECT\r\nSUM(IFNULL(page_video_views_10s,0))/1000000 as videoViews10sMill\r\n\r\n \r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 55 },
   "options": {
    "content": "## $LastMonat_abkuerzung\r\n## $YearFromLastMonth"
   },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS (\r\n  SELECT\r\n  SUM(IFNULL(page_video_views_10s,0))/1000000 as past_sum_in_mil,\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\n), past_value_per_day AS (\r\n  SELECT past_sum_in_mil/(DATE_DIFF(LAST_DAY(DATE_SUB(DATE($Jahr,$Monat,1),INTERVAL 1 MONTH),MONTH),DATE_SUB(DATE($Jahr,$Monat,1),INTERVAL 1 MONTH),DAY) + 1) as past_sum_per_day\r\n  FROM past_value_in_mil\r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(IFNULL(page_video_views_10s,0))/1000000 as current_sum_in_mil,\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n), current_value_per_day AS(\r\n  SELECT current_sum_in_mil/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1) as current_sum_per_day\r\n  FROM current_value_in_mil\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil, current_value_per_day, past_value_per_day"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 58 },
   "options": {
    "content": "## $Monat_abkuerzung\r\n## $LastJahr"
   },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS (\r\n  SELECT\r\n  SUM(IFNULL(page_video_views_10s,0))/1000000 as past_sum_in_mil,\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr-1\r\n), past_value_per_day AS (\r\n  SELECT past_sum_in_mil/(DATE_DIFF(LAST_DAY(DATE_SUB(DATE($Jahr,$Monat,1),INTERVAL 1 YEAR),MONTH),DATE_SUB(DATE($Jahr,$Monat,1),INTERVAL 1 YEAR),DAY) + 1) as past_sum_per_day\r\n  FROM past_value_in_mil\r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(IFNULL(page_video_views_10s,0))/1000000 as current_sum_in_mil,\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n), current_value_per_day AS(\r\n  SELECT current_sum_in_mil/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1) as current_sum_per_day\r\n  FROM current_value_in_mil\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil, current_value_per_day, past_value_per_day"
    }
   ]
  },
  {
   "title": "Aktive Nutzer & Potenzielle Reichweite |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }
  },
  {
   "title": "Ø Aktive Nutzer pro Tag | $Month $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 11, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nCAST(ROUND(SUM(page_engaged_users)/COUNT(facebook.time)) as INT64) as engaged_users_PerDay ,\r\nprofile as Profil\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE --True AND\r\n\r\n EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n AND page_follows IS NOT NULL\r\nGROUP BY profile\r\nORDER BY engaged_users_PerDay desc\r\n"
    }
   ]
  },
  {
   "title": "Ø Potenzielle Reichweite pro Tag | $Month $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 13, "x": 11, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nCAST(ROUND(SUM(page_impressions_unique)/(COUNT(facebook.time))) as INT64) as impressions_unique_PerDay ,\r\nprofile as Profil\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\n\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nAND page_follows is not null\r\nGROUP BY profile\r\nORDER BY impressions_unique_PerDay desc\r\n"
    }
   ]
  },
  { "title": "Follower | ${Month} ${Jahr}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Follower | Stichtag: $Day_number. $Month ",
   "type": "bargauge",
   "gridPos": { "h": 28, "w": 16, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nprofile as Profil,\r\npage_follows as followers\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n\r\nORDER BY followers desc"
    }
   ]
  },
  {
   "title": "Veränderung zum Vormonat in %",
   "type": "barchart",
   "gridPos": { "h": 28, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nlm.Profil,\r\n(lm_follower/llm_follower - 1)*100 as FollowerVeraenderung\r\nFROM\r\n(SELECT\r\npage_follows lm_follower,\r\nprofile as Profil\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n\r\nORDER BY page_follows desc) as lm\r\nLEFT JOIN\r\n(SELECT\r\npage_follows as llm_follower,\r\nprofile as Profil\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n            WHERE EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)))\r\n\r\nORDER BY page_follows desc) as llm ON llm.Profil = lm.Profil\r\nORDER BY lm.lm_follower DESC"
    }
   ]
  },
  {
   "title": "Videostarts |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 }
  },
  {
   "title": "Videostarts (10 Sek.)",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nprofile as Profil,\r\nSUM(page_video_views_10s) as videoViews10s\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\n\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile\r\nORDER BY videoViews10s desc\r\n"
    }
   ]
  },
  {
   "title": "Videostarts (3 Sek.)",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nSUM(page_video_views) as videoViews3s,\r\nprofile\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\n\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile\r\nORDER BY videoViews3s desc\r\n"
    }
   ]
  },
  {
   "title": "ARD Facebook Score $LRA |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 }
  },
  {
   "title": "Facebook Score | $Month $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 15, "x": 0, "y": 140 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "(SELECT \r\na.profile,\r\nROUND(a.followers/1000 + b.interactions/10) as ARD_Facebook_Score\r\n\r\nFROM\r\n(SELECT \r\nprofile,\r\nfollowers\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")  \r\n  WHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n  GROUP BY profile, followers) as a,\r\n  \r\n(SELECT \r\n(ROUND (AVG(ownPostsLikes + ownPostsLove + ownPostsWow + ownPostsHaha + ownPostsSad + ownPostsAngry + ownPostsShares + ownPostsComments))) AS interactions,\r\nprofile\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n  GROUP BY profile\r\n  ) as b\r\n  WHERE a.profile = b.profile\r\n  ORDER BY ARD_Facebook_Score DESC)\r\n"
    }
   ]
  },
  {
   "title": "zum Vormonat",
   "type": "barchart",
   "gridPos": { "h": 24, "w": 9, "x": 15, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nlm.Profil as Profil,\r\n(lm.ARD_Facebook_Score/llm.ARD_Facebook_Score - 1) * 100 as ARDScore_Veraenderung\r\n\r\nFROM(SELECT \r\na.profile as Profil,\r\nROUND(a.followers/1000 + b.interactions/10) as ARD_Facebook_Score\r\n\r\nFROM\r\n(SELECT \r\nprofile,\r\nfollowers\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")  \r\n  WHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n  GROUP BY profile, followers) as a,\r\n  \r\n(SELECT \r\n(ROUND (AVG(ownPostsLikes + ownPostsLove + ownPostsWow + ownPostsHaha + ownPostsSad + ownPostsAngry + ownPostsShares + ownPostsComments))) AS interactions,\r\nprofile\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n  GROUP BY profile\r\n  ) as b\r\n  WHERE a.profile = b.profile\r\n  ORDER BY ARD_Facebook_Score DESC) as lm\r\n  LEFT JOIN\r\n  (SELECT \r\na.profile as Profil,\r\nROUND(a.followers/1000 + b.interactions/10) as ARD_Facebook_Score\r\n\r\nFROM\r\n(SELECT \r\nprofile,\r\nfollowers\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\") \r\n  WHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n            WHERE EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)))\r\n  GROUP BY profile, followers) as a,\r\n  \r\n(SELECT \r\n(ROUND (AVG(ownPostsLikes + ownPostsLove + ownPostsWow + ownPostsHaha + ownPostsSad + ownPostsAngry + ownPostsShares + ownPostsComments))) AS interactions,\r\nprofile\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\n  GROUP BY profile\r\n  ) as b\r\n  WHERE a.profile = b.profile\r\n  ORDER BY ARD_Facebook_Score DESC) as llm\r\n  ON lm.Profil = llm.Profil\r\n  ORDER BY lm.ARD_Facebook_Score DESC"
    }
   ]
  },
  {
   "title": "ARD Facebook Score regional - Länder",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 164 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "(SELECT \r\na.profile,\r\nCASE\r\nWHEN a.profile = \"NDR Hamburg\" THEN ROUND((a.followers/1000 + b.interactions/10)*0.64516129)\r\nWHEN a.profile = \"NDR Niedersachsen\" THEN ROUND((a.followers/1000 + b.interactions/10)*0.14714538)\r\nWHEN a.profile = \"NDR Schleswig-Holstein\" THEN ROUND((a.followers/1000 + b.interactions/10)*0.40420372)\r\nWHEN a.profile = \"NDR Mecklenburg-Vorpommern\" THEN ROUND((a.followers/1000 + b.interactions/10)*0.71942446) END as ARD_Facebook_Score\r\n\r\nFROM\r\n(SELECT \r\nprofile,\r\nfollowers\r\n  FROM `ndr-code-bi-dashboard.Quintly.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")  \r\n  WHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n  GROUP BY profile, followers) as a,\r\n  \r\n(SELECT \r\n(ROUND (AVG(ownPostsLikes + ownPostsLove + ownPostsWow + ownPostsHaha + ownPostsSad + ownPostsAngry + ownPostsShares + ownPostsComments))) AS interactions,\r\nprofile\r\n  FROM `ndr-code-bi-dashboard.Quintly.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n  GROUP BY profile\r\n  ) as b\r\n  WHERE a.profile = b.profile AND a.profile IN UNNEST([\"NDR Hamburg\", \"NDR Niedersachsen\", \"NDR Schleswig-Holstein\", \"NDR Mecklenburg-Vorpommern\"])\r\n  ORDER BY ARD_Facebook_Score DESC)"
    }
   ]
  },
  {
   "title": "Interaktionen |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 }
  },
  {
   "title": "Interaktionen | $Month $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 15, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Interaktionen pro Post und Anzahl Posts\r\n\r\nSELECT\r\nProfil, Interaktionen as InteraktionenProPost\r\n--CAST(ROUND(Interaktionen/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1)) AS INT64) AS InteraktionenProPost\r\n\r\nFROM\r\n(SELECT \r\nprofile as Profil,\r\nsum(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link) as Interaktionen\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP by profile)\r\nORDER BY InteraktionenProPost DESC\r\n"
    }
   ]
  },
  {
   "title": "Anzahl Posts | $Month $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 9, "x": 15, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH interaktionenProPost AS (SELECT \r\nprofile as Profil,\r\nsum(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link) as Interaktionen\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP by profile)\r\n-- Interaktionen pro Post und Anzahl Posts\r\nSELECT Profil, anzahlPosts FROM(\r\nSELECT\r\nt2.Profil,\r\nSUM(anzahlPosts) as anzahlPosts,\r\nMAX(t2.Interaktionen) as Interaktionen\r\n\r\nFROM\r\n(SELECT \r\nprofile as Profil,\r\nCOUNT(DISTINCT externalId) as anzahlPosts,\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsightsOwnPosts` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile\r\nUNION ALL\r\nSELECT\r\nprofile as Profil,\r\nCOUNT(DISTINCT externalId) as anzahlPosts\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsightsExpiredPosts` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile) as t1\r\nJOIN (SELECT \r\nProfil,\r\nInteraktionen from interaktionenProPost) as t2 ON t1.Profil = t2.Profil\r\nGROUP BY t2.Profil\r\n--ORDER BY CAST(ROUND(Interaktionen/(DATE_DIFF(LAST_DAY(DATE($Jahr,$Monat,1),MONTH),DATE($Jahr,$Monat,1),DAY) + 1)) AS INT64)  DESC\r\n)\r\nORDER by Interaktionen desc\r\n"
    }
   ]
  },
  {
   "title": "Top Posts nach Interaktionen |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 195 },
   "options": {
    "content": "<p style=\"text-align: right\"><font size=\"2\">Legende: &nbsp;🖼️ = Bild &nbsp;&nbsp; 🎥 = Video &nbsp;&nbsp; 🔗 = Link &nbsp;&nbsp; 📕 = Album &nbsp;&nbsp; 📄 = Status </font><font size=\"6\"> </font>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top Posts nach Interaktionen |  ${Month} ${Jahr}",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- TODO: Left Join mit facebookInsightsOwnVideos für Spalte 10s views\r\n\r\nSELECT \r\nprofile as Profil,\r\nfacebook.time as PostDatum,\r\nmessage as Post,\r\nfacebook.link,\r\ntype as Typ,\r\npost_reactions_by_type_total_like\t+ post_reactions_by_type_total_love\t+ \r\n  post_reactions_by_type_total_wow + post_reactions_by_type_total_haha + \r\n  post_reactions_by_type_total_sorry\t+ post_reactions_by_type_total_anger + \r\n  post_activity_by_action_type_share + post_activity_by_action_type_comment as Interaktionen,\r\n\r\npost_reactions_by_type_total_like\t+ post_reactions_by_type_total_love\t+ \r\n  post_reactions_by_type_total_wow + post_reactions_by_type_total_haha + \r\n  post_reactions_by_type_total_sorry\t+ post_reactions_by_type_total_anger as Reaktionen,\r\n\r\n  post_activity_by_action_type_comment as Kommentare,\r\n\r\n  post_activity_by_action_type_share as Shares,\r\n  total_video_10s_views\r\n  \r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsightsOwnPosts` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nLEFT JOIN `ndr-code-bi-dashboard.$dataset.facebookInsightsOwnVideos`as videos ON facebook.objectId = videos.externalId\r\nWHERE True\r\nAND CASE WHEN facebook.objectId = videos.externalId THEN True\r\n                     ELSE TRUE END\r\n\r\nAND EXTRACT(MONTH from facebook.time) = $Monat AND EXTRACT(YEAR from facebook.time) = $Jahr\r\nORDER BY Interaktionen DESC"
    }
   ]
  },
  {
   "title": "Top One Post je Profil |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 215 },
   "options": {
    "content": "<p style=\"text-align: right\"><font size=\"2\">Legende: &nbsp;🖼️ = Bild &nbsp;&nbsp; 🎥 = Video &nbsp;&nbsp; 🔗 = Link &nbsp;&nbsp; 📕 = Album &nbsp;&nbsp; 📄 = Status </font><font size=\"6\"> </font>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top One Post je Profil |  ${Month} ${Jahr}",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 218 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DISTINCT\r\n  profile,\r\n  PostDatum,\r\n  Post,\r\n  link,\r\n  Typ,\r\n  Interaktionen,\r\n  Reaktionen,\r\n  Kommentare,\r\n  Shares,\r\n  total_video_10s_views \r\nFROM (\r\n  SELECT \r\n    profiles.profile,\r\n    facebook.time as PostDatum,\r\n    message as Post,\r\n    facebook.link,\r\n    type as Typ,\r\n    post_reactions_by_type_total_like + post_reactions_by_type_total_love + \r\n      post_reactions_by_type_total_wow + post_reactions_by_type_total_haha + \r\n      post_reactions_by_type_total_sorry  + post_reactions_by_type_total_anger + \r\n      post_activity_by_action_type_share + post_activity_by_action_type_comment as Interaktionen,\r\n    post_reactions_by_type_total_like + post_reactions_by_type_total_love + \r\n      post_reactions_by_type_total_wow + post_reactions_by_type_total_haha + \r\n      post_reactions_by_type_total_sorry  + post_reactions_by_type_total_anger as Reaktionen,\r\n    post_activity_by_action_type_comment as Kommentare,\r\n    post_activity_by_action_type_share as Shares,\r\n    total_video_10s_views,\r\n    ROW_NUMBER() OVER (PARTITION BY profiles.facebookID ORDER BY \r\n      post_reactions_by_type_total_like + post_reactions_by_type_total_love + \r\n      post_reactions_by_type_total_wow + post_reactions_by_type_total_haha + \r\n      post_reactions_by_type_total_sorry  + post_reactions_by_type_total_anger + \r\n      post_activity_by_action_type_share + post_activity_by_action_type_comment DESC) as row_num\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebookInsightsOwnPosts` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  LEFT JOIN `ndr-code-bi-dashboard.$dataset.facebookInsightsOwnVideos` as videos ON facebook.objectId = videos.externalId\r\n  WHERE True\r\n  AND CASE \r\n    WHEN facebook.objectId = videos.externalId THEN True\r\n    ELSE TRUE \r\n  END\r\n  AND EXTRACT(MONTH from facebook.time) = $Monat \r\n  AND EXTRACT(YEAR from facebook.time) = $Jahr\r\n) as subquery\r\nWHERE row_num = 1\r\nORDER BY Interaktionen DESC\r\n"
    }
   ]
  },
  {
   "title": "Zusammenfassung aller Profile | $Monat $Jahr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 }
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 235 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH followers as (\r\n  SELECT \r\nlm.Profil,\r\nlm_follower as followers,\r\nlm_follower-llm_follower as FollowerVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_follower,llm_follower)-1)*100 as FollowerVeraenderung\r\nFROM\r\n(SELECT\r\npage_follows lm_follower,\r\nprofile as Profil\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n\r\nORDER BY page_follows desc) as lm\r\nLEFT JOIN\r\n(SELECT\r\npage_follows as llm_follower,\r\nprofile as Profil\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n            WHERE EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)))\r\n\r\nORDER BY page_follows desc) as llm ON llm.Profil = lm.Profil\r\nORDER BY lm.lm_follower DESC\r\n),anzahl_posts as (\r\n  SELECT\r\nProfil,\r\nSUM(anzahlPosts) as anzahlPosts,\r\nFROM\r\n(SELECT \r\nprofile as Profil,\r\nCOUNT(DISTINCT externalId) as anzahlPosts\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsightsOwnPosts` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile\r\nUNION ALL\r\nSELECT\r\nprofile as Profil,\r\nCOUNT(DISTINCT externalId) as anzahlPosts,\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsightsExpiredPosts` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile)\r\nGROUP BY Profil\r\n), aktive_nutzer_per_tag_und_interaktionen as (\r\nSELECT\r\nlm.Profil,\r\nlm_aktive_nutzer as AktiveNutzer,\r\nlm_aktive_nutzer-llm_aktive_nutzer as AktiveNutzerVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_aktive_nutzer,llm_aktive_nutzer)-1) * 100 as AktiveNutzerVeraenderung,\r\nlm_Interaktionen as Interaktionen,\r\nlm_Interaktionen - llm_Interaktionen as InteraktionenVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_Interaktionen,llm_Interaktionen)-1)*100 as InteraktionenVeraenderung,\r\nlm_potenzielle_reichweite as PotenzielleReichweite,\r\nlm_potenzielle_reichweite - llm_potenzielle_reichweite as PotenzielleReichweiteVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_potenzielle_reichweite,llm_potenzielle_reichweite)-1)*100 as PotenzielleReichweiteVeraenderung\r\nFROM\r\n(SELECT\r\nCAST(ROUND(SUM(page_engaged_users)/(COUNT(time))) as INT64) as lm_aktive_nutzer ,\r\nprofile as Profil,\r\nSUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0)) as lm_Interaktionen,\r\nCAST(ROUND(SUM(page_impressions_unique)/(COUNT(time))) as INT64) as lm_potenzielle_reichweite\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\n\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nAND page_follows is not null\r\nGROUP BY profile\r\nORDER BY lm_aktive_nutzer desc\r\n) as lm\r\nLEFT JOIN\r\n(SELECT\r\nCAST(ROUND(SUM(page_engaged_users)/COUNT(time)) as INT64) as llm_aktive_nutzer ,\r\nprofile as Profil,\r\nSUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0)) as llm_Interaktionen,\r\nCAST(ROUND(SUM(page_impressions_unique)/COUNT(time)) as INT64) as llm_potenzielle_reichweite\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\n\r\nAND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\nAND page_follows is not null\r\nGROUP BY profile\r\nORDER BY llm_aktive_nutzer desc\r\n) as llm ON llm.Profil = lm.Profil\r\nORDER BY lm.lm_aktive_nutzer,lm.lm_Interaktionen, lm_potenzielle_reichweite DESC\r\n), video_start as (\r\nSELECT\r\nlm.Profil,\r\nlm_videoViews10s as videoViews10s,\r\nlm_videoViews10s - llm_videoViews10s as videoViews10sVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_videoViews10s,llm_videoViews10s)-1)*100 as videoViews10sVeraenderung,\r\nlm_videoViews3s as videoViews3s,\r\nlm_videoViews3s - llm_videoViews3s as videoViews3sVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_videoViews3s,llm_videoViews3s)-1)*100 as videoViews3sVeraenderung,\r\nFROM\r\n(SELECT\r\nSUM(page_video_views_10s) as lm_videoViews10s,\r\nSUM(page_video_views) as lm_videoViews3s,\r\nprofile as Profil\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\n\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile\r\nORDER BY lm_videoViews10s, lm_videoViews3s DESC\r\n) as lm\r\nLEFT JOIN\r\n(SELECT\r\nprofile as Profil,\r\nSUM(page_video_views_10s) as llm_videoViews10s,\r\nSUM(page_video_views) as llm_videoViews3s\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\nGROUP BY profile\r\nORDER BY llm_videoViews10s, llm_videoViews3s DESC\r\n) as llm ON llm.Profil = lm.Profil\r\nORDER BY lm.lm_videoViews10s, lm.lm_videoViews3s DESC\r\n), ard_facebook_score as (\r\nSELECT\r\nlm.Profil as Profil,\r\nlm.ARD_Facebook_Score as ARD_facebook_score,\r\nlm.ARD_Facebook_Score-llm.ARD_Facebook_Score as ARDScore_VeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm.ARD_Facebook_Score,llm.ARD_Facebook_Score)-1)*100 as ARDScore_Veraenderung\r\n\r\nFROM(SELECT \r\na.profile as Profil,\r\nROUND(a.followers/1000 + b.interactions/10) as ARD_Facebook_Score\r\n\r\nFROM\r\n(SELECT \r\nprofile,\r\nfollowers\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")  \r\n  WHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n  GROUP BY profile, followers) as a,\r\n  \r\n(SELECT \r\n(ROUND (AVG(ownPostsLikes + ownPostsLove + ownPostsWow + ownPostsHaha + ownPostsSad + ownPostsAngry + ownPostsShares + ownPostsComments))) AS interactions,\r\nprofile\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n  GROUP BY profile\r\n  ) as b\r\n  WHERE a.profile = b.profile\r\n  ORDER BY ARD_Facebook_Score DESC) as lm\r\n  LEFT JOIN\r\n  (SELECT \r\na.profile as Profil,\r\nROUND(a.followers/1000 + b.interactions/10) as ARD_Facebook_Score\r\n\r\nFROM\r\n(SELECT \r\nprofile,\r\nfollowers\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\") \r\n  WHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n            WHERE EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)))\r\n  GROUP BY profile, followers) as a,\r\n  \r\n(SELECT \r\n(ROUND (AVG(ownPostsLikes + ownPostsLove + ownPostsWow + ownPostsHaha + ownPostsSad + ownPostsAngry + ownPostsShares + ownPostsComments))) AS interactions,\r\nprofile\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\n  GROUP BY profile\r\n  ) as b\r\n  WHERE a.profile = b.profile\r\n  ORDER BY ARD_Facebook_Score DESC) as llm\r\n  ON lm.Profil = llm.Profil\r\n  ORDER BY lm.ARD_Facebook_Score DESC\r\n)\r\nSELECT followers.Profil,followers.followers, followers.FollowerVeraenderungAbsolut, followers.FollowerVeraenderung,anzahl_posts.Anzahlposts,\r\naktive_nutzer_per_tag_und_interaktionen.AktiveNutzer, aktive_nutzer_per_tag_und_interaktionen.AktiveNutzerVeraenderungAbsolut, aktive_nutzer_per_tag_und_interaktionen.AktiveNutzerVeraenderung,\r\naktive_nutzer_per_tag_und_interaktionen.Interaktionen, aktive_nutzer_per_tag_und_interaktionen.InteraktionenVeraenderungAbsolut, aktive_nutzer_per_tag_und_interaktionen.InteraktionenVeraenderung,\r\naktive_nutzer_per_tag_und_interaktionen.PotenzielleReichweite, aktive_nutzer_per_tag_und_interaktionen.PotenzielleReichweiteVeraenderungAbsolut, aktive_nutzer_per_tag_und_interaktionen.PotenzielleReichweiteVeraenderung,\r\nvideo_start.videoViews10s, video_start.videoViews10sVeraenderungAbsolut, video_start.videoViews10sVeraenderung, video_start.videoViews3s, video_start.videoViews3sVeraenderungAbsolut, video_start.videoViews3sVeraenderung,\r\nard_facebook_score.ARD_facebook_score, ard_facebook_score.ARDScore_VeraenderungAbsolut, ard_facebook_score.ARDScore_Veraenderung \r\nFROM followers \r\nJOIN anzahl_posts ON followers.Profil = anzahl_posts.Profil\r\nJOIN aktive_nutzer_per_tag_und_interaktionen ON followers.Profil = aktive_nutzer_per_tag_und_interaktionen.Profil\r\nJOIN video_start ON followers.Profil = video_start.Profil\r\nJOIN ard_facebook_score ON followers.Profil = ard_facebook_score.Profil"
    }
   ]
  },
  {
   "title": "Zusammenfassung aller Profile auf Tagesebene | $Monat $Jahr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 250 }
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 251 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH followers as (\r\n  SELECT \r\nlm.Profil,\r\nlm_follower as followers,\r\nlm_follower-llm_follower as FollowerVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_follower,llm_follower)-1)*100 as FollowerVeraenderung\r\nFROM\r\n(SELECT\r\npage_follows lm_follower,\r\nprofile as Profil\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n\r\nORDER BY page_follows desc) as lm\r\nLEFT JOIN\r\n(SELECT\r\npage_follows as llm_follower,\r\nprofile as Profil\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\n            WHERE EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)))\r\n\r\nORDER BY page_follows desc) as llm ON llm.Profil = lm.Profil\r\nORDER BY lm.lm_follower DESC\r\n),anzahl_posts as (\r\n  SELECT\r\nProfil,\r\nSUM(anzahlPosts) as anzahlPosts,\r\nFROM\r\n(SELECT \r\nprofile as Profil,\r\nCOUNT(DISTINCT externalId) as anzahlPosts\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsightsOwnPosts` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile\r\nUNION ALL\r\nSELECT\r\nprofile as Profil,\r\nCOUNT(DISTINCT externalId) as anzahlPosts,\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsightsExpiredPosts` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile)\r\nGROUP BY Profil\r\n), aktive_nutzer_per_tag_und_interaktionen as (\r\nSELECT\r\nlm.Profil,\r\nlm_aktive_nutzer as AktiveNutzer,\r\nlm_aktive_nutzer-llm_aktive_nutzer as AktiveNutzerVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_aktive_nutzer,llm_aktive_nutzer)-1) * 100 as AktiveNutzerVeraenderung,\r\nlm_Interaktionen as Interaktionen,\r\nlm_Interaktionen - llm_Interaktionen as InteraktionenVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_Interaktionen,llm_Interaktionen)-1)*100 as InteraktionenVeraenderung,\r\nlm_potenzielle_reichweite as PotenzielleReichweite,\r\nlm_potenzielle_reichweite - llm_potenzielle_reichweite as PotenzielleReichweiteVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_potenzielle_reichweite,llm_potenzielle_reichweite)-1)*100 as PotenzielleReichweiteVeraenderung\r\nFROM\r\n(SELECT\r\nCAST(ROUND(SUM(page_engaged_users)/COUNT(time)) as INT64) as lm_aktive_nutzer,\r\nprofile as Profil,\r\nCAST(ROUND(SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0))/(COUNT(time))) as INT64) as lm_Interaktionen,\r\nCAST(ROUND(SUM(page_impressions_unique)/(COUNT(time))) as INT64) as lm_potenzielle_reichweite\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND page_follows is not null\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile\r\nORDER BY lm_aktive_nutzer desc\r\n) as lm\r\nLEFT JOIN\r\n(SELECT\r\nCAST(ROUND(SUM(page_engaged_users)/COUNT(time)) as INT64) as llm_aktive_nutzer ,\r\nprofile as Profil,\r\nCAST(ROUND(SUM(IFNULL(page_actions_post_reactions_total_like + page_actions_post_reactions_total_love + \r\n  page_actions_post_reactions_total_wow + page_actions_post_reactions_total_haha + \r\n  page_actions_post_reactions_total_sorry + page_actions_post_reactions_total_anger +\r\n  page_positive_feedback_by_type_comment + page_positive_feedback_by_type_link,0))/COUNT(time)) as INT64) as llm_Interaktionen,\r\nCAST(ROUND(SUM(page_impressions_unique)/COUNT(time)) as INT64) as llm_potenzielle_reichweite\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND page_follows is not null\r\n\r\nAND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\nGROUP BY profile\r\nORDER BY llm_aktive_nutzer desc\r\n) as llm ON llm.Profil = lm.Profil\r\nORDER BY lm.lm_aktive_nutzer,lm.lm_Interaktionen, lm_potenzielle_reichweite DESC\r\n), video_start as (\r\nSELECT\r\nlm.Profil,\r\nlm_videoViews10s as videoViews10s,\r\nlm_videoViews10s - llm_videoViews10s as videoViews10sVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_videoViews10s,llm_videoViews10s)-1)*100 as videoViews10sVeraenderung,\r\nlm_videoViews3s as videoViews3s,\r\nlm_videoViews3s - llm_videoViews3s as videoViews3sVeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm_videoViews3s,llm_videoViews3s)-1)*100 as videoViews3sVeraenderung,\r\nFROM\r\n(SELECT\r\nCAST(ROUND(SUM(page_video_views_10s)/COUNT(time) )as INT64) as lm_videoViews10s,\r\nCAST(ROUND(SUM(page_video_views)/COUNT(time)) as INT64) as lm_videoViews3s,\r\nprofile as Profil\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND page_follows is not null\r\n\r\nAND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\nGROUP BY profile\r\nORDER BY lm_videoViews10s, lm_videoViews3s DESC\r\n) as lm\r\nLEFT JOIN\r\n(SELECT\r\nprofile as Profil,\r\nCAST(ROUND(SUM(page_video_views_10s)/COUNT(time)) as INT64) as llm_videoViews10s,\r\nCAST(ROUND(SUM(page_video_views)/COUNT(time)) as INT64) as llm_videoViews3s\r\n\r\nFROM `ndr-code-bi-dashboard.$dataset.facebookInsights` as facebook\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND page_follows is not null\r\nAND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\nGROUP BY profile\r\nORDER BY llm_videoViews10s, llm_videoViews3s DESC\r\n) as llm ON llm.Profil = lm.Profil\r\nORDER BY lm.lm_videoViews10s, lm.lm_videoViews3s DESC\r\n), ard_facebook_score as (\r\nSELECT\r\nlm.Profil as Profil,\r\nlm.ARD_Facebook_Score as ARD_facebook_score,\r\nlm.ARD_Facebook_Score-llm.ARD_Facebook_Score as ARDScore_VeraenderungAbsolut,\r\n(SAFE_DIVIDE(lm.ARD_Facebook_Score,llm.ARD_Facebook_Score)-1)*100 as ARDScore_Veraenderung\r\n\r\nFROM(SELECT \r\na.profile as Profil,\r\nROUND(a.followers/1000 + b.interactions/10) as ARD_Facebook_Score\r\n\r\nFROM\r\n(SELECT \r\nprofile,\r\nfollowers\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")  \r\n  WHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n            WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n  GROUP BY profile, followers) as a,\r\n  \r\n(SELECT \r\n(ROUND (AVG(ownPostsLikes + ownPostsLove + ownPostsWow + ownPostsHaha + ownPostsSad + ownPostsAngry + ownPostsShares + ownPostsComments))) AS interactions,\r\nprofile\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n  GROUP BY profile\r\n  ) as b\r\n  WHERE a.profile = b.profile\r\n  ORDER BY ARD_Facebook_Score DESC) as lm\r\n  LEFT JOIN\r\n  (SELECT \r\na.profile as Profil,\r\nROUND(a.followers/1000 + b.interactions/10) as ARD_Facebook_Score\r\n\r\nFROM\r\n(SELECT \r\nprofile,\r\nfollowers\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\") \r\n  WHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n            WHERE EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)))\r\n  GROUP BY profile, followers) as a,\r\n  \r\n(SELECT \r\n(ROUND (AVG(ownPostsLikes + ownPostsLove + ownPostsWow + ownPostsHaha + ownPostsSad + ownPostsAngry + ownPostsShares + ownPostsComments))) AS interactions,\r\nprofile\r\n  FROM `ndr-code-bi-dashboard.$dataset.facebook` as facebook\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (facebook.profileId = profiles.facebookID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH))\r\n  GROUP BY profile\r\n  ) as b\r\n  WHERE a.profile = b.profile\r\n  ORDER BY ARD_Facebook_Score DESC) as llm\r\n  ON lm.Profil = llm.Profil\r\n  ORDER BY lm.ARD_Facebook_Score DESC\r\n)\r\nSELECT followers.Profil,followers.followers, followers.FollowerVeraenderungAbsolut, followers.FollowerVeraenderung,anzahl_posts.Anzahlposts,\r\naktive_nutzer_per_tag_und_interaktionen.AktiveNutzer, aktive_nutzer_per_tag_und_interaktionen.AktiveNutzerVeraenderungAbsolut, aktive_nutzer_per_tag_und_interaktionen.AktiveNutzerVeraenderung,\r\naktive_nutzer_per_tag_und_interaktionen.Interaktionen, aktive_nutzer_per_tag_und_interaktionen.InteraktionenVeraenderungAbsolut, aktive_nutzer_per_tag_und_interaktionen.InteraktionenVeraenderung,\r\naktive_nutzer_per_tag_und_interaktionen.PotenzielleReichweite, aktive_nutzer_per_tag_und_interaktionen.PotenzielleReichweiteVeraenderungAbsolut, aktive_nutzer_per_tag_und_interaktionen.PotenzielleReichweiteVeraenderung,\r\nvideo_start.videoViews10s, video_start.videoViews10sVeraenderungAbsolut, video_start.videoViews10sVeraenderung, video_start.videoViews3s, video_start.videoViews3sVeraenderungAbsolut, video_start.videoViews3sVeraenderung,\r\nard_facebook_score.ARD_facebook_score, ard_facebook_score.ARDScore_VeraenderungAbsolut, ard_facebook_score.ARDScore_Veraenderung FROM followers \r\nJOIN anzahl_posts ON followers.Profil = anzahl_posts.Profil\r\nJOIN aktive_nutzer_per_tag_und_interaktionen ON followers.Profil = aktive_nutzer_per_tag_und_interaktionen.Profil\r\nJOIN video_start ON followers.Profil = video_start.Profil\r\nJOIN ard_facebook_score ON followers.Profil = ard_facebook_score.Profil"
    }
   ]
  },
  { "title": "Hinweise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 266 } },
  {
   "title": "Hinweis",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 267 },
   "options": {
    "content": "# 📊 Hinweis\n\n- Aktuell laufen in diesem Dashboard Daten ein, die regelmäßig aktualisiert werden. Ab Juni 2023 werden die Daten am 7. jedes Monats für den Vormonat endgültig gespeichert. Deswegen kann es im Vergleich mit anderen Stichtags-Erhebungen (z.B. den Berichten der Medienforschungen) Abweichungen bei den Daten geben."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}