{
 "title": "Quotenreport Old",
 "description": "Before 1065 Ticket 09.03.2025",
 "time": { "from": "2023-11-30T10:08:12.740Z", "to": "2023-12-02T10:08:12.740Z" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": "ARD : ard, MDR : mdr, NDR : ndr, Sender : sender"
   },
   {
    "name": "date_range",
    "query": {}
   },
   {
    "name": "Sendung",
    "query": {}
   },
   {
    "name": "SehbOderSeher",
    "query": {}
   },
   {
    "name": "ndrOderGesamt",
    "query": {}
   },
   {
    "name": "Jahr",
    "query": {}
   },
   {
    "name": "LastJahr",
    "query": {}
   },
   {
    "name": "LastLastJahr",
    "query": {}
   },
   {
    "name": "numShows",
    "query": {}
   },
   {
    "name": "BRD_or_NDR",
    "query": {}
   },
   {
    "name": "BRD_or_none",
    "query": {}
   },
   {
    "name": "jahrHidden",
    "query": {}
   },
   {
    "name": "lastJahrHidden",
    "query": {}
   },
   {
    "name": "lastLastJahrHidden",
    "query": {}
   },
   {
    "name": "zielgruppen_und_facts",
    "query": "zielgruppen_facts_native : ${table_prefix}zielgruppen_facts_native"
   },
   {
    "name": "SehbGesamt",
    "query": {}
   },
   {
    "name": "SeherGesamt",
    "query": {}
   },
   {
    "name": "SendetagGesamt",
    "query": {}
   },
   {
    "name": "special_region",
    "query": {}
   },
   {
    "name": "dmt_kennziffern_hinweis",
    "query": {}
   },
   {
    "name": "dmtOrder",
    "query": "CASE target_group\n    WHEN \"Vereinfachende\" THEN 1\n    WHEN \"Ablenkungssuchende\" THEN 2\n    WHEN \"Ambitionierte\" THEN 3\n    WHEN \"Neokulturelle\" THEN 4\n    WHEN \"Selbstgenügsame\" THEN 5\n    WHEN \"Sicherheitsorientierte\" THEN 6\n    WHEN \"Traditionsbewusste\" THEN 7\n    WHEN \"Verantwortungsvolle\" THEN 8\n    WHEN \"Gleichmütige\" THEN 9\nEND"
   },
   {
    "name": "sehbDurchschnitt",
    "query": {}
   },
   {
    "name": "seherDurchschnitt",
    "query": {}
   },
   {
    "name": "marktanteilDurchschnitt",
    "query": {}
   },
   {
    "name": "special_region_dmt",
    "query": {}
   },
   {
    "name": "gesamtjahre_hidden",
    "query": {}
   },
   {
    "name": "sendung_or_sendetag",
    "query": {}
   },
   {
    "name": "special_region_aufkleber",
    "query": {}
   },
   {
    "name": "table_prefix",
    "query": {}
   },
   {
    "name": "verweildauer_native",
    "query": "verweildauer_native : ${table_prefix}verweildauer_native"
   },
   {
    "name": "sendungsliste_native",
    "query": "sendungsliste_native : ${table_prefix}sendungsliste_native"
   },
   {
    "name": "monatswerte_native",
    "query": "monatswerte_native : ${table_prefix}monatswerte_native"
   },
   {
    "name": "vergleichssender_native",
    "query": "vergleichssender_native : ${table_prefix}vergleichssender_native"
   },
   {
    "name": "hinweis_regionalmagazin",
    "query": {}
   },
   {
    "name": "hinweis_regionalmagazin_top",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<font size=\"6\" color=\"#2671c6\" style=\"font-weight:bold;\">Marktstandard Bewegtbild – lineare TV-Nutzung inkl. 24/7-Livestream</font>\r\n\r\n<font size=\"6\" style=\"font-weight:bold;\">${LRA:text} | $Sendung | Stand: $date_range </font>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 4 },
   "options": {
    "content": "#### Beinhaltet Sendungen, deren Startzeit nicht mehr als eine halbe Stunde vom Sendeplatz abweicht. Sonderausgaben bleiben in der Regel unberücksichtigt."
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 4 },
   "options": {
    "content": "#### Aktualisierung erfolgt am 09. jedes Monats"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "options": {
    "content": "##### <b>Nur zur ARD-internen Verwendung</b>"
   }
  },
  { "title": "Jahresdaten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "options": {
    "content": "</br><center><font size=\"5\" style=\"font-weight:bold;\">Anzahl $sendung_or_sendetag</font></center>"
   }
  },
  {
   "title": "$date_range:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Quotenreport_Sample",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(title) as Sendungen\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_native}`\r\nWHERE\r\nshow = \"${Sendung:text}\"\r\nAND year like \"$Jahr\""
    }
   ]
  },
  {
   "title": "Gesamtjahr $LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Quotenreport_Sample",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(title) as Sendungen\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_native}`\r\nWHERE\r\nCASE WHEN \"${LRA}\" like \"sender\"\r\nTHEN\r\n  lra like \"SENDER\" and broadcaster_short like \"NDR FS\"\r\nELSE show = \"${Sendung:text}\"\r\nEND\r\nAND year like \"$LastJahr\""
    }
   ]
  },
  {
   "title": "Gesamtjahr $LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Quotenreport_Sample",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(title) as Sendungen\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_native}`\r\nWHERE\r\nCASE WHEN \"${LRA}\" like \"sender\"\r\nTHEN\r\n  lra like \"SENDER\" and broadcaster_short like \"NDR FS\"\r\nELSE show = \"${Sendung:text}\"\r\nEND\r\nAND year like \"$LastLastJahr\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "description": "Anzahl der Zuschauer einer Zielgruppe, die anteilig ihrer Nutzungsdauer gezählt werden",
   "gridPos": { "h": 2, "w": 5, "x": 2, "y": 10 },
   "options": {
    "content": "\n<center><font size=\"5\" style=\"font-weight:bold;\">   Sehbeteiligung (Mio.)</font></center>\n"
   }
  },
  {
   "type": "text",
   "description": "Gibt den prozentualen Anteil der durchschnittlichen Sehbeteiligung einer Sendung oder Zeitintervalls an der Sehbeteiligung TV Gesamt zum Zeitpunkt an",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 10 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Marktanteil (%)</font></center>"
   }
  },
  {
   "type": "text",
   "description": "Personen, die sich für mindestens eine Minute in das Programm eingeschaltet haben",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 10 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Seher (Mio.)</font></center>"
   }
  },
  {
   "type": "text",
   "description": "Verweildauer in Minuten (Durchschnittliche Sehdauer der Zuschauer die mindestens 1 Minute ohne Unterbrechung geschaut haben)",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 10 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Verweildauer</font></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 10 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Durchschnittsalter</font></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": {
    "content": "\n<font size=\"5\" color=\"#2671c6\" style=\"font-weight:bold;\">${BRD_or_NDR}</font>"
   }
  },
  {
   "title": "$date_range:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n)\r\n as Sehbeteiligung\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung:text}\"\r\nAND year like \"$Jahr\""
    }
   ]
  },
  {
   "title": "$date_range:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(market_share,2) as STRING),'%') as Marktanteil\r\nCONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year LIKE \"$Jahr\""
    }
   ]
  },
  {
   "title": "$date_range:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(viewers,3) AS STRING), ' Mio.') as Seher\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', viewers), r'\\.', ','), \r\n  ' Mio.'\r\n) as Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$Jahr\""
    }
   ]
  },
  {
   "title": "$date_range:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  (EXTRACT(HOUR FROM PARSE_TIME('%H:%M:%S', watch_time))*3600) + \r\n  (EXTRACT(MINUTE FROM PARSE_TIME('%H:%M:%S', watch_time))*60) + \r\n  (EXTRACT(SECOND FROM PARSE_TIME('%H:%M:%S', watch_time))) as Verweildauer\r\nFROM \r\n  `ndr-code-bi-dashboard.Quotenreport.${verweildauer_native}` \r\nWHERE \r\n  show LIKE \"${Sendung}\"\r\n  AND year like \"$Jahr\""
    }
   ]
  },
  {
   "title": "$date_range:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT ROUND(average_age,0) as Durchschnittsalter\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$Jahr\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 15 },
   "options": {
    "content": "<font size=\"3\" color=\"#4d86c7\" style=\"font-weight:bold;\"><i>Gesamtjahre</i></font>"
   }
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as sb\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND year = \"$LastJahr\"\r\nAND show LIKE \"${Sendung:text}\"\r\n-- remove\r\nAND show not like \"Rote Rosen\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 0.331026659685 as Sehbeteiligung\r\n);\r\nELSE ( \r\n  SELECT \r\n   CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) AS Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE\r\n    target_group LIKE \"${BRD_or_NDR}%\"\r\n    AND year = \"$LastLastJahr\"\r\n    AND show LIKE \"${Sendung:text}\"\r\n    -- remove after data fix\r\n    -- AND show NOT LIKE \"Extra3\"\r\n    -- AND show NOT LIKE \"Weltspiegel\"\r\n    -- AND show NOT LIKE \"Zoodokus\"\r\n    -- AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(market_share,1) as STRING),'%') as Marktanteil\r\nCONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year LIKE \"$LastJahr\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 14.985605308226 as Marktanteil\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) as STRING),'%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year LIKE \"$LastLastJahr\"\r\n  --AND show NOT LIKE \"Extra3\"\r\n  ---AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(viewers,3) AS STRING), ' Mio.') as Seher\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', viewers), r'\\.', ','), \r\n  ' Mio.'\r\n)\r\n as Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$LastJahr\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 0.828348250387 as Seher\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(viewers,3) AS STRING), ' Mio.') as Seher\r\n CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', viewers), r'\\.', ','), \r\n  ' Mio.'\r\n)\r\n as Seher\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year like \"$LastLastJahr\"\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Nrdt. Factual Entertainment\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  (EXTRACT(HOUR FROM PARSE_TIME('%H:%M:%S', watch_time))*3600) + \r\n  (EXTRACT(MINUTE FROM PARSE_TIME('%H:%M:%S', watch_time))*60) + \r\n  (EXTRACT(SECOND FROM PARSE_TIME('%H:%M:%S', watch_time))) as Verweildauer\r\nFROM \r\n  `ndr-code-bi-dashboard.Quotenreport.${verweildauer_native}` \r\nWHERE \r\n  show LIKE \"${Sendung}\"\r\n  AND year like \"$LastJahr\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT \"00:51:39\" as Verweildauer\r\n);\r\nELSE ( \r\n  SELECT \r\n    (EXTRACT(HOUR FROM PARSE_TIME('%H:%M:%S', watch_time))*3600) + \r\n    (EXTRACT(MINUTE FROM PARSE_TIME('%H:%M:%S', watch_time))*60) + \r\n    (EXTRACT(SECOND FROM PARSE_TIME('%H:%M:%S', watch_time))) as Verweildauer\r\n  FROM \r\n    `ndr-code-bi-dashboard.Quotenreport.${verweildauer_native}` \r\n  WHERE \r\n    show LIKE \"${Sendung}\"\r\n    AND year like \"$LastLastJahr\"\r\n    --remove after data fix\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Nrdt. Factual Entertainment\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT ROUND(average_age,0) as Durchschnittsalter\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$LastJahr\"\r\n--remove\r\nAND show not like \"Schleswig-Holstein Magazin\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 71.540083717991 as Durchschnittsalter\r\n);\r\nELSE ( \r\n  SELECT ROUND(average_age,0) as Durchschnittsalter\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year like \"$LastLastJahr\"\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "description": "Ergebnisse für BRD gesamt werden nur für NDR & MDR angezeigt.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "options": {
    "content": "\n<font size=\"5\" color=\"#2671c6\" style=\"font-weight:bold;\">${BRD_or_none}</font>"
   }
  },
  {
   "title": "$jahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ((\"${LRA:text}\" LIKE \"Sender\" AND \"${Sendung:text}\" NOT LIKE \"%DR Fernsehen\") OR \"${LRA:text}\" LIKE \"ARD\" OR \"${special_region}\" NOT LIKE \"\") THEN (\r\n  SELECT \"\" as INVALID\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\n  CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$Jahr\"\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$jahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ((\"${LRA:text}\" LIKE \"Sender\" AND \"${Sendung:text}\" NOT LIKE \"%DR Fernsehen\") OR \"${LRA:text}\" LIKE \"ARD\" OR \"${special_region}\" NOT LIKE \"\") THEN (\r\n  SELECT \"\" as INVALID\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) AS STRING), '%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$Jahr\"\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 22 },
   "options": {
    "content": "\n<font size=\"3\" color=\"#4d86c7\" style=\"font-weight:bold;\"><i>$gesamtjahre_hidden</i></font>"
   }
  },
  {
   "title": "$lastJahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ((\"${LRA:text}\" LIKE \"Sender\" AND \"${Sendung:text}\" NOT LIKE \"%DR Fernsehen\") OR \"${LRA:text}\" LIKE \"ARD\" OR \"${special_region}\" NOT LIKE \"\") THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\n  CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastJahr\"\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$lastLastJahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Handle the first condition\r\nSELECT \"\" AS INVALID\r\nFROM UNNEST([1]) AS dummy\r\nWHERE (\"${LRA:text}\" LIKE \"Sender\" AND \"${Sendung:text}\" NOT LIKE \"%DR Fernsehen\")\r\n   OR \"${LRA:text}\" LIKE \"ARD\"\r\n   OR \"${special_region}\" NOT LIKE \"\"\r\n\r\nUNION ALL\r\n\r\n-- Handle the second condition\r\nSELECT CAST(0.611194112454 AS STRING) AS Sehbeteiligung\r\nFROM UNNEST([1]) AS dummy\r\nWHERE \"${Sendung}\" LIKE \"Riverboat\" AND $Jahr = 2024\r\n\r\nUNION ALL\r\n\r\n-- Default case: the main query\r\nSELECT \r\n  CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) AS Sehbeteiligung\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\nWHERE \r\n  target_group = \"BRD gesamt\"\r\n  AND show LIKE \"${Sendung}\"\r\n  AND year LIKE \"$LastLastJahr\"\r\n  AND NOT (\r\n    (\"${LRA:text}\" LIKE \"Sender\" AND \"${Sendung:text}\" NOT LIKE \"%DR Fernsehen\")\r\n    OR \"${LRA:text}\" LIKE \"ARD\"\r\n    OR \"${special_region}\" NOT LIKE \"\"\r\n    OR (\"${Sendung}\" LIKE \"Riverboat\" AND $Jahr = 2024)\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "$lastJahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ((\"${LRA:text}\" LIKE \"Sender\" AND \"${Sendung:text}\" NOT LIKE \"%DR Fernsehen\") OR \"${LRA:text}\" LIKE \"ARD\" OR \"${special_region}\" NOT LIKE \"\") THEN (\r\n  SELECT \"\" as INVALID\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) AS STRING), '%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastJahr\"\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$lastLastJahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Handle the first condition\r\nSELECT \"\" AS INVALID\r\nFROM UNNEST([1]) AS dummy\r\nWHERE (\"${LRA:text}\" LIKE \"Sender\" AND \"${Sendung:text}\" NOT LIKE \"%DR Fernsehen\")\r\n   OR \"${LRA:text}\" LIKE \"ARD\"\r\n   OR \"${special_region}\" NOT LIKE \"\"\r\n\r\nUNION ALL\r\n\r\n-- Handle the second condition: Riverboat 2024 with hardcoded market_share\r\nSELECT CAST(3.2 as STRING) AS Marktanteil\r\nFROM UNNEST([1]) AS dummy\r\nWHERE \"${Sendung}\" LIKE \"Riverboat\" AND $Jahr = 2024\r\n\r\nUNION ALL\r\n\r\n-- Default case: the main query\r\nSELECT \r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil \r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\nWHERE \r\n  target_group = \"BRD gesamt\"\r\n  AND show LIKE \"${Sendung}\"\r\n  AND year LIKE \"$LastLastJahr\"\r\n  AND NOT (\r\n    (\"${LRA:text}\" LIKE \"Sender\" AND \"${Sendung:text}\" NOT LIKE \"%DR Fernsehen\")\r\n    OR \"${LRA:text}\" LIKE \"ARD\"\r\n    OR \"${special_region}\" NOT LIKE \"\"\r\n    OR (\"${Sendung}\" LIKE \"Riverboat\" AND $Jahr = 2024)\r\n  )\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Zielgruppen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "## <span style=\"color:#BC4542\"><b>$hinweis_regionalmagazin_top</b></span>\n\n### $hinweis_regionalmagazin $special_region_aufkleber"
   }
  },
  {
   "title": "Übersicht Sendegebiete | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR | $date_range",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 30 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  market_share as ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` as data\r\nWHERE\r\n  show = \"${Sendung}\"\r\n  and year like \"$Jahr\"\r\n  AND\r\n    CASE WHEN \"${LRA:text}\" LIKE \"NDR\" OR \"${Sendung:text}\" LIKE \"NDR Fernsehen\"\r\n      THEN\r\n      target_group LIKE \"NDR Gebiet\"\r\n      OR target_group LIKE \"Niedersachsen\"\r\n      OR target_group LIKE \"Schleswig-Holstein\"\r\n      OR target_group LIKE \"Mecklenburg-Vorpommern\"\r\n      OR target_group LIKE \"Hamburg\"\r\n      OR target_group LIKE \"Bremen\"\r\n      OR target_group LIKE \"%BRD%\"\r\n    WHEN \"${LRA:text}\" LIKE \"MDR\"\r\n      THEN\r\n      target_group LIKE \"MDR-Gebiet Z3+\"\r\n      OR target_group LIKE \"Sachsen\"\r\n      OR target_group LIKE \"Thüringen\"\r\n      OR target_group LIKE \"Sachsen-Anhalt\"\r\n      OR target_group LIKE \"%BRD%\"\r\n    WHEN \"${LRA:text}\" LIKE \"ARD\" --OR \"${Sendung:text}\" NOT LIKE \"NDR Fernsehen\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n    WHEN \"${LRA:text}\" LIKE \"Sender\" \r\n      THEN  target_group LIKE \"Baden-Württemberg\"\r\n      OR target_group LIKE \"Bayern\"\r\n      OR target_group LIKE \"Berlin\"\r\n      OR target_group LIKE \"Brandenburg\"\r\n      OR target_group LIKE \"Bremen\"\r\n      OR target_group LIKE \"Hamburg\"\r\n      OR target_group LIKE \"Hessen\"\r\n      OR target_group LIKE \"Mecklenburg-Vorpommern\"\r\n      OR target_group LIKE \"Niedersachsen\"\r\n      OR target_group LIKE \"Nordrhein-Westfalen\"\r\n      OR target_group LIKE \"Rheinland-Pfalz\"\r\n      OR target_group LIKE \"Saarland\"\r\n      OR target_group LIKE \"Sachsen\"\r\n      OR target_group LIKE \"Sachsen-Anhalt\"\r\n      OR target_group LIKE \"Schleswig-Holstein\"\r\n      OR target_group LIKE \"Thüringen\"\r\n      OR target_group LIKE \"%BRD%\"\r\n      OR target_group LIKE \"RBB Gebiet\"\r\n      OR target_group LIKE \"SW Gebiet\"\r\n    END\r\n    AND CASE \"${LRA:text}\"\r\n    WHEN \"MDR\" THEN True\r\n    ELSE  1 = CASE WHEN \"${special_region}\" LIKE \"\" THEN 1 ELSE 0 END\r\n    END\r\nORDER BY \r\n  CASE zg\r\n    WHEN \"BRD gesamt\" THEN 1\r\n    WHEN \"BRD West\" THEN 2\r\n    WHEN \"BRD Ost\" THEN 3\r\n    WHEN \"NDR Gebiet\" THEN 4\r\n    WHEN \"MDR Gebiet\" THEN 5\r\n    WHEN \"Niedersachsen\" THEN 6\r\n    WHEN \"Schleswig-Holstein\" THEN 7\r\n    WHEN \"Mecklenburg-Vorpommern\" THEN 8\r\n    WHEN \"Hamburg\" THEN 9\r\n    WHEN \"Bremen\" THEN 10\r\n    WHEN \"Sachsen\" THEN 11\r\n    WHEN \"Sachsen-Anhalt\" THEN 12\r\n    WHEN \"Thüringen\" THEN 13\r\n  END"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
   "options": {
    "content": "###### Zusammensetzung $SehbOderSeher nach Sendegebieten | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR | $date_range"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n  AND\r\n    CASE WHEN \"${LRA:text}\" LIKE \"NDR\" OR \"${Sendung:text}\" LIKE \"NDR Fernsehen\"\r\n      THEN\r\n      target_group LIKE \"Niedersachsen\"\r\n      OR target_group LIKE \"Schleswig-Holstein\"\r\n      OR target_group LIKE \"Mecklenburg-Vorpommern\"\r\n      OR target_group LIKE \"Hamburg\"\r\n      OR target_group LIKE \"Bremen\"\r\n    WHEN \"${LRA:text}\" LIKE \"MDR\"\r\n      THEN\r\n      target_group LIKE \"Sachsen\"\r\n      OR target_group LIKE \"Thüringen\"\r\n      OR target_group LIKE \"Sachsen-Anhalt\"\r\n    WHEN \"${LRA:text}\" LIKE \"ARD\" OR \"${Sendung:text}\" NOT LIKE \"NDR Fernsehen\"\r\n      THEN target_group LIKE \"BRD %st\"\r\n    END\r\n  AND 1 = CASE WHEN \"${special_region}\" LIKE \"\" THEN 1 ELSE 0 END\r\nORDER BY \r\n  CASE zg\r\n    WHEN \"BRD West\" THEN 2\r\n    WHEN \"BRD Ost\" THEN 3\r\n    WHEN \"Niedersachsen\" THEN 6\r\n    WHEN \"Schleswig-Holstein\" THEN 7\r\n    WHEN \"Mecklenburg-Vorpommern\" THEN 8\r\n    WHEN \"Hamburg\" THEN 9\r\n    WHEN \"Bremen\" THEN 10\r\n    WHEN \"Sachsen\" THEN 11\r\n    WHEN \"Sachsen-Anhalt\" THEN 12\r\n    WHEN \"Thüringen\" THEN 13\r\n  END"
    }
   ]
  },
  {
   "title": "Übersicht Altersgruppen | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR | $date_range",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 46 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\ndistinct\r\n  target_group as zg,\r\n  market_share as ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` as data\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n  AND target_group NOT LIKE \"Erw. ab 14 J.\"\r\n  AND (target_group LIKE \"%Erw.%\"\r\n  OR target_group LIKE \"Kinder%\"\r\n  OR target_group LIKE \"Zuschauer gesamt\"\r\n  OR target_group LIKE \"MDR-Gebiet Z3+\"\r\n   OR CASE \"${Sendung:text}\"\r\n  WHEN \"MDR Sachsen-Anhalt heute\" THEN target_group = \"Sachsen-Anhalt\"\r\n  WHEN \"MDR Sachsenspiegel\" THEN target_group = \"Sachsen\"\r\n  WHEN \"MDR Thüringen Journal\" THEN target_group = \"Thüringen\"\r\n  END\r\n  )\r\nORDER BY target_group ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 46 },
   "options": {
    "content": "###### Zusammensetzung $SehbOderSeher nach Altersgruppen | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR | $date_range"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 49 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN viewers\r\n    ELSE sehbeteiligung\r\n  END AS sb,\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n  AND target_group NOT LIKE \"Erw. ab 50\"\r\n  AND target_group NOT LIKE \"Erw. ab 14%\"\r\n  AND target_group NOT LIKE \"Erw. 30-49\"\r\n  AND target_group NOT LIKE \"Erw. 14-49\"\r\n  AND (target_group LIKE \"%Erw.%\"\r\n  OR target_group LIKE \"Kinder 3-13\")\r\nORDER BY\r\n  CASE\r\n    WHEN target_group LIKE \"Kinder 3-13\" THEN 1\r\n    WHEN target_group LIKE \"Erw. 14-29\" THEN 2\r\n    WHEN target_group LIKE \"Erw. 30-39\" THEN 3\r\n    WHEN target_group LIKE \"Erw. 40-49\" THEN 4\r\n    WHEN target_group LIKE \"Erw. 50-64\" THEN 5\r\n    WHEN target_group LIKE \"Erw. 50-59\" THEN 6\r\n    WHEN target_group LIKE \"Erw. ab 65 \" THEN 7\r\n    WHEN target_group LIKE \"Erw. 60-69\" THEN 8\r\n    WHEN target_group LIKE \"Erw. ab 70\" THEN 9\r\n  END\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 63 },
   "options": {
    "content": "###### Zusammensetzung $SehbOderSeher nach Geschlecht | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR | $date_range"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 63 },
   "options": {
    "content": "###### Zusammensetzung $SehbOderSeher nach Bildung | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR | $date_range"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n  AND (target_group LIKE \"Frauen 14-49 J.\"\r\n  OR target_group LIKE \"Frauen ab 50 J.\"\r\n  OR target_group LIKE \"Männer 14-49 J.\"\r\n  OR target_group LIKE \"Männer ab 50 J.\")\r\n  --AND target_group LIKE \"%Kinder 3-13\"\r\nORDER BY target_group asc"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n  AND (target_group LIKE \"Volks%\"\r\n  OR target_group LIKE \"Weiterf. Schule\"\r\n  OR target_group LIKE \"Abitur, Hochschule, Studium\")\r\nORDER BY \r\n  CASE target_group\r\n    WHEN \"Volks%\" THEN 1\r\n    WHEN \"Weiterf. Schule\" THEN 2\r\n    WHEN \"Abitur, Hochschule, Studium\" THEN 3\r\n  END"
    }
   ]
  },
  { "title": "Digital Media Types", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 82 },
   "options": {
    "content": "## <span style=\"color:#BC4542\"><b>Hinweis</b></span>\n\n### Die Darstellung der DMTs wird erst angezeigt, wenn 10 oder mehr $sendung_or_sendetag verfügbar sind. Für ${Sendung:text} sind gerade ${numShows} $sendung_or_sendetag verfügbar."
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 11, "x": 13, "y": 82 } },
  { "type": "text", "gridPos": { "h": 3, "w": 11, "x": 13, "y": 83 }, "options": { "content": "### ${special_region_dmt}" } },
  {
   "title": "Digital Media Types | ${LRA:text} | $Sendung | $BRD_or_NDR | $date_range",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DISTINCT\r\n  target_group as zg, \r\n  market_share as ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName,\r\n  (SELECT market_share FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\n   WHERE target_group = \"Erw. ab 14 J.\" AND show = \"${Sendung:text}\" AND year = \"$Jahr\") AS ma_erw_14\r\nFROM \r\n  `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\nWHERE \r\n  target_group IN (\r\n    \"Vereinfachende\",\r\n    \"Ablenkungssuchende\",\r\n    \"Ambitionierte\",\r\n    \"Neokulturelle\",\r\n    \"Selbstgenügsame\",\r\n    \"Sicherheitsorientierte\", \r\n    \"Traditionsbewusste\",\r\n    \"Verantwortungsvolle\", \r\n    \"Gleichmütige\"\r\n  )\r\n  AND 1 = CASE WHEN $numShows > 9 THEN 1 ELSE 0 END\r\n  AND 2 = CASE \r\n            WHEN \"$special_region\" LIKE \"\" THEN 2\r\n            WHEN \"$special_region\" IN (\"Sachsen\", \"Sachsen-Anhalt\", \"Thüringen\") THEN 2\r\n            ELSE 0 \r\n          END\r\n  AND show = \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\nORDER BY $dmtOrder"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Strukturanteile Digital Media Types | ${LRA:text} | $Sendung | $BRD_or_NDR | $date_range",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT\r\n   target_group as Zielgruppe,\r\n   ROUND((sehbeteiligung / $SehbGesamt * 100)) as Reichweite,\r\n   \"$LRA\" as Sender,\r\n   \"${Sendung:text}\" as sendungsName,\r\n   \"${numShows}\" as numberShows\r\n FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\n WHERE target_group IN (\r\n    \"Vereinfachende\",\r\n    \"Ablenkungssuchende\",\r\n    \"Ambitionierte\",\r\n    \"Neokulturelle\",\r\n    \"Selbstgenügsame\",\r\n    \"Sicherheitsorientierte\", \r\n    \"Traditionsbewusste\",\r\n    \"Verantwortungsvolle\", \r\n    \"Gleichmütige\"\r\n  )\r\n   AND 1 = CASE WHEN $numShows > 9 THEN 1 ELSE 0 END\r\n    AND 2 = CASE \r\n              WHEN \"$special_region\" LIKE \"\" THEN 2\r\n              WHEN \"$special_region\" IN (\"Sachsen\", \"Sachsen-Anhalt\", \"Thüringen\") THEN 2\r\n              ELSE 0 \r\n            END\r\n   AND show like \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\nORDER BY $dmtOrder"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT\r\n target_group as Zielgruppe,\r\n ROUND((viewers / $SeherGesamt * 100)) as Reichweite,\r\n \"${numShows}\" as numberShows,\r\n CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Fernsehmarkt\\n03-03 Uhr\"\r\n    ELSE \"Fernsehmarkt zur Sendezeit\"\r\n  END as legendName,\r\n FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\n WHERE target_group IN (\r\n    \"Vereinfachende\",\r\n    \"Ablenkungssuchende\",\r\n    \"Ambitionierte\",\r\n    \"Neokulturelle\",\r\n    \"Selbstgenügsame\",\r\n    \"Sicherheitsorientierte\", \r\n    \"Traditionsbewusste\",\r\n    \"Verantwortungsvolle\", \r\n    \"Gleichmütige\"\r\n  )\r\n  AND 1 = CASE WHEN $numShows > 9 THEN 1 ELSE 0 END\r\n  AND 2 = CASE WHEN \"$special_region\" LIKE \"\" THEN 2 ELSE 0 END\r\n  AND show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n  ORDER BY $dmtOrder"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN \"-\"\r\n    ELSE target_group\r\n  END AS Zielgruppe,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN NULL\r\n    ELSE ROUND((sehbeteiligung / $SendetagGesamt * 100))\r\n  END AS Sehbeteiligung,\r\n  \"$LRA\" AS Sender,\r\n  \"${numShows}\" AS numberShows,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN 1\r\n    ELSE 0\r\n  END AS hidePanel, \r\n  $dmtOrder AS rank\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}`\r\nWHERE target_group IN (\r\n  \"Vereinfachende\",\r\n  \"Ablenkungssuchende\",\r\n  \"Ambitionierte\",\r\n  \"Neokulturelle\",\r\n  \"Selbstgenügsame\",\r\n  \"Sicherheitsorientierte\", \r\n  \"Traditionsbewusste\",\r\n  \"Verantwortungsvolle\", \r\n  \"Gleichmütige\"\r\n)\r\nAND \"${LRA:text}\" != \"Sender\" \r\nAND show LIKE \"${LRA:text}%\"\r\nAND lra LIKE \"SENDER\"\r\nAND $numShows > 9\r\nand year like \"$Jahr\"\r\nAND 2 = CASE WHEN \"$special_region\" LIKE \"\" THEN 2 ELSE 0 END\r\nAND CASE \"${LRA:text}\"\r\nWHEN \"ARD\"\r\nTHEN show = \"ARD Das Erste\"\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 106 },
   "options": {
    "content": "## <span style=\"color:#BC4542\"><b>Hinweis</b></span>\n\n### $dmt_kennziffern_hinweis Mögliche Differenzen zu 100% entstehen durch unterjährige Fluktuationen im Panel."
   }
  },
  { "title": "Hitlisten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Hitliste $sendung_or_sendetag |  ${LRA:text} | $Sendung | $BRD_or_NDR | $date_range",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${LRA:text}\" = \"Sender\") THEN (\r\n  SELECT \r\n    --Nummer, \r\n    Sender, \r\n    Datum,\r\n    Wochentag,\r\n    REGEXP_REPLACE(FORMAT('%.3f', Seher), r'\\.', ','),\r\n    REGEXP_REPLACE(FORMAT('%.1f', Marktanteil), r'\\.', ',') AS Marktanteil\r\n  FROM (\r\n    SELECT \r\n      --ROW_NUMBER() OVER (ORDER BY -market_share) AS Nummer, \r\n      show AS Sender, \r\n      date AS Datum,\r\n      weekday AS Wochentag,\r\n      $SehbOderSeher AS Seher,\r\n      market_share AS Marktanteil\r\n    FROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_native}`\r\n    WHERE show LIKE \"${Sendung:text}\" AND year LIKE \"$Jahr\"\r\n  ) AS subquery\r\n  ORDER BY Marktanteil DESC\r\n);\r\nELSE (\r\n  SELECT \r\n    --Nummer, \r\n    Sender, \r\n    Datum,\r\n    Wochentag,\r\n    Folgentitel,\r\n    REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ',') as Sehbeteiligung,\r\n    REGEXP_REPLACE(FORMAT('%.1f', Marktanteil), r'\\.', ',') AS Marktanteil\r\n  FROM (\r\n    SELECT \r\n      ROW_NUMBER() OVER (ORDER BY -sehbeteiligung, -market_share) AS Nummer, \r\n      lra AS Sender, \r\n      date AS Datum,\r\n      weekday AS Wochentag,\r\n      title AS Folgentitel,\r\n      sehbeteiligung AS Sehbeteiligung,\r\n      market_share AS Marktanteil\r\n    FROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_native}`\r\n    WHERE show LIKE \"${Sendung:text}\" AND year LIKE \"$Jahr\"\r\n  ) AS subquery\r\n  ORDER BY Marktanteil DESC\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "$sendung_or_sendetag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 124 },
   "options": {
    "content": "## <span style=\"color:#BC4542\"><b>Hinweis</b></span>\n\n### Der Wert der Durchschnittslinie bezieht sich auf das aktuelle Jahr."
   }
  },
  {
   "title": "$sendung_or_sendetag im Zeitverlauf | $LRA | $Sendung | $BRD_or_NDR | $date_range",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  PARSE_DATE(\"%d.%m.%Y\", date) as datum,\r\n  ROUND(market_share, 3) as ma,\r\n  ROUND($SehbOderSeher, 3) as sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN $seherDurchschnitt\r\n    ELSE $sehbDurchschnitt\r\n  END as reichweiteDurchschnitt,\r\n  $marktanteilDurchschnitt as marktanteilDurchschnitt\r\nFROM\r\n  `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_native}`\r\nWHERE show = \"${Sendung:text}\" and year like \"$Jahr\"\r\nORDER BY datum ASC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Monatsdurchschnitte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 145 },
   "options": {
    "content": "###### Marktanteil (%) Aktuelles Jahr vs. Vorjahr | ${LRA:text} | $Sendung | $BRD_or_NDR | $date_range"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 145 },
   "options": {
    "content": "###### $SehbOderSeher (Mio.) Aktuelles Jahr vs. Vorjahr | ${LRA:text}  | $Sendung | $BRD_or_NDR | $date_range"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nROUND(market_share, 1) as ma,\r\nmonth as mon,\r\nyear as jahre,\r\n\"$Jahr\" as aktuelles_jahr,\r\n\"$LastJahr\" as vor_jahr\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${monatswerte_native}`\r\nWHERE show like \"${Sendung:name}\" AND (year LIKE \"$Jahr\" OR year LIKE \"$LastJahr\")\r\nORDER BY \r\n  CASE mon\r\n    WHEN \"Januar\" THEN 1\r\n    WHEN \"Februar\" THEN 2\r\n    WHEN \"März\" THEN 3\r\n    WHEN \"April\" THEN 4\r\n    WHEN \"Mai\" THEN 5\r\n    WHEN \"Juni\" THEN 6\r\n    WHEN \"Juli\" THEN 7\r\n    WHEN \"August\" THEN 8\r\n    WHEN \"September\" THEN 9\r\n    WHEN \"Oktober\" THEN 10\r\n    WHEN \"November\" THEN 11\r\n    WHEN \"Dezember\" THEN 12\r\n  END\r\n-- LIMIT 10"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nROUND(sehbeteiligung, 3) as sb,\r\nmonth as mon,\r\nyear as jahre,\r\n\"$Jahr\" as aktuelles_jahr,\r\n\"$LastJahr\" as vor_jahr\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${monatswerte_native}`\r\nWHERE show LIKE \"${Sendung:text}\" AND (year LIKE \"$Jahr\" OR year LIKE \"$LastJahr\")\r\nORDER BY \r\n  CASE mon\r\n    WHEN \"Januar\" THEN 1\r\n    WHEN \"Februar\" THEN 2\r\n    WHEN \"März\" THEN 3\r\n    WHEN \"April\" THEN 4\r\n    WHEN \"Mai\" THEN 5\r\n    WHEN \"Juni\" THEN 6\r\n    WHEN \"Juli\" THEN 7\r\n    WHEN \"August\" THEN 8\r\n    WHEN \"September\" THEN 9\r\n    WHEN \"Oktober\" THEN 10\r\n    WHEN \"November\" THEN 11\r\n    WHEN \"Dezember\" THEN 12\r\n  END\r\n-- LIMIT 10"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Vergleichssender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "Top 10 Sender zur Sendezeit nach Marktanteil (%) | $LRA | $Sendung | $BRD_or_NDR | $date_range",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 160 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\ncomparison_sender as Vergleichssender,\r\nROUND(market_share, 1) as Marktanteil,\r\nlra as lra,\r\nshow as sendung\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${vergleichssender_native}`\r\nWHERE show like \"${Sendung}\" and year like \"$Jahr\"\r\nORDER BY Marktanteil DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Glossar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 175 },
   "options": {
    "content": "# Sehbeteiligung (Mio.)\n\nAnzahl der Zuschauer einer Zielgruppe, die anteilig ihrer Nutzungsdauer gezählt werden"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 175 },
   "options": {
    "content": "# Marktanteil\n\nGibt den prozentualen Anteil der durchschnittlichen Sehbeteiligung einer Sendung oder Zeitintervalls an der Sehbeteiligung TV Gesamt zum Zeitpunkt an"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 175 },
   "options": {
    "content": "# Seher (Mio.)\n\nPersonen, die sich für mindestens eine Minute in das Programm eingeschaltet haben"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 175 },
   "options": {
    "content": "# Verweildauer\n\nVerweildauer in Minuten (Durchschnittliche Sehdauer der Zuschauer die mindestens 1 Minute ohne Unterbrechung geschaut haben)"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  }
 ]
}