{
 "title": "TV-Quotenreport Sender",
 "description": "Quotenreport Sender 1259",
 "time": { "from": "2023-11-30T10:08:12.740Z", "to": "2023-12-02T10:08:12.740Z" },
 "templating": {
  "list": [
   { "name": "LRA", "query": "Sender : sender" },
   {
    "name": "date_range",
    "query": {}
   },
   {
    "name": "date_range_monthly",
    "query": {}
   },
   {
    "name": "date_range_monthly_last_year",
    "query": {}
   },
   {
    "name": "Sendung",
    "query": {}
   },
   {
    "name": "SehbOderSeher",
    "query": {}
   },
   {
    "name": "ndrOderGesamt",
    "query": {}
   },
   {
    "name": "Jahr",
    "query": {}
   },
   {
    "name": "LastJahr",
    "query": {}
   },
   {
    "name": "LastLastJahr",
    "query": {}
   },
   {
    "name": "numShows",
    "query": {}
   },
   {
    "name": "BRD_or_NDR",
    "query": {}
   },
   {
    "name": "BRD_or_NDR_text",
    "query": {}
   },
   {
    "name": "BRD_or_none",
    "query": {}
   },
   {
    "name": "jahrHidden",
    "query": {}
   },
   {
    "name": "lastJahrHidden",
    "query": {}
   },
   {
    "name": "lastJahrHiddenMDR",
    "query": {}
   },
   {
    "name": "lastLastJahrHidden",
    "query": {}
   },
   {
    "name": "lastLastJahrHiddenMDR",
    "query": {}
   },
   {
    "name": "zielgruppen_und_facts",
    "query": {}
   },
   {
    "name": "zielgruppen_und_facts_monthly",
    "query": {}
   },
   {
    "name": "sendungsliste_monthly",
    "query": {}
   },
   {
    "name": "verweildauer_monthly",
    "query": {}
   },
   {
    "name": "zeitschnitte_monthly",
    "query": {}
   },
   {
    "name": "monatswerte_monthly",
    "query": {}
   },
   {
    "name": "vergleichssender_monthly",
    "query": {}
   },
   {
    "name": "wochentage_monthly",
    "query": {}
   },
   {
    "name": "SehbGesamt",
    "query": {}
   },
   {
    "name": "SeherGesamt",
    "query": {}
   },
   {
    "name": "SendetagGesamt",
    "query": {}
   },
   {
    "name": "special_region",
    "query": {}
   },
   {
    "name": "dmt_kennziffern_hinweis",
    "query": {}
   },
   {
    "name": "dmtOrder",
    "query": "CASE target_group\n    WHEN \"Vereinfachende\" THEN 1\n    WHEN \"Ablenkungssuchende\" THEN 2\n    WHEN \"Ambitionierte\" THEN 3\n    WHEN \"Neokulturelle\" THEN 4\n    WHEN \"Selbstgenügsame\" THEN 5\n    WHEN \"Sicherheitsorientierte\" THEN 6\n    WHEN \"Traditionsbewusste\" THEN 7\n    WHEN \"Verantwortungsvolle\" THEN 8\n    WHEN \"Gleichmütige\" THEN 9\nEND"
   },
   {
    "name": "sehbDurchschnitt",
    "query": {}
   },
   {
    "name": "seherDurchschnitt",
    "query": {}
   },
   {
    "name": "marktanteilDurchschnitt",
    "query": {}
   },
   {
    "name": "special_region_dmt",
    "query": {}
   },
   {
    "name": "gesamtjahre_hidden",
    "query": {}
   },
   {
    "name": "gesamtjahre_hidden_monat",
    "query": {}
   },
   {
    "name": "sendung_or_sendetag",
    "query": {}
   },
   {
    "name": "special_region_aufkleber",
    "query": {}
   },
   {
    "name": "table_prefix",
    "query": {}
   },
   {
    "name": "verweildauer_native",
    "query": "verweildauer_native : ${table_prefix}verweildauer_native"
   },
   {
    "name": "sendungsliste_native",
    "query": "sendungsliste_native : ${table_prefix}sendungsliste_native"
   },
   {
    "name": "monatswerte_native",
    "query": "monatswerte_native : ${table_prefix}monatswerte_native"
   },
   {
    "name": "vergleichssender_native",
    "query": "vergleichssender_native : ${table_prefix}vergleichssender_native"
   },
   {
    "name": "hinweis_regionalmagazin",
    "query": {}
   },
   {
    "name": "hinweis_regionalmagazin_top",
    "query": {}
   },
   {
    "name": "Monat",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "label": "Monat",
    "query": {}
   },
   {
    "name": "src_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<font size=\"6\" color=\"#2671c6\" style=\"font-weight:bold;\">Marktstandard Bewegtbild – lineare TV-Nutzung inkl. 24/7-Livestream</font>\r\n\r\n<font size=\"6\" style=\"font-weight:bold;\">${LRA:text} | $Sendung | Stand: $date_range_monthly </font>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "options": {
    "content": "<img \n  src=\"${src_url}\" \n  alt=\"Tracking Pixel\" \n  width=\"1\" \n  height=\"1\" \n  style=\"display:none;\"\n/>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 4 },
   "options": {
    "content": "#### Aktualisierung erfolgt am 09. jedes Monats"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "options": {
    "content": "##### <b>Nur zur ARD-internen Verwendung</b>"
   }
  },
  { "title": "Jahresdaten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "options": {
    "content": "</br><center><font size=\"5\" style=\"font-weight:bold;\">Anzahl $sendung_or_sendetag</font></center>"
   }
  },
  {
   "title": "$date_range_monthly:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Quotenreport_Sample",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(title) as Sendungen\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_monthly}`\r\nWHERE\r\nshow = \"${Sendung:text}\"\r\nAND year like \"$Jahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "Gesamtjahr $LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Quotenreport_Sample",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(title) as Sendungen\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_native}`\r\nWHERE\r\nCASE WHEN \"${LRA}\" like \"sender\"\r\nTHEN\r\n  lra like \"SENDER\" and broadcaster_short like \"NDR FS\"\r\nELSE show = \"${Sendung:text}\"\r\nEND\r\nAND year like \"$LastJahr\""
    }
   ]
  },
  {
   "title": "Gesamtjahr $LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Quotenreport_Sample",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(title) as Sendungen\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_native}`\r\nWHERE\r\nCASE WHEN \"${LRA}\" like \"sender\"\r\nTHEN\r\n  lra like \"SENDER\" and broadcaster_short like \"NDR FS\"\r\nELSE show = \"${Sendung:text}\"\r\nEND\r\nAND year like \"$LastLastJahr\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "description": "Anzahl der Zuschauer einer Zielgruppe, die anteilig ihrer Nutzungsdauer gezählt werden",
   "gridPos": { "h": 2, "w": 5, "x": 2, "y": 10 },
   "options": {
    "content": "\n<center><font size=\"5\" style=\"font-weight:bold;\">   Sehbeteiligung (Mio.)</font></center>\n"
   }
  },
  {
   "type": "text",
   "description": "Gibt den prozentualen Anteil der durchschnittlichen Sehbeteiligung einer Sendung oder Zeitintervalls an der Sehbeteiligung TV Gesamt zum Zeitpunkt an",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 10 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Marktanteil (%)</font></center>"
   }
  },
  {
   "type": "text",
   "description": "Personen, die sich für mindestens eine Minute in das Programm eingeschaltet haben",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 10 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Seher (Mio.)</font></center>"
   }
  },
  {
   "type": "text",
   "description": "Verweildauer in Minuten (Durchschnittliche Sehdauer der Zuschauer die mindestens 1 Minute ohne Unterbrechung geschaut haben)",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 10 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Verweildauer</font></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 10 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Durchschnittsalter</font></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": {
    "content": "\n<font size=\"5\" color=\"#2671c6\" style=\"font-weight:bold;\">${BRD_or_NDR_text}</font>"
   }
  },
  {
   "title": "$date_range_monthly:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n)\r\n as Sehbeteiligung\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung:text}\"\r\nAND year like \"$Jahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "$date_range_monthly:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(market_share,2) as STRING),'%') as Marktanteil\r\nCONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year LIKE \"$Jahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND \r\n"
    }
   ]
  },
  {
   "title": "$date_range_monthly:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(viewers,3) AS STRING), ' Mio.') as Seher\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', viewers), r'\\.', ','), \r\n  ' Mio.'\r\n) as Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$Jahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "$date_range_monthly:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  (EXTRACT(HOUR FROM PARSE_TIME('%H:%M:%S', watch_time))*3600) + \r\n  (EXTRACT(MINUTE FROM PARSE_TIME('%H:%M:%S', watch_time))*60) + \r\n  (EXTRACT(SECOND FROM PARSE_TIME('%H:%M:%S', watch_time))) as Verweildauer\r\nFROM \r\n  `ndr-code-bi-dashboard.Quotenreport.${verweildauer_monthly}` \r\nWHERE \r\n  show LIKE \"${Sendung}\"\r\n  AND year like \"$Jahr\"\r\n  AND CASE \"${table_prefix}\" \r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "$date_range_monthly:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT ROUND(average_age,0) as Durchschnittsalter\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$Jahr\"\r\n--AND lra like \"${LRA:text}\" \r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 15 },
   "options": {
    "content": "<font size=\"3\" color=\"#4d86c7\" style=\"font-weight:bold;\"><i>Gesamtjahre</i></font>"
   }
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as sb\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND year = \"$LastJahr\"\r\nAND show LIKE \"${Sendung:text}\"\r\n-- remove\r\nAND show not like \"Rote Rosen\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 0.331026659685 as Sehbeteiligung\r\n);\r\nELSE ( \r\n  SELECT \r\n   CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) AS Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE\r\n    target_group LIKE \"${BRD_or_NDR}%\"\r\n    AND year = \"$LastLastJahr\"\r\n    AND show LIKE \"${Sendung:text}\"\r\n    -- remove after data fix\r\n    -- AND show NOT LIKE \"Extra3\"\r\n    -- AND show NOT LIKE \"Weltspiegel\"\r\n    -- AND show NOT LIKE \"Zoodokus\"\r\n    -- AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(market_share,1) as STRING),'%') as Marktanteil\r\nCONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year LIKE \"$LastJahr\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 14.985605308226 as Marktanteil\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) as STRING),'%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year LIKE \"$LastLastJahr\"\r\n  --AND show NOT LIKE \"Extra3\"\r\n  ---AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(viewers,3) AS STRING), ' Mio.') as Seher\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', viewers), r'\\.', ','), \r\n  ' Mio.'\r\n)\r\n as Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$LastJahr\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 0.828348250387 as Seher\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(viewers,3) AS STRING), ' Mio.') as Seher\r\n CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', viewers), r'\\.', ','), \r\n  ' Mio.'\r\n)\r\n as Seher\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year like \"$LastLastJahr\"\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Nrdt. Factual Entertainment\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  (EXTRACT(HOUR FROM PARSE_TIME('%H:%M:%S', watch_time))*3600) + \r\n  (EXTRACT(MINUTE FROM PARSE_TIME('%H:%M:%S', watch_time))*60) + \r\n  (EXTRACT(SECOND FROM PARSE_TIME('%H:%M:%S', watch_time))) as Verweildauer\r\nFROM \r\n  `ndr-code-bi-dashboard.Quotenreport.${verweildauer_native}` \r\nWHERE \r\n  show LIKE \"${Sendung}\"\r\n  AND year like \"$LastJahr\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT \"00:51:39\" as Verweildauer\r\n);\r\nELSE ( \r\n  SELECT \r\n    (EXTRACT(HOUR FROM PARSE_TIME('%H:%M:%S', watch_time))*3600) + \r\n    (EXTRACT(MINUTE FROM PARSE_TIME('%H:%M:%S', watch_time))*60) + \r\n    (EXTRACT(SECOND FROM PARSE_TIME('%H:%M:%S', watch_time))) as Verweildauer\r\n  FROM \r\n    `ndr-code-bi-dashboard.Quotenreport.${verweildauer_native}` \r\n  WHERE \r\n    show LIKE \"${Sendung}\"\r\n    AND year like \"$LastLastJahr\"\r\n    --remove after data fix\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Nrdt. Factual Entertainment\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT ROUND(average_age,0) as Durchschnittsalter\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$LastJahr\"\r\n--remove\r\nAND show not like \"Schleswig-Holstein Magazin\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 71.540083717991 as Durchschnittsalter\r\n);\r\nELSE ( \r\n  SELECT ROUND(average_age,0) as Durchschnittsalter\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year like \"$LastLastJahr\"\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 18 },
   "options": {
    "content": "<font size=\"3\" color=\"#4d86c7\" style=\"font-weight:bold;\"><i>Januar - ${Zeitraum:text} </i></font>"
   }
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as sb\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\n FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}`\r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND year = \"$LastJahr\"\r\nAND show LIKE \"${Sendung:text}\"\r\n-- remove\r\nAND show not like \"Rote Rosen\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 0.331026659685 as Sehbeteiligung\r\n);\r\nELSE ( \r\n  SELECT \r\n   CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) AS Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE\r\n    target_group LIKE \"${BRD_or_NDR}%\"\r\n    AND year = \"$LastLastJahr\"\r\n    AND show LIKE \"${Sendung:text}\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n    -- remove after data fix\r\n    -- AND show NOT LIKE \"Extra3\"\r\n    -- AND show NOT LIKE \"Weltspiegel\"\r\n    -- AND show NOT LIKE \"Zoodokus\"\r\n    -- AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(market_share,1) as STRING),'%') as Marktanteil\r\nCONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year LIKE \"$LastJahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 14.985605308226 as Marktanteil\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) as STRING),'%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year LIKE \"$LastLastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  --AND show NOT LIKE \"Extra3\"\r\n  ---AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT --CONCAT(CAST(ROUND(viewers,3) AS STRING), ' Mio.') as Seher\r\nCONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', viewers), r'\\.', ','), \r\n  ' Mio.'\r\n)\r\n as Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$LastJahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 0.828348250387 as Seher\r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(viewers,3) AS STRING), ' Mio.') as Seher\r\n CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', viewers), r'\\.', ','), \r\n  ' Mio.'\r\n)\r\n as Seher\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year like \"$LastLastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Nrdt. Factual Entertainment\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  (EXTRACT(HOUR FROM PARSE_TIME('%H:%M:%S', watch_time))*3600) + \r\n  (EXTRACT(MINUTE FROM PARSE_TIME('%H:%M:%S', watch_time))*60) + \r\n  (EXTRACT(SECOND FROM PARSE_TIME('%H:%M:%S', watch_time))) as Verweildauer\r\nFROM \r\n  `ndr-code-bi-dashboard.Quotenreport.${verweildauer_monthly}` \r\nWHERE  \r\n  show LIKE \"${Sendung}\"\r\n  AND year like \"$LastJahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT \"00:51:39\" as Verweildauer\r\n);\r\nELSE ( \r\n  SELECT \r\n    (EXTRACT(HOUR FROM PARSE_TIME('%H:%M:%S', watch_time))*3600) + \r\n    (EXTRACT(MINUTE FROM PARSE_TIME('%H:%M:%S', watch_time))*60) + \r\n    (EXTRACT(SECOND FROM PARSE_TIME('%H:%M:%S', watch_time))) as Verweildauer\r\n  FROM \r\n    `ndr-code-bi-dashboard.Quotenreport.${verweildauer_monthly}` \r\n  WHERE \r\n    show LIKE \"${Sendung}\"\r\n    AND year like \"$LastLastJahr\"\r\n        AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n    --remove after data fix\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Nrdt. Factual Entertainment\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT ROUND(average_age,0) as Durchschnittsalter\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\nWHERE\r\ntarget_group = \"${BRD_or_NDR}\"\r\nAND show like \"${Sendung}\"\r\nAND year like \"$LastJahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n--remove\r\nAND show not like \"Schleswig-Holstein Magazin\""
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Special case for Riverboat 2024: show had a different name in 2022, so data for that year does not exist in dataset\r\nIF (\"${Sendung:text}\" = \"Riverboat\" AND $Jahr = 2024) THEN (\r\n  SELECT 71.540083717991 as Durchschnittsalter\r\n);\r\nELSE ( \r\n  SELECT ROUND(average_age,0) as Durchschnittsalter\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE\r\n  target_group = \"${BRD_or_NDR}\"\r\n  AND show like \"${Sendung}\"\r\n  AND year like \"$LastLastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  --AND show NOT LIKE \"Extra3\"\r\n  --AND show NOT LIKE \"Weltspiegel\"\r\n  --AND show NOT LIKE \"Zoodokus\"\r\n  --AND show NOT LIKE \"Dokumentationen und Service\"\r\n);\r\nEND IF;"
    }
   ]
  },
  {
   "type": "text",
   "description": "Ergebnisse für BRD gesamt werden nur für NDR & MDR angezeigt.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": {
    "content": "\n<font size=\"5\" color=\"#2671c6\" style=\"font-weight:bold;\">${BRD_or_none}</font>"
   }
  },
  {
   "title": "$jahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\n  CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$Jahr\" \r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$jahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) AS STRING), '%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$Jahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 24 },
   "options": {
    "content": "\n<font size=\"3\" color=\"#4d86c7\" style=\"font-weight:bold;\"><i>$gesamtjahre_hidden</i></font>"
   }
  },
  {
   "title": "$lastJahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nIF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\n  CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastJahr\"\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$lastLastJahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nIF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\n  CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastLastJahr\"\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$lastJahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) AS STRING), '%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastJahr\"\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$lastLastJahrHidden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) AS STRING), '%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastLastJahr\"\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 2, "x": 1, "y": 26 }, "options": { "content": "\n" } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 27 },
   "options": {
    "content": "\n<font size=\"3\" color=\"#4d86c7\" style=\"font-weight:bold;\"><i>$gesamtjahre_hidden_monat</i></font>"
   }
  },
  {
   "title": "$lastJahrHiddenMDR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nIF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" OR \"${Sendung:text}\"  LIKE \"MDR%\" ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\n  CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$lastLastJahrHiddenMDR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Mio." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nIF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" OR \"${Sendung:text}\"  LIKE \"MDR%\"  ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(sehbeteiligung,3) AS STRING), ' Mio.') as Sehbeteiligung\r\n  CONCAT(\r\n  REGEXP_REPLACE(FORMAT('%.3f', sehbeteiligung), r'\\.', ','), \r\n  ' Mio.'\r\n) as Sehbeteiligung\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastLastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$lastJahrHiddenMDR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\"  OR \"${Sendung:text}\"  LIKE \"MDR%\" ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) AS STRING), '%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$lastLastJahrHiddenMDR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${BRD_or_none}\" NOT LIKE \"BRD Gesamt\" OR \"${Sendung:text}\"  LIKE \"MDR%\"  ) THEN (\r\n  SELECT \"\" as INVALID \r\n);\r\nELSE ( \r\n  SELECT --CONCAT(CAST(ROUND(market_share,1) AS STRING), '%') as Marktanteil\r\n  CONCAT(REGEXP_REPLACE(FORMAT('%.1f', market_share), r'\\.', ','), \"%\")\r\n as Marktanteil\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  WHERE target_group = \"BRD gesamt\" AND show like \"${Sendung}\" AND year like \"$LastLastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Zielgruppen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "## <span style=\"color:#BC4542\"><b>$hinweis_regionalmagazin_top</b></span>\n\n### $hinweis_regionalmagazin $special_region_aufkleber"
   }
  },
  {
   "title": "Übersicht Sendegebiete | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 35 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH sender AS(\r\n  SELECT\r\n  target_group as zg,\r\n  market_share as ma,\r\n seher as sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.ndr_gcs_bundeslaender_monthly_f` as data\r\nWHERE\r\n  show = \"${Sendung}\"\r\n  and year like \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND AND CASE\r\nWHEN \"${Sendung:text}\" LIKE \"BR-Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group LIKE \"Bayern\"\r\n    WHEN \"${Sendung:text}\" LIKE \"hr-fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group LIKE \"Hessen\"\r\n    WHEN \"${Sendung:text}\" LIKE \"WDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group LIKE \"Nordrhein-Westfalen\"\r\n    WHEN \"${Sendung:text}\" LIKE \"RBB Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group IN (\"RBB Gebiet\", \"Berlin\", \"Brandenburg\") \r\n    WHEN \"${Sendung:text}\" LIKE \"SW Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group IN (\"SW Gebiet\", \"Baden-Württemberg\", \"Rheinland-Pfalz\", \"Saarland\") \r\n    WHEN \"${Sendung:text}\" LIKE \"MDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group IN (\"MDR Gebiet\", \"Sachsen\", \"Sachsen-Anhalt\", \"Thüringen\") \r\n    WHEN \"${LRA:text}\" LIKE \"ARD\" OR \"${Sendung:text}\" NOT LIKE \"NDR Fernsehen\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n    --  OR target_group LIKE \"Bayern\"\r\n    END\r\nORDER BY 1\r\n), \r\nbase_data AS (\r\nSELECT\r\ntarget_group as zg,\r\n  market_share as ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` as data\r\nWHERE\r\n  show = \"${Sendung}\"\r\n  and year like \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND\r\n    CASE WHEN \"${LRA:text}\" LIKE \"NDR\" OR \"${Sendung:text}\" LIKE \"NDR Fernsehen\"\r\n      THEN\r\n      target_group LIKE \"NDR Gebiet\"\r\n      OR target_group LIKE \"Niedersachsen\"\r\n      OR target_group LIKE \"Schleswig-Holstein\"\r\n      OR target_group LIKE \"Mecklenburg-Vorpommern\"\r\n      OR target_group LIKE \"Hamburg\"\r\n      OR target_group LIKE \"Bremen\"\r\n      OR target_group LIKE \"%BRD%\"\r\n    WHEN \"${LRA:text}\" LIKE \"MDR\"\r\n      THEN\r\n      target_group LIKE \"MDR-Gebiet Z3+\"\r\n      OR target_group LIKE \"Sachsen\"\r\n      OR target_group LIKE \"Thüringen\"\r\n      OR target_group LIKE \"Sachsen-Anhalt\"\r\n      OR target_group LIKE \"%BRD%\"\r\n      OR target_group LIKE \"MDR Gebiet\"\r\n    WHEN \"${Sendung:text}\" LIKE \"BR-Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group LIKE \"Bayern\"\r\n    WHEN \"${Sendung:text}\" LIKE \"hr-fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group LIKE \"Hessen\"\r\n    WHEN \"${Sendung:text}\" LIKE \"WDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group LIKE \"Nordrhein-Westfalen\"\r\n    WHEN \"${Sendung:text}\" LIKE \"RBB Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group IN (\"RBB Gebiet\", \"Berlin\", \"Brandenburg\") \r\n    WHEN \"${Sendung:text}\" LIKE \"SW Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group IN (\"SW Gebiet\", \"Baden-Württemberg\", \"Rheinland-Pfalz\", \"Saarland\") \r\n    WHEN \"${Sendung:text}\" LIKE \"MDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n      OR target_group IN (\"MDR-Gebiet Z3+\", \"Sachsen\", \"Sachsen-Anhalt\", \"Thüringen\") \r\n    WHEN \"${LRA:text}\" LIKE \"ARD\" OR \"${Sendung:text}\" NOT LIKE \"NDR Fernsehen\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n    --  OR target_group LIKE \"Bayern\"\r\n    END\r\n    AND CASE \"${LRA:text}\"\r\n    WHEN \"MDR\" THEN True\r\n    ELSE  1 = CASE WHEN \"${special_region}\" LIKE \"\" THEN 1 ELSE 0 END\r\n    END\r\n)\r\nSELECT CASE zg\r\n  WHEN \"MDR-Gebiet Z3+\"\r\n  THEN \"MDR Gebiet\"\r\n  ELSE zg \r\n  END as zg, MAX(sb) as sb, MAX(ma) as ma, MAX(legendName) as legendName\r\nFROM (\r\nSELECT DISTINCT * FROM base_data \r\nUNION ALL SELECT DISTINCT * FROM sender\r\n) GROUP BY zg\r\n\r\nORDER BY \r\n  CASE zg\r\n    WHEN \"BRD gesamt\" THEN 1\r\n    WHEN \"BRD West\" THEN 2\r\n    WHEN \"BRD Ost\" THEN 3\r\n    WHEN \"NDR Gebiet\" THEN 4\r\n    WHEN \"MDR Gebiet\" THEN 5\r\n    WHEN \"RBB Gebiet\" THEN 6\r\n    WHEN \"SW Gebiet\" THEN 6\r\n    WHEN \"Niedersachsen\" THEN 7\r\n    WHEN \"Schleswig-Holstein\" THEN 8\r\n    WHEN \"Mecklenburg-Vorpommern\" THEN 9\r\n    WHEN \"Hamburg\" THEN 10\r\n    WHEN \"Bremen\" THEN 11\r\n    WHEN \"Sachsen\" THEN 12\r\n    WHEN \"Sachsen-Anhalt\" THEN 13\r\n    WHEN \"Thüringen\" THEN 14\r\n    ELSE 100\r\n  END"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 35 },
   "options": {
    "content": "###### Zusammensetzung $SehbOderSeher nach Sendegebieten | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR_text | $date_range_monthly"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 38 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH sender AS(\r\n  SELECT\r\n  target_group as zg,\r\n  market_share as ma,\r\n seher as sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.ndr_gcs_bundeslaender_monthly_f` as data\r\nWHERE\r\n  show = \"${Sendung}\"\r\n  and year like \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND AND CASE\r\n WHEN \"${Sendung:text}\" LIKE \"BR-Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN FALSE\r\n      OR target_group LIKE \"Bayern\"\r\n  WHEN \"${Sendung:text}\" LIKE \"hr-fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n    THEN FALSE\r\n    OR target_group LIKE \"Hessen\"\r\n    \r\n  WHEN \"${Sendung:text}\" LIKE \"WDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n    THEN FALSE\r\n    OR target_group LIKE \"Nordrhein-Westfalen\"\r\n\r\n  WHEN \"${Sendung:text}\" LIKE \"RBB Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n    THEN FALSE\r\n    OR target_group IN ( \"Berlin\", \"Brandenburg\") \r\n\r\n  WHEN \"${Sendung:text}\" LIKE \"SW Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n    THEN FALSE\r\n    OR target_group IN ( \"Baden-Württemberg\", \"Rheinland-Pfalz\", \"Saarland\") \r\n\r\n  WHEN \"${Sendung:text}\" LIKE \"NDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n    THEN FALSE\r\n    OR target_group IN (\"Niedersachsen\", \"Schleswig-Holstein\", \"Mecklenburg-Vorpommern\", \"Hamburg\", \"Bremen\") \r\n\r\n  WHEN \"${LRA:text}\" LIKE \"ARD\" OR \"${Sendung:text}\" NOT LIKE \"NDR Fernsehen\"\r\n    THEN target_group LIKE \"%BRD%\"\r\n  --  OR target_group LIKE \"Bayern\"\r\n    END\r\nORDER BY 1\r\n), \r\nbase_data AS (\r\nSELECT\r\n  target_group as zg,\r\n  market_share as ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` as data\r\nWHERE\r\n  show = \"${Sendung}\"\r\n  and year like \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND\r\n    CASE WHEN \"${LRA:text}\" LIKE \"NDR\" OR \"${Sendung:text}\" LIKE \"NDR Fernsehen\"\r\n      THEN\r\n      --target_group LIKE \"NDR Gebiet\" OR\r\n      target_group LIKE \"Niedersachsen\"\r\n      OR target_group LIKE \"Schleswig-Holstein\"\r\n      OR target_group LIKE \"Mecklenburg-Vorpommern\"\r\n      OR target_group LIKE \"Hamburg\"\r\n      OR target_group LIKE \"Bremen\"\r\n    WHEN \"${LRA:text}\" LIKE \"MDR\"\r\n      THEN\r\n      target_group LIKE \"MDR-Gebiet Z3+\"\r\n      OR target_group LIKE \"Sachsen\"\r\n      OR target_group LIKE \"Thüringen\"\r\n      OR target_group LIKE \"Sachsen-Anhalt\"\r\n      OR target_group LIKE \"%BRD%\"\r\n    WHEN \"${Sendung:text}\" LIKE \"BR-Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN FALSE\r\n      OR target_group LIKE \"Bayern\"\r\n    WHEN \"${Sendung:text}\" LIKE \"hr-fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN FALSE\r\n      OR target_group LIKE \"Hessen\"\r\n    WHEN \"${Sendung:text}\" LIKE \"WDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN FALSE\r\n      OR target_group LIKE \"Nordrhein-Westfalen\"\r\n    WHEN \"${Sendung:text}\" LIKE \"RBB Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN FALSE\r\n      OR target_group IN (\"Berlin\", \"Brandenburg\") \r\n    WHEN \"${Sendung:text}\" LIKE \"SW Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN FALSE\r\n      OR target_group IN (\"Baden-Württemberg\", \"Rheinland-Pfalz\", \"Saarland\") \r\n     WHEN \"${Sendung:text}\" LIKE \"NDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN FALSE\r\n      OR target_group IN (\"Niedersachsen\", \"Schleswig-Holstein\", \"Mecklenburg-Vorpommern\", \"Hamburg\", \"Bremen\") \r\n    WHEN \"${Sendung:text}\" LIKE \"MDR Fernsehen\" AND \"${LRA:text}\" LIKE \"Sender\"\r\n      THEN FALSE\r\n      OR target_group IN (\"MDR Gebiet\", \"Sachsen\", \"Sachsen-Anhalt\", \"Thüringen\") \r\n    WHEN \"${LRA:text}\" LIKE \"ARD\" OR \"${Sendung:text}\" NOT LIKE \"NDR Fernsehen\"\r\n      THEN target_group LIKE \"%BRD%\"\r\n    --  OR target_group LIKE \"Bayern\"\r\n    END\r\n    AND CASE \"${LRA:text}\"\r\n    WHEN \"MDR\" THEN True\r\n    ELSE  1 = CASE WHEN \"${special_region}\" LIKE \"\" THEN 1 ELSE 0 END\r\n    END\r\n)\r\nSELECT zg, MAX(sb) as sb, MAX(ma) as ma, MAX(legendName) as legendName\r\nFROM (\r\nSELECT DISTINCT * FROM base_data \r\nWHERE zg != \"BRD gesamt\"   \r\nUNION ALL SELECT DISTINCT * FROM sender\r\nWHERE zg != \"BRD gesamt\"   \r\n\r\n) GROUP BY zg\r\n\r\nORDER BY \r\n  CASE zg\r\n    WHEN \"BRD gesamt\" THEN 1\r\n    WHEN \"BRD West\" THEN 2\r\n    WHEN \"BRD Ost\" THEN 3\r\n    WHEN \"NDR Gebiet\" THEN 4\r\n    WHEN \"MDR Gebiet\" THEN 5\r\n    WHEN \"Niedersachsen\" THEN 6\r\n    WHEN \"Schleswig-Holstein\" THEN 7\r\n    WHEN \"Mecklenburg-Vorpommern\" THEN 8\r\n    WHEN \"Hamburg\" THEN 9\r\n    WHEN \"Bremen\" THEN 10\r\n    WHEN \"Sachsen\" THEN 11\r\n    WHEN \"Sachsen-Anhalt\" THEN 12\r\n    WHEN \"Thüringen\" THEN 13\r\n  END"
    }
   ]
  },
  {
   "title": "Übersicht Bundesländer | ${LRA:text} | ${Sendung:text} | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  market_share as ma,\r\n seher as sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.ndr_gcs_bundeslaender_monthly_f` as data\r\nWHERE\r\n  show = \"${Sendung}\"\r\n  and year like \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Übersicht Altersgruppen | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 67 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nSELECT\r\ndistinct\r\n  target_group as zg,\r\n  market_share as ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` as data\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n  AND target_group NOT LIKE \"Erw. ab 14 J.\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND (target_group LIKE \"%Erw.%\"\r\n  OR target_group LIKE \"Kinder%\"\r\n  OR target_group LIKE \"Zuschauer gesamt\"\r\n  OR target_group LIKE \"MDR-Gebiet Z3+\"\r\n   OR CASE \"${Sendung:text}\"\r\n  WHEN \"MDR Sachsen-Anhalt heute\" THEN target_group = \"Sachsen-Anhalt\"\r\n  WHEN \"MDR Sachsenspiegel\" THEN target_group = \"Sachsen\"\r\n  WHEN \"MDR Thüringen Journal\" THEN target_group = \"Thüringen\"\r\n  END\r\n  )\r\nORDER BY target_group ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 67 },
   "options": {
    "content": "###### Zusammensetzung $SehbOderSeher nach Altersgruppen | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR_text | $date_range_monthly"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 70 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN viewers\r\n    ELSE sehbeteiligung\r\n  END AS sb,\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}`\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n  AND target_group NOT LIKE \"Erw. ab 50\"\r\n  AND target_group NOT LIKE \"Erw. ab 14%\"\r\n  AND target_group NOT LIKE \"Erw. 30-49\"\r\n  AND target_group NOT LIKE \"Erw. 14-49\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND (target_group LIKE \"%Erw.%\"\r\n  OR target_group LIKE \"Kinder 3-13\")\r\nORDER BY\r\n  CASE\r\n    WHEN target_group LIKE \"Kinder 3-13\" THEN 1\r\n    WHEN target_group LIKE \"Erw. 14-29\" THEN 2\r\n    WHEN target_group LIKE \"Erw. 30-39\" THEN 3\r\n    WHEN target_group LIKE \"Erw. 40-49\" THEN 4\r\n    WHEN target_group LIKE \"Erw. 50-64\" THEN 5\r\n    WHEN target_group LIKE \"Erw. 50-59\" THEN 6\r\n    WHEN target_group LIKE \"Erw. ab 65 \" THEN 7\r\n    WHEN target_group LIKE \"Erw. 60-69\" THEN 8\r\n    WHEN target_group LIKE \"Erw. ab 70\" THEN 9\r\n  END\r\n"
    }
   ]
  },
  {
   "title": "Marktanteil (%) Aktuelles Jahr vs. Vorjahr | ${LRA:text} | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_values AS(\r\nSELECT\r\ndistinct\r\n  target_group as zg,\r\n  market_share as current_ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS current_sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` as data\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND target_group NOT LIKE \"Erw. ab 14 J.\"\r\n  AND (target_group LIKE \"%Erw.%\"\r\n  OR target_group LIKE \"Kinder%\"\r\n  OR target_group LIKE \"Zuschauer gesamt\"\r\n  OR target_group LIKE \"MDR-Gebiet Z3+\"\r\n   OR CASE \"${Sendung:text}\"\r\n  WHEN \"MDR Sachsen-Anhalt heute\" THEN target_group = \"Sachsen-Anhalt\"\r\n  WHEN \"MDR Sachsenspiegel\" THEN target_group = \"Sachsen\"\r\n  WHEN \"MDR Thüringen Journal\" THEN target_group = \"Thüringen\"\r\n  END\r\n  )\r\nORDER BY target_group ASC),\r\npast_values AS(\r\n  SELECT\r\ndistinct\r\n  target_group as zg,\r\n  market_share as past_ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS past_sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` as data\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$LastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND target_group NOT LIKE \"Erw. ab 14 J.\"\r\n  AND (target_group LIKE \"%Erw.%\"\r\n  OR target_group LIKE \"Kinder%\"\r\n  OR target_group LIKE \"Zuschauer gesamt\"\r\n  OR target_group LIKE \"MDR-Gebiet Z3+\"\r\n   OR CASE \"${Sendung:text}\"\r\n  WHEN \"MDR Sachsen-Anhalt heute\" THEN target_group = \"Sachsen-Anhalt\"\r\n  WHEN \"MDR Sachsenspiegel\" THEN target_group = \"Sachsen\"\r\n  WHEN \"MDR Thüringen Journal\" THEN target_group = \"Thüringen\"\r\n  END\r\n  )\r\nORDER BY target_group ASC\r\n)\r\nSELECT * FROM current_values\r\nJOIN past_values\r\nUSING(zg, legendName)\r\nORDER BY zg ASC"
    }
   ]
  },
  {
   "title": "$SehbOderSeher (Mio.) Aktuelles Jahr vs. Vorjahr | ${LRA:text}  | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_values AS(\r\nSELECT\r\ndistinct\r\n  target_group as zg,\r\n  market_share as current_ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS current_sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` as data\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND target_group NOT LIKE \"Erw. ab 14 J.\"\r\n  AND (target_group LIKE \"%Erw.%\"\r\n  OR target_group LIKE \"Kinder%\"\r\n  OR target_group LIKE \"Zuschauer gesamt\"\r\n  OR target_group LIKE \"MDR-Gebiet Z3+\"\r\n   OR CASE \"${Sendung:text}\"\r\n  WHEN \"MDR Sachsen-Anhalt heute\" THEN target_group = \"Sachsen-Anhalt\"\r\n  WHEN \"MDR Sachsenspiegel\" THEN target_group = \"Sachsen\"\r\n  WHEN \"MDR Thüringen Journal\" THEN target_group = \"Thüringen\"\r\n  END\r\n  )\r\nORDER BY target_group ASC),\r\npast_values AS(\r\n  SELECT\r\ndistinct\r\n  target_group as zg,\r\n  market_share as past_ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS past_sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` as data\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$LastJahr\"\r\n  AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND target_group NOT LIKE \"Erw. ab 14 J.\"\r\n  AND (target_group LIKE \"%Erw.%\"\r\n  OR target_group LIKE \"Kinder%\"\r\n  OR target_group LIKE \"Zuschauer gesamt\"\r\n  OR target_group LIKE \"MDR-Gebiet Z3+\"\r\n   OR CASE \"${Sendung:text}\"\r\n  WHEN \"MDR Sachsen-Anhalt heute\" THEN target_group = \"Sachsen-Anhalt\"\r\n  WHEN \"MDR Sachsenspiegel\" THEN target_group = \"Sachsen\"\r\n  WHEN \"MDR Thüringen Journal\" THEN target_group = \"Thüringen\"\r\n  END\r\n  )\r\nORDER BY target_group ASC\r\n)\r\nSELECT * FROM current_values\r\nJOIN past_values\r\nUSING(zg, legendName)\r\nORDER BY zg ASC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 101 },
   "options": {
    "content": "###### Zusammensetzung $SehbOderSeher nach Geschlecht | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR_text | $date_range_monthly"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 101 },
   "options": {
    "content": "###### Zusammensetzung $SehbOderSeher nach Bildung | ${LRA:text} | ${Sendung:text} | $BRD_or_NDR_text | $date_range_monthly"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}`\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND (target_group LIKE \"Frauen 14-49 J.\"\r\n  OR target_group LIKE \"Frauen ab 50 J.\"\r\n  OR target_group LIKE \"Männer 14-49 J.\"\r\n  OR target_group LIKE \"Männer ab 50 J.\")\r\n  --AND target_group LIKE \"%Kinder 3-13\"\r\nORDER BY target_group asc"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  target_group as zg,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}`\r\nWHERE\r\n  show LIKE \"${Sendung:text}\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  and year like \"$Jahr\"\r\n  AND (target_group LIKE \"Volks%\"\r\n  OR target_group LIKE \"Weiterf. Schule\"\r\n  OR target_group LIKE \"Abitur, Hochschule, Studium\")\r\nORDER BY \r\n  CASE target_group\r\n    WHEN \"Volks%\" THEN 1\r\n    WHEN \"Weiterf. Schule\" THEN 2\r\n    WHEN \"Abitur, Hochschule, Studium\" THEN 3\r\n  END"
    }
   ]
  },
  { "title": "Digital Media Types", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 120 },
   "options": {
    "content": "## <span style=\"color:#BC4542\"><b>Hinweis</b></span>\n\n### Die Darstellung der DMTs wird erst angezeigt, wenn 10 oder mehr $sendung_or_sendetag verfügbar sind. Für ${Sendung:text} sind gerade ${numShows} $sendung_or_sendetag verfügbar."
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 11, "x": 13, "y": 120 } },
  { "type": "text", "gridPos": { "h": 3, "w": 11, "x": 13, "y": 121 }, "options": { "content": "### ${special_region_dmt}" } },
  {
   "title": "Digital Media Types | ${LRA:text} | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DISTINCT\r\n  target_group as zg, \r\n  market_share as ma,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN ROUND(viewers, 3)\r\n    ELSE ROUND(sehbeteiligung, 3)\r\n  END AS sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName,\r\n  (SELECT market_share FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}` \r\n  \r\n   WHERE target_group = \"Erw. ab 14 J.\" AND show = \"${Sendung:text}\" AND year = \"$Jahr\" AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND)  AS ma_erw_14\r\nFROM \r\n  `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}`\r\nWHERE \r\n\r\n  target_group IN (\r\n    \"Vereinfachende\",\r\n    \"Ablenkungssuchende\",\r\n    \"Ambitionierte\",\r\n    \"Neokulturelle\",\r\n    \"Selbstgenügsame\",\r\n    \"Sicherheitsorientierte\", \r\n    \"Traditionsbewusste\",\r\n    \"Verantwortungsvolle\", \r\n    \"Gleichmütige\"\r\n  )\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  AND 1 = CASE WHEN $numShows > 9 THEN 1 ELSE 0 END\r\n  AND 2 = CASE \r\n            WHEN \"$special_region\" LIKE \"\" THEN 2\r\n            WHEN \"$special_region\" IN (\"Sachsen\", \"Sachsen-Anhalt\", \"Thüringen\") THEN 2\r\n            ELSE 0 \r\n          END\r\n  AND show = \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\nORDER BY $dmtOrder"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Strukturanteile Digital Media Types | ${LRA:text} | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT\r\n   target_group as Zielgruppe,\r\n   ROUND((sehbeteiligung / $SehbGesamt * 100)) as Reichweite,\r\n   \"$LRA\" as Sender,\r\n   \"${Sendung:text}\" as sendungsName,\r\n   \"${numShows}\" as numberShows\r\n FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}`\r\n WHERE target_group IN (\r\n    \"Vereinfachende\",\r\n    \"Ablenkungssuchende\",\r\n    \"Ambitionierte\",\r\n    \"Neokulturelle\",\r\n    \"Selbstgenügsame\",\r\n    \"Sicherheitsorientierte\", \r\n    \"Traditionsbewusste\",\r\n    \"Verantwortungsvolle\", \r\n    \"Gleichmütige\"\r\n  )\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n   AND 1 = CASE WHEN $numShows > 9 THEN 1 ELSE 0 END\r\n    AND 2 = CASE \r\n              WHEN \"$special_region\" LIKE \"\" THEN 2\r\n              WHEN \"$special_region\" IN (\"Sachsen\", \"Sachsen-Anhalt\", \"Thüringen\") THEN 2\r\n              ELSE 0 \r\n            END\r\n   AND show like \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n\r\nORDER BY $dmtOrder"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT\r\n target_group as Zielgruppe,\r\n ROUND((viewers / $SeherGesamt * 100)) as Reichweite,\r\n \"${numShows}\" as numberShows,\r\n CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Fernsehmarkt\\n03-03 Uhr\"\r\n    ELSE \"Fernsehmarkt zur Sendezeit\"\r\n  END as legendName,\r\n FROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}`\r\n WHERE target_group IN (\r\n    \"Vereinfachende\",\r\n    \"Ablenkungssuchende\",\r\n    \"Ambitionierte\",\r\n    \"Neokulturelle\",\r\n    \"Selbstgenügsame\",\r\n    \"Sicherheitsorientierte\", \r\n    \"Traditionsbewusste\",\r\n    \"Verantwortungsvolle\", \r\n    \"Gleichmütige\"\r\n  )\r\n  AND 1 = CASE WHEN $numShows > 9 THEN 1 ELSE 0 END\r\n  AND 2 = CASE WHEN \"$special_region\" LIKE \"\" THEN 2 ELSE 0 END\r\n  AND show LIKE \"${Sendung:text}\"\r\n  and year like \"$Jahr\"\r\n   AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n\r\n  ORDER BY $dmtOrder"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN \"-\"\r\n    ELSE target_group\r\n  END AS Zielgruppe,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN NULL\r\n    ELSE ROUND((sehbeteiligung / $SendetagGesamt * 100))\r\n  END AS Sehbeteiligung,\r\n  \"$LRA\" AS Sender,\r\n  \"${numShows}\" AS numberShows,\r\n  CASE \"${LRA:text}\"\r\n    WHEN \"Sender\" THEN 1\r\n    ELSE 0\r\n  END AS hidePanel, \r\n  $dmtOrder AS rank\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${zielgruppen_und_facts_monthly}`\r\nWHERE target_group IN (\r\n  \"Vereinfachende\",\r\n  \"Ablenkungssuchende\",\r\n  \"Ambitionierte\",\r\n  \"Neokulturelle\",\r\n  \"Selbstgenügsame\",\r\n  \"Sicherheitsorientierte\", \r\n  \"Traditionsbewusste\",\r\n  \"Verantwortungsvolle\", \r\n  \"Gleichmütige\"\r\n)\r\nAND \"${LRA:text}\" != \"Sender\" \r\nAND show LIKE \"${LRA:text}%\"\r\nAND lra LIKE \"SENDER\"\r\nAND $numShows > 9\r\nand year like \"$Jahr\"\r\nAND 2 = CASE WHEN \"$special_region\" LIKE \"\" THEN 2 ELSE 0 END\r\nAND CASE \"${LRA:text}\"\r\nWHEN \"ARD\"\r\nTHEN show = \"ARD Das Erste\"\r\nELSE TRUE \r\nEND\r\n AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 144 },
   "options": {
    "content": "## <span style=\"color:#BC4542\"><b>Hinweis</b></span>\n\n### $dmt_kennziffern_hinweis Mögliche Differenzen zu 100% entstehen durch unterjährige Fluktuationen im Panel."
   }
  },
  { "title": "Hitlisten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Hitliste $sendung_or_sendetag  auflaufendes Jahr |  ${LRA:text} | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 148 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${LRA:text}\" = \"Sender\") THEN (\r\n  SELECT \r\n    --Nummer, \r\n    Sender, \r\n    Datum,\r\n    Wochentag,\r\n    REPLACE(CAST(Seher AS STRING FORMAT '990.999'),\".\",\",\") as Seher ,\r\n    REPLACE(CAST(ROUND(Marktanteil,1) AS STRING FORMAT '990.9'),\".\",\",\") as Marktanteil\r\n  FROM (\r\n    SELECT \r\n      --ROW_NUMBER() OVER (ORDER BY -market_share) AS Nummer, \r\n      show AS Sender, \r\n      date AS Datum,\r\n      weekday AS Wochentag,\r\n      $SehbOderSeher AS Seher,\r\n      market_share AS Marktanteil\r\n    FROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_monthly}`\r\n    WHERE show LIKE \"${Sendung:text}\" AND year LIKE \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  ) AS subquery\r\n  ORDER BY Marktanteil DESC\r\n);\r\nELSE (\r\n  SELECT \r\n    --Nummer, \r\n    Sender, \r\n    Datum,\r\n    Wochentag,\r\n    Folgentitel,\r\n    REPLACE(CAST(Seher AS STRING FORMAT '990.999'),\".\",\",\") as Seher ,\r\n        REPLACE(CAST(ROUND(Marktanteil,1) AS STRING FORMAT '990.9'),\".\",\",\") as Marktanteil\r\n\r\n  FROM (\r\n    SELECT \r\n      ROW_NUMBER() OVER (ORDER BY -sehbeteiligung, -market_share) AS Nummer, \r\n      lra AS Sender, \r\n      date AS Datum,\r\n      weekday AS Wochentag,\r\n      title AS Folgentitel,\r\n      sehbeteiligung AS Sehbeteiligung,\r\n      market_share AS Marktanteil\r\n    FROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_monthly}`\r\n    WHERE show LIKE \"${Sendung:text}\" AND year LIKE \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\n  ) AS subquery\r\n  ORDER BY Marktanteil DESC\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "Hitliste $sendung_or_sendetag ausgewählter Monat |  ${LRA:text} | $Sendung | $BRD_or_NDR_text | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 160 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF (\"${LRA:text}\" = \"Sender\") THEN (\r\n  SELECT \r\n    --Nummer, \r\n    Sender, \r\n    Datum,\r\n    Wochentag,\r\n   REPLACE(CAST(Seher AS STRING FORMAT '990.999'),\".\",\",\") as Seher ,\r\n    REPLACE(CAST(ROUND(Marktanteil,1) AS STRING FORMAT '990.9'),\".\",\",\") as Marktanteil\r\n  FROM (\r\n    SELECT \r\n      --ROW_NUMBER() OVER (ORDER BY -market_share) AS Nummer, \r\n      show AS Sender, \r\n      date AS Datum,\r\n      weekday AS Wochentag,\r\n      $SehbOderSeher AS Seher,\r\n      market_share AS Marktanteil\r\n    FROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_monthly}`\r\n    WHERE show LIKE \"${Sendung:text}\" AND year LIKE \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat AND EXTRACT(MONTH FROM PARSE_DATE('%d.%m.%Y', date)) = CAST($Monat AS INT) and EXTRACT(YEAR FROM PARSE_DATE('%d.%m.%Y', date)) = $Jahr\r\nELSE TRUE \r\nEND\r\n  ) AS subquery\r\n  ORDER BY Marktanteil DESC\r\n);\r\nELSE (\r\n  SELECT \r\n    --Nummer, \r\n    Sender, \r\n    Datum,\r\n    Wochentag,\r\n    Folgentitel,\r\n    REPLACE(CAST(Sehbeteiligung AS STRING FORMAT '990.999'),\".\",\",\") as Sehbeteiligung ,\r\n    REPLACE(CAST(ROUND(Marktanteil,1) AS STRING FORMAT '990.9'),\".\",\",\") as Marktanteil\r\n  FROM (\r\n    SELECT \r\n      ROW_NUMBER() OVER (ORDER BY -sehbeteiligung, -market_share) AS Nummer, \r\n      lra AS Sender, \r\n      date AS Datum,\r\n      weekday AS Wochentag,\r\n      title AS Folgentitel,\r\n      sehbeteiligung AS Sehbeteiligung,\r\n      market_share AS Marktanteil\r\n    FROM `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_monthly}`\r\n    WHERE show LIKE \"${Sendung:text}\" AND year LIKE \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat AND EXTRACT(MONTH FROM PARSE_DATE('%d.%m.%Y', date)) = CAST($Monat AS INT) and EXTRACT(YEAR FROM PARSE_DATE('%d.%m.%Y', date)) = $Jahr\r\n\r\nELSE TRUE \r\nEND\r\n  ) AS subquery\r\n  ORDER BY Marktanteil DESC\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "$sendung_or_sendetag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 174 },
   "options": {
    "content": "## <span style=\"color:#BC4542\"><b>Hinweis</b></span>\n\n### Der Wert der Durchschnittslinie bezieht sich auf das aktuelle Jahr."
   }
  },
  {
   "title": "$sendung_or_sendetag im Zeitverlauf | $LRA | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  PARSE_DATE(\"%d.%m.%Y\", date) as datum,\r\n  ROUND(market_share, 3) as ma,\r\n  ROUND($SehbOderSeher, 3) as sb,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n    ELSE \"Sehbeteiligung\"\r\n  END as legendName,\r\n  CASE\r\n    WHEN ${LRA:doublequote} = \"sender\" THEN $seherDurchschnitt\r\n    ELSE $sehbDurchschnitt\r\n  END as reichweiteDurchschnitt,\r\n  $marktanteilDurchschnitt as marktanteilDurchschnitt\r\nFROM\r\n  `ndr-code-bi-dashboard.Quotenreport.${sendungsliste_monthly}`\r\nWHERE show = \"${Sendung:text}\" and year like \"$Jahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\nORDER BY datum ASC"
    }
   ]
  },
  {
   "title": "Marktanteil und Seher nach Wochentagen | $LRA | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 193 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH base_data AS (\r\n  SELECT\r\n    SAFE_CAST(market_share AS NUMERIC) as ma, \r\n    SAFE_CAST($SehbOderSeher AS NUMERIC) as sb,\r\n    weekday as zg,\r\n    CASE weekday\r\n      WHEN \"Montag\" THEN 1 \r\n      WHEN \"Dienstag\" THEN 2\r\n      WHEN \"Mittwoch\" THEN 3\r\n      WHEN \"Donnerstag\" THEN 4\r\n      WHEN \"Freitag\" THEN 5\r\n      WHEN \"Samstag\" THEN 6\r\n      WHEN \"Sonntag\" THEN 7\r\n      WHEN \"Montag-Sonntag\" THEN -2\r\n      WHEN \"Montag-Freitag\" THEN -1\r\n      WHEN \"Samstag+Sonntag\" THEN 0\r\n    END as rank,\r\n    CASE\r\n      WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\"\r\n      ELSE \"Sehbeteiligung\"\r\n    END as legendName,\r\n    SAFE_CAST(\r\n      CASE\r\n        WHEN ${LRA:doublequote} = \"sender\" THEN $seherDurchschnitt\r\n        ELSE $sehbDurchschnitt\r\n      END AS NUMERIC\r\n    ) as reichweiteDurchschnitt,\r\n    SAFE_CAST($marktanteilDurchschnitt AS NUMERIC) as marktanteilDurchschnitt\r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${wochentage_monthly}`\r\n  WHERE show = \"${Sendung:text}\" AND year LIKE \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\n      WHEN \"ndr_\" THEN month = $Monat\r\n      ELSE TRUE \r\n    END\r\n  ORDER BY rank ASC\r\n), \r\n\r\nweekday_data AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    zg, \r\n    rank\r\n  FROM base_data \r\n  GROUP BY zg, rank\r\n  HAVING rank > 0\r\n),\r\n\r\nmonday_friday AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"Mo-Fr\" as zg, \r\n    -1 as rank \r\n  FROM base_data \r\n  WHERE rank = -1\r\n), \r\n\r\nmonday_sunday AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"Mo-So\" as zg, \r\n    -2 as rank \r\n  FROM base_data \r\n  WHERE rank = -2\r\n), \r\n\r\nsaturday_sunday AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"Sa + So\" as zg, \r\n    0 as rank \r\n  FROM base_data \r\n  WHERE rank = 0\r\n)\r\n\r\nSELECT *, MAX(ma) OVER() as max_ma FROM (\r\n  SELECT * FROM monday_friday\r\n  UNION ALL \r\n  SELECT * FROM weekday_data\r\n  UNION ALL \r\n  SELECT * FROM monday_sunday\r\n  UNION ALL \r\n  SELECT * FROM saturday_sunday\r\n)\r\nWHERE ma > 0\r\nORDER BY rank ASC;\r\n"
    }
   ]
  },
  {
   "title": "Marktanteil und Seher pro Sender nach Zeitintervallen | $LRA | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 209 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH base_data AS (\r\n  SELECT\r\n    SAFE_CAST(market_share AS NUMERIC) as ma,  \r\n    SAFE_CAST($SehbOderSeher AS NUMERIC) as sb, \r\n    SAFE_CAST(LEFT(zeit,2) AS INT) as zg,\r\n    zeit,\r\n    CASE\r\n      WHEN ${LRA:doublequote} = \"sender\" THEN \"Seher\" \r\n      ELSE \"Sehbeteiligung\"\r\n    END as legendName,\r\n    SAFE_CAST(\r\n      CASE\r\n        WHEN ${LRA:doublequote} = \"sender\" THEN $seherDurchschnitt\r\n        ELSE $sehbDurchschnitt\r\n      END AS NUMERIC\r\n    ) as reichweiteDurchschnitt,\r\n    SAFE_CAST($marktanteilDurchschnitt AS NUMERIC) as marktanteilDurchschnitt \r\n  FROM `ndr-code-bi-dashboard.Quotenreport.${zeitschnitte_monthly}`\r\n  WHERE show = \"${Sendung:text}\" AND year LIKE \"$Jahr\"\r\n    AND CASE \"${table_prefix}\"\r\n      WHEN \"ndr_\" THEN month = $Monat\r\n      ELSE TRUE \r\n    END\r\n), \r\n\r\nzero_three AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"00-03 Uhr\" as zg, \r\n    0 as rank\r\n  FROM base_data \r\n  WHERE zg < 3\r\n),\r\n\r\nthree_twelve AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"03 - 12 Uhr \" as zg, \r\n    1 as rank \r\n  FROM base_data \r\n  WHERE zg BETWEEN 3 and 11\r\n), \r\ntwelve_fourteen AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"12-14 Uhr\" as zg, \r\n    2 as rank \r\n  FROM base_data \r\n  WHERE zg between 12 and 13\r\n), \r\n\r\nfourteen_sixteen AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"14-16 Uhr\" as zg, \r\n    3 as rank \r\n  FROM base_data \r\n  WHERE zg between 14 and 15\r\n), \r\nsixteen_eighteen AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"16-18 Uhr\" as zg, \r\n    4 as rank \r\n  FROM base_data \r\n  WHERE zg between 16 and 17\r\n), \r\neightteen_twenty AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"18-20 Uhr\" as zg, \r\n    5 as rank \r\n  FROM base_data \r\n  WHERE zg between 18 and 19\r\n), \r\ntwenty_twenty_two AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"20-22 Uhr\" as zg, \r\n    6 as rank \r\n  FROM base_data \r\n  WHERE zg between 20 and 21\r\n), \r\ntwenty_two_zero AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"22-00 Uhr\" as zg, \r\n    7 as rank \r\n  FROM base_data \r\n  WHERE zg >= 22\r\n),\r\nthree_three AS (\r\n  SELECT \r\n    SAFE_CAST(AVG(ma) AS NUMERIC) as ma,\r\n    SAFE_CAST(AVG(sb) AS NUMERIC) as sb, \r\n    MAX(legendName) as legendName,\r\n    \"3-3 Uhr\" as zg, \r\n    -1 as rank \r\n  FROM base_data \r\n  WHERE zeit = \"03:00 - 03:00\"\r\n)\r\nSELECT * FROM (\r\n  SELECT * FROM zero_three\r\n  UNION ALL \r\n  SELECT * FROM three_twelve\r\n  UNION ALL \r\n  SELECT * FROM twelve_fourteen\r\n  UNION ALL \r\n  SELECT * FROM fourteen_sixteen\r\n  UNION ALL \r\n  SELECT * FROM sixteen_eighteen\r\n  UNION ALL \r\n  SELECT * FROM eightteen_twenty\r\n    UNION ALL \r\n  SELECT * FROM twenty_twenty_two\r\n    UNION ALL \r\n  SELECT * FROM twenty_two_zero\r\n  UNION ALL \r\n  SELECT * FROM three_three\r\n)\r\nWHERE ma > 0\r\nORDER BY rank ASC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 225 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Monatsdurchschnitte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 226 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 227 },
   "options": {
    "content": "###### Marktanteil (%) Aktuelles Jahr vs. Vorjahr | ${LRA:text} | $Sendung | $BRD_or_NDR_text | $date_range"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 227 },
   "options": {
    "content": "###### $SehbOderSeher (Mio.) Aktuelles Jahr vs. Vorjahr | ${LRA:text}  | $Sendung | $BRD_or_NDR_text | $date_range"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 229 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nROUND(market_share, 1) as ma,\r\nmonth as mon,\r\nyear as jahre,\r\n\"$Jahr\" as aktuelles_jahr,\r\n\"$LastJahr\" as vor_jahr\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${monatswerte_native}`\r\nWHERE show like \"${Sendung:name}\" AND (year LIKE \"$Jahr\" OR year LIKE \"$LastJahr\")\r\nORDER BY \r\n  CASE mon\r\n    WHEN \"Januar\" THEN 1\r\n    WHEN \"Februar\" THEN 2\r\n    WHEN \"März\" THEN 3\r\n    WHEN \"April\" THEN 4\r\n    WHEN \"Mai\" THEN 5\r\n    WHEN \"Juni\" THEN 6\r\n    WHEN \"Juli\" THEN 7\r\n    WHEN \"August\" THEN 8\r\n    WHEN \"September\" THEN 9\r\n    WHEN \"Oktober\" THEN 10\r\n    WHEN \"November\" THEN 11\r\n    WHEN \"Dezember\" THEN 12\r\n  END\r\n-- LIMIT 10"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 229 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DISTINCT\r\nROUND(sehbeteiligung, 3) as sb,\r\nmonat as mon,\r\nyear as jahre,\r\n\"$Jahr\" as aktuelles_jahr,\r\n\"$LastJahr\" as vor_jahr\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${monatswerte_monthly}`\r\nWHERE show LIKE \"${Sendung:text}\" AND (year LIKE \"$Jahr\" OR year LIKE \"$LastJahr\")\r\nORDER BY \r\n  CASE mon\r\n    WHEN \"Januar\" THEN 1\r\n    WHEN \"Februar\" THEN 2\r\n    WHEN \"März\" THEN 3\r\n    WHEN \"April\" THEN 4\r\n    WHEN \"Mai\" THEN 5\r\n    WHEN \"Juni\" THEN 6\r\n    WHEN \"Juli\" THEN 7\r\n    WHEN \"August\" THEN 8\r\n    WHEN \"September\" THEN 9\r\n    WHEN \"Oktober\" THEN 10\r\n    WHEN \"November\" THEN 11\r\n    WHEN \"Dezember\" THEN 12\r\n  END\r\n-- LIMIT 10"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 240 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Vergleichssender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 241 } },
  {
   "title": "Top 10 Sender nach Marktanteil (%) | $LRA | $Sendung | $BRD_or_NDR_text | $date_range_monthly",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 242 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\ncomparison_sender as Vergleichssender,\r\nROUND(market_share, 1) as Marktanteil,\r\nlra as lra,\r\nshow as sendung\r\nFROM `ndr-code-bi-dashboard.Quotenreport.${vergleichssender_monthly}`\r\nWHERE show like \"${Sendung}\" and year like \"$Jahr\"\r\nAND CASE \"${table_prefix}\"\r\nWHEN \"ndr_\" THEN month = $Monat\r\nELSE TRUE \r\nEND\r\nORDER BY Marktanteil DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 255 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Glossar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 256 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 257 },
   "options": {
    "content": "# Sehbeteiligung (Mio.)\n\nAnzahl der Zuschauer einer Zielgruppe, die anteilig ihrer Nutzungsdauer gezählt werden"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 257 },
   "options": {
    "content": "# Marktanteil\n\nGibt den prozentualen Anteil der durchschnittlichen Sehbeteiligung einer Sendung oder Zeitintervalls an der Sehbeteiligung TV Gesamt zum Zeitpunkt an"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 257 },
   "options": {
    "content": "# Seher (Mio.)\n\nPersonen, die sich für mindestens eine Minute in das Programm eingeschaltet haben"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 257 },
   "options": {
    "content": "# Verweildauer\n\nVerweildauer in Minuten (Durchschnittliche Sehdauer der Zuschauer die mindestens 1 Minute ohne Unterbrechung geschaut haben)"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 261 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  }
 ]
}