{
 "title": "Podcast Monatsbericht NDR",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Monat",
    "label": "Zeitraum",
    "query": {}
   },
   {
    "name": "Monat_wrapper",
    "label": "Zeitraum",
    "query": {}
   },
   {
    "name": "Jahr",
    "query": {}
   },
   {
    "name": "profiles_dataset",
    "query": {}
   },
   {
    "name": "platform_dataset",
    "query": {}
   },
   {
    "name": "episode_dataset",
    "query": {}
   },
   { "name": "filled_size", "query": "20" },
   {
    "name": "Zeitraum",
    "query": {}
   },
   { "name": "filled_size_big", "query": "10" },
   {
    "name": "hinweis_comp_last_month",
    "query": {}
   },
   {
    "name": "LastMonat_abkuerzung",
    "query": {}
   },
   {
    "name": "YearFromLastMonth",
    "query": {}
   },
   {
    "name": "Monat_last_year_abkuerzung",
    "query": {}
   },
   {
    "name": "LastYear",
    "query": {}
   },
   {
    "name": "hinweis_comp_last_year",
    "query": {}
   },
   {
    "name": "Month",
    "query": {}
   },
   {
    "name": "datenstand",
    "query": {}
   },
   {
    "name": "NDR_default_image",
    "query": {}
   },
   {
    "name": "NDR_branding_images",
    "query": {}
   },
   {
    "name": "NDR_podcast_images",
    "query": {}
   },
   {
    "name": "table_name_last_month_absolute",
    "query": {}
   },
   {
    "name": "table_name_last_month_prozent",
    "query": {}
   },
   {
    "name": "table_name_last_year_absolute",
    "query": {}
   },
   {
    "name": "table_name_last_year_prozent",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "10" },
   {
    "name": "filled_size_headline_last_month",
    "query": {}
   },
   {
    "name": "filled_size_headline_last_year",
    "query": {}
   },
   {
    "name": "vorjahresmonat_zeitraum",
    "query": {}
   },
   {
    "name": "min_date",
    "query": {}
   },
   {
    "name": "max_date",
    "query": {}
   },
   {
    "name": "min_date_last_year_formated",
    "query": {}
   },
   {
    "name": "max_date_last_year_formated",
    "query": {}
   },
   {
    "name": "hinweis_comp_last_year_kpi_boxes",
    "query": {}
   },
   {
    "name": "lastUpdate",
    "query": {}
   },
   {
    "name": "ausgewerteteZeitraum",
    "query": {}
   },
   {
    "name": "Plattformen",
    "query": {}
   },
   {
    "name": "PlattformenMehrereWerte",
    "query": {}
   },
   {
    "name": "plattformen_images",
    "query": {}
   },
   {
    "name": "MDR_default_image",
    "query": {}
   },
   {
    "name": "dashboard_image",
    "query": {}
   },
   {
    "name": "branding_images",
    "query": {}
   },
   {
    "name": "podcast_images",
    "query": {}
   },
   {
    "name": "mdr_ard_kultur_podcasts",
    "query": {}
   },
   {
    "name": "datenstand_start",
    "query": {}
   },
   {
    "name": "vormonat_zeitraum",
    "query": {}
   },
   {
    "name": "Bereich",
    "query": {}
   },
   {
    "name": "Podcast",
    "query": {}
   },
   {
    "name": "Genre",
    "query": {}
   },
   {
    "name": "src_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# Podcast Report | ${Month} ${Jahr}\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 1, "x": 10, "y": 0 },
   "options": {
    "content": "<img \n  src=\"${src_url}\" \n  alt=\"Tracking Pixel\" \n  width=\"1\" \n  height=\"1\" \n  style=\"display:none;\"\n/>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [
         { "name": "total_video_10s_views", "type": "functionParameter" }
        ],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "facebookInsightsOwnVideos"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 3 },
   "options": {
    "content": "## Der ausgewertete Zeitraum lautet: ${ausgewerteteZeitraum}"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Übersicht ${LRA} Gesamt |  ${Monat_text} ${Jahr}'))), 'Übersicht ${LRA} Gesamt |  ${Monat:text} ${Jahr}'), \nFROM(\nSELECT 'Übersicht ${LRA} Gesamt |  ${Monat:text} ${Jahr}' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$dashboard_image\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('$LRA - Gesamt'))), '$LRA - Gesamt'), \nFROM(\nSELECT '$LRA - Gesamt' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 17, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Apps'))), 'Apps'), \nFROM(\nSELECT 'Apps' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt aller Podcast-Reihen im ausgewählten Bereich",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT\n  SUM(m_zugriffe_1) AS summe\n  FROM $episode_dataset\n  WHERE \n  $Zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('ARD Audiothek')), 'ARD Audiothek')\nFROM(\nSELECT 'ARD Audiothek' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "NDR: Spotify-Daten ab 01.01.2021 verfügbar (ab August 2023 auf Basis von Serverlogfiles, für ältere Zeiträume auf Basis von Streams ab 60 Sekunden)",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('Spotify')), 'Spotify')\nFROM(\nSELECT 'Spotify' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size - CHAR_LENGTH('Apple Podcasts'))), 'Apple Podcasts')\nFROM(\nSELECT 'Apple Podcasts' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \nSUM(m_zugriffe_1) AS summe,\nplatform\nFROM $platform_dataset\nWHERE \n$Zeitraum\nAND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY platform"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\n    SELECT \n    SUM(m_zugriffe_1) AS summe\n    FROM $platform_dataset\n    WHERE \n    platform = \"ARD Audiothek\" \n    AND \n    $Zeitraum\n    AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\n    SELECT \n    SUM(m_zugriffe_1) AS summe\n    FROM $platform_dataset\n    WHERE \n    platform = \"Spotify\" \n    AND \n    $Zeitraum\n    AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\n    SELECT \n    SUM(m_zugriffe_1) AS summe\n    FROM $platform_dataset\n    WHERE \n    platform = \"Apple Podcasts\" \n    AND \n    $Zeitraum\n    AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": {
    "content": "Letztes Update: <br> \r\n${lastUpdate}\r\n<br> <br> \r\nDatenstand: <br> \r\n${datenstand_start} – ${datenstand}"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", 0), 'Veränderung im Vergleich zu:'), \nFROM(\nSELECT 'Veränderung im Vergleich zu:' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- declare and set the value of Monat as the value of the variable \"$Monat\"\nDECLARE Monat INT64;\nSET Monat = $Monat_wrapper;\n\n-- if \"Jahr\" is selected, then select an empty string\nIF Monat > 12 THEN \n  EXECUTE IMMEDIATE \"\"\"\n  SELECT CASE \"${Monat:text}\"\nWHEN \"Jahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\nWHEN \"1. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Quartal $LastYear\"))), \"1. Quartal $LastYear\")\nWHEN \"2. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Quartal $LastYear\"))), \"2. Quartal $LastYear\")\nWHEN \"3. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"3. Quartal $LastYear\"))), \"3. Quartal $LastYear\")\nWHEN \"4. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"4. Quartal $LastYear\"))), \"4. Quartal $LastYear\")\nWHEN \"1. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Halbjahr $LastYear\"))), \"1. Halbjahr $LastYear\")\nWHEN \"2. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Halbjahr $LastYear\"))), \"2. Halbjahr $LastYear\")\nEND\n\"\"\";\n--CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\n-- if a month is selected, then compute the difference\nELSE \n  EXECUTE IMMEDIATE \"\"\"\n   SELECT CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(CONCAT('$LastMonat_abkuerzung', ' ', '$YearFromLastMonth')))), CONCAT('$LastMonat_abkuerzung', ' ', '$YearFromLastMonth')),\n   CASE \"${Monat:text}\"\n    WHEN \"Jahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\n    WHEN \"1. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Quartal $LastYear\"))), \"1. Quartal $LastYear\")\n    WHEN \"2. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Quartal $LastYear\"))), \"2. Quartal $LastYear\")\n    WHEN \"3. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"3. Quartal $LastYear\"))), \"3. Quartal $LastYear\")\n    WHEN \"4. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"4. Quartal $LastYear\"))), \"4. Quartal $LastYear\")\n    WHEN \"1. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Halbjahr $LastYear\"))), \"1. Halbjahr $LastYear\")\n    WHEN \"2. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Halbjahr $LastYear\"))), \"2. Halbjahr $LastYear\")\n    ELSE CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$Monat_last_year_abkuerzung $LastYear\"))), \"$Monat_last_year_abkuerzung $LastYear\")\n    END\n  \"\"\";\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- declare and set the value of Monat as the value of the variable \"$Monat\"\nDECLARE Monat INT64;\nSET Monat = $Monat_wrapper;\n\n-- if \"Jahr\" is selected, then select an empty string\nIF Monat > 12 THEN \n  EXECUTE IMMEDIATE \"\"\"\n  SELECT CASE \"${Monat:text}\"\nWHEN \"Jahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\nWHEN \"1. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Quartal $LastYear\"))), \"1. Quartal $LastYear\")\nWHEN \"2. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Quartal $LastYear\"))), \"2. Quartal $LastYear\")\nWHEN \"3. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"3. Quartal $LastYear\"))), \"3. Quartal $LastYear\")\nWHEN \"4. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"4. Quartal $LastYear\"))), \"4. Quartal $LastYear\")\nWHEN \"1. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Halbjahr $LastYear\"))), \"1. Halbjahr $LastYear\")\nWHEN \"2. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Halbjahr $LastYear\"))), \"2. Halbjahr $LastYear\")\nEND\n\"\"\";\n--CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\n-- if a month is selected, then compute the difference\nELSE \n  EXECUTE IMMEDIATE \"\"\"\n   SELECT CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(CONCAT('$LastMonat_abkuerzung', ' ', '$YearFromLastMonth')))), CONCAT('$LastMonat_abkuerzung', ' ', '$YearFromLastMonth')),\n   CASE \"${Monat:text}\"\n    WHEN \"Jahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\n    WHEN \"1. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Quartal $LastYear\"))), \"1. Quartal $LastYear\")\n    WHEN \"2. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Quartal $LastYear\"))), \"2. Quartal $LastYear\")\n    WHEN \"3. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"3. Quartal $LastYear\"))), \"3. Quartal $LastYear\")\n    WHEN \"4. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"4. Quartal $LastYear\"))), \"4. Quartal $LastYear\")\n    WHEN \"1. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Halbjahr $LastYear\"))), \"1. Halbjahr $LastYear\")\n    WHEN \"2. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Halbjahr $LastYear\"))), \"2. Halbjahr $LastYear\")\n    ELSE CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$Monat_last_year_abkuerzung $LastYear\"))), \"$Monat_last_year_abkuerzung $LastYear\")\n    END\n  \"\"\";\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- declare and set the value of Monat as the value of the variable \"$Monat\"\nDECLARE Monat INT64;\nSET Monat = $Monat_wrapper;\n\n-- if \"Jahr\" is selected, then select an empty string\nIF Monat > 12 THEN \n  EXECUTE IMMEDIATE \"\"\"\n  SELECT CASE \"${Monat:text}\"\nWHEN \"Jahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\nWHEN \"1. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Quartal $LastYear\"))), \"1. Quartal $LastYear\")\nWHEN \"2. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Quartal $LastYear\"))), \"2. Quartal $LastYear\")\nWHEN \"3. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"3. Quartal $LastYear\"))), \"3. Quartal $LastYear\")\nWHEN \"4. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"4. Quartal $LastYear\"))), \"4. Quartal $LastYear\")\nWHEN \"1. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Halbjahr $LastYear\"))), \"1. Halbjahr $LastYear\")\nWHEN \"2. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Halbjahr $LastYear\"))), \"2. Halbjahr $LastYear\")\nEND\n\"\"\";\n--CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\n-- if a month is selected, then compute the difference\nELSE \n  EXECUTE IMMEDIATE \"\"\"\n   SELECT CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(CONCAT('$LastMonat_abkuerzung', ' ', '$YearFromLastMonth')))), CONCAT('$LastMonat_abkuerzung', ' ', '$YearFromLastMonth')),\n   CASE \"${Monat:text}\"\n    WHEN \"Jahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\n    WHEN \"1. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Quartal $LastYear\"))), \"1. Quartal $LastYear\")\n    WHEN \"2. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Quartal $LastYear\"))), \"2. Quartal $LastYear\")\n    WHEN \"3. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"3. Quartal $LastYear\"))), \"3. Quartal $LastYear\")\n    WHEN \"4. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"4. Quartal $LastYear\"))), \"4. Quartal $LastYear\")\n    WHEN \"1. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Halbjahr $LastYear\"))), \"1. Halbjahr $LastYear\")\n    WHEN \"2. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Halbjahr $LastYear\"))), \"2. Halbjahr $LastYear\")\n    ELSE CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$Monat_last_year_abkuerzung $LastYear\"))), \"$Monat_last_year_abkuerzung $LastYear\")\n    END\n  \"\"\";\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- declare and set the value of Monat as the value of the variable \"$Monat\"\nDECLARE Monat INT64;\nSET Monat = $Monat_wrapper;\n\n-- if \"Jahr\" is selected, then select an empty string\nIF Monat > 12 THEN \n  EXECUTE IMMEDIATE \"\"\"\n  SELECT CASE \"${Monat:text}\"\nWHEN \"Jahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\nWHEN \"1. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Quartal $LastYear\"))), \"1. Quartal $LastYear\")\nWHEN \"2. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Quartal $LastYear\"))), \"2. Quartal $LastYear\")\nWHEN \"3. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"3. Quartal $LastYear\"))), \"3. Quartal $LastYear\")\nWHEN \"4. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"4. Quartal $LastYear\"))), \"4. Quartal $LastYear\")\nWHEN \"1. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Halbjahr $LastYear\"))), \"1. Halbjahr $LastYear\")\nWHEN \"2. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Halbjahr $LastYear\"))), \"2. Halbjahr $LastYear\")\nEND\n\"\"\";\n--CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\n-- if a month is selected, then compute the difference\nELSE \n  EXECUTE IMMEDIATE \"\"\"\n   SELECT CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(CONCAT('$LastMonat_abkuerzung', ' ', '$YearFromLastMonth')))), CONCAT('$LastMonat_abkuerzung', ' ', '$YearFromLastMonth')),\n   CASE \"${Monat:text}\"\n    WHEN \"Jahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$LastYear\"))), \"$LastYear\")\n    WHEN \"1. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Quartal $LastYear\"))), \"1. Quartal $LastYear\")\n    WHEN \"2. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Quartal $LastYear\"))), \"2. Quartal $LastYear\")\n    WHEN \"3. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"3. Quartal $LastYear\"))), \"3. Quartal $LastYear\")\n    WHEN \"4. Quartal\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"4. Quartal $LastYear\"))), \"4. Quartal $LastYear\")\n    WHEN \"1. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"1. Halbjahr $LastYear\"))), \"1. Halbjahr $LastYear\")\n    WHEN \"2. Halbjahr\" THEN CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"2. Halbjahr $LastYear\"))), \"2. Halbjahr $LastYear\")\n    ELSE CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH(\"$Monat_last_year_abkuerzung $LastYear\"))), \"$Monat_last_year_abkuerzung $LastYear\")\n    END\n  \"\"\";\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- declare and set the value of Monat as the value of the variable \"$Monat\"\nDECLARE Monat INT64;\nSET Monat = $Monat_wrapper;\n\n-- if \"Jahr\" is selected, then select an empty string\nIF Monat > 12 THEN \n  EXECUTE IMMEDIATE \"\"\"\n  WITH past_zugriffe AS(\n  SELECT\n  SUM(m_zugriffe_1) AS past_sum\n  FROM $episode_dataset\n  WHERE $vorjahresmonat_zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n),\ncurrent_zugriffe AS(\n  SELECT\n  SUM(m_zugriffe_1) AS current_sum\n  FROM $episode_dataset\n  WHERE \n  $Zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\nSELECT\n-- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\nCASE\nWHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\nELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END\nFROM past_zugriffe, current_zugriffe\n\"\"\";\n\n-- if a month is selected, then compute the difference\nELSE \n  EXECUTE IMMEDIATE \"\"\"\n    WITH past_zugriffe AS(\n    SELECT\n  SUM(m_zugriffe_1) AS past_sum\nFROM $episode_dataset\nWHERE $vormonat_zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n),\ncurrent_zugriffe AS(\n    SELECT\n  SUM(m_zugriffe_1) AS current_sum\nFROM $episode_dataset\nWHERE $Zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n),\npast_zugriffe_vorjahresmonat AS(\n  SELECT\n  SUM(m_zugriffe_1) AS past_sum\n  FROM $episode_dataset\n  WHERE $vorjahresmonat_zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\nSELECT\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN current_sum / past_zugriffe.past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_zugriffe.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_zugriffe.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN current_sum / past_zugriffe_vorjahresmonat.past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_zugriffe_vorjahresmonat.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_zugriffe_vorjahresmonat.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\nFROM past_zugriffe, current_zugriffe, past_zugriffe_vorjahresmonat\n  \"\"\";\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- declare and set the value of Monat as the value of the variable \"$Monat\"\nDECLARE Monat INT64;\nSET Monat = $Monat_wrapper;\n\n-- if \"Jahr\" is selected, then select an empty string\nIF Monat > 12 THEN \n  EXECUTE IMMEDIATE \"\"\"\n  WITH past_zugriffe AS(\n  SELECT\n  SUM(m_zugriffe_1) AS past_sum\n  FROM $platform_dataset\n  WHERE $vorjahresmonat_zeitraum\n  AND platform = \"ARD Audiothek\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n),\ncurrent_zugriffe AS(\n  SELECT\n  SUM(m_zugriffe_1) AS current_sum\n  FROM $platform_dataset\n  WHERE \n  $Zeitraum\n  AND platform = \"ARD Audiothek\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\nSELECT\n-- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\nCASE\nWHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\nELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END\nFROM past_zugriffe, current_zugriffe\n\"\"\";\n\n-- if a month is selected, then compute the difference\nELSE \n  EXECUTE IMMEDIATE \"\"\"\n    WITH past_zugriffe AS(\n    SELECT\n  SUM(m_zugriffe_1) AS past_sum\nFROM $platform_dataset\nWHERE $vormonat_zeitraum\n        AND platform = \"ARD Audiothek\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n),\ncurrent_zugriffe AS(\n    SELECT\n  SUM(m_zugriffe_1) AS current_sum\nFROM $platform_dataset\nWHERE $Zeitraum\nAND platform = \"ARD Audiothek\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n),\npast_zugriffe_vorjahresmonat AS(\n  SELECT\n  SUM(m_zugriffe_1) AS past_sum\n  FROM $platform_dataset\n  WHERE $vorjahresmonat_zeitraum\n  AND platform = \"ARD Audiothek\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n  \n)\nSELECT\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN current_sum / past_zugriffe.past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_zugriffe.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_zugriffe.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN current_sum / past_zugriffe_vorjahresmonat.past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_zugriffe_vorjahresmonat.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_zugriffe_vorjahresmonat.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\nFROM past_zugriffe, current_zugriffe, past_zugriffe_vorjahresmonat\n  \"\"\";\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- declare and set the value of Monat as the value of the variable \"$Monat\"\nDECLARE Monat INT64;\nSET Monat = $Monat_wrapper;\n\n-- if \"Jahr\" is selected, then select an empty string\nIF Monat > 12 THEN \n  EXECUTE IMMEDIATE \"\"\"\n  WITH past_zugriffe AS(\n  SELECT\n  SUM(m_zugriffe_1) AS past_sum\n  FROM $platform_dataset\n  WHERE $vorjahresmonat_zeitraum\n  AND platform = \"Spotify\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n),\ncurrent_zugriffe AS(\n  SELECT\n  SUM(m_zugriffe_1) AS current_sum\n  FROM $platform_dataset\n  WHERE \n  $Zeitraum\n  AND platform = \"Spotify\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n  \n)\nSELECT\n-- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\nCASE\nWHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\nELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END\nFROM past_zugriffe, current_zugriffe\n\"\"\";\n\n-- if a month is selected, then compute the difference\nELSE \n  EXECUTE IMMEDIATE \"\"\"\n    WITH past_zugriffe AS(\n    SELECT\n  SUM(m_zugriffe_1) AS past_sum\nFROM $platform_dataset\nWHERE $vormonat_zeitraum\n        AND platform = \"Spotify\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n),\ncurrent_zugriffe AS(\n    SELECT\n  SUM(m_zugriffe_1) AS current_sum\nFROM $platform_dataset\nWHERE $Zeitraum\nAND platform = \"Spotify\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n),\npast_zugriffe_vorjahresmonat AS(\n  SELECT\n  SUM(m_zugriffe_1) AS past_sum\n  FROM $platform_dataset\n  WHERE $vorjahresmonat_zeitraum\n  AND platform = \"Spotify\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n)\nSELECT\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN current_sum / past_zugriffe.past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_zugriffe.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_zugriffe.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN current_sum / past_zugriffe_vorjahresmonat.past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_zugriffe_vorjahresmonat.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_zugriffe_vorjahresmonat.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\nFROM past_zugriffe, current_zugriffe, past_zugriffe_vorjahresmonat\n  \"\"\";\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- declare and set the value of Monat as the value of the variable \"$Monat\"\nDECLARE Monat INT64;\nSET Monat = $Monat_wrapper;\n\n-- if \"Jahr\" is selected, then select an empty string\nIF Monat > 12 THEN \n  EXECUTE IMMEDIATE \"\"\"\n  WITH past_zugriffe AS(\n  SELECT\n  SUM(m_zugriffe_1) AS past_sum\n  FROM $platform_dataset\n  WHERE $vorjahresmonat_zeitraum\n  AND platform = \"Apple Podcasts\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n),\ncurrent_zugriffe AS(\n  SELECT\n  SUM(m_zugriffe_1) AS current_sum\n  FROM $platform_dataset\n  WHERE \n  $Zeitraum\n  AND platform = \"Apple Podcasts\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n)\nSELECT\n-- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\nCASE\nWHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\nELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END\nFROM past_zugriffe, current_zugriffe\n\"\"\";\n\n-- if a month is selected, then compute the difference\nELSE \n  EXECUTE IMMEDIATE \"\"\"\n    WITH past_zugriffe AS(\n    SELECT\n  SUM(m_zugriffe_1) AS past_sum\nFROM $platform_dataset\nWHERE $vormonat_zeitraum\n        AND platform = \"Apple Podcasts\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n        \n),\ncurrent_zugriffe AS(\n    SELECT\n  SUM(m_zugriffe_1) AS current_sum\nFROM $platform_dataset\nWHERE $Zeitraum\nAND platform = \"Apple Podcasts\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n),\npast_zugriffe_vorjahresmonat AS(\n  SELECT\n  SUM(m_zugriffe_1) AS past_sum\n  FROM $platform_dataset\n  WHERE $vorjahresmonat_zeitraum\n  AND platform = \"Apple Podcasts\"\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n\n)\nSELECT\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN current_sum / past_zugriffe.past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_zugriffe.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_zugriffe.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN current_sum / past_zugriffe_vorjahresmonat.past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_zugriffe_vorjahresmonat.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_zugriffe_vorjahresmonat.past_sum - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\nFROM past_zugriffe, current_zugriffe, past_zugriffe_vorjahresmonat\n  \"\"\";\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$plattformen_images\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Plattformen | Zugriffe",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1) as Monat, SUM(m_zugriffe_1) AS Zugriffe\r\nFROM $platform_dataset\r\nWHERE \r\nCASE\r\nWHEN \"${Monat:text}\" = \"Jahr\" THEN EXTRACT(YEAR FROM date) = $Jahr\r\nWHEN CONTAINS_SUBSTR(\"${Monat:text}\",\"Quartal\") THEN $Zeitraum\r\nWHEN CONTAINS_SUBSTR(\"${Monat:text}\",\"Halbjahr\") THEN $Zeitraum\r\nELSE (DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1) <= DATE($Jahr, $Monat_wrapper, 1) AND DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1)  >= DATE_SUB(DATE($Jahr, $Monat_wrapper, 1), INTERVAL 12 MONTH)) END\r\nAND\r\nCASE \"$Plattformen\"\r\nWHEN \"Alle Plattformen\" THEN TRUE\r\nELSE platform = \"$Plattformen\" END\r\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\nGROUP BY Monat\r\nORDER BY Monat ASC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Zusammensetzung Zugriffe ${LRA} Gesamt |  ${Monat_text} ${Jahr}'))), 'Zusammensetzung Zugriffe ${LRA} Gesamt |  ${Monat:text} ${Jahr}'), \nFROM(\nSELECT 'Zusammensetzung Zugriffe ${LRA} Gesamt |  ${Monat:text} ${Jahr}' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Bereiche'))), 'Bereiche'), \nFROM(\nSELECT 'Bereiche' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Podcastreihen'))), 'Podcastreihen'), \nFROM(\nSELECT 'Podcastreihen' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Genres'))), 'Genres'), \nFROM(\nSELECT 'Genres' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \nSUM(m_zugriffe_1) AS summe,\nbranding\nFROM $episode_dataset\nWHERE \n$Zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY branding"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH top_100_podcasts AS(\nSELECT \nSUM(m_zugriffe_1) AS summe,\npodcast_title\nFROM $episode_dataset AS episoden\nWHERE \n$Zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY podcast_title\nORDER BY summe DESC\nLIMIT 100\n), rest AS(\n  SELECT\n  SUM(m_zugriffe_1) AS summe,\n\"Sonstige\" AS podcast_title\nFROM $episode_dataset AS episoden\nLEFT JOIN top_100_podcasts\nUSING (podcast_title)\nWHERE \n$Zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nAND top_100_podcasts.podcast_title IS NULL\n)\nSELECT summe, CASE \nWHEN LENGTH(podcast_title) <= 20 THEN podcast_title\nELSE CONCAT(SUBSTR(podcast_title,0,20),\"...\") END\nFROM top_100_podcasts\nUNION ALL\nSELECT * FROM rest\nORDER BY summe DESC"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE LRA STRING;\nSET LRA = \"$LRA\";\n\nIF LRA = \"NDR\" THEN \n  EXECUTE IMMEDIATE \"\"\"\n    SELECT \nSUM(m_zugriffe_1) AS summe,\ngenre\nFROM $episode_dataset AS episoden\nJOIN $profiles_dataset AS profiles\nON (episoden.branding = profiles.branding AND episoden.podcast_title = profiles.podcast_title)\nWHERE \n$Zeitraum\n  AND episoden.broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY genre\n  \"\"\";\nEND IF;"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Bereiche |  ${Monat_text} ${Jahr}'))), 'Bereiche |  ${Monat:text} ${Jahr}'), \nFROM(\nSELECT 'Bereiche |  ${Monat:text} ${Jahr}' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 70 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$branding_images\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Bereich | Summe aller Podcastreihen",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1) as Monat, SUM(m_zugriffe_1) AS Zugriffe\r\nFROM $episode_dataset\r\nWHERE \r\nCASE\r\nWHEN \"${Monat:text}\" = \"Jahr\" THEN EXTRACT(YEAR FROM date) = $Jahr\r\nWHEN CONTAINS_SUBSTR(\"${Monat:text}\",\"Quartal\") THEN $Zeitraum\r\nWHEN CONTAINS_SUBSTR(\"${Monat:text}\",\"Halbjahr\") THEN $Zeitraum\r\nELSE (DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1) <= DATE($Jahr, $Monat_wrapper, 1) AND DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1)  >= DATE_SUB(DATE($Jahr, $Monat_wrapper, 1), INTERVAL 12 MONTH)) END\r\nAND\r\nCASE \"$Bereich\"\r\nWHEN \"Alle Bereiche\" THEN TRUE\r\nELSE branding = \"$Bereich\" END\r\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\nGROUP BY Monat\r\nORDER BY Monat ASC"
    }
   ]
  },
  {
   "title": "$Bereich | Alle Podcastreihen",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH zugriffe_vormonat AS (\r\n  SELECT\r\n  branding,\r\n  podcast_title,\r\n  SUM(m_zugriffe_1) AS zugriffe,\r\n  FROM $episode_dataset\r\n  WHERE\r\n  CASE\r\n  WHEN $Monat_wrapper > 12 THEN $Zeitraum\r\n  ELSE $vormonat_zeitraum END\r\n  AND CASE \"$Bereich\"\r\n  WHEN \"Alle Bereiche\" THEN TRUE\r\n  ELSE branding = \"$Bereich\" END\r\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title\r\n),\r\nzugriffe_vorjahresmonat AS (\r\n  SELECT\r\n  branding,\r\n  podcast_title,\r\n  SUM(m_zugriffe_1) AS zugriffe,\r\n  FROM $episode_dataset\r\n  WHERE \r\n  $vorjahresmonat_zeitraum\r\n  AND CASE \"$Bereich\"\r\n  WHEN \"Alle Bereiche\" THEN TRUE\r\n  ELSE branding = \"$Bereich\" END\r\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title\r\n),\r\nzugriffe_aktuell AS (\r\n  SELECT \r\n  branding,\r\n  podcast_title,\r\n  SUM(m_zugriffe_1) AS zugriffe\r\n  FROM $episode_dataset\r\n  WHERE\r\n  $Zeitraum\r\n  AND CASE \"$Bereich\"\r\n  WHEN \"Alle Bereiche\" THEN TRUE\r\n  ELSE branding = \"$Bereich\" END\r\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title\r\n),\r\njoined_zugriffe AS (\r\n  SELECT \r\n  zugriffe_aktuell.branding, \r\n  zugriffe_aktuell.podcast_title, \r\n  zugriffe_aktuell.zugriffe AS aktuelle_zugriffe,\r\n  zugriffe_vormonat.zugriffe AS vormonat_zugriffe, \r\n  zugriffe_vorjahresmonat.zugriffe AS vorjahresmonat_zugriffe\r\n  FROM zugriffe_aktuell\r\n  LEFT JOIN zugriffe_vormonat ON (zugriffe_aktuell.branding = zugriffe_vormonat.branding AND zugriffe_aktuell.podcast_title = zugriffe_vormonat.podcast_title)\r\n  LEFT JOIN zugriffe_vorjahresmonat ON (zugriffe_aktuell.branding = zugriffe_vorjahresmonat.branding AND zugriffe_aktuell.podcast_title = zugriffe_vorjahresmonat.podcast_title)\r\n)\r\nSELECT \r\nbranding AS Bereich,\r\npodcast_title AS Podcast,\r\naktuelle_zugriffe AS Zugriffe,\r\nCASE \r\nWHEN $Monat_wrapper > 12 THEN CAST(NULL AS INT64)\r\nELSE aktuelle_zugriffe - vormonat_zugriffe\r\nEND AS AbsoluteAenderungVormonat,\r\nCASE\r\nWHEN $Monat_wrapper > 12 THEN CAST(NULL AS INT64)\r\nELSE (aktuelle_zugriffe / vormonat_zugriffe - 1) * 100\r\nEND AS ProzentAenderungVormonat,\r\naktuelle_zugriffe - vorjahresmonat_zugriffe AS AbsoluteAenderungVorjahresmonat,\r\n(aktuelle_zugriffe / vorjahresmonat_zugriffe - 1) * 100 AS ProzentAenderungVorjahresmonat\r\nFROM joined_zugriffe\r\nORDER BY aktuelle_zugriffe DESC"
    }
   ]
  },
  {
   "title": "$Bereich | Alle Episoden",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SAFE_CAST(publication_date_2 AS DATE) as publication_date_2,\n  podcast_title,\n    broadcast_id,\n  headline,\n  SUM(zugriffe) as zugriffe\nFROM (\n  SELECT\n    FIRST_VALUE(publication_date_1) OVER (PARTITION BY headline ORDER BY publication_date_1 DESC) AS publication_date_2,\n    REPLACE(podcast_title,'\"','') AS podcast_title,\n      broadcast_id,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n  FROM $episode_dataset\nWHERE CASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nAND $Zeitraum\n  GROUP BY\n    publication_date_1,\n    podcast_title,\n    headline,\n      broadcast_id\n  ORDER BY\n    zugriffe DESC )\nGROUP BY\n  publication_date_2,\n  podcast_title,\n  headline, \n  broadcast_id\nORDER BY zugriffe DESC\nLIMIT 1000"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Podcastreihen |  ${Monat_text} ${Jahr}'))), 'Podcastreihen |  ${Monat:text} ${Jahr}'), \nFROM(\nSELECT 'Podcastreihen |  ${Monat:text} ${Jahr}' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 120 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$podcast_images\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Podcast",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1) as Monat, SUM(m_zugriffe_1) AS Zugriffe\r\nFROM $episode_dataset\r\nWHERE \r\nCASE\r\nWHEN \"${Monat:text}\" = \"Jahr\" THEN EXTRACT(YEAR FROM date) = $Jahr\r\nWHEN CONTAINS_SUBSTR(\"${Monat:text}\",\"Quartal\") THEN $Zeitraum\r\nWHEN CONTAINS_SUBSTR(\"${Monat:text}\",\"Halbjahr\") THEN $Zeitraum \r\nELSE (DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1) <= DATE($Jahr, $Monat_wrapper, 1) AND DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1)  >= DATE_SUB(DATE($Jahr, $Monat_wrapper, 1), INTERVAL 12 MONTH)) END\r\nAND\r\nCASE \"$Podcast\"\r\nWHEN \"Alle Titel\" THEN TRUE\r\nELSE podcast_title = \"$Podcast\" END\r\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\nGROUP BY Monat\r\nORDER BY Monat ASC"
    }
   ]
  },
  {
   "title": "$Podcast | Alle Episoden",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SAFE_CAST(publication_date_2 AS DATE) as publication_date_2,\n  podcast_title,\n    broadcast_id,\n  headline,\n  SUM(zugriffe) as zugriffe\nFROM (\n  SELECT\n    FIRST_VALUE(publication_date_1) OVER (PARTITION BY headline ORDER BY publication_date_1 DESC) AS publication_date_2,\n    REPLACE(podcast_title,'\"','') AS podcast_title,\n      broadcast_id,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n  FROM $episode_dataset\nWHERE CASE \"$Podcast\"\nWHEN \"Alle Titel\" THEN TRUE\nELSE podcast_title = \"$Podcast\" END\nAND $Zeitraum\n  AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n  GROUP BY\n    publication_date_1,\n    podcast_title,\n    headline,\n      broadcast_id\n  ORDER BY\n    zugriffe DESC )\nGROUP BY\n  publication_date_2,\n  podcast_title,\n  headline, \n  broadcast_id\nORDER BY zugriffe DESC\nLIMIT 1000"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Genres |  ${Monat_text} ${Jahr}'))), 'Genres |  ${Monat:text} ${Jahr}'), \nFROM(\nSELECT 'Genres |  ${Monat:text} ${Jahr}' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 156 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Genre",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE LRA STRING;\r\nSET LRA = \"$LRA\";\r\n\r\nIF LRA = \"NDR\" THEN  \r\n  EXECUTE IMMEDIATE \"\"\"\r\n    SELECT DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1) as Monat, SUM(m_zugriffe_1) AS Zugriffe\r\nFROM $episode_dataset\r\nWHERE \r\nCASE \r\nWHEN \"${Monat:text}\" = \"Jahr\" THEN EXTRACT(YEAR FROM date) = $Jahr\r\nWHEN CONTAINS_SUBSTR(\"${Monat:text}\",\"Quartal\") THEN $Zeitraum\r\nWHEN CONTAINS_SUBSTR(\"${Monat:text}\",\"Halbjahr\") THEN $Zeitraum\r\nELSE (DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1) <= DATE($Jahr, $Monat_wrapper, 1) AND DATE(EXTRACT(YEAR from date),EXTRACT(MONTH from date), 1)  >= DATE_SUB(DATE($Jahr, $Monat_wrapper, 1), INTERVAL 12 MONTH)) END\r\nAND\r\npodcast_title IN (SELECT podcast_title\r\n  FROM $profiles_dataset\r\n  WHERE\r\n  CASE \"$Genre\"\r\n  WHEN \"Alle Genres\" THEN TRUE\r\n  ELSE genre = \"$Genre\" END\r\n  AND broadcast_id[0] NOT IN ($mdr_ard_kultur_podcasts)\r\n  )\r\nGROUP BY Monat\r\nORDER BY Monat ASC\r\n  \"\"\";\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$Genre | Alle Podcastreihen",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 169 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE LRA STRING;\r\nSET LRA = \"$LRA\";\r\n\r\nIF LRA = \"NDR\" THEN \r\n  EXECUTE IMMEDIATE \"\"\"\r\n    WITH zugriffe_vormonat AS (\r\n  SELECT\r\n  branding,\r\n  podcast_title,\r\n  SUM(m_zugriffe_1) AS zugriffe,\r\n  FROM $episode_dataset\r\n  WHERE\r\n  CASE\r\n  WHEN $Monat_wrapper > 12 THEN $Zeitraum\r\n  ELSE $vormonat_zeitraum END\r\n  AND podcast_title IN (SELECT podcast_title\r\n  FROM $profiles_dataset\r\n  WHERE\r\n  CASE \"$Genre\"\r\n  WHEN \"Alle Genres\" THEN TRUE\r\n  ELSE genre = \"$Genre\" END\r\n  AND broadcast_id[0] NOT IN ($mdr_ard_kultur_podcasts)\r\n  )\r\n  GROUP BY branding, podcast_title\r\n),\r\nzugriffe_vorjahresmonat AS (\r\n  SELECT\r\n  branding,\r\n  podcast_title,\r\n  SUM(m_zugriffe_1) AS zugriffe,\r\n  FROM $episode_dataset\r\n  WHERE \r\n  $vorjahresmonat_zeitraum\r\n  AND podcast_title IN (SELECT podcast_title\r\n  FROM $profiles_dataset\r\n  WHERE\r\n  CASE \"$Genre\"\r\n  WHEN \"Alle Genres\" THEN TRUE\r\n  ELSE genre = \"$Genre\" END\r\n  AND broadcast_id[0] NOT IN ($mdr_ard_kultur_podcasts)\r\n  )\r\n  GROUP BY branding, podcast_title\r\n),\r\nzugriffe_aktuell AS (\r\n  SELECT \r\n  branding,\r\n  podcast_title,\r\n  SUM(m_zugriffe_1) AS zugriffe\r\n  FROM $episode_dataset\r\n  WHERE\r\n  $Zeitraum\r\n  AND podcast_title IN (SELECT podcast_title\r\n  FROM $profiles_dataset\r\n  WHERE\r\n  CASE \"$Genre\"\r\n  WHEN \"Alle Genres\" THEN TRUE\r\n  ELSE genre = \"$Genre\" END\r\n  AND broadcast_id[0] NOT IN ($mdr_ard_kultur_podcasts)\r\n  )\r\n  GROUP BY branding, podcast_title\r\n),\r\njoined_zugriffe AS (\r\n  SELECT \r\n  zugriffe_aktuell.branding, \r\n  zugriffe_aktuell.podcast_title,\r\n  profiles.genre, \r\n  zugriffe_aktuell.zugriffe AS aktuelle_zugriffe,\r\n  zugriffe_vormonat.zugriffe AS vormonat_zugriffe, \r\n  zugriffe_vorjahresmonat.zugriffe AS vorjahresmonat_zugriffe\r\n  FROM zugriffe_aktuell\r\n  LEFT JOIN zugriffe_vormonat ON (zugriffe_aktuell.branding = zugriffe_vormonat.branding AND zugriffe_aktuell.podcast_title = zugriffe_vormonat.podcast_title)\r\n  LEFT JOIN zugriffe_vorjahresmonat ON (zugriffe_aktuell.branding = zugriffe_vorjahresmonat.branding AND zugriffe_aktuell.podcast_title = zugriffe_vorjahresmonat.podcast_title)\r\n  LEFT JOIN $profiles_dataset AS profiles ON (zugriffe_aktuell.branding = profiles.branding AND zugriffe_aktuell.podcast_title = profiles.podcast_title)\r\n)\r\nSELECT \r\nbranding AS Bereich,\r\npodcast_title AS Podcast,\r\ngenre AS Genre,\r\naktuelle_zugriffe AS Zugriffe,\r\nCASE \r\nWHEN $Monat_wrapper > 12 THEN CAST(NULL AS INT64)\r\nELSE aktuelle_zugriffe - vormonat_zugriffe\r\nEND AS AbsoluteAenderungVormonat,\r\nCASE\r\nWHEN $Monat_wrapper > 12 THEN CAST(NULL AS INT64)\r\nELSE (aktuelle_zugriffe / vormonat_zugriffe - 1) * 100\r\nEND AS ProzentAenderungVormonat,\r\naktuelle_zugriffe - vorjahresmonat_zugriffe AS AbsoluteAenderungVorjahresmonat,\r\n(aktuelle_zugriffe / vorjahresmonat_zugriffe - 1) * 100 AS ProzentAenderungVorjahresmonat\r\nFROM joined_zugriffe\r\nORDER BY aktuelle_zugriffe DESC\r\n  \"\"\";\r\nEND IF;"
    }
   ]
  },
  {
   "title": "$Genre | Alle Episoden",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE LRA STRING;\nSET LRA = \"$LRA\";\n\nIF LRA = \"NDR\" THEN \n  EXECUTE IMMEDIATE \"\"\"\n    WITH episoden AS(SELECT\n  SAFE_CAST(publication_date_2 AS DATE) as publication_date_2,\n  podcast_title,\n    broadcast_id,\n  headline,\n  SUM(zugriffe) as zugriffe\nFROM (\n  SELECT\n    FIRST_VALUE(publication_date_1) OVER (PARTITION BY headline ORDER BY publication_date_1 DESC) AS publication_date_2,\n    REPLACE(podcast_title,'\"','') AS podcast_title,\n      broadcast_id,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n  FROM $episode_dataset\nWHERE podcast_title IN (SELECT podcast_title\n  FROM $profiles_dataset\n  WHERE\n  CASE \"$Genre\"\n  WHEN \"Alle Genres\" THEN TRUE\n  ELSE genre = \"$Genre\" END\n  AND broadcast_id[0] NOT IN ($mdr_ard_kultur_podcasts)\n  )\nAND $Zeitraum\n  GROUP BY\n    publication_date_1,\n    podcast_title,\n    headline,\n      broadcast_id\n  ORDER BY\n    zugriffe DESC )\nGROUP BY\n  publication_date_2,\n  podcast_title,\n  headline, \n  broadcast_id\nORDER BY zugriffe DESC\nLIMIT 1000)\nSELECT episoden.publication_date_2, episoden.podcast_title, profiles.genre, episoden.headline, episoden.zugriffe\nFROM episoden\nJOIN $profiles_dataset AS profiles\nON episoden.podcast_title = profiles.podcast_title\n  \"\"\";\nEND IF;"
    }
   ]
  }
 ]
}