{
 "title": "WIP Web&App Dashboard fester Zeitraum",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "LRA", "query": "NDR,MDR" },
   {
    "name": "Redaktionen",
    "query": {}
   },
   {
    "name": "Unterkapitel",
    "query": {}
   },
   {
    "name": "Sendung",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": "Heute : EXTRACT(DATE from time) = CURRENT_DATE(),Gestern : EXTRACT(DATE from time) = DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY), Letztes Wochenende :  DATE(time) >= (SELECT saturday FROM(SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 2 DAY) as saturday))  AND DATE(time) <= (SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 1 DAY) as sunday), Letzte 7 Tage : time >= DATE_SUB(CURRENT_DATE()\\, INTERVAL  7 DAY) AND time < CURRENT_DATE(), Letzte 30 Tage : time >= DATE_SUB(CURRENT_DATE()\\, INTERVAL  30 DAY) AND time <= CURRENT_DATE()"
   },
   {
    "name": "Vergleichszeitraum",
    "query": {}
   },
   {
    "name": "Tage",
    "query": {}
   },
   {
    "name": "app_name",
    "query": {}
   },
   {
    "name": "site_level2",
    "query": {}
   },
   {
    "name": "page_chapter1",
    "query": {}
   },
   {
    "name": "page_chapter2",
    "query": {}
   },
   {
    "name": "sendungsid",
    "query": {}
   },
   {
    "name": "av_condition",
    "query": {}
   },
   {
    "name": "app_name_long",
    "query": {}
   },
   {
    "name": "table_fever_curve",
    "query": {}
   },
   {
    "name": "Einheit",
    "query": {}
   },
   {
    "name": "granularity",
    "query": {}
   },
   {
    "name": "av_table_fever_curve",
    "query": {}
   },
   {
    "name": "hinweis_zeitraum",
    "query": {}
   },
   {
    "name": "fromDay",
    "query": {}
   },
   {
    "name": "toDay",
    "query": {}
   },
   {
    "name": "av_page_chapter2",
    "query": {}
   },
   {
    "name": "webFilter",
    "query": {}
   },
   {
    "name": "avwebFilter",
    "query": {}
   },
   {
    "name": "articleTable",
    "query": {}
   },
   {
    "name": "newZeitraum",
    "query": {}
   },
   {
    "name": "listwebFilter",
    "query": {}
   },
   {
    "name": "list_page_chapter2",
    "query": {}
   },
   {
    "name": "avZeitraum",
    "query": {}
   },
   {
    "name": "zeitraumListe",
    "query": {}
   },
   {
    "name": "oldZeitraum",
    "query": {}
   },
   {
    "name": "fevergranularity",
    "query": {}
   },
   {
    "name": "appFilter",
    "query": {}
   },
   {
    "name": "buffer",
    "query": {}
   },
   {
    "name": "avzeitraumListe",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Verlaufsdiagramme", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Visits - Web - Verlaufsdiagramm",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with now as (\r\n  With A as (\r\n    SELECT\r\n      CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 7 Tage' THEN 0\r\n        ELSE m_visits\r\n      END as m_visits,\r\n      $fevergranularity as time,\r\n      date\r\n    FROM\r\n      `ndr-code-bi-dashboard.Piano.total_visits${table_fever_curve}`\r\n    WHERE\r\n      $webFilter\r\n      AND DATE(tmstp) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)\r\n      AND DATE(tmstp) <= CURRENT_DATE()\r\n      AND CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 30 Tage' THEN DATE(tmstp) < DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)\r\n        ELSe TRUE\r\n        END\r\n  ),\r\n  B as (\r\n    SELECT\r\n      CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 7 Tage' THEN MAX(m_visits)\r\n        WHEN 'Letzte 30 Tage' THEN MAX(m_visits)\r\n        ELSE 0\r\n      END as m_visits,\r\n      date as time,\r\n      date\r\n    FROM\r\n      `ndr-code-bi-dashboard.Piano.total_visits_today_append`\r\n    WHERE\r\n      $webFilter\r\n      AND CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 30 Tage' THEN date = CURRENT_DATE()\r\n        OR date = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)\r\n        ELSE TRUE\r\n      END\r\n    GROUP BY\r\n      date\r\n  )\r\n  SELECT\r\n    *\r\n  FROM\r\n    A\r\n  UNION\r\n  ALL\r\n  SELECt\r\n    *\r\n  FROM\r\n    B\r\n),\r\ndata as (\r\n  SELECT\r\n    sum(m_visits) as m_visits,\r\n    $granularity as time,\r\n    '${Zeitraum:text}' as Zeitraum\r\n  FROM\r\n    now\r\n  WHERE\r\n    $Zeitraum\r\n    AND $newZeitraum\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  CASE '${Zeitraum:text}'\r\n    WHEN 'Letzte 30 Tage' THEN DATE_SUB(time, INTERVAL 1 DAY)\r\n    ELSE time\r\n    END AS time,\r\n  Zeitraum,\r\n  CASE\r\n    '${Zeitraum:text}'\r\n    WHEN 'Heute' THEN IF(\r\n      (\r\n        m_visits - LAG(m_visits) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      ) < 0,\r\n      0,\r\n      (\r\n        m_visits - LAG(m_visits) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      )\r\n    )\r\n    WHEN 'Gestern' THEN IF(\r\n      (\r\n        m_visits - LAG(m_visits) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      ) < 0,\r\n      0,\r\n      (\r\n        m_visits - LAG(m_visits) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      )\r\n    )\r\n    ELSE IF(m_visits < 0, 0, m_visits)\r\n  ENd as m_visits\r\nFROM\r\n  data\r\n  WHERE m_visits > 0\r\nORDER BY\r\n  time ASC"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with past as (\r\n  SELECT\r\n    m_visits,\r\n    datetime_add(\r\n      datetime($fevergranularity),\r\n      INTERVAL $Tage $Einheit\r\n    ) as time,\r\n    date_ADD(date, INTERVAL $Tage $Einheit) as date\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.total_visits${table_fever_curve}`\r\n  WHERE\r\n    $webFilter --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n),\r\ndata as (\r\n  SELECT\r\n    sum(m_visits) as m_visits,\r\n    $granularity as time,\r\n    '${Vergleichszeitraum:text}' as Zeitraum\r\n  FROM\r\n    past\r\n  WHERE\r\n    CASE\r\n      '${Zeitraum:text}'\r\n      WHEN 'Letzte 7 Tage' THEN date <= DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)\r\n      ELSE $Zeitraum\r\n    END\r\n    AND $newZeitraum\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  CASE\r\n    '${Zeitraum:text}'\r\n    WHEN 'Letzte 7 Tage' THEN DATE_SUB(time, INTERVAL 1 DAY)\r\n    ELSE time\r\n  END as time,\r\n  Zeitraum,\r\n  CASE\r\n    '${Zeitraum:text}'\r\n    WHEN 'Heute' THEN IF(\r\n      (\r\n        m_visits - LAG(m_visits) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      ) < 0,\r\n      0,\r\n      (\r\n        m_visits - LAG(m_visits) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      )\r\n    )\r\n    WHEN 'Gestern' THEN IF(\r\n      (\r\n        m_visits - LAG(m_visits) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      ) < 0,\r\n      0,\r\n      (\r\n        m_visits - LAG(m_visits) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      )\r\n    )\r\n    ELSE IF(m_visits < 0, 0, m_visits)\r\n  ENd as m_visits\r\nFROM\r\n  data\r\nORDER BY\r\n  time ASC\r\n"
    }
   ]
  },
  {
   "title": "Wiedergaben - Web - Verlaufsdiagramm",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with now as \r\n(SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(tmstp) as time\r\nFROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n  ($avwebFilter\r\n  --AND sendungs_id = '$Sendung'\r\n  )\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  GROUP BY time \r\n)\r\nSELECT m_av_playbacks, date(time) as time, '${Zeitraum:text}' as Zeitraum\r\nFROM now \r\nWHERE $Zeitraum\r\nORDER BY time"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with old as \r\n(SELECT sum(m_av_playbacks) as m_av_playbacks, DATETIME_ADD(datetime(tmstp), INTERVAL $Tage $Einheit) as time\r\nFROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\nWHERE \r\n  ($avwebFilter  )\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  GROUP BY time \r\n)\r\nSELECT m_av_playbacks, \r\ndate(time) as time,\r\n '${Vergleichszeitraum:text}' as Zeitraum\r\nFROM old \r\nWHERE $Zeitraum\r\nORDER BY time"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 14, "y": 7 },
   "options": {
    "content": "#### AV Daten aktuell nur für MDR Apps verfügbar\n##### ${hinweis_zeitraum}\n"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Visits Web&App | ${Zeitraum:text}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with now as (\r\n  WITH A AS (\r\n    SELECT\r\n      CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 7 Tage' THEN 0\r\n        ELSE m_visits\r\n      END as m_visits,\r\n      DATETIME($fevergranularity) as time,\r\n      date\r\n    FROM\r\n      `ndr-code-bi-dashboard.Piano.total_visits${table_fever_curve}`\r\n    WHERE\r\n      ($webFilter)\r\n      AND CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 30 Tage' THEN DATE(tmstp) < DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)\r\n        ELSe TRUE\r\n      END\r\n  ),\r\n  B as (\r\n    SELECT\r\n      CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 7 Tage' THEN MAX(m_visits)\r\n        WHEN 'Letzte 30 Tage' THEN MAX(m_visits)\r\n        ELSE 0\r\n      END as m_visits,\r\n      date as time,\r\n      date\r\n    FROM\r\n      `ndr-code-bi-dashboard.Piano.total_visits_today_append`\r\n    WHERE\r\n      $webFilter\r\n      AND CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 30 Tage' THEN date = CURRENT_DATE()\r\n        OR date = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)\r\n        ELSE TRUE\r\n      END\r\n    GROUP BY\r\n      date\r\n  )\r\n  SELECT\r\n    *\r\n  FROM\r\n    A\r\n  UNION\r\n  ALL\r\n  SELECt\r\n    *\r\n  FROM\r\n    B\r\n),\r\ndata as (\r\n  SELECT\r\n    sum(m_visits) as m_visits,\r\n    $granularity as time,\r\n    'Web' as Zeitraum\r\n  FROM\r\n    now --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n  WHERE\r\n    $Zeitraum\r\n    AND $newZeitraum\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  CASE '${Zeitraum:text}'\r\n    WHEN 'Letzte 30 Tage' THEN DATE_SUB(time, INTERVAL 1 DAY)\r\n    ELSE time\r\n    END AS time,\r\n  Zeitraum,\r\n  CASE\r\n    '${Zeitraum:text}'\r\n    WHEN 'Heute' THEN IF(\r\n      (\r\n        IFNULL(m_visits, 0) - LAG(IFNULL(m_visits, 0)) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      ) < 0,\r\n      0,\r\n      (\r\n        IFNULL(m_visits, 0) - LAG(IFNULL(m_visits, 0)) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      )\r\n    )\r\n    WHEN 'Gestern' THEN IF(\r\n      (\r\n        IFNULL(m_visits, 0) - LAG(IFNULL(m_visits, 0)) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      ) < 0,\r\n      0,\r\n      (\r\n        IFNULL(m_visits, 0) - LAG(IFNULL(m_visits, 0)) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      )\r\n    )\r\n    ELSE IF(IFNULL(m_visits, 0) < 0, 0, IFNULL(m_visits, 0))\r\n  ENd as m_visits\r\nFROM\r\n  data\r\nWHERE m_visits >0\r\nORDER BY\r\n  time ASC"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with now as (\r\n  WITH A AS (\r\n    SELECT\r\n      CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 7 Tage' THEN 0\r\n        ELSE m_visits\r\n      END as m_visits,\r\n      DATETIME($fevergranularity) as time,\r\n      date\r\n    FROM\r\n      `ndr-code-bi-dashboard.Piano.total_visits${table_fever_curve}`\r\n    WHERE\r\n      ($appFilter)\r\n      AND CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 30 Tage' THEN DATE(tmstp) < DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)\r\n        ELSe TRUE\r\n      END\r\n  ),\r\n  B AS (\r\n    SELECT\r\n      CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 7 Tage' THEN MAX(m_visits)\r\n        WHEN 'Letzte 30 Tage' THEN MAX(m_visits)\r\n        ELSE 0\r\n      END as m_visits,\r\n      date as time,\r\n      date\r\n    FROM\r\n      `ndr-code-bi-dashboard.Piano.total_visits_today_append`\r\n    WHERE\r\n      $appFilter\r\n      AND CASE\r\n        '${Zeitraum:text}'\r\n        WHEN 'Letzte 30 Tage' THEN date = CURRENT_DATE()\r\n        OR date = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)\r\n        ELSE TRUE\r\n      END\r\n    GROUP BY\r\n      date\r\n  )\r\n  SELECT\r\n    *\r\n  FROM\r\n    A\r\n  UNION\r\n  ALL\r\n  SELECt\r\n    *\r\n  FROM\r\n    B\r\n),\r\ndata as (\r\n  SELECT\r\n    DISTINCT(sum(m_visits)) as m_visits,\r\n    $granularity as time,\r\n    'App' as Zeitraum\r\n  FROM\r\n    now --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n  WHERE\r\n    $Zeitraum\r\n    AND $newZeitraum\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  CASE '${Zeitraum:text}'\r\n    WHEN 'Letzte 30 Tage' THEN DATE_SUB(time, INTERVAL 1 DAY)\r\n    ELSE time\r\n    END AS time,\r\n  Zeitraum,\r\n  CASE\r\n    '${Zeitraum:text}'\r\n    WHEN 'Heute' THEN IF(\r\n      (\r\n        IFNULL(m_visits, 0) - LAG(IFNULL(m_visits, 0)) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      ) < 0,\r\n      0,\r\n      (\r\n        IFNULL(m_visits, 0) - LAG(IFNULL(m_visits, 0)) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      )\r\n    )\r\n    WHEN 'Gestern' THEN IF(\r\n      (\r\n        IFNULL(m_visits, 0) - LAG(IFNULL(m_visits, 0)) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      ) < 0,\r\n      0,\r\n      (\r\n        IFNULL(m_visits, 0) - LAG(IFNULL(m_visits, 0)) OVER (\r\n          PARTITION BY Zeitraum\r\n          ORDER BY\r\n            time ASC\r\n        )\r\n      )\r\n    )\r\n    ELSE IF(IFNULL(m_visits, 0) < 0, 0, IFNULL(m_visits, 0))\r\n  ENd as m_visits\r\nFROM\r\n  data\r\n  WHERE m_visits >0\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "Wiedergaben Web&App | ${Zeitraum:text}",
   "type": "volkovlabs-echarts-panel",
   "description": "Daten nur für MDR Apps verfügbar",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with data as (\r\n  SELECT sum(m_av_playbacks) as m_av_playbacks, \r\n  datetime(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE ($avwebFilter) \r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  GROUP BY time \r\n)\r\nSELECT \r\n  m_av_playbacks, \r\n  date(time) as time, \r\n  'Web' as Zeitraum, \r\n  '${Zeitraum:text}' as Darstellung\r\nFROM data \r\n--WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\nWHERE $Zeitraum\r\nORDER BY time"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with app as (\r\n  SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE ${av_condition}\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n     GROUP BY time \r\n)\r\nSELECT m_av_playbacks, DATE(time) as time, 'App' as Zeitraum, '${Zeitraum:text}' as Darstellung\r\nFROM app \r\nWHERE $Zeitraum\r\n--GROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 } },
  { "title": "KPI Boxes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 5, "x": 4, "y": 19 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 5, "x": 9, "y": 19 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 5, "x": 14, "y": 19 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 5, "x": 19, "y": 19 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 22 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND $newZeitraum),\r\na as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits${table_fever_curve}` \r\n  WHERE $appFilter AND $newZeitraum\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY m_visits DESC\r\n  LIMIT 1)\r\n\r\n\r\nSELECT  w.m_visits + a.m_visits as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM (\r\n      SELECT DATE_ADD(date, INTERVAL ${Tage} ${Einheit}) as date, m_visits\r\n      FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n      WHERE $webFilter \r\n    )\r\n    WHERE $newZeitraum\r\n),\r\na as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits${table_fever_curve}` \r\n  WHERE $appFilter AND $newZeitraum\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY m_visits DESC\r\n  LIMIT 1\r\n    )\r\nSELECT  w.m_visits + a.m_visits as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith w as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($webFilter\r\n    AND $newZeitraum \r\n    ) \r\n),\r\na as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter\r\n  AND $newZeitraum \r\n)\r\nSELECT REPLACE( CAST(ROUND(SUM(w.m_page_loads+a.m_page_loads)/SUM(w.m_visits + a.m_visits),2) as string), '.', ',') as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith w as (\r\n  SELECT SUM(m_visits) as m_visits, sum(m_page_loads) as m_page_loads, 1 as id\r\n  FROM (\r\n      SELECT m_visits, datetime_add(datetime(date), INTERVAL ${Tage} ${Einheit}) as date, m_page_loads \r\n      FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n      WHERE \r\n        $webFilter\r\n      ) \r\n  --WHERE $Zeitraum\r\n  WHERE $newZeitraum  \r\n  ),\r\na as (\r\n  SELECT SUM(m_visits) as m_visits, 1 as id,sum(m_page_loads) as m_page_loads\r\n  FROM(\r\n    SELECT datetime_add(datetime(date), INTERVAL ${Tage} ${Einheit}) as date, m_visits, m_page_loads\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $appFilter)\r\n  WHERE $newZeitraum  \r\n  )\r\n\r\nSELECT REPLACE( CAST(ROUND(SUM(w.m_page_loads+a.m_page_loads)/SUM(w.m_visits + a.m_visits),2) as string), '.', ',') as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n    --Select 'N/A' as Zeitraum\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $webFilter \r\n  )\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM now \r\n  --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n  WHERE $newZeitraum\r\n),\r\na as(\r\n    --Select 'N/A' as Zeitraum\r\n\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($appFilter\r\n    --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    ) \r\n  )\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM now \r\n  --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n   WHERE $newZeitraum\r\n)\r\nSELECT  CONCAT(REPLACE(CAST(ROUND((a.time_spent + w.time_spent)/(a.visits + w.visits),1) as STRING), '.', ','), ' Sek.') as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n    --Select 'N/A' as Zeitraum\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, DATE_ADD(date, INTERVAL $Tage $Einheit) as date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $webFilter \r\n  )\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM now \r\n  --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n  WHERE $newZeitraum\r\n),\r\na as(\r\n    --Select 'N/A' as Zeitraum\r\n\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($appFilter\r\n    --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    ) \r\n  )\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM now \r\n  --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n   WHERE $newZeitraum\r\n)\r\nSELECT  CONCAT(REPLACE(CAST(ROUND((a.time_spent + w.time_spent)/(a.visits + w.visits),1) as STRING), '.', ','), ' Sek.') as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as \r\n(\r\n  SELECT \r\n    sum(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n  WHERE $newZeitraum AND $avwebFilter\r\n),\r\napp as (\r\n  SELECT \r\n    SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n  WHERE ${av_condition} AND $newZeitraum \r\n )\r\nSELECT SUM(web.Zeitraum) + SUM(app.Zeitraum) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with data_web as \r\n(\r\n  SELECT sum(m_av_playbacks) as m_av_playbacks, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as date\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE $avwebFilter\r\n  AND date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    GROUP BY date \r\n),\r\nweb as (\r\n  SELECT \r\n  sum(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_web\r\n  WHERE $newZeitraum),\r\ndata_app as (\r\n  SELECT m_av_playbacks, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as date\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE ${av_condition}\r\n  AND date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n),\r\napp as (\r\n  SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $newZeitraum\r\n)\r\nSELECT web.Zeitraum + app.Zeitraum as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND $newZeitraum),\r\na as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits${table_fever_curve}` \r\n  WHERE $appFilter AND $newZeitraum\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY m_visits DESC\r\n  LIMIT 1),\r\n\r\nnew_data as (SELECT  w.m_visits + a.m_visits as Zeitraum, 2 as id\r\nFROM w \r\nJOIN a ON w.id = a.id),\r\n--Select 'N/A' as Zeitraum\r\nw_old as (\r\n    SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM (\r\n      SELECT DATE_ADD(date, INTERVAL ${Tage} ${Einheit}) as date, m_visits\r\n      FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n      WHERE $webFilter \r\n    )\r\n    WHERE $newZeitraum),\r\na_old as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n    FROM (\r\n      SELECT DATE_ADD(date, INTERVAL ${Tage} ${Einheit}) as date, m_visits, site_level2, tmstp\r\n      FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n      WHERE $appFilter\r\n    )\r\n    WHERE $newZeitraum \r\n    GROUP BY site_level2, tmstp\r\n  ORDER BY m_visits DESC\r\n  LIMIT 1),\r\nold_data as (SELECT  w_old.m_visits + a_old.m_visits as Zeitraum, 2 as id\r\nFROM w_old\r\nJOIN a_old ON w_old.id = a_old.id)\r\nSELECT CONCAT(IF(ROUND(((new_data.Zeitraum / old_data.Zeitraum )-1)*100,1)>0, '+', ''),REPLACE(CAST(ROUND(((new_data.Zeitraum / old_data.Zeitraum )-1)*100,1) as STRING), '.', ','),' %') as Differenz\r\nFROM new_data\r\nJOIN old_data\r\nON new_data.id = old_data.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith w as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($webFilter\r\n    AND $newZeitraum \r\n    ) \r\n),\r\na as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter\r\n  AND $newZeitraum \r\n),\r\nnew_data as (SELECT SUM(w.m_page_loads+a.m_page_loads)/SUM(w.m_visits + a.m_visits) as Zeitraum, 2 as id\r\nFROM w \r\nJOIN a ON w.id = a.id),\r\n--Select 'N/A' as Zeitraum\r\nw_old as (\r\n  SELECT SUM(m_visits) as m_visits, sum(m_page_loads) as m_page_loads, 1 as id\r\n  FROM (\r\n      SELECT m_visits, datetime_add(datetime(date), INTERVAL ${Tage} ${Einheit}) as date, m_page_loads \r\n      FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n      WHERE \r\n        $webFilter\r\n      ) \r\n  --WHERE $Zeitraum\r\n  WHERE $newZeitraum  \r\n  ),\r\na_old as (\r\n  SELECT SUM(m_visits) as m_visits, 1 as id,sum(m_page_loads) as m_page_loads\r\n  FROM(\r\n    SELECT datetime_add(datetime(date), INTERVAL ${Tage} ${Einheit}) as date, m_visits, m_page_loads\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $appFilter)\r\n  WHERE $newZeitraum  \r\n  ),\r\nold_data as (SELECT  ROUND((w_old.m_page_loads+a_old.m_page_loads)/(w_old.m_visits + a_old.m_visits),6) as Zeitraum, 2 as id\r\nFROM w_old\r\nJOIN a_old ON w_old.id = a_old.id)\r\nSELECT CONCAT(IF(ROUND(((new_data.Zeitraum / old_data.Zeitraum )-1)*100,2)>0, '+', ''),REPLACE(CAST(ROUND(((new_data.Zeitraum / old_data.Zeitraum )-1)*100,2) as STRING), '.', ','),' %') as Differenz\r\nFROM new_data\r\nJOIN old_data\r\nON new_data.id = old_data.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n    --Select 'N/A' as Zeitraum\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, DATE_ADD(date, INTERVAL $Tage $Einheit) as date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $webFilter \r\n  )\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM now \r\n  --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n  WHERE $newZeitraum\r\n),\r\na as(\r\n    --Select 'N/A' as Zeitraum\r\n\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($appFilter\r\n    ) \r\n  )\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM now \r\n   WHERE $newZeitraum\r\n),\r\ndata_old as (SELECT  ((w.time_spent + a.time_spent)/(w.visits + a.visits)) as Zeitraum, 2 as id\r\nFROM w \r\nJOIN a ON w.id = a.id),\r\nw_new as (\r\n    --Select 'N/A' as Zeitraum\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $webFilter \r\n  )\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM now \r\n  --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n  WHERE $newZeitraum\r\n),\r\na_new as(\r\n    --Select 'N/A' as Zeitraum\r\n\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($appFilter\r\n    --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    ) \r\n  )\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM now \r\n  --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n   WHERE $newZeitraum\r\n),\r\ndata_new as (\r\n  SELECT  ((w_new.time_spent + a_new.time_spent)/(w_new.visits + a_new.visits)) as Zeitraum, 2 as id\r\n  FROM w_new \r\n  JOIN a_new ON w_new.id = a_new.id)\r\n\r\nSELECT CONCAT(IF(ROUND(((data_new.Zeitraum/data_old.Zeitraum)-1)*100,2)>0, '+',''),REPLACE(CAST(ROUND(((data_new.Zeitraum/data_old.Zeitraum)-1)*100,2) as STRING), '.', ','), '%') as Differenz\r\nfrom data_old\r\njoin data_new\r\non data_old.id = data_new.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with old as (with data_web as \r\n  (SELECT sum(m_av_playbacks) as m_av_playbacks, DATETIME(DATE_ADD(date(date), INTERVAL $Tage $Einheit)) as date, \r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE \r\n    ($avwebFilter\r\n    )\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    GROUP BY date \r\n  ),\r\n  web as (\r\n    SELECT \r\n    sum(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_web\r\n    WHERE $newZeitraum),\r\n  data_app as (SELECT m_av_playbacks, DATETIME(DATE_ADD(date(date), INTERVAL $Tage $Einheit)) as date, \r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE ${av_condition}\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  ),\r\n  app as (SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $newZeitraum )\r\n  SELECT SUM(web.Zeitraum) + SUM(app.Zeitraum) as Zeitraum, 2 as id\r\n  FROM web\r\n  JOIN app\r\n  ON web.id = app.id\r\n),\r\nnew_data as (\r\n    with data_web as \r\n  (SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(date) as date\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE \r\n    $avwebFilter\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    GROUP BY date \r\n  ),\r\n  web as (\r\n    SELECT \r\n    sum(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_web\r\n    WHERE $newZeitraum ),\r\n  data_app as (SELECT m_av_playbacks, DATETIME(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE ${av_condition}\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  ),\r\n  app as (SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $Zeitraum )\r\n  SELECT SUM(web.Zeitraum) + SUM(app.Zeitraum) as Zeitraum, 2 as id\r\n  FROM web\r\n  JOIN app\r\n  ON web.id = app.id\r\n\r\n\r\n\r\n)\r\nSELECT CONCAT(IF(ROUND(((new_data.Zeitraum / old.Zeitraum)-1)*100,1)>0, '+', ''),REPLACE(CAST(ROUND(((new_data.Zeitraum / old.Zeitraum)-1)*100,1) as string), '.', ','), ' %') as Zeitraum\r\nFROM old\r\nJOIN new_data\r\nON old.id = new_data.id"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\n--with now as (\r\n--  SELECT m_visits, datetime(tmstp) as time\r\n--  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n--  WHERE \r\n--    ($webFilter)\r\n--   AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n--  )\r\n--SELECT  SUM(m_visits) as Zeitraum\r\n--FROM now \r\n--WHERE $Zeitraum\r\n\r\nSELECT  SUM(COALESCE(m_visits,0))\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE $webFilter AND $newZeitraum\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND $newZeitraum),\r\na as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $appFilter AND $newZeitraum\r\n)\r\n\r\nSELECT  a.m_visits/(w.m_visits+a.m_visits)*100 as App, w.m_visits/(w.m_visits+a.m_visits)*100 as Web\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith w as (SELECT m_visits, date, m_page_loads\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE \r\n  ($webFilter\r\n  AND $newZeitraum \r\n  --AND sendungs_id = '$Sendung'\r\n  ) \r\n)\r\nSELECT  REPLACE(CAST(ROUND(SUM(m_page_loads)/SUM(m_visits),2) as string),'.',',') as Zeitraum\r\nFROM w \r\n--WHERE $Zeitraum\r\n\r\n"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith w as (\r\n  SELECT SUM(m_page_loads)/SUM(m_visits) as m_visits, 1 as id\r\n  FROM (\r\n      SELECT m_visits, date, m_page_loads\r\n      FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n      WHERE \r\n        $webFilter\r\n        --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n        --AND sendungs_id = '$Sendung'\r\n    )  \r\n  WHERE $newZeitraum),\r\na as (\r\n  SELECT SUM(m_page_loads)/SUM(m_visits) as m_visits, 1 as id\r\n  FROM(\r\n    SELECT m_visits, date, m_page_loads\r\n      FROM `ndr-code-bi-dashboard.Piano.total_visits`\r\n    WHERE ($appFilter)\r\n    --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  )\r\n  WHERE $newZeitraum  )\r\n\r\nSELECT  w.m_visits as Web, a.m_visits as App\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith now as (SELECT m_time_spent_per_visits as m_time_spent, m_visits, date--time(tmstp) as time\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE \r\n  ($webFilter \r\n  --AND sendungs_id = '$Sendung'\r\n  ) \r\n  --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n)\r\n--SELECT  CONCAT(REPLACE(CAST(ROUND(SUM(m_time_spent) / SUM(m_visits)/1000,1) AS STRING),'.',','), ' Sek.') as Zeitraum\r\nSELECT CONCAT(REPLACE(CAST(ROUND(SUM(m_visits * m_time_spent/1000) / SUM(m_visits),1) AS STRING),'.',','), ' Sek.') as Zeitraum\r\nFROM now \r\n--WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n WHERE $newZeitraum"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  with now as (SELECT m_time_spent_per_visits as m_time_spent, m_visits, date--time(tmstp) as time\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE \r\n  ($webFilter   ) \r\n)\r\nSELECT ROUND(SUM(m_visits * m_time_spent/1000) / SUM(m_visits),1) as Zeitraum, 2 as id\r\nFROM now \r\n WHERE $newZeitraum\r\n),\r\na as(\r\n    --Select 'N/A' as Zeitraum\r\n\r\n  with now as (SELECT m_time_spent_per_visits, m_visits, date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($appFilter\r\n    --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    ) \r\n  )\r\n  SELECT  (SUM(m_time_spent_per_visits/1000 * m_visits))/SUM(m_visits) as Zeitraum, 2 as id\r\n  FROM now \r\n  --WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n   WHERE $newZeitraum\r\n)\r\nSELECT  w.Zeitraum as Web, a.Zeitraum as App\r\nFROM w \r\nJOIN a ON w.id = a.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  sum(m_av_playbacks) as Zeitraum\r\nFROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n--WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\nWHERE $newZeitraum AND $avwebFilter"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as \r\n(\r\n  SELECT \r\n    sum(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n  WHERE $newZeitraum AND $avwebFilter\r\n),\r\napp as (\r\n  SELECT \r\n    SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n  WHERE ${av_condition} AND $newZeitraum \r\n )\r\n  SELECT SUM(web.Zeitraum)/(SUM(app.Zeitraum) + SUM(web.Zeitraum)) as Web, SUM(app.Zeitraum)/(SUM(app.Zeitraum) + SUM(web.Zeitraum)) as App\r\n  FROM web\r\n  JOIN app\r\n  ON web.id = app.id\r\n\r\n"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\n\r\nSELECT  SUM(m_visits) as summe\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits${table_fever_curve}` \r\nWHERE $appFilter AND $newZeitraum\r\nGROUP BY site_level2, tmstp\r\nORDER BY summe DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with app as (SELECT m_visits, date, m_page_loads\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE \r\n  ( $appFilter\r\n  --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n) \r\n)\r\nSELECT REPLACE(CAST(ROUND(SUM(m_page_loads)/SUM(m_visits),2) as string),'.',',') as Zeitraum\r\nFROM app \r\nWHERE $newZeitraum \r\n--WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--Select 'N/A' as Zeitraum\r\n\r\nwith now as (\r\n  SELECT m_time_spent_per_visits, m_visits, date--time(tmstp) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($appFilter\r\n    --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    ) \r\n)\r\nSELECT  CONCAT(REPLACE(CAST(ROUND(SUM(m_time_spent_per_visits/1000 * m_visits) / SUM(m_visits),1) AS STRING),'.',','), ' Sek.') as Zeitraum\r\nFROM now \r\n--WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n WHERE $newZeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT SUM(m_av_playbacks) as Zeitraum\r\nFROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\nWHERE ${av_condition} AND $newZeitraum "
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 } },
  { "title": "Top Artikel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Top Artikel",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT   \r\n    ANY_VALUE(publishing_date) as publishing_date,\r\n    ANY_VALUE(content_id_sophora) as content_id_sophora, \r\n    ANY_VALUE(content_titel) as content_titel,\r\n    ANY_VALUE(url) as url,\r\n    IFNULL(SUM(m_visits),0) as m_visits,\r\n    IFNULL(SUM(m_page_loads),0) as m_page_loads, \r\n    uuid--,DATETIME(tmstp) as date\r\n  from `ndr-code-bi-dashboard.Piano.articles${articleTable}` \r\n  WHERE \r\n    $listwebFilter \r\n    --AND \"$page_chapter1\" IN UNNEST(page_chapter1_tags) \r\n    --AND \"$page_chapter2\" IN UNNEST(page_chapter2_tags)\r\n    --AND \"Alle Sendungs-ID\" IN UNNEST(sendungs_id_tags)\r\n    AND $newZeitraum \r\n    AND objekt_typ NOT LIKE 'indexPage'\r\n  GROUP BY uuid\r\n\r\n),\r\napp as (\r\n  SELECT \r\n    IFNULL(SUM(m_visits),0) as m_visits, \r\n    ANY_VALUE(publishing_date) as publishing_date,\r\n    ANY_VALUE(content_id_sophora) as content_id_sophora, \r\n    ANY_VALUE(content_titel) as content_titel,\r\n    ANY_VALUE(url) as url,\r\n    IFNULL(SUM(m_page_loads),0) as m_page_loads, \r\n    ANY_VALUE(page_chapter1) as Kapitel,\r\n    uuid\r\n  from `ndr-code-bi-dashboard.Piano.articles${articleTable}` \r\n  WHERE CONTAINS_SUBSTR(site_level2, '$app_name')\r\n  AND $newZeitraum\r\n  AND content_id_sophora NOT LIKE '%index%'\r\n  AND content_id_sophora NOT LIKE '%N/A%'\r\n  GROUP BY uuid\r\n  ),\r\nsum_raw as (\r\n  SELECT \r\n  IFNULL(web.publishing_date, app.publishing_date) as publishing_date,\r\n  IFNULL(web.content_titel, app.content_titel) as content_titel, \r\n  IFNULL(web.content_id_sophora,app.content_id_sophora) as content_id_sophora, \r\n  IFNULL(web.url, app.url) as url,\r\n  web.uuid as uuid,\r\n  IFNULL(web.m_visits,0) as visits_web, \r\n  IFNULL(app.m_visits,0) as visits_app, \r\n  IFNULL(web.m_page_loads,0) as page_web, \r\n  IFNULL(app.m_page_loads,0) as page_app, \r\n  Kapitel\r\n  FROM web\r\n  FULL JOIN app \r\n  ON web.uuid = app.uuid\r\n)\r\nSELECT \r\n  IF(LENGTH(MAX(publishing_date)) > 4,FORMAT_DATETIME('%d.%m.%Y | %R Uhr', DATETIME(MAX(publishing_date))),MAX(publishing_date)) as Datum, \r\n  content_titel as Artikel, \r\n  content_id_sophora as Sophora, \r\n  ANY_VALUE(url HAVING MAX LENGTH(url)) as url, \r\n  SUM(visits_web) + SUM(visits_app) as Visits, \r\n  SUM(visits_web) as visits_web, \r\n  SUM(visits_app) as visits_app, \r\n  SUM(page_web) + SUM(page_app) as page_views, \r\n  SUM(page_web) as page_web, \r\n  SUM(page_app) as page_app, \r\n  ANY_VALUE(Kapitel) as Kapitel\r\nFROM sum_raw\r\nGROUP BY content_titel,  content_id_sophora, uuid--, publishing_date,\r\nORDER BY Visits DESC\r\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 } },
  { "title": "AV KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 55 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 10, "x": 4, "y": 55 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 10, "x": 14, "y": 55 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 58 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with data_web as \r\n(\r\n  SELECT sum(IFNULL(m_av_playbacks,0)) as m_av_playbacks, datetime(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE \r\n    $avwebFilter\r\n    AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n    --AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  GROUP BY time \r\n),\r\nweb as (\r\n  SELECT \r\n  sum(IFNULL(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM data_web\r\n  WHERE $Zeitraum \r\n),\r\ndata_app as (\r\n  SELECT m_av_playbacks, DATETIME(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE ${av_condition}\r\n    AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n),\r\napp as (\r\n  SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $Zeitraum \r\n)\r\n\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with data_web as \r\n(\r\n  SELECT sum(m_av_playbacks) as m_av_playbacks, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE \r\n    $avwebFilter\r\n    AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  GROUP BY time \r\n),\r\nweb as (\r\n  SELECT \r\n  sum(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_web\r\n  WHERE $Zeitraum\r\n),\r\ndata_app as (\r\n  SELECT m_av_playbacks, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE ${av_condition}\r\n  AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n),\r\napp as (\r\n  SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $Zeitraum\r\n)\r\nSELECT SUM(web.Zeitraum) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with data_web as \r\n(\r\n  SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE \r\n    $avwebFilter\r\n    AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n  GROUP BY time \r\n),\r\nweb as (\r\n  SELECT \r\n  sum(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_web\r\n  WHERE $Zeitraum \r\n),\r\ndata_app as (\r\n  SELECT m_av_playbacks, DATETIME(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE ${av_condition}\r\n    AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n),\r\napp as (\r\n  SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $Zeitraum \r\n)\r\n\r\nSELECT SUM(web.Zeitraum) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with data_web as \r\n(\r\n  SELECT sum(m_av_playbacks) as m_av_playbacks, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE \r\n    $avwebFilter\r\n    AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  GROUP BY time \r\n),\r\nweb as (\r\n  SELECT \r\n  sum(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_web\r\n  WHERE $Zeitraum\r\n),\r\ndata_app as (\r\n  SELECT m_av_playbacks, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE ${av_condition}\r\n  AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n),\r\napp as (\r\n  SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $Zeitraum\r\n)\r\nSELECT SUM(web.Zeitraum) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with old as (\r\n  with data_web as \r\n  (\r\n    SELECT sum(m_av_playbacks) as m_av_playbacks, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as time\r\n    FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n    WHERE \r\n      $avwebFilter\r\n      AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n      AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    GROUP BY time \r\n  ),\r\n  web as (\r\n    SELECT \r\n    sum(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_web\r\n    WHERE $Zeitraum\r\n  ),\r\n  data_app as (\r\n    SELECT m_av_playbacks, DATE_ADD(datetime(date), INTERVAL $Tage $Einheit) as time\r\n    FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n    WHERE ${av_condition}\r\n    AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  ),\r\n  app as (\r\n    SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_app \r\n    WHERE $Zeitraum\r\n  )\r\n  SELECT SUM(web.Zeitraum) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum, 2 as id\r\n  FROM web\r\n  JOIN app\r\n  ON web.id = app.id\r\n\r\n),\r\nnew_data as (\r\n  with data_web as \r\n(\r\n  SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE \r\n    $avwebFilter\r\n    AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  GROUP BY time \r\n),\r\nweb as (\r\n  SELECT \r\n  sum(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_web\r\n  WHERE $Zeitraum \r\n),\r\ndata_app as (\r\n  SELECT m_av_playbacks, DATETIME(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n  WHERE ${av_condition}\r\n    AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n),\r\napp as (\r\n  SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $Zeitraum \r\n)\r\n\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum, 2 as id\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n\r\n)\r\nSELECT CONCAT(IF(ROUND(((new_data.Zeitraum / old.Zeitraum)-1)*100,2)>0,'+',''),REPLACE(CAST(ROUND(((new_data.Zeitraum / old.Zeitraum)-1)*100,2) as string), '.', ','), ' %') as Zeitraum\r\nFROM old\r\nJOIN new_data\r\nON old.id = new_data.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with old as (\r\n  with data_web as \r\n  (\r\n    SELECT sum(m_av_playbacks) as m_av_playbacks, DATETIME(DATE_ADD(date(date), INTERVAL $Tage $Einheit)) as time, \r\n    FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n    WHERE \r\n      $avwebFilter\r\n      AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n      AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    GROUP BY time \r\n  ),\r\n  web as (\r\n    SELECT \r\n    sum(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_web\r\n    WHERE $Zeitraum\r\n  ),\r\n  data_app as (\r\n    SELECT m_av_playbacks, DATETIME(DATE_ADD(date(date), INTERVAL $Tage $Einheit)) as time, \r\n    FROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\n    WHERE ${av_condition}\r\n    AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  ),\r\n  app as (\r\n    SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_app \r\n    WHERE $Zeitraum \r\n  )\r\n  SELECT SUM(web.Zeitraum) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum, 2 as id\r\n  FROM web\r\n  JOIN app\r\n  ON web.id = app.id\r\n),\r\nnew_data as (\r\n  with data_web as (\r\n    SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(date) as time\r\n    FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n    WHERE \r\n      $avwebFilter\r\n      AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n      AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    GROUP BY time \r\n    ),\r\n  web as (\r\n    SELECT sum(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_web\r\n    WHERE $Zeitraum \r\n  ),\r\n  data_app as (\r\n    SELECT m_av_playbacks, DATETIME(date) as time\r\n    FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n    WHERE ${av_condition}\r\n      AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n      AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  ),\r\n  app as (\r\n    SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_app \r\n    WHERE $Zeitraum \r\n  )\r\n  SELECT SUM(web.Zeitraum) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum, 2 as id\r\n  FROM web\r\n  JOIN app\r\n  ON web.id = app.id\r\n)\r\nSELECT CONCAT(IF(ROUND(((new_data.Zeitraum / old.Zeitraum)-1)*100,2)>0,'+',''),REPLACE(CAST(ROUND(((new_data.Zeitraum / old.Zeitraum)-1)*100,2) as string), '.', ','), ' %') as Zeitraum\r\nFROM old\r\nJOIN new_data\r\nON old.id = new_data.id"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 66 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with data as \r\n(SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(date) as time\r\nFROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n  ($avwebFilter\r\n  AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  )\r\n  GROUP BY time \r\n)\r\nSELECT \r\n  IFNULL(sum(m_av_playbacks),0) as Zeitraum\r\nFROM data \r\n--WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\nWHERE $Zeitraum"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "  with data_web as \r\n  (SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE \r\n    ($avwebFilter)\r\n    AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    GROUP BY time \r\n  ),\r\n  web as (\r\n    SELECT \r\n    sum(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_web\r\n    WHERE $Zeitraum),\r\n  data_app as (SELECT m_av_playbacks, DATETIME(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE ${av_condition}\r\n  AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  ),\r\n  app as (SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $Zeitraum)\r\n  SELECT SUM(web.Zeitraum) as Web, SUM(app.Zeitraum) as App\r\n  FROM web\r\n  JOIN app\r\n  ON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with data as \r\n(SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(date) as time\r\nFROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n  ($avwebFilter\r\n  AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  )\r\n  GROUP BY time \r\n)\r\nSELECT \r\n  sum(m_av_playbacks) as Zeitraum\r\nFROM data \r\n--WHERE time BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\nWHERE $Zeitraum"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "  with data_web as \r\n  (SELECT sum(m_av_playbacks) as m_av_playbacks, datetime(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE \r\n    ($avwebFilter)\r\n    AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n    GROUP BY time \r\n  ),\r\n  web as (\r\n    SELECT \r\n    sum(m_av_playbacks) as Zeitraum, 1 as id\r\n    FROM data_web\r\n    WHERE $Zeitraum),\r\n  data_app as (SELECT m_av_playbacks, DATETIME(date) as time\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\n  WHERE ${av_condition}\r\n  AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n  ),\r\n  app as (SELECT SUM(m_av_playbacks) as Zeitraum, 1 as id\r\n  FROM data_app \r\n  WHERE $Zeitraum)\r\n  SELECT SUM(web.Zeitraum) as Web, SUM(app.Zeitraum) as App\r\n  FROM web\r\n  JOIN app\r\n  ON web.id = app.id\r\n\r\n"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 69 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with app as (SELECT m_av_playbacks, DATETIME(date) as time\r\nFROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE ${av_condition}\r\n  AND (av_content_type LIKE 'video' OR av_content_type LIKE 'Video')\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n)\r\nSELECT SUM(m_av_playbacks) as Zeitraum\r\nFROM app \r\nWHERE $Zeitraum "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with app as (SELECT m_av_playbacks, DATETIME(date) as time\r\nFROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE ${av_condition}\r\n  AND (av_content_type LIKE 'audio' OR av_content_type LIKE 'Audio')\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH) AND CURRENT_DATE()\r\n)\r\nSELECT SUM(m_av_playbacks) as Zeitraum\r\nFROM app \r\nWHERE $Zeitraum "
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 72 } },
  { "title": "Top AV on Demand", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Top AV on Demand",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web_raw as (\r\n  SELECT\r\n    --DATETIME(tmstp) as time,  \r\n    MAX(bi_av_publication_date) as bi_av_publication_date,\r\n    SUM(m_av_playbacks) as m_av_playbacks,\r\n    MAX(av_content_duration) as av_content_duration,\r\n    bi_av_content_id,\r\n    ANY_VALUE(bi_av_content HAVING MAX bi_av_publication_date) as bi_av_content,\r\n    ANY_VALUE(bi_av_url HAVING MAX bi_av_publication_date) as url,\r\n    ANY_VALUE(av_content_type) as av_content_type\r\n  from\r\n    `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE\r\n    $avwebFilter\r\n    AND $avzeitraumListe\r\n    AND bi_av_broadcasting_type LIKE 'ondemand'\r\n    AND bi_av_content_id NOT LIKE '%index%'\r\n  GROUP By\r\n    --bi_av_content,\r\n    bi_av_content_id\r\n),\r\nweb as (\r\n  select\r\n    bi_av_publication_date,\r\n    m_av_playbacks,\r\n    bi_av_content_id,\r\n    bi_av_content as content_titel,\r\n    url,\r\n    av_content_duration,\r\n    av_content_type\r\n  FROM\r\n    web_raw\r\n),\r\napp_raw as (\r\n  SELECT\r\n    MAX(av_content_duration) as av_content_duration,\r\n    bi_av_content_id,\r\n    SUM(m_av_playbacks) as m_av_playbacks,\r\n    bi_av_content,\r\n    ANY_VALUE(bi_av_url) as url,\r\n    ANY_VALUE(av_content_type) as av_content_type,\r\n    MAX(bi_av_publication_date) as bi_av_publication_date\r\n  from\r\n    `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE\r\n    ${av_condition}\r\n    AND bi_av_content_id NOT LIKE '%index%'\r\n    AND bi_av_broadcasting_type LIKE 'ondemand'\r\n    AND $avzeitraumListe\r\n  GROUP BY\r\n    bi_av_content,\r\n    bi_av_content_id\r\n  ORDER BY\r\n    m_av_playbacks DESC\r\n),\r\napp as (\r\n  SELECT\r\n    m_av_playbacks,\r\n    bi_av_content_id,\r\n    av_content_duration,\r\n    bi_av_content,\r\n    url,\r\n    av_content_type,\r\n    bi_av_publication_date\r\n  FROM\r\n    app_raw\r\n),\r\nsum_raw as (\r\n  SELECT\r\n    IFNULL(\r\n      web.bi_av_publication_date,\r\n      app.bi_av_publication_date\r\n    ) as bi_av_publication_date,\r\n    IFNULL(content_titel, app.bi_av_content) as content_titel,\r\n    IFNULL(web.av_content_duration, app.av_content_duration) as av_content_duration,\r\n    IFNULL(web.bi_av_content_id, app.bi_av_content_id) as bi_av_content_id,\r\n    IFNULL(web.url, app.url) as url,\r\n    IFNULL(web.m_av_playbacks, 0) as playbacks_web,\r\n    IFNULL(app.m_av_playbacks, 0) as playbacks_app,\r\n    IFNULL(web.av_content_type, app.av_content_type) as av_content_type\r\n  FROM\r\n    web FULL\r\n    JOIN app ON web.bi_av_content_id = app.bi_av_content_id\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  (\r\n    SELECT\r\n      IF(\r\n        LENGTH(MAX(bi_av_publication_date)) > 4,\r\n        FORMAT_DATETIME(\r\n          '%d.%m.%Y | %R Uhr',\r\n          DATETIME(MAX(bi_av_publication_date))\r\n        ),\r\n        MAX(bi_av_publication_date)\r\n      ) as Datum,\r\n      content_titel as Titel,\r\n      bi_av_content_id as Sophora,\r\n      url,\r\n      SUM(\r\n        IFNULL(playbacks_web, 0) + IFNULL(playbacks_app, 0)\r\n      ) as playbacks,\r\n      SUM(IFNULL(playbacks_web, 0)) as playbacks_web,\r\n      SUM(IFNULL(playbacks_app, 0)) as playbacks_app,\r\n      IFNULL(av_content_duration, 0) / 1000 as av_content_duration,\r\n      IFNULL(av_content_type, 'N/A') as av_content_type\r\n    FROM\r\n      sum_raw\r\n    GROUP BY\r\n      bi_av_content_id,\r\n      content_titel,\r\n      bi_av_publication_date,\r\n      url,\r\n      av_content_duration,\r\n      av_content_type\r\n  )\r\nWHERE\r\n  playbacks > 0\r\nORDER BY\r\n  playbacks DESC\r\nLIMIT\r\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 88 } },
  { "title": "Top AV Livestream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Top AV Livestream",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web_raw as (\r\n  SELECT\r\n    DATETIME(date) as time,\r\n    bi_av_publication_date,\r\n    m_av_playbacks,\r\n    av_content_duration,\r\n    bi_av_content_id,\r\n    bi_av_content,\r\n    bi_av_url as url,\r\n    av_content_type\r\n  from\r\n    `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE\r\n    $avwebFilter\r\n    AND (\r\n      bi_av_broadcasting_type LIKE 'live'\r\n      OR bi_av_broadcasting_type LIKE 'Live'\r\n    )\r\n    AND $avzeitraumListe\r\n),\r\nweb as (\r\n  select\r\n    MAX(bi_av_publication_date) as bi_av_publication_date,\r\n    SUM(m_av_playbacks) as m_av_playbacks,\r\n    bi_av_content_id,\r\n    bi_av_content as content_titel,\r\n    ANY_VALUE(url) as url,\r\n    ANY_VALUE(av_content_duration) as av_content_duration,\r\n    ANY_VALUE(av_content_type) as av_content_type,\r\n  FROM\r\n    web_raw\r\n  GROUP BY\r\n    bi_av_content_id,\r\n    bi_av_content\r\n),\r\napp_raw as (\r\n  SELECT\r\n    DATETIME(date) as time,\r\n    bi_av_publication_date,\r\n    av_content_duration,\r\n    bi_av_content_id,\r\n    IFNULL(m_av_playbacks, 0) as m_av_playbacks,\r\n    bi_av_content,\r\n    bi_av_url as url,\r\n    av_content_type\r\n  from\r\n    `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE\r\n    ${av_condition}\r\n    AND (\r\n      bi_av_broadcasting_type LIKE 'live'\r\n      OR bi_av_broadcasting_type LIKE 'Live'\r\n    )\r\n    AND bi_av_content_id NOT LIKE '%index%'\r\n    AND $avzeitraumListe\r\n),\r\napp as (\r\n  SELECT\r\n    SUM(IFNULL(m_av_playbacks, 0)) as m_av_playbacks,\r\n    bi_av_content_id,\r\n    bi_av_content,\r\n    ANY_VALUE(bi_av_publication_date) as bi_av_publication_date,\r\n    ANY_VALUE(url) as url,\r\n    MAX(av_content_duration) as av_content_duration,\r\n    ANY_VALUE(av_content_type) as av_content_type\r\n  FROM\r\n    app_raw\r\n  GROUP BY\r\n    bi_av_content_id,\r\n    bi_av_content\r\n),\r\nsum_raw as (\r\n  SELECT\r\n    IFNULL(\r\n      web.bi_av_publication_date,\r\n      app.bi_av_publication_date\r\n    ) as bi_av_publication_date,\r\n    IFNULL(web.content_titel, app.bi_av_content) as content_titel,\r\n    IFNULL(web.av_content_duration, app.av_content_duration) as av_content_duration,\r\n    IFNULL(web.bi_av_content_id, app.bi_av_content_id) as bi_av_content_id,\r\n    IFNULL(web.url, app.url) as url,\r\n    IFNULL(web.m_av_playbacks, 0) as playbacks_web,\r\n    IFNULL(app.m_av_playbacks, 0) as playbacks_app,\r\n    IFNULL(web.av_content_type, app.av_content_type) as av_content_type\r\n  FROM\r\n    web FULL\r\n    JOIN app ON web.bi_av_content_id = app.bi_av_content_id\r\n)\r\nSELECT\r\n  *\r\nFROM\r\n  (\r\n    SELECT\r\n      IF(\r\n        LENGTH(bi_av_publication_date) > 3,\r\n        FORMAT_DATETIME(\r\n          '%d.%m.%Y | %R Uhr',\r\n          DATETIME(bi_av_publication_date)\r\n        ),\r\n        bi_av_publication_date\r\n      ) as Datum,\r\n      content_titel as Titel,\r\n      bi_av_content_id as Sophora,\r\n      url,\r\n      SUM(IFNULL(playbacks_web, 0)) + SUM(IFNULL(playbacks_app, 0)) as playbacks,\r\n      SUM(IFNULL(playbacks_web, 0)) as playbacks_web,\r\n      SUM(IFNULL(playbacks_app, 0)) as playbacks_app,\r\n      --av_content_duration/1000 as av_content_duration,\r\n      av_content_type\r\n    FROM\r\n      sum_raw\r\n    GROUP BY\r\n      bi_av_content_id,\r\n      content_titel,\r\n      bi_av_publication_date,\r\n      url,\r\n      av_content_duration,\r\n      av_content_type\r\n  )\r\nWHERE\r\n  playbacks > 0\r\nORDER BY\r\n  playbacks DESC\r\nLIMIT\r\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 104 } },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Distribution nach Gerätetyp - $Zeitraum",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 14, "x": 5, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with raw as (\r\n  SELECT  device_type, tmstp as time\r\n  FROM `ndr-code-bi-dashboard.Piano.distro` \r\n  WHERE ($webFilter OR CONTAINS_SUBSTR(site_level2, '$app_name'))\r\n  AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY) AND CURRENT_DATE()\r\n),\r\nfiltered as (\r\n  SELECT device_type, COUNT(device_type) as number, ROW_NUMBER() OVER (ORDER BY COUNT(device_type) DESC) as RNB\r\n  FROM raw\r\n  WHERE $Zeitraum\r\n  GROUP BY device_type \r\n  ORDER BY number DESC\r\n)\r\nSELECT IF (RNB <= 15, device_type, 'Sonstige') as device_type, SUM(number) as number\r\nFROM filtered\r\nGROUP BY device_type\r\nORDER BY number DESC"
    }
   ]
  }
 ]
}