{
 "title": "Podcast_Testing_MDR+NDR",
 "description": "Mapping included",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "label": "LRA:",
    "query": {}
   },
   {
    "name": "datenstand",
    "query": {}
   },
   {
    "name": "Podcast_title",
    "query": {}
   },
   {
    "name": "AllePodcastsCondition",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "Bereich",
    "label": "Bereich:",
    "query": {}
   },
   {
    "name": "Podcast",
    "label": "Podcast:",
    "query": {}
   },
   {
    "name": "Episode",
    "label": "Episode:",
    "query": {}
   },
   { "name": "filled_size_big", "query": "10" },
   { "name": "filled_size", "query": "20" },
   {
    "name": "filled_size_headline",
    "query": {}
   },
   {
    "name": "filled_size_headline_small",
    "query": {}
   },
   {
    "name": "broadcast_id_branding",
    "query": {}
   },
   {
    "name": "Image",
    "query": {}
   },
   {
    "name": "type",
    "query": {}
   },
   {
    "name": "NDR_default_image",
    "query": {}
   },
   {
    "name": "lastUpdate",
    "query": {}
   },
   {
    "name": "mapping_dataset",
    "query": {}
   },
   {
    "name": "MDR_default_image",
    "query": {}
   },
   {
    "name": "AllePodcasts",
    "label": "Podcastsuche:",
    "query": {}
   },
   {
    "name": "number_of_days",
    "query": {}
   },
   {
    "name": "dataset_suffix",
    "query": {}
   },
   {
    "name": "episode_dataset",
    "query": {}
   },
   {
    "name": "platform_dataset",
    "query": {}
   },
   {
    "name": "profiles_dataset",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Anleitung und Hinweise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Anleitung zur Podcast-Suche\n\n## Es gibt zwei Möglichkeiten, um nach einem Podcast zu suchen:\n\n### Option 1:\nWählen Sie zuerst den gewünschten Bereich über das Dropdown-Menü \"Bereich\" aus. Anschließend wählen Sie über das dazugehörige Dropdown-Menü \"Podcast\" den gewünschten Podcast aus. Soll diese Option verwendet werden, muss der Wert im Dropdown-Menü \"Podcastsuche\" auf \"None\" gesetzt werden.\n\n### Option 2:\nVerwenden Sie das Dropdown-Menü \"Podcastsuche\". In diesem Menü finden Sie alle von uns geführten Podcasts. Soll diese Option nicht verwendet werden, muss der Wert auf \"None\" gesetzt werden.\n"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"160\" src=\"$Image\n\" />\n\n<!-- src=${Image} />"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('$Podcast_title'))), '$Podcast_title'), \nFROM(\nSELECT '$Podcast_title' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Quellen: Apps'),0)), 'Quellen: Apps')\nFROM(\nSELECT 'Quellen: Apps' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END\n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \nFROM $platform_dataset AS podcast_platform\nINNER JOIN broadcastids ON podcast_platform.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "*Basis für den Durchschnitt pro Episode sind die im Analysezeitraum neu veröffentlichten Folgen",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT\n  SAFE_DIVIDE(SUM(m_zugriffe_1),COUNT(DISTINCT headline)) as summe,\nFROM $episode_dataset\nWHERE\nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END\nAND\nCASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE  broadcast_id = \"$broadcast_id_branding\" END\nAND headline != \"All headlines\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND DATE(publication_date_1) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\"))"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset as podcast_platform\nINNER JOIN broadcastids ON podcast_platform.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT * FROM ${dataset}\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('ARD Audiothek')), 'ARD Audiothek')\nFROM(\nSELECT 'ARD Audiothek' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('Spotify')), 'Spotify')\nFROM(\nSELECT 'Spotify' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size - CHAR_LENGTH('Apple Podcasts'))), 'Apple Podcasts')\nFROM(\nSELECT 'Apple Podcasts' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE \n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset AS pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"ARD Audiothek\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"ARD Audiothek\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"Spotify\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"Spotify\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"Apple Podcasts\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"Apple Podcasts\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "options": {
    "content": "Letztes Update: <br> \r\n${lastUpdate}\r\n<br> <br> \r\nDatenstand: <br> \r\n01.01.2021 – ${datenstand}"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Bereich: $Bereich'),0)), 'Bereich: $Bereich')\nFROM(\nSELECT 'Bereich: $Bereich' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Ausgewählte Episoden'),0)), 'Ausgewählte Episoden')\nFROM(\nSELECT 'Ausgewählte Episoden' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": {
    "content": "Podcast-Daten werden erst mit 5 Tagen Verzögerung zur Verfügung gestellt. Die freie Datumsauswahl oder Verwendung fester Zeiträume (bspw. „letzte 7 Tage“ oder „letzte 30 Tage“) beziehen sich deswegen hier auf die letzten verfügbaren 7 bzw. 30 Tage."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT\n  SUM(m_zugriffe_1) AS summe\nFROM $episode_dataset\nWHERE\nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END\nAND headline != \"All headlines\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \n  SUM(m_zugriffe_1) AS summe \nFROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END \nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE  broadcast_id = \"$broadcast_id_branding\" END\nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(headline,\"'\",\"\") IN UNNEST(ARRAY_CONCAT(ARRAY[$Episode], ARRAY['None'])) END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT \n  SAFE_DIVIDE(SUM(m_zugriffe_1),COUNT(DISTINCT headline)) as summe \nFROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END \nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE  broadcast_id = \"$broadcast_id_branding\" END\nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(headline,\"'\",\"\") IN UNNEST(ARRAY_CONCAT(ARRAY[$Episode], ARRAY['None'])) END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\"))"
    }
   ]
  },
  {
   "title": "Zugriffe pro Tag für \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform,\n    date\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform, date),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform,\n  date\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform, date\n),\nard_data AS (\n  SELECT summe, date FROM \n  ${dataset}\n  WHERE platform = \"ARD Audiothek\"\n),\napple_data AS\n(\n    SELECT summe, date FROM \n  ${dataset}\n  WHERE platform = \"Apple Podcasts\"\n),\nspotify_data AS\n(\n  SELECT summe as summe, date FROM \n  ${dataset}\n  WHERE platform = \"Spotify\"\n),\nrest AS(\n  SELECT SUM(summe) as summe, date FROM \n  ${dataset}\n  WHERE platform != \"ARD Audiothek\" AND platform != \"Apple Podcasts\" AND platform != \"Spotify\"\n  GROUP BY date\n)\nSELECT\n  ${dataset}.date,\n  ard_data.summe as ard_summe, \n  apple_data.summe as apple_summe, \n  spotify_data.summe as spotify_summe,\n  rest.summe as rest_summe,\n  COALESCE(ard_data.summe,0) + COALESCE(apple_data.summe, 0) + COALESCE(spotify_data.summe,0) + COALESCE(rest.summe,0) as zugriffe,\n  \"${type}\" as type,\n  DATE_DIFF(DATE('${__to:date}', \"Europe/Berlin\"),DATE('${__from:date}', \"Europe/Berlin\"),DAY) + 1 as timeRange\nFROM ${dataset}\nLEFT JOIN ard_data ON ${dataset}.date = ard_data.date\nLEFT JOIN apple_data ON ${dataset}.date = apple_data.date\nLEFT JOIN spotify_data ON ${dataset}.date = spotify_data.date\nLEFT JOIN rest ON ${dataset}.date = rest.date\nGROUP BY ${dataset}.date, ard_data.summe, apple_data.summe, spotify_data.summe, rest.summe\nORDER by date ASC"
    }
   ]
  },
  {
   "title": "Top 3 Episoden von \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  headline,\n  SUM(zugriffe) as zugriffe,\nFROM (\n  SELECT\n    FIRST_VALUE(publication_date_1) OVER (PARTITION BY headline ORDER BY publication_date_1 DESC) AS publication_date_2,\n    REPLACE(podcast_title,'\"','') as podcast_title,\n      broadcast_id,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n    SUM(m_technische_nutzer) AS technische_nutzer,\n  FROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END\nAND CASE \"\"\"${Podcast}\"\"\"\nWHEN \"All titles\" THEN True\nELSE REPLACE(podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND  headline != \"All headlines\" \nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n  GROUP BY\n    publication_date_1,\n    podcast_title,\n    headline,\n      broadcast_id\n  ORDER BY\n    zugriffe DESC )\nGROUP BY\n  publication_date_2,\n  podcast_title,\n  headline, \n  broadcast_id\n\nORDER BY 2 DESC\nLIMIT 3"
    }
   ]
  },
  {
   "title": "Episoden",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  DATE(publication_date_2) as publication_date_2,\n  podcast_title,\n    broadcast_id,\n  headline,\n  SUM(zugriffe) as zugriffe,\n  ROUND(SUM(technische_nutzer)/$number_of_days) as technische_nutzer\n  --SUM(technische_nutzer)\nFROM (\n  SELECT\n    FIRST_VALUE(publication_date_1) OVER (PARTITION BY headline ORDER BY publication_date_1 DESC) AS publication_date_2,\n    REPLACE(podcast_title,'\"','') AS podcast_title,\n      broadcast_id,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n    SUM(m_technische_nutzer) AS technische_nutzer\n    --SUM(m_technische_nutzer) AS technische_nutzer,\n  FROM $episode_dataset\nWHERE CASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END\nAND  CASE \"$Podcast\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND CASE \"${Podcast:text}\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(headline,\"'\",\"\") IN UNNEST(ARRAY_CONCAT(ARRAY[$Episode], ARRAY['None'])) END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n  GROUP BY\n    publication_date_1,\n    podcast_title,\n    headline,\n      broadcast_id\n  ORDER BY\n    zugriffe DESC )\nGROUP BY\n  publication_date_2,\n  podcast_title,\n  headline, \n  broadcast_id\n\nORDER BY zugriffe DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Gesamt Zugriffe und Technische Nutzer für \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH \nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS vu,\n  SUM(m_technische_nutzer) AS tu,\n  date\nFROM Piano.NDR_podcast_show_daily_f_mapped\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by date)\nSELECT date, \nvu, \ntu,\n\"${type}\" as type,\nDATE_DIFF(DATE('${__to:date}', \"Europe/Berlin\"),DATE('${__from:date}', \"Europe/Berlin\"),DAY) + 1 as timeRange\nFROM not_all_titles_platforms\nORDER by date ASC"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"Podcast\", \"ARD Audiothek\", \"Spotifiy\", \"Apple Podcasts\", \"Zugriffe Gesamt\""
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id, podcast_title\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE \n    ELSE branding = \"$Bereich\" END \n    AND CASE \"\"\"$Podcast\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE CAST(broadcast_id[0] AS STRING) = \"$broadcast_id_branding\" END\n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(SELECT \npodcast_title as Title,\n1 as join_key,\nsum(m_zugriffe_1) as zugriffe,\nplatform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform, podcast_title),\ntechnische_nutzer_summe AS(\n  SELECT podcast_title as Title,\n  1 as join_key,\n  ROUND(sum(m_technische_nutzer)/$number_of_days) as technische_nutzer\n  FROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\n  WHEN \"Alle Bereiche\"\n  THEN TRUE \n  ELSE \nbranding = \"$Bereich\" END\nAND CASE \"\"\"$Podcast\"\"\"\nWHEN \"All titles\" THEN True\nELSE podcast_title = \"\"\"$Podcast\"\"\" END \nAND headline != \"All headlines\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY podcast_title),\nmain_data AS(\nSELECT Title, join_key, sum(zugriffe) as zugriffe\nFROM all_titles_platforms\nGROUP BY Title, join_key),\nard_data AS (\n  SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"ARD Audiothek\"\n),\napple_data AS\n(\n    SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"Apple Podcasts\"\n),\nspotify_data AS\n(\n  SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"Spotify\"\n)\nSELECT\n  main_data.Title, \n  main_data.zugriffe,\n  technische_nutzer_summe.technische_nutzer, \n  ard_data.zugriffe as ard_summe, \n  apple_data.zugriffe as apple_summe, \n  spotify_data.zugriffe as spotify_summe\nFROM main_data\nLEFT JOIN ard_data ON (main_data.join_key = ard_data.join_key AND main_data.Title = ard_data.Title)\nLEFT JOIN apple_data ON (main_data.join_key = apple_data.join_key AND main_data.Title = apple_data.Title)\nLEFT JOIN spotify_data ON (main_data.join_key = spotify_data.join_key AND main_data.Title = spotify_data.Title)\nLEFT JOIN technische_nutzer_summe on (main_data.join_key = technische_nutzer_summe.join_key AND main_data.Title = technische_nutzer_summe.Title)\nORDER BY main_data.zugriffe DESC"
    }
   ]
  },
  {
   "title": " Podcast",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id, podcast_title\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE \n    ELSE branding = \"$Bereich\" END \n    AND CASE \"\"\"$Podcast\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE CAST(broadcast_id[0] AS STRING) = \"$broadcast_id_branding\" END\n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(SELECT \npodcast_title as Title,\n1 as join_key,\nsum(m_zugriffe_1) as zugriffe,\nplatform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform, podcast_title),\ntechnische_nutzer_summe AS(\n  SELECT podcast_title as Title,\n  1 as join_key,\n  ROUND(sum(m_technische_nutzer)/$number_of_days) as technische_nutzer\n  FROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\n  WHEN \"Alle Bereiche\"\n  THEN TRUE \n  ELSE \nbranding = \"$Bereich\" END\nAND CASE \"\"\"$Podcast\"\"\"\nWHEN \"All titles\" THEN True\nELSE podcast_title = \"\"\"$Podcast\"\"\" END \nAND headline != \"All headlines\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY podcast_title),\nmain_data AS(\nSELECT Title, join_key, sum(zugriffe) as zugriffe\nFROM all_titles_platforms\nGROUP BY Title, join_key),\nard_data AS (\n  SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"ARD Audiothek\"\n),\napple_data AS\n(\n    SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"Apple Podcasts\"\n),\nspotify_data AS\n(\n  SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"Spotify\"\n)\nSELECT\n  main_data.Title, \n  main_data.zugriffe,\n  technische_nutzer_summe.technische_nutzer, \n  ard_data.zugriffe as ard_summe, \n  apple_data.zugriffe as apple_summe, \n  spotify_data.zugriffe as spotify_summe\nFROM main_data\nLEFT JOIN ard_data ON (main_data.join_key = ard_data.join_key AND main_data.Title = ard_data.Title)\nLEFT JOIN apple_data ON (main_data.join_key = apple_data.join_key AND main_data.Title = apple_data.Title)\nLEFT JOIN spotify_data ON (main_data.join_key = spotify_data.join_key AND main_data.Title = spotify_data.Title)\nLEFT JOIN technische_nutzer_summe on (main_data.join_key = technische_nutzer_summe.join_key AND main_data.Title = technische_nutzer_summe.Title)\nORDER BY main_data.zugriffe DESC"
    }
   ]
  },
  {
   "title": "Debugging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 69 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT \n  sum(m_zugriffe_1) AS summe, platform\nFROM `ndr-code-bi-dashboard.Piano.NDR_podcast_platform_daily_f`\nWHERE --profileId = $profileID \n--AND \n--branding = \"$Bereich\" \n broadcast_id = \"$broadcast_id_branding\"\n--AND platform = \"ARD Audiothek\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform"
      }
     ]
    },
    {
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 8, "w": 7, "x": 16, "y": 69 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT \n  sum(m_zugriffe_1) AS summe, platform\nFROM `ndr-code-bi-dashboard.Piano.NDR_podcast_platform_daily_f`\nWHERE --profileId = $profileID \n--AND \n--branding = \"$Bereich\" \n broadcast_id = \"$broadcast_id_branding\"\n--AND platform = \"ARD Audiothek\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform"
      }
     ]
    },
    {
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 8, "w": 7, "x": 11, "y": 77 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT \n  sum(m_zugriffe_1) AS summe, platform\nFROM `ndr-code-bi-dashboard.Piano.NDR_podcast_platform_daily_f`\nWHERE --profileId = $profileID \n--AND \n--branding = \"$Bereich\" \n broadcast_id = \"$broadcast_id_branding\"\n--AND platform = \"ARD Audiothek\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform"
      }
     ]
    },
    {
     "title": "NDR_podcast_platform_daily_f",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "dataset": "Piano",
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT \nbroadcast_id,\nuser_agent,\nplatform,\nm_zugriffe_1,\ndate, tmstp\nFROM `ndr-code-bi-dashboard.Piano.NDR_podcast_platform_daily_f`\n--WHERE branding = \"$Bereich\" \n--AND podcast_title = \"$Podcast\"\n--AND headline =\"$Episode\"\nWHERE date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\nORDER BY m_zugriffe_1 DESC\nLIMIT  100\n"
      }
     ]
    },
    {
     "title": "NDR_spotify_podcasts",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
     "targets": [
      {
       "dataset": "Piano",
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT * FROM `ndr-code-bi-dashboard.Piano.NDR_spotify_podcasts` LIMIT 50 "
      }
     ]
    },
    {
     "title": "NDR_spotify_podcasts_platform",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
     "targets": [
      {
       "dataset": "Piano",
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT * FROM `ndr-code-bi-dashboard.Piano.NDR_spotify_podcasts_platform` LIMIT 50 "
      }
     ]
    }
   ]
  }
 ]
}