{
 "title": "Piano App Kalender",
 "description": "Datepicker V 02/2024",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "filled_size", "query": "13" },
   {
    "name": "Vergleichszeitraumlabels",
    "query": {}
   },
   {
    "name": "Vergleichszeitraum",
    "query": {}
   },
   {
    "name": "LRA",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "App",
    "query": {}
   },
   {
    "name": "app_name",
    "query": {}
   },
   {
    "name": "table",
    "query": {}
   },
   {
    "name": "bq_comp_timeframe_end",
    "query": {}
   },
   {
    "name": "bq_comp_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_timeframe_end",
    "query": {}
   },
   {
    "name": "Zeitraumlabels",
    "query": {}
   },
   {
    "name": "dataset_zeitraum",
    "query": {}
   },
   {
    "name": "av_filter",
    "query": {}
   },
   {
    "name": "dataset_vergleichs_zeitraum",
    "query": {}
   },
   {
    "name": "zeitraum",
    "query": {}
   },
   {
    "name": "fromDay",
    "query": {}
   },
   {
    "name": "toDay",
    "query": {}
   },
   {
    "name": "hinweis",
    "query": {}
   },
   {
    "name": "HeuteDatum",
    "query": {}
   },
   {
    "name": "av_app_condition_video",
    "query": {}
   },
   {
    "name": "av_app_condition_audio",
    "query": {}
   },
   {
    "name": "av_pub_date",
    "query": {}
   },
   {
    "name": "av_content_id",
    "query": {}
   },
   {
    "name": "av_content",
    "query": {}
   },
   {
    "name": "av_on_demand_filter",
    "query": {}
   },
   {
    "name": "av_live_stream_filter",
    "query": {}
   },
   {
    "name": "src_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# 📊 Hinweis\n\n- Audio- und Video-Daten ohne Livestream-Nutzung, mit Ausnahme der Livestream-Tabelle."
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 1, "x": 9, "y": 0 },
   "options": {
    "content": "<img \n  src=\"${src_url}\" \n  alt=\"Tracking Pixel\" \n  width=\"1\" \n  height=\"1\" \n  style=\"display:none;\"\n/>"
   }
  },
  { "type": "text", "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 }, "options": { "content": " ${hinweis}" } },
  {
   "title": "Visits | Time Picker",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version\nSELECT\n  TIMESTAMP(date), sum(m_visits)\nFROM\n  Piano.total_visits\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $zeitraum\nGROUP BY date\nORDER BY date asc"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "options": { "content": " " } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Visits')), 'Visits')\r\nFROM(\r\nSELECT 'Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Page Views / Visit')), 'Page Views / Visit')\r\nFROM(\r\nSELECT 'Page Views / Visit' as pi_visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Time spent / Visit in s')), 'Time spent / Visit in s')\r\nFROM(\r\nSELECT 'Time spent / Visit in s' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SUM(COALESCE(m_visits,0)) AS summe\nFROM\n  Piano.total_visits\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $zeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\nFROM\n  Piano.total_visits\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $zeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\nFROM\n  Piano.total_visits\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $zeitraum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "options": { "content": " " } },
  { "title": "Top Inhalte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Top 100 App Artikel",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version\nSELECT\n  publishing_date as Datum,\n  content_titel as Artikel,\n  sum(m_visits) as Visits,\n  sum(m_page_loads) as page_views,\n  content_id_sophora,\n  '' as Type\nFROM\n  (\n    SELECT\n      --publishing_date,\n      FIRST_VALUE(publishing_date) OVER (PARTITION BY CASE uuid WHEN \"N/A\" THEN content_id_sophora ELSE uuid END ORDER BY publishing_date DESC) as publishing_date, \n      FIRST_VALUE(content_id_sophora) OVER (PARTITION BY CASE uuid WHEN \"N/A\" THEN content_id_sophora ELSE uuid END ORDER BY publishing_date DESC) as content_id_sophora, \n      m_visits,\n      m_page_loads,\n      FIRST_VALUE(content_titel) OVER ( PARTITION BY CASE uuid WHEN \"N/A\" THEN content_id_sophora ELSE uuid END ORDER BY publishing_date DESC) as content_titel\n    FROM\n      $table\n    WHERE\n      site_level2 = '${app_name}'\n      AND content_id_sophora NOT LIKE '%index%'\n      AND content_id_sophora NOT LIKE '%N/A%'\n      AND (\n        CASE \n            WHEN \"$LRA\" = 'NDR' THEN\n                content_titel NOT LIKE '%Video Livestream%'\n            AND content_titel NOT LIKE '%Startteaser%'\n            AND content_titel NOT LIKE '%startteaser%'\n            AND content_titel NOT LIKE '%-Anmelden%'\n            AND content_titel NOT LIKE '%_Start'\n            AND content_titel != 'Anmelden'\n            AND content_titel != 'Jetzt läuft'\n        ELSE\n          TRUE\n        END)\n      AND $zeitraum\n  )\nGROUP BY\n  content_id_sophora,\n  content_titel,\n  publishing_date\nORDER BY\n  3 DESC\nLIMIT\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "options": { "content": " " } },
  { "title": "AV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), '')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaben')), 'Wiedergaben')\r\nFROM(\r\nSELECT 'Wiedergaben' as Wiedergaben\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaberate in %')), 'Wiedergaberate in %')\r\nFROM(\r\nSELECT 'Wiedergaberate' as Wiedergaberate\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Video')), 'Video')\r\nFROM(\r\nSELECT 'Video' as Video\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton,m_av_playbacks,0)) as summe\r\nFROM \r\n  `Piano.av${dataset_zeitraum:raw}`\r\nWHERE \r\n$av_filter \r\nAND $zeitraum\r\nAND $av_app_condition_video "
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ohne Live-Videos",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  REPLACE(CONCAT(ROUND(SAFE_DIVIDE(100*SUM(m_av_playbacks * m_av_average_playback_completion_rate),SUM(m_av_playbacks)),1), \"%\"),\".\",\",\") as summe\r\nFROM \r\n`Piano.av${dataset_zeitraum:raw}`\r\nWHERE \r\n$av_filter \r\nAND $zeitraum\r\nAND $av_app_condition_video \r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), 'Audio')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks,0)) as summe\r\nFROM \r\n  `Piano.av${dataset_zeitraum:raw}`\r\nWHERE \r\n$av_filter \r\nAND $zeitraum\r\nAND $av_app_condition_audio "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  --AVG(m_av_average_playback_completion_rate) as summe\r\n  REPLACE(CONCAT(ROUND(SAFE_DIVIDE(100*SUM(m_av_playbacks * m_av_average_playback_completion_rate),SUM(m_av_playbacks)),1), \"%\"),\".\",\",\") as summe\r\nFROM \r\n`Piano.av${dataset_zeitraum:raw}`\r\nWHERE \r\n$av_filter \r\nAND $zeitraum\r\nAND $av_app_condition_audio "
    }
   ]
  },
  {
   "title": "Top 100 App Audios & Videos on Demand",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version \r\n\r\nSELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nCONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nCASE \"$LRA\"\r\nWHEN \"NDR\" THEN NULL\r\nELSE 100*(SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks)) END AS wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE($av_pub_date) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_publication_date, \r\nCOALESCE(m_playbutton,m_av_playbacks) as m_av_playbacks,\r\nCAST(av_content_duration/1000 AS INT) as av_content_duration,\r\nm_av_average_playback_completion_rate,\r\nCOALESCE(content_typ,av_content_type) as av_content_type,\r\n$av_content_id as bi_av_content_id,\r\nCOALESCE(objekt_typ,bi_av_broadcasting_type) as bi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE($av_content) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_content, \r\nFROM \r\n`Piano.av${dataset_zeitraum:raw}`\r\nWHERE $av_filter \r\nAND $av_content_id  NOT LIKE '%index%'\r\nAND COALESCE(objekt_typ,bi_av_broadcasting_type) IN $av_on_demand_filter \r\nAND $zeitraum)\r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,av_content_duration,av_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  {
   "title": "Top 100 App Audios & Videos Livestreams",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE($av_pub_date) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_publication_date, \r\nCOALESCE(m_playbutton,m_av_playbacks) as m_av_playbacks,\r\nCOALESCE(content_typ,av_content_type) as av_content_type,\r\n$av_content_id as bi_av_content_id,\r\nCOALESCE(objekt_typ,bi_av_broadcasting_type) as bi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE($av_content) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_content, \r\nFROM \r\n`Piano.av${dataset_zeitraum:raw}`\r\nWHERE $av_filter \r\nAND $av_content_id  NOT LIKE '%index%'\r\nAND COALESCE(objekt_typ,bi_av_broadcasting_type) IN $av_live_stream_filter \r\nAND $zeitraum)\r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "App | Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version\nSELECT \n  SUM(m_visits), os_group \nFROM \n  Piano.distro_joined_daily\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $zeitraum\n  AND device_type NOT LIKE '%N/A%'\nGROUP BY os_group\nORDER BY 1 DESC\n"
    }
   ]
  },
  {
   "title": "App | Devices",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\ndevice_type,\nSUM(m_visits) as visits\nFROM\nPiano.distro_joined_daily\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $zeitraum\n  AND device_type NOT LIKE '%N/A%'\nGROUP BY device_type \nORDER BY visits DESC \nLIMIT 10"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 }, "options": { "content": " " } }
 ]
}