{
 "title": "TikTok Monatsbericht mit KiKa",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Monat",
    "query": {}
   },
   {
    "name": "month_as_number",
    "query": {}
   },
   {
    "name": "Jahr",
    "query": {}
   },
   {
    "name": "datenstand",
    "query": {}
   },
   {
    "name": "last_month",
    "query": {}
   },
   {
    "name": "year_from_last_month",
    "query": {}
   },
   {
    "name": "month_from_last_year",
    "query": {}
   },
   {
    "name": "last_year",
    "query": {}
   },
   {
    "name": "Monat_abkuerzung",
    "query": {}
   },
   {
    "name": "Vorjahresmonat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastMonat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastJahr",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": {}
   },
   {
    "name": "Stichtag",
    "query": {}
   },
   {
    "name": "top_videos_except",
    "query": {}
   },
   {
    "name": "LRA_profiles",
    "query": {}
   },
   {
    "name": "veraenderung_zum_vormonat_title",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# 📊 Hinweise\n\n- Ab August 2024 liegen uns gespeicherte Daten für die neuen TikTok-Metriken und -Datensichtweisen vor.\nFür deep und deutlich konnten diese Daten erst ab November 2024 gesichert werden. Für die Monate davor werden für deep und deutlich nur profilbezogene Daten ausgewiesen.\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(DISTINCT profile) \nFROM Quintly.profiles\nWHERE LRA = '$LRA'\nAND tiktokID != 0\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "Letzter Datenstand: </br>\n${datenstand}\n\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [
         { "name": "total_video_10s_views", "type": "functionParameter" }
        ],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "facebookInsightsOwnVideos"
    }
   ]
  },
  { "title": "Entwicklung: Videostarts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Summe Videostarts $LRA Profile",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE profiles STRING;\r\nSET profiles = (\"$LRA_profiles\");\r\nEXECUTE IMMEDIATE format(\"\"\"\r\nSELECT * FROM(\r\nSELECT \r\nDATE(jahr,monat,1) as month_year, \r\nREPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss'), '?', '') as profile,\r\nvideostarts as videostarts \r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE LRA = \"$LRA\" AND \r\nCASE $month_as_number\r\nWHEN 13 THEN jahr = $Jahr AND monat != 13\r\nELSE monat != 13 AND DATE(jahr,monat,1) BETWEEN DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL 1 YEAR) AND DATE($Jahr,$month_as_number,1) END\r\nAND DATE(jahr,monat,1) >= DATE(2024,8,1)\r\n)\r\nPIVOT (\r\n  SUM(videostarts) FOR profile IN (%s)\r\n)\r\nORDER BY DATE(month_year) ASC\r\n\"\"\", profiles);\r\n"
    }
   ]
  },
  {
   "title": "Anteil Videostarts $LRA Profile",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n  SELECT profile FROM Quintly.profiles WHERE LRA = \"$LRA\" AND tiktokID != 0\r\n),\r\nall_values AS(\r\n  SELECT\r\n  profile,\r\n  videostarts\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $month_as_number AND jahr = $Jahr \r\n)\r\nSELECT \r\nREPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss'),\"?\",\"\") as profile,\r\nIFNULL(videostarts,0) as videostarts\r\nFROM all_profiles\r\nLEFT JOIN all_values\r\nUSING(profile)\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 5 }, "options": { "content": "### Videostarts in Mio.\n" } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH('Summe')), 'Summe')\r\nFROM(\r\nSELECT 'Summe' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH('Ø Pro Tag')), 'Ø Pro Tag')\r\nFROM(\r\nSELECT 'Ø Pro Tag' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" \", $Jahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nSUM(videostarts)/1000000 as Videostarts,\r\n(SUM(videostarts)/MAX(anzahltage))/1000000 as VideostartsProTag\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE LRA = \"$LRA\" AND monat = $month_as_number AND jahr = $Jahr"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CASE $month_as_number\r\n            WHEN 13 THEN \"\"\r\n            WHEN 8 THEN \"\"\r\n            ELSE \"$LastMonat_abkuerzung $year_from_last_month\"\r\n            END As Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS(\r\n  SELECT\r\n  SUM(videostarts)/1000000 as past_sum_in_mil,\r\n  (SUM(videostarts)/MAX(anzahltage))/1000000 as past_sum_per_day\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $last_month AND jahr = $year_from_last_month \r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(videostarts)/1000000 as current_sum_in_mil,\r\n  (SUM(videostarts)/MAX(anzahltage))/1000000 as current_sum_per_day\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $month_as_number AND jahr = $Jahr\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Vorjahresmonat_abkuerzung\", \" \", $LastJahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS(\r\n  SELECT\r\n  SUM(videostarts)/1000000 as past_sum_in_mil,\r\n  (SUM(videostarts)/MAX(anzahltage))/1000000 as past_sum_per_day\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $month_from_last_year AND jahr = $last_year \r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(videostarts)/1000000 as current_sum_in_mil,\r\n  (SUM(videostarts)/MAX(anzahltage))/1000000 as current_sum_per_day\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $month_as_number AND jahr = $Jahr\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil"
    }
   ]
  },
  { "title": "Entwicklung: Interaktionen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Summe Interaktionen $LRA Profile",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE profiles STRING;\r\nSET profiles = (\"$LRA_profiles\");\r\nEXECUTE IMMEDIATE format(\"\"\"\r\nSELECT * FROM(\r\nSELECT \r\nDATE(jahr,monat,1) as month_year, \r\nREPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss'), '?', '') as profile,\r\ninteractions\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE LRA = \"$LRA\" AND \r\nCASE $month_as_number\r\nWHEN 13 THEN jahr = $Jahr AND monat != 13\r\nELSE monat != 13 AND DATE(jahr,monat,1) BETWEEN DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL 1 YEAR) AND DATE($Jahr,$month_as_number,1) END\r\nAND DATE(jahr,monat,1) >= DATE(2024,8,1)\r\n)\r\nPIVOT (\r\n  SUM(interactions) FOR profile IN (%s)\r\n)\r\nORDER BY DATE(month_year) ASC\r\n\"\"\", profiles);\r\n"
    }
   ]
  },
  {
   "title": "Anteil Interaktionen $LRA Profile",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--SELECT \r\n--REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n--interactions\r\n--FROM Quintly_frozen.tiktok_metrics\r\n--WHERE LRA = \"$LRA\" AND \r\n--monat = $month_as_number AND jahr = $Jahr\r\n\r\n\r\nWITH all_profiles AS(\r\n  SELECT profile FROM Quintly.profiles WHERE LRA = \"$LRA\" AND tiktokID != 0\r\n),\r\nall_values AS(\r\n  SELECT\r\n  profile,\r\n  interactions\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $month_as_number AND jahr = $Jahr \r\n)\r\nSELECT \r\nREPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss'),\"?\",\"\") as profile,\r\nIFNULL(interactions,0) as interactions\r\nFROM all_profiles\r\nLEFT JOIN all_values\r\nUSING(profile)\r\n\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 2, "x": 16, "y": 21 } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 21 }, "options": { "content": "### Interaktionen in Mio.\n" } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH('Summe')), 'Summe')\r\nFROM(\r\nSELECT 'Summe' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH('Ø Pro Tag')), 'Ø Pro Tag')\r\nFROM(\r\nSELECT 'Ø Pro Tag' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" \", $Jahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nSUM(interactions)/1000000 as interactions,\r\n(SUM(interactions)/MAX(anzahltage))/1000000 as interactionsProTag\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE LRA = \"$LRA\" AND monat = $month_as_number AND jahr = $Jahr"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CASE $month_as_number\r\n            WHEN 13 THEN \"\"\r\n            WHEN 8 THEN \"\"\r\n            ELSE \"$LastMonat_abkuerzung $year_from_last_month\"\r\n            END As Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS(\r\n  SELECT\r\n  SUM(interactions)/1000000 as past_sum_in_mil,\r\n  (SUM(interactions)/MAX(anzahltage))/1000000 as past_sum_per_day\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $last_month AND jahr = $year_from_last_month \r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(interactions)/1000000 as current_sum_in_mil,\r\n  (SUM(interactions)/MAX(anzahltage))/1000000 as current_sum_per_day\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $month_as_number AND jahr = $Jahr\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", 48 - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Vorjahresmonat_abkuerzung\", \" \", $LastJahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS(\r\n  SELECT\r\n  SUM(interactions)/1000000 as past_sum_in_mil,\r\n  (SUM(interactions)/MAX(anzahltage))/1000000 as past_sum_per_day\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $month_from_last_year AND jahr = $last_year \r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(interactions)/1000000 as current_sum_in_mil,\r\n  (SUM(interactions)/MAX(anzahltage))/1000000 as current_sum_per_day\r\n  FROM Quintly_frozen.tiktok_metrics\r\n  WHERE LRA = \"$LRA\" AND monat = $month_as_number AND jahr = $Jahr\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil"
    }
   ]
  },
  { "title": "Follower | ${Monat} ${Jahr} ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Follower | Stichtag: $Stichtag",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n  SELECT profile, tiktokID as profileId\r\n  FROM Quintly.profiles\r\n  WHERE tiktokID != 0 AND LRA = \"$LRA\"\r\n), follower_values AS(\r\n  SELECT\r\nprofile, profileId, followers\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(followers,0) as followers FROM all_profiles\r\nLEFT JOIN follower_values\r\nUSING(profile,profileId)\r\nORDER BY followers DESC"
    }
   ]
  },
  {
   "title": "${veraenderung_zum_vormonat_title}",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($month_as_number = 8 AND $Jahr = 2024) OR ($month_as_number = 13 AND $Jahr = 2024) THEN\r\nSELECT \"\", NULL;\r\nELSE\r\nSELECT \r\nlm.profile as Profil,\r\nIFNULL((lm_follower/llm_follower - 1)*100,0) as FollowerVeraenderung\r\nFROM\r\n(\r\nSELECT\r\nprofile, followers as lm_follower\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\nORDER BY followers desc\r\n) as lm\r\nLEFT JOIN\r\n(\r\nSELECT\r\nprofile, followers as llm_follower\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE \r\nCASE $month_as_number\r\nWHEN 13 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nAND LRA = \"$LRA\"\r\nORDER BY followers desc\r\n) as llm \r\nON llm.profile = lm.profile\r\nORDER BY lm.lm_follower DESC;\r\nEND IF"
    }
   ]
  },
  {
   "title": "Videostarts | ${Monat} ${Jahr} ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "Videostarts",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n  SELECT profile, tiktokID as profileId\r\n  FROM Quintly.profiles\r\n  WHERE tiktokID != 0 AND LRA = \"$LRA\"\r\n), videostarts_values AS(\r\n  SELECT\r\nprofile, profileId, videostarts\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(videostarts,0) as videostarts FROM all_profiles\r\nLEFT JOIN videostarts_values\r\nUSING(profile,profileId)\r\nORDER BY videostarts DESC"
    }
   ]
  },
  {
   "title": "${veraenderung_zum_vormonat_title}",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($month_as_number = 8 AND $Jahr = 2024) OR ($month_as_number = 13 AND $Jahr = 2024) THEN\r\nSELECT \"\", NULL;\r\nELSE\r\nSELECT \r\nlm.profile as Profil,\r\nIFNULL((lm_videostarts/llm_videostarts - 1)*100,0) as VideostartsVeraenderung\r\nFROM\r\n(\r\nSELECT\r\nprofile, videostarts as lm_videostarts\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\nORDER BY videostarts desc\r\n) as lm\r\nLEFT JOIN\r\n(\r\nSELECT\r\nprofile, videostarts as llm_videostarts\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE \r\nCASE $month_as_number\r\nWHEN 13 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nAND LRA = \"$LRA\"\r\nORDER BY videostarts desc\r\n) as llm \r\nON llm.profile = lm.profile\r\nORDER BY lm.lm_videostarts DESC;\r\nEND IF"
    }
   ]
  },
  {
   "title": "Interaktionen | ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Interaktionen",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n  SELECT profile, tiktokID as profileId\r\n  FROM Quintly.profiles\r\n  WHERE tiktokID != 0 AND LRA = \"$LRA\"\r\n), interaktionen_values AS(\r\n  SELECT\r\nprofile, profileId, interactions\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(interactions,0) as interaktionen FROM all_profiles\r\nLEFT JOIN interaktionen_values\r\nUSING(profile,profileId)\r\nORDER BY interaktionen DESC"
    }
   ]
  },
  {
   "title": "${veraenderung_zum_vormonat_title}",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($month_as_number = 8 AND $Jahr = 2024) OR ($month_as_number = 13 AND $Jahr = 2024) THEN\r\nSELECT \"\", NULL;\r\nELSE\r\nSELECT \r\nlm.profile as Profil,\r\nIFNULL((lm_interactions/llm_interactions - 1)*100,0) as InteraktionenVeraenderung\r\nFROM\r\n(\r\nSELECT\r\nprofile, interactions as lm_interactions\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\nORDER BY interactions desc\r\n) as lm\r\nLEFT JOIN\r\n(\r\nSELECT\r\nprofile, interactions as llm_interactions\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE \r\nCASE $month_as_number\r\nWHEN 13 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nAND LRA = \"$LRA\"\r\nORDER BY interactions desc\r\n) as llm \r\nON llm.profile = lm.profile\r\nORDER BY lm.lm_interactions DESC;\r\nEND IF"
    }
   ]
  },
  {
   "title": "Gesamte Wiedergabedauer in Stunden | ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "Gesamte Wiedergabedauer in Stunden",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n  SELECT profile, tiktokID as profileId\r\n  FROM Quintly.profiles\r\n  WHERE tiktokID != 0 AND LRA = \"$LRA\"\r\n), wiedergabedauer_in_std_values AS(\r\n  SELECT\r\nprofile, profileId, sehVolumen\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(sehVolumen,0) as sehVolumen FROM all_profiles\r\nLEFT JOIN wiedergabedauer_in_std_values\r\nUSING(profile,profileId)\r\nORDER BY sehVolumen DESC, profile ASC"
    }
   ]
  },
  {
   "title": "Anzahl Videos",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n  SELECT profile, tiktokID as profileId\r\n  FROM Quintly.profiles\r\n  WHERE tiktokID != 0 AND LRA = \"$LRA\"\r\n), anzahlvideos_value AS(\r\n  SELECT\r\nprofile, profileId, anzahlVideos, sehVolumen\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(anzahlVideos,0) as anzahlVideos FROM all_profiles\r\nLEFT JOIN anzahlvideos_value\r\nUSING(profile,profileId)\r\nORDER BY sehVolumen DESC, profile ASC"
    }
   ]
  },
  {
   "title": "Potenzielle Reichweite pro Video | ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 }
  },
  {
   "title": "Potenzielle Reichweite pro Video",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n  SELECT profile, tiktokID as profileId\r\n  FROM Quintly.profiles\r\n  WHERE tiktokID != 0 AND LRA = \"$LRA\"\r\n), pot_reichweite_values AS(\r\n  SELECT\r\nprofile, profileId, pot_reichweite_pro_video\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(pot_reichweite_pro_video,0) as pot_reichweite_pro_video FROM all_profiles\r\nLEFT JOIN pot_reichweite_values\r\nUSING(profile,profileId)\r\nORDER BY pot_reichweite_pro_video DESC, profile ASC"
    }
   ]
  },
  {
   "title": "Anzahl Videos",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n  SELECT profile, tiktokID as profileId\r\n  FROM Quintly.profiles\r\n  WHERE tiktokID != 0 AND LRA = \"$LRA\"\r\n), anzahlvideos_value AS(\r\n  SELECT\r\nprofile, profileId, anzahlVideos, pot_reichweite_pro_video\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(anzahlVideos,0) as anzahlVideos FROM all_profiles\r\nLEFT JOIN anzahlvideos_value\r\nUSING(profile,profileId)\r\nORDER BY pot_reichweite_pro_video DESC, profile ASC"
    }
   ]
  },
  {
   "title": "Top Videos nach Videostarts | ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 }
  },
  {
   "title": "Top Videos nach Videostarts",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH top_100_videos AS(\nSELECT\n* EXCEPT(LRA, profileId, likes, comments, shares, monat, jahr, interaction_rate, averageTimeWatched_in_minutes, hashtags)\nFROM Quintly_frozen.tiktok_posts\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"),\ntop_100_videos_covers AS(\n  SELECT distinct externalId, MAX(videoCoverUrl) as videoCoverUrl\n  FROM Quintly.tiktokAnalyticsOwnPosts\n  WHERE CASE $month_as_number WHEN 13 THEN TRUE ELSE EXTRACT(MONTH from time) = $month_as_number END AND EXTRACT(YEAR from time) = $Jahr AND \n  CASE \"$LRA\" WHEN \"KiKa\" THEN LRA = \"MDR\" ELSE LRA = \"$LRA\" END\n  GROUP BY externalId\n)\nSELECT * EXCEPT(externalId) FROM top_100_videos\nJOIN \ntop_100_videos_covers\nUSING(externalId)\nORDER BY views DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Top One Video je Profil nach Videostarts | ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 }
  },
  {
   "title": "Top One Video je Profil nach Videostarts",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH top_100_videos AS(\nSELECT * EXCEPT(row_num) FROM(\nSELECT\n* EXCEPT(LRA, profileId, likes, comments, shares, monat, jahr, interaction_rate, averageTimeWatched_in_minutes, hashtags),\nROW_NUMBER() OVER (PARTITION BY profile ORDER BY views DESC) as row_num,\nFROM Quintly_frozen.tiktok_posts\nWHERE CASE $month_as_number WHEN 13 THEN TRUE ELSE  monat = $month_as_number END AND jahr = $Jahr AND LRA = \"$LRA\")\nWHERE row_num = 1\n),\ntop_100_videos_covers AS(\n  SELECT distinct externalId, MAX(videoCoverUrl) as videoCoverUrl\n  FROM Quintly.tiktokAnalyticsOwnPosts\n  WHERE CASE $month_as_number WHEN 13 THEN TRUE ELSE EXTRACT(MONTH from time) = $month_as_number END AND EXTRACT(YEAR from time) = $Jahr AND \n  CASE \"$LRA\" WHEN \"KiKa\" THEN LRA = \"MDR\" ELSE LRA = \"$LRA\" END\n  GROUP BY externalId\n)\nSELECT * EXCEPT(externalId) FROM top_100_videos\nJOIN top_100_videos_covers\nUSING(externalId)\nORDER BY views DESC"
    }
   ]
  },
  {
   "title": "Zusammenfassung aller Profile | ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_values AS(\r\nSELECT profile, followers as current_followers, anzahlVideos as current_anzahlPosts, interactions as current_interactions, videostarts as current_views, sehVolumen as current_sehVolumen, pot_reichweite_pro_video as current_pot_reichweite_pro_tag\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA\"),\r\npast_values AS(\r\nSELECT profile, followers as past_followers, anzahlVideos as past_anzahlPosts, interactions as past_interactions, videostarts as past_views, sehVolumen as past_sehVolumen, pot_reichweite_pro_video as past_pot_reichweite_pro_tag\r\nFROM Quintly_frozen.tiktok_metrics\r\nWHERE CASE $month_as_number\r\nWHEN 13 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nAND LRA = \"$LRA\"\r\n), joined_data AS(\r\nSELECT * FROM current_values\r\nLEFT JOIN \r\npast_values\r\nUSING(profile))\r\nSELECT profile as Profil,\r\nCASE current_followers\r\nWHEN 0 THEN NULL\r\nELSE current_followers END as followers,\r\nCASE \r\nWHEN (current_followers - past_followers = 0) OR (past_followers = 0) THEN NULL\r\nELSE current_followers - past_followers END as FollowerVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_followers,past_followers)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_followers,past_followers)-1)*100 END as FollowerVeraenderung,\r\n\r\nCASE current_anzahlPosts\r\nWHEN 0 THEN NULL\r\nELSE current_anzahlPosts END as Anzahlposts,\r\n\r\nCASE current_views\r\nWHEN 0 THEN NULL\r\nELSE current_views END as videoViews10s,\r\nCASE \r\nWHEN (current_views - past_views = 0) OR (past_views = 0) THEN NULL\r\nELSE current_views - past_views END as videoViews10sVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_views,past_views)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_views,past_views)-1)*100 END as videoViews10sVeraenderung,\r\n\r\nCASE current_interactions\r\nWHEN 0 THEN NULL\r\nELSE current_interactions END as Interaktionen,\r\nCASE \r\nWHEN (current_interactions - past_interactions = 0) OR (past_interactions = 0) THEN NULL\r\nELSE current_interactions - past_interactions END as InteraktionenVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_interactions,past_interactions)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_interactions,past_interactions)-1)*100 END as InteraktionenVeraenderung,\r\n\r\nCASE current_sehVolumen\r\nWHEN 0 THEN NULL\r\nELSE current_sehVolumen END as sehVolumen,\r\nCASE \r\nWHEN (current_sehVolumen - past_sehVolumen = 0) OR (past_sehVolumen = 0) THEN NULL \r\nELSE current_sehVolumen - past_sehVolumen END as sehVolumenVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_sehVolumen,past_sehVolumen)-1)*100 \r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_sehVolumen,past_sehVolumen)-1)*100 END as sehVolumenVeraenderung,\r\n\r\nCASE current_pot_reichweite_pro_tag\r\nWHEN 0 THEN NULL \r\nELSE current_pot_reichweite_pro_tag END as PotReichweiteProVideo,\r\nCASE \r\nWHEN (current_pot_reichweite_pro_tag - past_pot_reichweite_pro_tag = 0) OR (past_pot_reichweite_pro_tag = 0)  THEN NULL\r\nELSE current_pot_reichweite_pro_tag - past_pot_reichweite_pro_tag END as PotReichweiteProVideoVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_pot_reichweite_pro_tag,past_pot_reichweite_pro_tag)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_pot_reichweite_pro_tag,past_pot_reichweite_pro_tag)-1)*100 END as PotReichweiteProVideoVeraenderung,\r\n\r\nFROM joined_data\r\nORDER BY Profil DESC"
    }
   ]
  }
 ]
}