{
 "title": "Piano Web Desktop mit Länderfilter",
 "description": "With SEO Table",
 "time": { "from": "2023-05-01T00:00:00.000Z", "to": "2023-05-09T16:12:25.000Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "media_house",
    "query": {}
   },
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Redaktionen",
    "query": {}
   },
   {
    "name": "Unterkapitel",
    "query": {}
   },
   {
    "name": "Sendung",
    "query": {}
   },
   {
    "name": "Vergleichszeitraum",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "Vergleichszeitraumlabels",
    "query": {}
   },
   { "name": "filled_size", "query": "13" },
   {
    "name": "Zeitraum",
    "query": "Letzte Stunde : CAST(tmstp AS DATE) = CURRENT_DATE(),    Heute : date = CURRENT_DATE,  Heute -7d : date = CURRENT_DATE(), Gestern : date = DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY), Letztes Wochenende :  date >= (SELECT saturday FROM(SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 2 DAY) as saturday)) AND date <= (SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 1 DAY) as sunday), Letzte 7 Tage : date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  7 DAY) AND date < CURRENT_DATE(), Letzte 30 Tage : date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  30 DAY) AND date < CURRENT_DATE()"
   },
   {
    "name": "time_shift",
    "query": {}
   },
   {
    "name": "dataset_zeitraum",
    "query": {}
   },
   {
    "name": "dataset_vergleichs_zeitraum",
    "query": {}
   },
   {
    "name": "dataset_articles_zeitraum",
    "query": {}
   },
   {
    "name": "bq_timeframe_end",
    "query": {}
   },
   {
    "name": "bq_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_comp_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_comp_timeframe_end",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "Zeitraumfever",
    "query": {}
   },
   {
    "name": "lim",
    "query": {}
   },
   {
    "name": "type",
    "query": {}
   },
   {
    "name": "feverCurveDataset",
    "query": {}
   },
   { "name": "Glaettung", "query": "Glätten, Nicht Glätten" },
   {
    "name": "comp_fever",
    "query": {}
   },
   {
    "name": "Uhrzeit",
    "query": {}
   },
   {
    "name": "Zeitraumlabels",
    "query": {}
   },
   {
    "name": "articles_table",
    "query": {}
   },
   {
    "name": "av_table",
    "query": {}
   },
   {
    "name": "distro_table",
    "query": {}
   },
   {
    "name": "av_table_comp",
    "query": {}
   },
   {
    "name": "dataset_kpi",
    "query": {}
   },
   {
    "name": "distroRefTable",
    "query": {}
   },
   {
    "name": "sophora",
    "query": {}
   },
   {
    "name": "distroRefAppendix",
    "query": {}
   },
   {
    "name": "Redaktionen_mapped",
    "query": {}
   },
   {
    "name": "bq_fever",
    "query": {}
   },
   {
    "name": "ndr_sendungen_av_filter",
    "query": {}
   },
   {
    "name": "sendungs_id_tags_filter",
    "query": {}
   },
   {
    "name": "sendungen_av_join_filter",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# 📊 Hinweis\n\n- Audio- und Video-Daten ohne Livestream-Nutzung, mit Ausnahme der Livestream-Tabelle."
   }
  },
  {
   "title": "Verlaufsdiagramm Visits",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH lagged_data AS (\n  SELECT\n    TIMESTAMP(tmstp) as time,\n    m_visits,\n    LAG(m_visits) OVER (ORDER BY tmstp) as prev_m_visits,\n    LAG(TIMESTAMP(tmstp)) OVER (ORDER BY tmstp) as pre_timestamp\n  FROM\n    `Piano.total_visits_today_append`\n  WHERE\n    site_level2 = \"$LRA\"\n        AND page_chapter1 = \"$Redaktionen_mapped\"\n        AND page_chapter2 = \"$Unterkapitel\"\n        AND sendungs_id = \"$Sendung\"\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} --$Zeitraum \n    AND source != \"mdr_app\"\n    AND \n    CASE \"$LRA\"\n    WHEN \"ndr.de\" THEN True\n    WHEN \"eurovision.de\" THEN True\n    ELSE (\n      CASE \"$Redaktionen_mapped\"\n        WHEN \"Brisant\" THEN origin = \"sendung\"\n        WHEN \"Jump\" THEN origin = \"sendung\"\n        WHEN \"Sputnik\" THEN origin = \"sendung\"\n        WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\n        WHEN \"klassik\" THEN origin = \"klassik\"\n        WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\n        ELSE True\n      END\n    )\n    END\n    ORDER by time DESC\n    ${lim}\n    -- 09:00     --> 09:20. --- > 09:30\n\n),\nmin_time_from_base AS (\n  -- This with statement will used in order to find out which is the last valid upload(e.g. the one with valid successor)\n  SELECT MIN(pre_timestamp) min_time FROM lagged_data\n  WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10\n), \nmax_time_from_base AS (\n    -- THis with statement will be used if no gap exists\n    SELECT MAX(time) as max_time FROM lagged_data\n    WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10\n),\ncleaned_lagged_data AS (\n  SELECT * from lagged_data \n  WHERE\n  time <= (SELECT COALESCE( min_time_from_base.min_time, max_time_from_base.max_time )\n  FROM max_time_from_base, min_time_from_base)\n),\ndaily_data AS (\n  SELECT\n     TIMESTAMP(date, \"Europe/Berlin\") as time,\n    TIMESTAMP_SUB(TIMESTAMP(date,  \"Europe/Berlin\"), INTERVAL 10 MINUTE) as pre_timestamp,\n    m_visits as visits_past_5_minutes_adjusted,\n    \"${type}\" as type, \"${Zeitraumlabels:text}\" as refId\n  FROM\n    `Piano.total_visits${feverCurveDataset:raw}`\n  WHERE\n    site_level2 = \"$LRA\"\n    AND page_chapter1 = \"$Redaktionen_mapped\"\n    AND page_chapter2 = \"$Unterkapitel\"\n    AND sendungs_id = \"$Sendung\"\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}--$Zeitraum\n    ORDER BY time DESC\n),\nadjusted_lagged_data AS (\n  SELECT\n    DATE_SUB(time, INTERVAL 2 hour) as time,\n    DATE_SUB(pre_timestamp, INTERVAL 2 hour) as pre_timestamp,\n    -- Calculate time difference in minutes\n    TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) as time_diff,\n    -- Adjust visits count based on time difference\n    CASE\n      WHEN FALSE AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10 OR TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) < 0 AND \"${Glaettung:text}\" = \"Glätten\" THEN\n        (m_visits - prev_m_visits) / TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) * 10\n      ELSE\n        m_visits - prev_m_visits\n    END as visits_past_5_minutes_adjusted,\n    \"${type}\" as type, \n    \"${Zeitraumlabels:text}\" as refId\n  FROM\n    cleaned_lagged_data\n)\nSELECT\n  TIMESTAMP_ADD(time, INTERVAL 1 SECOND) as time,\n  TIMESTAMP_ADD(pre_timestamp, INTERVAL 1 SECOND) as pre_timestamp,\n  MAX(ROUND(visits_past_5_minutes_adjusted)) as visits_past_5_minutes,\n  type,\n  refId,\n   \"${Glaettung:text}\" as glaettung,\n   \"Zeitraum\" as zeitraum\nFROM\n  ${dataset}\nWHERE\n  visits_past_5_minutes_adjusted IS NOT NULL\n  AND visits_past_5_minutes_adjusted > 0\n  AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10 OR TIMESTAMP_DIFF(time, pre_timestamp, HOUR) = 1\n  GROUP BY time, pre_timestamp, type, refId\nORDER BY\n  time ASC\n  ${lim}\n"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH min_time AS ( \n      SELECT\n        MIN(tmstp) as min_tmstp,\n        MAX(tmstp) as max_tmstp\n        FROM\n      (SELECT tmstp\n      from\n        `Piano.total_visits${feverCurveDataset:raw}`\n      WHERE\n        date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} --$Zeitraum\n        AND site_level2 = \"$LRA\"\n        AND page_chapter1 = \"$Redaktionen_mapped\"\n        AND page_chapter2 = \"$Unterkapitel\"\n        AND sendungs_id = \"$Sendung\"\n        AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} -- $Zeitraum\n        AND CASE\n          \"$LRA\"\n          WHEN \"ndr.de\" THEN True\n          WHEN \"eurovision.de\" THEN True\n          ELSE (\n            CASE\n              \"$Redaktionen_mapped\"\n              WHEN \"Brisant\" THEN origin = \"sendung\"\n              WHEN \"Jump\" THEN origin = \"sendung\"\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\n              WHEN \"klassik\" THEN origin = \"klassik\"\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\n              ELSE True\n            END\n          )\n        END\n        ORDER BY tmstp DESC\n        ${lim}\n        )\n    )\n    , lagged_data AS (\n    SELECT\n        TIMESTAMP(tmstp) as time,\n        m_visits,\n        LAG(m_visits) OVER (ORDER BY tmstp) as prev_m_visits,\n        LAG(TIMESTAMP(tmstp)) OVER (ORDER BY tmstp) as pre_timestamp\n  FROM\n     `Piano.total_visits_today_append`\n  WHERE\n     date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} --$Vergleichszeitraum\n    AND $Zeitraumfever \n    AND source != \"mdr_app\"\n    AND site_level2 = \"$LRA\"\n        AND page_chapter1 = \"$Redaktionen_mapped\"\n        AND page_chapter2 = \"$Unterkapitel\"\n        AND sendungs_id = \"$Sendung\"\n        AND CASE\n          \"$LRA\"\n          WHEN \"ndr.de\" THEN True\n          WHEN \"eurovision.de\" THEN True\n          ELSE (\n            CASE\n              \"$Redaktionen_mapped\"\n              WHEN \"Brisant\" THEN origin = \"sendung\"\n              WHEN \"Jump\" THEN origin = \"sendung\"\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\n              WHEN \"klassik\" THEN origin = \"klassik\"\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\n              ELSE True\n            END\n          )\n        END\n),\nmin_time_from_base AS (\n  -- This with statement will used in order to find out which is the last valid upload(e.g. the one with valid successor)\n  SELECT MIN(pre_timestamp) min_time FROM lagged_data\n  WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10\n), \nmax_time_from_base AS (\n    -- THis with statement will be used if no gap exists\n    SELECT MAX(time) as max_time FROM lagged_data\n    WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10\n),\ncleaned_lagged_data AS (\n  SELECT * from lagged_data \n  WHERE\n  time <= (SELECT COALESCE(min_time_from_base.min_time,max_time_from_base.max_time )\n  FROM max_time_from_base, min_time_from_base)\n),\nadjusted_lagged_data AS (\n    SELECT\n        time,\n        pre_timestamp,\n        -- Calculate time difference in minutes\n        TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) as time_diff,\n        -- Adjust visits count based on time difference\n        CASE\n            WHEN FALSE AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10 THEN\n                (m_visits - prev_m_visits) / TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) * 10\n            ELSE\n                m_visits - prev_m_visits\n        END as visits_past_5_minutes_adjusted\n    FROM\n        cleaned_lagged_data\n),\ndaily_data AS (\n  SELECT\n    TIMESTAMP(date) as time,\n    m_visits as visits_past_5_minutes_adjusted,\n    TIMESTAMP_SUB(TIMESTAMP(date), INTERVAL 10 MINUTE) as pre_timestamp\n  FROM\n    `Piano.total_visits${feverCurveDataset:raw}`\n  WHERE\n    site_level2 = \"$LRA\"\n    AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} --$Vergleichszeitraum\n    AND site_level2 = \"$LRA\"\n        AND page_chapter1 = \"$Redaktionen_mapped\"\n        AND page_chapter2 = \"$Unterkapitel\"\n        AND sendungs_id = \"$Sendung\"\n        AND CASE\n          \"$LRA\"\n          WHEN \"ndr.de\" THEN True\n          WHEN \"eurovision.de\" THEN True\n          ELSE (\n            CASE\n              \"$Redaktionen_mapped\"\n              WHEN \"Brisant\" THEN origin = \"sendung\"\n              WHEN \"Jump\" THEN origin = \"sendung\"\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\n              ELSE True\n            END\n          )\n        END\n)\nSELECT\n    DATE_SUB(DATE_ADD(TIMESTAMP_ADD(time, INTERVAL 1 SECOND), INTERVAL ${time_shift} DAY), INTERVAL 2 HOUR) as time,\n    DATE_SUB(DATE_ADD(TIMESTAMP_ADD(pre_timestamp, INTERVAL 1 SECOND), INTERVAL ${time_shift} DAY), INTERVAL 2 HOUR) as pre_timestamp,\n    MAX(visits_past_5_minutes_adjusted) as visits_past_5_minutes,\n    \"${type}\" as type,\n    \"${Vergleichszeitraumlabels:text}\" as refId,\n    \"${Glaettung:text}\" as glaettung,\n    \"Vergleichszeitraum\" as zeitraum\nFROM\n    ${dataset}\nWHERE\n    visits_past_5_minutes_adjusted IS NOT NULL\n    AND visits_past_5_minutes_adjusted > 0\n     AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10 OR TIMESTAMP_DIFF(time, pre_timestamp, HOUR) = 1\n     AND  CASE \"${Zeitraum:text}\"\n     WHEN \"Gestern\" THEN EXTRACT(date from time) = \"$bq_fever\"\n     WHEN \"Heute\" THEN EXTRACT(date from time) = \"$bq_fever\"\n      WHEN \"Heute -7d\" THEN EXTRACT(date from time) = \"$bq_fever\"\n     ELSE True\n     END\n     \nGROUP BY time, pre_timestamp, type, refId\nORDER BY\n    time ASC\n\n  ${lim}\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "options": { "content": " " } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Visits')), 'Visits')\r\nFROM(\r\nSELECT 'Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Bounce Rate in %')), 'Bounce Rate in %')\r\nFROM(\r\nSELECT 'Bounce Rate in %' as Bounce\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Page Views / Visits')), 'Page Views / Visits')\r\nFROM(\r\nSELECT 'Page Views / Visits' as pi_visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Time spent/Visit in s')), 'Time spent/Visit in s')\r\nFROM(\r\nSELECT 'Time spent/Visit in s' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio- & Videostarts')), 'Audio- & Videostarts')\r\nFROM(\r\nSELECT 'Audio- & Videostarts' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version \r\n\r\nSELECT \r\n  SUM(COALESCE(m_visits,0)) as summe\r\nFROM \r\n  `Piano.total_visits${dataset_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH adjusted_lagged_data AS (\r\nSELECT\r\n        TIMESTAMP(tmstp) as time,\r\n        FIRST_VALUE(m_visits) OVER(ORDER by tmstp DESC) as summe\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`  \r\n  WHERE TRUE\r\n     AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    AND site_level2 = \"$LRA\"\r\n        AND page_chapter1 = \"$Redaktionen_mapped\"\r\n        AND page_chapter2 = \"$Unterkapitel\"\r\n        AND sendungs_id = \"$Sendung\"\r\n        AND CASE\r\n          \"$LRA\"\r\n          WHEN \"ndr.de\" THEN True\r\n          WHEN \"eurovision.de\" THEN True\r\n          ELSE (\r\n            CASE\r\n              \"$Redaktionen_mapped\"\r\n              WHEN \"Brisant\" THEN origin = \"sendung\"\r\n              WHEN \"Jump\" THEN origin = \"sendung\"\r\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\r\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\r\n              WHEN \"klassik\" THEN origin = \"klassik\"\r\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\r\n              ELSE True\r\n            END\r\n          )\r\n        END\r\n        ORDER BY tmstp DESC\r\n        LIMIT 1\r\n),\r\ndaily_data AS (\r\n  SELECT \r\n  SUM(COALESCE(m_visits,0)) as summe\r\nFROM \r\n  `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} )\r\nSELECT * FROM ${dataset_kpi}\r\n     \r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version \r\n\r\nSELECT \r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\nFROM \r\n  `Piano.total_visits${dataset_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH adjusted_lagged_data AS (\r\nSELECT\r\n        TIMESTAMP(tmstp) as time,\r\n        -- SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe\r\n        COALESCE(FIRST_VALUE(m_bounce_rate) OVER(ORDER by tmstp DESC) *m_visits,0)/COALESCE(FIRST_VALUE(m_visits) OVER(ORDER by tmstp DESC),0)*100 as summe\r\n        --FIRST_VALUE(m_bounce_rate) OVER(ORDER by tmstp DESC) as summe\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`  \r\n  WHERE TRUE\r\n     AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    AND site_level2 = \"$LRA\"\r\n        AND page_chapter1 = \"$Redaktionen_mapped\"\r\n        AND page_chapter2 = \"$Unterkapitel\"\r\n        AND sendungs_id = \"$Sendung\"\r\n        AND CASE\r\n          \"$LRA\"\r\n          WHEN \"ndr.de\" THEN True\r\n          WHEN \"eurovision.de\" THEN True\r\n          ELSE (\r\n            CASE\r\n              \"$Redaktionen_mapped\"\r\n              WHEN \"Brisant\" THEN origin = \"sendung\"\r\n              WHEN \"Jump\" THEN origin = \"sendung\"\r\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\r\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\r\n              WHEN \"klassik\" THEN origin = \"klassik\"\r\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\r\n              ELSE True\r\n            END\r\n          )\r\n        END\r\n        ORDER BY tmstp DESC\r\n        LIMIT 1\r\n),\r\ndaily_data AS (\r\n  SELECT \r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe\r\nFROM \r\n  `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mappped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} )\r\nSELECT * FROM ${dataset_kpi}\r\n     \r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version \r\n\r\nSELECT \r\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM \r\n  `Piano.total_visits${dataset_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH adjusted_lagged_data AS (\r\nSELECT\r\n        TIMESTAMP(tmstp) as time,\r\n       COALESCE(FIRST_VALUE(m_page_loads)OVER(ORDER BY tmstp desc),0)/COALESCE(FIRST_VALUE(m_visits) OVER (ORDER BY tmstp DESC),1) as PI_per_visit\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`  \r\n  WHERE TRUE\r\n     AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    AND site_level2 = \"$LRA\"\r\n        AND page_chapter1 = \"$Redaktionen_mapped\"\r\n        AND page_chapter2 = \"$Unterkapitel\"\r\n        AND sendungs_id = \"$Sendung\"\r\n        AND CASE\r\n          \"$LRA\"\r\n          WHEN \"ndr.de\" THEN True\r\n          WHEN \"eurovision.de\" THEN True\r\n          ELSE (\r\n            CASE\r\n              \"$Redaktionen_mapped\"\r\n              WHEN \"Brisant\" THEN origin = \"sendung\"\r\n              WHEN \"Jump\" THEN origin = \"sendung\"\r\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\r\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\r\n              WHEN \"klassik\" THEN origin = \"klassik\"\r\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\r\n              ELSE True\r\n            END\r\n          )\r\n        END\r\n        ORDER BY tmstp DESC\r\n        LIMIT 1\r\n),\r\ndaily_data AS (\r\n  SELECT \r\n    SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM \r\n  `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} )\r\nSELECT * FROM ${dataset_kpi}\r\n     \r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\r\nFROM \r\n  `Piano.total_visits${dataset_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "    WITH adjusted_lagged_data AS(SELECT\r\n        TIMESTAMP(tmstp) as time,\r\n         (m_visits * m_time_spent_per_visits/1000) / (m_visits) AS time_spent\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}` \r\n  WHERE TRUE\r\n     AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    AND site_level2 = \"$LRA\"\r\n        AND page_chapter1 = \"$Redaktionen_mapped\"\r\n        AND page_chapter2 = \"$Unterkapitel\"\r\n        AND sendungs_id = \"$Sendung\"\r\n        AND CASE\r\n          \"$LRA\"\r\n          WHEN \"ndr.de\" THEN True\r\n          WHEN \"eurovision.de\" THEN True\r\n          ELSE (\r\n            CASE\r\n              \"$Redaktionen_mapped\"\r\n              WHEN \"Brisant\" THEN origin = \"sendung\"\r\n              WHEN \"Jump\" THEN origin = \"sendung\"\r\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\r\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\r\n              WHEN \"klassik\" THEN origin = \"klassik\"\r\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\r\n              ELSE True\r\n            END\r\n          )\r\n        END\r\n        ORDER BY tmstp DESC\r\n        LIMIT 1\r\n  ),\r\ndaily_data AS (\r\n SELECT \r\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\r\nFROM \r\n  `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n)\r\nSELECT * FROM ${dataset_kpi}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND $sendungs_id_tags_filter\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND $sendungs_id_tags_filter\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\nWITH adjusted_lagged_data AS (\r\nSELECT\r\n        TIMESTAMP(tmstp) as time,\r\n        FIRST_VALUE(m_visits) OVER(ORDER by tmstp DESC) as summe\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`  \r\n  WHERE TRUE\r\n     AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    AND site_level2 = \"$LRA\"\r\n        AND page_chapter1 = \"$Redaktionen_mapped\"\r\n        AND page_chapter2 = \"$Unterkapitel\"\r\n        AND sendungs_id = \"$Sendung\"\r\n        AND CASE\r\n          \"$LRA\"\r\n          WHEN \"ndr.de\" THEN True\r\n          WHEN \"eurovision.de\" THEN True\r\n          ELSE (\r\n            CASE\r\n              \"$Redaktionen_mapped\"\r\n              WHEN \"Brisant\" THEN origin = \"sendung\"\r\n              WHEN \"Jump\" THEN origin = \"sendung\"\r\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\r\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\r\n              WHEN \"klassik\" THEN origin = \"klassik\"\r\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\r\n              ELSE True\r\n            END\r\n          )\r\n        END\r\n        ORDER BY tmstp DESC\r\n        LIMIT 1\r\n),\r\ndaily_data AS (\r\n  SELECT \r\n  SUM(COALESCE(m_visits,0)) as summe\r\nFROM \r\n  `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} )\r\nSELECT summe as past_sum FROM ${dataset_kpi}\r\n)\r\n, current_value AS (\r\nSELECT \r\n  SUM(COALESCE(m_visits,0)) as current_sum\r\nFROM \r\n  `Piano.total_visits${dataset_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  )\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\nWITH adjusted_lagged_data AS (\r\nSELECT\r\n        TIMESTAMP(tmstp) as time,\r\n        -- SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe\r\n        COALESCE(FIRST_VALUE(m_bounce_rate) OVER(ORDER by tmstp DESC) *m_visits,0)/COALESCE(FIRST_VALUE(m_visits) OVER(ORDER by tmstp DESC),0)*100 as summe\r\n        --FIRST_VALUE(m_bounce_rate) OVER(ORDER by tmstp DESC) as past\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`  \r\n  WHERE TRUE\r\n     AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    AND site_level2 = \"$LRA\"\r\n        AND page_chapter1 = \"$Redaktionen_mapped\"\r\n        AND page_chapter2 = \"$Unterkapitel\"\r\n        AND sendungs_id = \"$Sendung\"\r\n        AND CASE\r\n          \"$LRA\"\r\n          WHEN \"ndr.de\" THEN True\r\n          WHEN \"eurovision.de\" THEN True\r\n          ELSE (\r\n            CASE\r\n              \"$Redaktionen_mapped\"\r\n              WHEN \"Brisant\" THEN origin = \"sendung\"\r\n              WHEN \"Jump\" THEN origin = \"sendung\"\r\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\r\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\r\n              WHEN \"klassik\" THEN origin = \"klassik\"\r\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\r\n              ELSE True\r\n            END\r\n          )\r\n        END\r\n        ORDER BY tmstp DESC\r\n        LIMIT 1\r\n),\r\ndaily_data AS (\r\n  SELECT \r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe \r\nFROM \r\n  `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote})\r\nSELECT summe as past_sum FROM ${dataset_kpi}),\r\ncurrent_value AS (\r\nSELECT \r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as current_sum,\r\nFROM \r\n  `Piano.total_visits${dataset_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  )\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\nWITH adjusted_lagged_data AS (\r\nSELECT\r\n        TIMESTAMP(tmstp) as time,\r\n       COALESCE(FIRST_VALUE(m_page_loads)OVER(ORDER BY tmstp desc),0)/COALESCE(FIRST_VALUE(m_visits) OVER (ORDER BY tmstp DESC),1) as PI_per_visit\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`  \r\n  WHERE TRUE\r\n     AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    AND site_level2 = \"$LRA\"\r\n        AND page_chapter1 = \"$Redaktionen_mapped\"\r\n        AND page_chapter2 = \"$Unterkapitel\"\r\n        AND sendungs_id = \"$Sendung\"\r\n        AND CASE\r\n          \"$LRA\"\r\n          WHEN \"ndr.de\" THEN True\r\n          WHEN \"eurovision.de\" THEN True\r\n          ELSE (\r\n            CASE\r\n              \"$Redaktionen_mapped\"\r\n              WHEN \"Brisant\" THEN origin = \"sendung\"\r\n              WHEN \"Jump\" THEN origin = \"sendung\"\r\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\r\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\r\n              WHEN \"klassik\" THEN origin = \"klassik\"\r\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\r\n              ELSE True\r\n            END\r\n          )\r\n        END\r\n        ORDER BY tmstp DESC\r\n        LIMIT 1\r\n),\r\ndaily_data AS (\r\n  SELECT \r\n    SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM \r\n  `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} )\r\nSELECT PI_per_visit as past_sum FROM ${dataset_kpi} )\r\n     \r\n, current_value AS (\r\nSELECT \r\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as current_sum,\r\nFROM \r\n  `Piano.total_visits${dataset_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  )\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\n    WITH adjusted_lagged_data AS(SELECT\r\n        TIMESTAMP(tmstp) as time,\r\n         (m_visits * m_time_spent_per_visits/1000) / (m_visits) AS time_spent\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}` \r\n  WHERE TRUE\r\n     AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    AND site_level2 = \"$LRA\"\r\n        AND page_chapter1 = \"$Redaktionen_mapped\"\r\n        AND page_chapter2 = \"$Unterkapitel\"\r\n        AND sendungs_id = \"$Sendung\"\r\n        AND CASE\r\n          \"$LRA\"\r\n          WHEN \"ndr.de\" THEN True\r\n          WHEN \"eurovision.de\" THEN True\r\n          ELSE (\r\n            CASE\r\n              \"$Redaktionen_mapped\"\r\n              WHEN \"Brisant\" THEN origin = \"sendung\"\r\n              WHEN \"Jump\" THEN origin = \"sendung\"\r\n              WHEN \"Sputnik\" THEN origin = \"sendung\"\r\n              WHEN \"Alle Kapitel 1\" THEN origin = \"sendung\"\r\n              WHEN \"klassik\" THEN origin = \"klassik\"\r\n              WHEN \"sorbisches-programm\" THEN origin = \"serbski\"\r\n              ELSE True\r\n            END\r\n          )\r\n        END\r\n        ORDER BY tmstp DESC\r\n        LIMIT 1\r\n  ),\r\ndaily_data AS (\r\n SELECT \r\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\r\nFROM \r\n  `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n)\r\nSELECT time_spent as past_sum FROM ${dataset_kpi}\r\n), current_value AS (\r\nSELECT\r\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS current_sum\r\nFROM \r\n  `Piano.total_visits${dataset_zeitraum:raw}`\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen_mapped\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  )\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\nSELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as past_sum\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND $sendungs_id_tags_filter\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}), \r\n\r\ncurrent_value AS (\r\nSELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as current_sum\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND $sendungs_id_tags_filter\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n  )\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "options": { "content": " " } },
  { "title": "Kapitel Visits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Kapitel Visits | $Zeitraumlabels",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nWITH nachrichten AS (\r\n  SELECT \r\n  CASE page_chapter2 WHEN \"thueringen\" THEN \"Thüringen\" WHEN \"sachsen\" THEN \"Sachsen\" WHEN \"sachsen-anhalt\" THEN \"Sachsen-Anhalt\" WHEN \"deutschland\" THEN \"Deutschland\" WHEN \"welt\" THEN \"Welt\" ELSE page_chapter2 END as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM   `Piano.total_visits${dataset_zeitraum:raw}`\r\n  WHERE page_chapter1 = \"nachrichten\" AND page_chapter2 IN (\"sachsen\",\"sachsen-anhalt\",\"thueringen\",\"deutschland\",\"welt\", \"hamburg\", \"info\", \"mecklenburg-vorpommern\", \"niedersachsen\", \"schleswig-holstein\") AND site_level2 = \"$LRA\" AND sendungs_id = \"$Sendung\" AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  GROUP BY page_chapter2\r\n), ratgeber AS(\r\n  SELECT \r\n  \"Ratgeber\" as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM   `Piano.total_visits${dataset_zeitraum:raw}`\r\n  WHERE page_chapter1 = \"ratgeber\" AND site_level2 = \"$LRA\" AND page_chapter2 = \"Alle Kapitel 2\" AND sendungs_id = \"$Sendung\" AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  GROUP BY Chapter\r\n--), app_aktuell AS (\r\n--  SELECT\r\n--  \"App Aktuell\" as Chapter,\r\n--  SUM(COALESCE(m_visits,0)) as summe\r\n--  FROM Piano.total_visits\r\n--  WHERE page_chapter1 = \"nachrichten\" AND page_chapter2 IN (\"app_aktuell\",\"app-aktuell\") AND site_level2 = \"$LRA\" AND sendungs_id = \"$Sendung\" AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n), ndr_kapitel as (\r\n  SELECT CASE page_chapter1 \r\n    WHEN \"nachrichten\" THEN \"Nachrichten\" \r\n    WHEN \"kultur\" THEN \"Kultur\" \r\n    WHEN \"sport\" THEN \"Sport\" \r\n    WHEN \"geschichte\" THEN \"Geschichte\"\r\n    WHEN \"ratgeber\" THEN \"Ratgeber\"\r\n    END as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM  `Piano.total_visits${dataset_zeitraum:raw}`\r\n  WHERE   site_level2 = \"$LRA\" AND page_chapter1 IN (\"nachrichten\",\"kultur\",\"sport\", \"geschichte\", \"ratgeber\") AND page_chapter2 = \"$Unterkapitel\" AND sendungs_id = \"$Sendung\" AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  GROUP BY Chapter ), mdr as(\r\n SELECT * FROM(\r\nSELECT\r\nChapter,\r\nsumme FROM nachrichten\r\n  WHERE Chapter IN (\"Thüringen\", \"Sachsen\" ,\"Sachsen-Anhalt\",\"Deutschland\", \"Welt\" ) \r\nUNION ALL\r\nSELECT\r\nChapter,\r\nsumme FROM ratgeber\r\n--UNION ALL \r\n--SELECT\r\n--Chapter,\r\n--summe FROM app_aktuell\r\n)), mdr_kapitel AS (\r\n  SELECT CASE \r\n    WHEN page_chapter1 = \"sport\" THEN \"Sport\" \r\n    WHEN page_chapter1 = \"kultur\" THEN \"Kultur\" \r\n    WHEN page_chapter1 = \"wissen\" THEN \"Wissen\" \r\n    ELSE page_chapter1\r\n    END as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM  `Piano.total_visits${dataset_zeitraum:raw}`\r\n  WHERE   site_level2 = \"$LRA\" AND page_chapter1 IN (\"sport\",\"wissen\",\"kultur\") AND page_chapter2 = \"$Unterkapitel\" AND sendungs_id = \"$Sendung\" AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  GROUP BY Chapter\r\n), mdr_not_nachrichten AS (\r\n  SELECT * FROM mdr_kapitel\r\n  UNION ALL\r\n  SELECT * FROM nachrichten\r\n  WHERE Chapter IN (\"Thüringen\", \"Sachsen\" ,\"Sachsen-Anhalt\",\"Deutschland\", \"Welt\" )\r\n)\r\nSELECT \r\n    Chapter, \r\n    summe \r\nFROM \r\n    (SELECT \r\n         'ndr_kapitel' as source_table, \r\n         Chapter, \r\n         summe \r\n     FROM ndr_kapitel\r\n     UNION ALL\r\n     SELECT \r\n         'mdr' as source_table, \r\n         Chapter, \r\n         summe \r\n      FROM mdr\r\n      UNION ALL\r\n     SELECT \r\n         'nachrichten' as source_table, \r\n         Chapter, \r\n         summe \r\n     FROM nachrichten\r\n     UNION ALL\r\n     SELECT\r\n     'mdr_not_nachrichten' as source_table,\r\n     Chapter,\r\n     summe\r\n     FROM mdr_not_nachrichten) as unified_table\r\nWHERE \r\n    source_table = CASE WHEN '$LRA' = 'ndr.de' AND \"$Redaktionen_mapped\" = \"nachrichten\" THEN 'nachrichten'\r\n                        WHEN '$LRA' = 'ndr.de' AND \"$Redaktionen_mapped\"!= \"nachrichten\" THEN 'ndr_kapitel'\r\n                        WHEN '$LRA' = 'mdr.de' AND \"$Redaktionen_mapped\" = \"nachrichten\" THEN 'mdr'\r\n                        WHEN '$LRA' = 'mdr.de' AND \"$Redaktionen_mapped\" != \"nachrichten\" THEN 'mdr_not_nachrichten'\r\n                    END\r\nORDER BY \r\n    summe DESC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "options": { "content": " " } },
  { "title": "Top Artikel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Top 100 Web Artikel",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\npublishing_date, \r\ncontent_titel,\r\nsum(m_visits) as visits,\r\nsum(m_page_loads) as page_views,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_bounce_rate*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS bounce_rate,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_suchmaschinen_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_suchmaschinen_anteil_visits,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_homepage_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_homepage_anteil_visits,\r\nCASE \r\n  WHEN \"$Redaktionen_mapped\" = \"Alle Kapitel 1\"  THEN page_chapter1 \r\n  WHEN \"$Redaktionen_mapped\" = \"nachrichten\"  THEN page_chapter2 \r\nEND AS Kapitel,\r\ncontent_id_sophora, url\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as publishing_date, \r\nFIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_id_sophora, \r\npage_chapter2, page_chapter1,\r\nm_visits,\r\nm_page_loads,\r\nm_bounce_rate,\r\nm_suchmaschinen_anteil_visits,\r\nm_homepage_anteil_visits, \r\nFIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as url, \r\nFIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_titel, \r\nFROM \r\n  ${articles_table:raw}\r\nWHERE site_level2 = \"$LRA\" AND\r\n\"$Redaktionen_mapped\" IN UNNEST(page_chapter1_tags) \r\nAND \"$Unterkapitel\" IN UNNEST(page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND content_id_sophora NOT LIKE '%index%'\r\nAND content_id_sophora NOT LIKE '%N/A%'\r\nAND content_id_sophora NOT LIKE '%verteilseite%'\r\nAND content_id_sophora NOT LIKE '%nachrichtenfeed%'\r\nAND page_chapter1 NOT LIKE \"CONT\"\r\nAND objekt_typ NOT LIKE 'indexPage'\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}) \r\nGROUP BY content_id_sophora, content_titel, publishing_date, page_chapter2, page_chapter1, url, publishing_date ORDER BY 4 DESC \r\n\r\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }, "options": { "content": " " } },
  { "title": "Top Audios & Videos ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), '')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 4, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaben')), 'Wiedergaben')\r\nFROM(\r\nSELECT 'Wiedergaben' as Wiedergaben\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 13, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaberate')), 'Wiedergaberate')\r\nFROM(\r\nSELECT 'Wiedergaberate' as Wiedergaberate\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Video')), 'Video')\r\nFROM(\r\nSELECT 'Video' as Video\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND $sendungs_id_tags_filter\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') \r\nOR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND \r\nAND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_value AS (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as current_sum\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n), past_value AS (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as past_sum\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n)\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as summe\r\n  --AVG(m_av_average_playback_completion_rate) as summe\r\n  -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_value AS (\r\n  SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as current_sum\r\n  -- AVG(m_av_average_playback_completion_rate) as current_sum\r\n   -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\n), past_value AS (\r\n  SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as past_sum\r\n  --AVG(m_av_average_playback_completion_rate) as past_sum\r\n   -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\n)\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), 'Audio')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') \r\nOR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_value AS (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as current_sum\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")\r\n), past_value AS (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as past_sum\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")\r\n)\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  --AVG(m_av_average_playback_completion_rate) as summe\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as summe\r\n  --AVG(m_av_average_playback_completion_rate) as summe\r\n  -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_value AS (\r\n  SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as current_sum\r\n  -- AVG(m_av_average_playback_completion_rate) as current_sum\r\n   -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")\r\n), past_value AS (\r\n  SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as past_sum\r\n  --AVG(m_av_average_playback_completion_rate) as past_sum\r\n   -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE \r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND AND\r\n\"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND (av_content_type = \"Audio\" OR av_content_type = \"audio\")\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nAND bi_av_broadcasting_type NOT IN (\"live\", \"Live\")\r\n)\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }, "options": { "content": " " } },
  {
   "title": "Top 100 Web Audios & Videos on Demand",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version \r\n\r\nSELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nCONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nSUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date, \r\nm_av_playbacks,\r\nCAST(av_content_duration/1000 AS INT) as av_content_duration,\r\nm_av_average_playback_completion_rate,\r\nav_content_type, bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\n  WHERE\r\nCASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND \r\nAND \"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) \r\nAND \"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND bi_av_content_id NOT LIKE '%index%'\r\nAND bi_av_broadcasting_type = \"ondemand\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\r\nWHERE m_av_playbacks > 0\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nGROUP BY bi_av_publication_date,bi_av_content,av_content_duration,av_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  {
   "title": "Top 100 Web Audios & Videos Livestreams",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date, \r\nm_av_playbacks,\r\nav_content_type, bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\nFROM \r\n  ${av_table:raw}\r\n$sendungen_av_join_filter\r\nWHERE CASE \"$Sendung\"\r\nWHEN \"Panorama - Das Erste\" THEN site_level2 IN (\"$LRA\", \"daserste.ndr.de\")\r\nELSE site_level2 IN (\"$LRA\")\r\nEND \r\nAND \"$Redaktionen_mapped\" IN UNNEST(bi_av_page_chapter1_tags) \r\nAND \"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND bi_av_content_id NOT LIKE '%index%'\r\nAND bi_av_broadcasting_type = \"live\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\r\nWHERE m_av_playbacks > 0\r\nAND ((\"$LRA\" = 'mdr.de' AND bi_av_url NOT LIKE '%app%') OR \"$LRA\" <> 'mdr.de')\r\nGROUP BY bi_av_publication_date,bi_av_content,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }, "options": { "content": " " } },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Web | Top Verweiser Domains | $Zeitraumlabels",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  src_referrer_site_domain \nFROM\n  ${distro_table:raw}\nWHERE \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen_mapped\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\nAND src_referrer_site_domain NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY src_referrer_site_domain \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Web | Devices | $Zeitraumlabels",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  device_type \nFROM\n  ${distro_table:raw}\nWHERE \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen_mapped\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\nAND device_type NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY device_type \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Web | Traffic Quellen | $Zeitraumlabels",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  src \nFROM\n  ${distro_table:raw}\nWHERE  \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen_mapped\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\nAND src NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY src \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }, "options": { "content": " " } },
  {
   "title": "Web | Top Referrer (nach Artikeln) | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nWITH referrer AS(\nSELECT \n  content_titel,\n  SUM(m_visits) as Visits,\n  referrer,\n  $sophora as content_id_sophora, \n  distribution as Distribution\nFROM\n(\n  SELECT\n  FIRST_VALUE(content_titel) OVER (PARTITION BY $sophora ORDER BY date DESC) as content_titel,\n  --content_titel,\n  m_visits, \n  referrer,\n  $sophora,\n  distribution,\n  date\n  FROM `$distroRefTable`\n  WHERE\n     site_level2 = \"${LRA}\"\n     AND CASE \"${Redaktionen:text}\"\n     WHEN \"Alle Kapitel 1\" THEN TRUE \n     ELSE LOWER(page_chapter1) = LOWER(\"$Redaktionen_mapped\") END\n     AND CASE \"${Unterkapitel:text}\"\n     WHEN \"Alle Kapitel 2\" THEN TRUE\n     ELSE LOWER(page_chapter2) = LOWER(\"$Unterkapitel\") END\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n    AND referrer NOT LIKE \"%N/A%\"\n)\nGROUP BY \nDistribution, \nreferrer,\ncontent_titel,\ncontent_id_sophora\nORDER BY Visits DESC), \narticles AS (\nSELECT content_id_sophora FROM (\n  SELECT\npublishing_date, \ncontent_titel,\nsum(m_visits) as visits,\nsum(m_page_loads) as page_views,\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_bounce_rate*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS bounce_rate,\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_suchmaschinen_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_suchmaschinen_anteil_visits,\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_homepage_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_homepage_anteil_visits,\nCASE \n  WHEN \"$Redaktionen_mapped\" = \"Alle Kapitel 1\"  THEN page_chapter1 \n  WHEN \"$Redaktionen_mapped\" = \"nachrichten\"  THEN page_chapter2 \nEND AS Kapitel,\ncontent_id_sophora, url\nFROM\n(\nSELECT\nFIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as publishing_date, \nFIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_id_sophora, \npage_chapter2, page_chapter1,\nm_visits,\nm_page_loads,\nm_bounce_rate,\nm_suchmaschinen_anteil_visits,\nm_homepage_anteil_visits, \nFIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as url, \nFIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_titel, \nFROM \n  ${articles_table:raw}\nWHERE site_level2 = \"$LRA\" AND\n\"$Redaktionen_mapped\" IN UNNEST(page_chapter1_tags) \nAND \"$Unterkapitel\" IN UNNEST(page_chapter2_tags)\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\nAND content_id_sophora NOT LIKE '%index%'\nAND content_id_sophora NOT LIKE '%N/A%'\nAND content_id_sophora NOT LIKE '%verteilseite%'\nAND content_id_sophora NOT LIKE '%nachrichtenfeed%'\nAND page_chapter1 NOT LIKE \"CONT\"\nAND objekt_typ NOT LIKE 'indexPage'\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}) \nGROUP BY content_id_sophora, content_titel, publishing_date, page_chapter2, page_chapter1, url, publishing_date ORDER BY 4 DESC \n))\nSELECT DISTINCT * FROM referrer JOIN articles ON referrer.content_id_sophora = articles.content_id_sophora ORDER BY Visits DESC LIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 }, "options": { "content": " " } }
 ]
}