{
 "title": "ML - Mock Up",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Profil", "query": "NDR Info, NDR Sport" },
   {
    "name": "Zeitraum",
    "query": "Heute, Gestern, Vor 7 Tagen, Vor 31 Tagen"
   },
   {
    "name": "Schaetzungszeitraum",
    "query": "Morgen, Nächste 7 Tage, Nächste 31 Tage"
   },
   { "name": "Plattform", "query": "Facebook" },
   { "name": "Vergleichsplattform", "query": "Instagram, Youtube, Tiktok" }
  ]
 },
 "panels": [
  {
   "title": "Sentiment Analyse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sentiment Analyse ${Plattform} | ${Zeitraum}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST([0.5, 0.7, 0.2, 0.3, 0.5, 0.4, 0.9]) AS score\r\n) AS dummy_data\r\n"
      },
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST([0.2, 0.4, 0.6, 0.4, 0.7, 0.1, 0.6]) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    },
    {
     "title": "Sentiment Analyse ${Vergleichsplattform} | ${Zeitraum}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST([0.5, 0.1, 0.2, 0.8, 0.3, 0.5, 0.8]) AS score\r\n) AS dummy_data\r\n"
      },
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST([0.8, 0.6, 0.1, 0.8, 0.9, 0.5, 0.4]) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Interaktionen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relative Interaktionen zum ersten abgeschlossenen Tag ${Plattform} | ${Zeitraum}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST([5,30,50,80,98,100,100]) AS score\r\n) AS dummy_data\r\n"
      },
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST([3,10,15,30,40,100,100]) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    },
    {
     "title": "Relative Interaktionen zum ersten abgeschlossenen Tag ${Vergleichsplattform} | ${Zeitraum}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST([10,50,60,70,88,98,100]) AS score\r\n) AS dummy_data\r\n"
      },
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST([20,40,65,75,80,95,100]) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    },
    {
     "title": "Durchschnittliche Interaktionen Pro Wochentag",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  score[0],score[1]\r\nFROM (\r\n  SELECT\r\n    score\r\n  FROM UNNEST([(RAND()*1000,\"Montag\"), (RAND()*1000,\"Dienstag\"), (RAND()*1000,\"Mittwoch\"), (RAND()*1000,\"Donnerstag\"), (RAND()*1000,\"Freitag\"), (RAND()*1000,\"Samstag\"), (RAND()*1000,\"Sonntag\")]) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Clustering",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Anzahl der Posts pro Stunde",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  CAST(number AS STRING) AS zeit,\r\n  ROUND(RAND() * 100) AS score\r\nFROM\r\n  UNNEST(GENERATE_ARRAY(1, 24)) AS number\r\n"
      }
     ]
    },
    {
     "title": "Interaktionen pro Stunde",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  CAST(number AS STRING) AS zeit,\r\n  ROUND(RAND() * 1000) AS score\r\nFROM\r\n  UNNEST(GENERATE_ARRAY(1, 24)) AS number\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Vorhersage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Followers ${Plattform} | ${Zeitraum}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST(ARRAY_REVERSE(GENERATE_ARRAY(100000,120000,20000/6))) AS score\r\n) AS dummy_data\r\n"
      },
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST(ARRAY_REVERSE(GENERATE_ARRAY(80000,100000,20000/6))) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    },
    {
     "title": "Followers ${Plattform} | ${Schaetzungszeitraum}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST(ARRAY_REVERSE(GENERATE_ARRAY(100000,120000,20000/6))) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    },
    {
     "title": "Followers ${Vergleichsplattform} | ${Zeitraum}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST(ARRAY_REVERSE(GENERATE_ARRAY(60000,70000,10000/6))) AS score\r\n) AS dummy_data\r\n"
      },
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST(ARRAY_REVERSE(GENERATE_ARRAY(40000,60000,20000/6))) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    },
    {
     "title": "Followers ${Vergleichsplattform} | ${Schaetzungszeitraum}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT\r\n    score,\r\n    DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL (ROW_NUMBER() OVER () - 1) DAY) AS zeit\r\n  FROM UNNEST(ARRAY_REVERSE(GENERATE_ARRAY(60000,70000,10000/6))) AS score\r\n) AS dummy_data\r\n"
      }
     ]
    }
   ]
  }
 ]
}