{
 "title": "SEO - Abfragen Optimieren (28.04.2025)",
 "time": { "from": "now", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Property",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": "Letzte 7 Tage, Letzte 28 Tage, Letzte 3 Monate, Letzte 6 Monate"
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "Redaktionen",
    "query": {}
   },
   {
    "name": "Unterkapitel",
    "query": {}
   },
   {
    "name": "searchconUrlTable",
    "query": {}
   },
   {
    "name": "bq_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_timeframe_end",
    "query": {}
   },
   {
    "name": "LRA_mapping",
    "query": {}
   },
   {
    "name": "KPI_query",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Hinweise",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "options": {
      "content": "**Piano-Daten**\n\n- Die Daten werden für die letzten abgeschlossenen Tage des gewählten Zeitraums angegeben.\n- Der heutige Tag wird also nicht einbezogen.\n- Daten können von Piano-Daten bei den Dashboards von AT Internet abweichen, wenn die Sophora-ID geändert wurde.\n- App-Daten sind nicht enthalten, zu sehen sind nur die Web-Daten."
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
     "options": {
      "content": "**GSC-Daten**\n\n- Die neuesten Daten aus der Google Search Console sind grundsätzlich drei Tage alt, da Google keine aktuelleren Daten anbietet.\n- Es fehlen also stets die Daten von heute, gestern und vorgestern.\n- Betrachtet werden die letzten sieben Tage ab diesem Zeitpunkt. "
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
     "options": {
      "content": "**Vergleichbarkeit der Daten**\n\n- In Piano wird der Traffic in Visits gezählt, in der Google Search Console in Klicks. Die zwei Metriken sind nicht identisch und weichen deshalb voneinander ab.\n"
     }
    }
   ]
  },
  { "title": "Leistungsübersicht (GSC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Leistung (Clicks)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\n  SELECT \"$KPI_query\" AS data\n), split_rows AS (\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\n  FROM data_string,\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\n), parsed_rows AS (\n  SELECT\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS time,\n    CAST(SPLIT(row_text, \"|\")[OFFSET(1)] AS FLOAT64) AS total,\n    CAST(SPLIT(row_text, \"|\")[OFFSET(2)] AS FLOAT64) AS search,\n    CAST(SPLIT(row_text, \"|\")[OFFSET(3)] AS FLOAT64) AS news,\n    CAST(SPLIT(row_text, \"|\")[OFFSET(4)] AS FLOAT64) AS discover,\n  FROM split_rows\n)\nSELECT\n  *, CASE \"$Zeitraum\"\n    WHEN \"Letzte 7 Tage\" THEN \"7 Tage\"\n    WHEN \"Letzte 28 Tage\" THEN \"28 Tage\"\n    WHEN \"Letzte 3 Monate\" THEN \"3 Monate\"\n    WHEN \"Letzte 6 Monate\" THEN \"6 Monate\"\n  END AS timeRange\nFROM\n  parsed_rows\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "location": "europe-west3", "project": "ndr-code-bi-dashboard", "rawSql": "SELECt ' ' as value" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT 'Clicks Total' as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT 'Impressions Total' as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT \"CTR Total\" as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT \"Total\" as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(1)] AS FLOAT64) AS clicks,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  SUM(clicks) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(5)] AS FLOAT64) AS impressions,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  SUM(impressions) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(9)] AS FLOAT64) AS CTR,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  AVG(CTR) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT \"Suche (Web, Bilder, Videos & News)\" as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(2)] AS FLOAT64) AS clicks,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  SUM(clicks) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(6)] AS FLOAT64) AS impressions,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  SUM(impressions) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(10)] AS FLOAT64) AS CTR,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  AVG(CTR) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT 'Google News' as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(3)] AS FLOAT64) AS clicks,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  SUM(clicks) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(7)] AS FLOAT64) AS impressions,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  SUM(impressions) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(11)] AS FLOAT64) AS CTR,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  AVG(CTR) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT 'Google Discover' as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(4)] AS FLOAT64) AS clicks,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  SUM(clicks) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(8)] AS FLOAT64) AS impressions,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  SUM(impressions) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH data_string AS(\r\n  SELECT \"$KPI_query\" AS data\r\n), split_rows AS (\r\n  SELECT TRIM(REPLACE(part, \"(\", \"\"), \")\") AS row_text\r\n  FROM data_string,\r\n  UNNEST(SPLIT(data, \" -ni- \")) AS part\r\n), parsed_rows AS (\r\n  SELECT\r\n    DATE(SPLIT(row_text, \"|\")[OFFSET(0)]) AS data_date,\r\n    CAST(SPLIT(row_text, \"|\")[OFFSET(12)] AS FLOAT64) AS CTR,\r\n  FROM split_rows\r\n)\r\nSELECT\r\n  AVG(CTR) as summe\r\nFROM\r\n  parsed_rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  { "title": "Top 100 Visits (Piano)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Top Web Artikel | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * EXCEPT(site_level2, page_chapter1, page_chapter2, rn, zeitraum) FROM SEO_scheduled_queries.top_web_articles\nWHERE zeitraum = \"$Zeitraum\" AND site_level2 = \"$LRA_mapping\" AND page_chapter1 = \"$Redaktionen\" AND page_chapter2 = \"$Unterkapitel\"\nORDER BY visits DESC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  { "title": "Top 100 Referrer (Piano)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Web | Top Referrer (nach Artikeln) | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * EXCEPT(site_level2, page_chapter1, page_chapter2, rn, zeitraum) FROM SEO_scheduled_queries.top_web_referrer\nWHERE zeitraum = \"$Zeitraum\" AND site_level2 = \"$LRA_mapping\" AND page_chapter1 = \"$Redaktionen\" AND page_chapter2 = \"$Unterkapitel\"\nORDER BY Visits DESC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  {
   "title": "Web | Top Referrer (Domains) | $Zeitraum",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 1, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * EXCEPT(site_level2, page_chapter1, page_chapter2, rn, zeitraum) FROM SEO_scheduled_queries.top_web_referrer_domains\nWHERE zeitraum = \"$Zeitraum\" AND site_level2 = \"$LRA_mapping\" AND page_chapter1 = \"$Redaktionen\" AND page_chapter2 = \"$Unterkapitel\"\nORDER BY visits DESC"
    }
   ]
  },
  {
   "title": "Web | Traffic Quellen | $Zeitraum",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 11, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * EXCEPT(site_level2, page_chapter1, page_chapter2, rn, zeitraum) FROM SEO_scheduled_queries.top_web_traffic_quellen\nWHERE zeitraum = \"$Zeitraum\" AND site_level2 = \"$LRA_mapping\" AND page_chapter1 = \"$Redaktionen\" AND page_chapter2 = \"$Unterkapitel\"\nORDER BY visits DESC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  { "title": "Top 100 Suchanfragen (GSC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Top Suchanfragen | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * EXCEPT(url_property, rn, zeitraum) FROM SEO_scheduled_queries.top_suchanfragen\nWHERE zeitraum = \"$Zeitraum\" AND url_property = \"$Property\"\nORDER BY Clicks DESC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  { "title": "Top 100 URLs (GSC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Top URLs | Gesamt | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Clicks, url FROM SEO_scheduled_queries.top_gsc_urls\nWHERE zeitraum = \"$Zeitraum\" AND url_property = \"$Property\" AND search_type = \"ALL\"\nORDER BY Clicks DESC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  {
   "title": "Top URLs | Suche (Web, Bilder, Videos & News) | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Clicks, url FROM SEO_scheduled_queries.top_gsc_urls\nWHERE zeitraum = \"$Zeitraum\" AND url_property = \"$Property\" AND search_type = \"WEB - IMAGE - VIDEO - NEWS\"\nORDER BY Clicks DESC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  {
   "title": "Top URLs | Discover | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Clicks, url FROM SEO_scheduled_queries.top_gsc_urls\nWHERE zeitraum = \"$Zeitraum\" AND url_property = \"$Property\" AND search_type = \"DISCOVER\"\nORDER BY Clicks DESC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 148 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  {
   "title": "Top URLs | Google News | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Clicks, url FROM SEO_scheduled_queries.top_gsc_urls\nWHERE zeitraum = \"$Zeitraum\" AND url_property = \"$Property\" AND search_type = \"GOOGLE_NEWS\"\nORDER BY Clicks DESC"
    }
   ]
  }
 ]
}