{
 "title": "WIP_SB_Monatsbericht_Online",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Sicht", "query": "NDR,Tagesschau" },
   {
    "name": "Monat",
    "query": "Januar : 1,Februar : 2,März : 3,April : 4,Mai : 5,Juni : 6,Juli : 7,August : 8,September : 9,Oktober : 10,November : 11,Dezember : 12"
   },
   { "name": "Jahr", "query": "2023,2024" },
   {
    "name": "siteArray",
    "query": {}
   },
   {
    "name": "siteArrayWeb",
    "query": {}
   },
   {
    "name": "SichtLang",
    "query": {}
   },
   { "name": "Datensicht", "query": "Verortungssicht,Erstellersicht" },
   {
    "name": "Trend",
    "query": {}
   },
   {
    "name": "visualisierung",
    "query": {}
   },
   {
    "name": "fussnote",
    "query": {}
   },
   {
    "name": "tableVisits",
    "query": {}
   },
   {
    "name": "grouper",
    "query": {}
   },
   {
    "name": "startDate",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "options": {
    "content": "### Dieses Dashboard hat erstmal nur explorative Zwecke, es ist *nicht* Teil eines Tickets.\n\nZuständigkeit: Silke"
   }
  },
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 17, "x": 2, "y": 4 },
   "options": {
    "content": "<center><font size=\"8\" style=\"font-weight:bold;\">$SichtLang Web + App + HbbTV</font></center>\r\n"
   }
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 3, "x": 1, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 3, "x": 4, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 4, "x": 7, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 4, "x": 11, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 6, "x": 15, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with by_day as(\r\n  SELECT\r\n    MAX(m_visits) as visits\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.NDR_total_visits`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(\r\n      year\r\n      from\r\n        date\r\n    ) = $Jahr\r\n  GROUP BY\r\n    date, site_level2\r\n)\r\nSELECt\r\n  SUM(visits) as visits\r\nfrom\r\n  by_day"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\n  SELECT\r\n    CONCAT(REPLACE(CAST(ROUND(avg(m_bounce_rate)*100,0) AS STRING),'.',','),'%') as entry\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.NDR_total_visits`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(\r\n      year\r\n      from\r\n        date\r\n    ) = $Jahr\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "  SELECT\r\n    --SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent, \r\n    AVG(m_time_spent_per_visits)/1000 AS time_spent,\r\n    '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.NDR_total_visits_site`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(year from  date) = $Jahr"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\n  SELECT\r\n    SUM(m_page_loads)/SUM(m_visits) as p_views\r\n   --SUM(m_impressions_per_visit)/sum(m_visits) as p_views\r\n   --avg(m_impressions_per_visit) as p_views \r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.NDR_total_visits_site`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(year from  date) = $Jahr\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\n  SELECT\r\n    SUM(m_av_playbacks) as p_views\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE\r\n    site_level2 IN $siteArrayWeb\r\n    --AND NOT (site_level2 LIKE '%app%')\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(year from  date) = $Jahr\r\n    AND (av_content_type = 'Video' OR av_content_type = 'video')\r\n    and bi_av_broadcasting_type = 'ondemand'\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\n  SELECT\r\n    SUM(m_av_playbacks) as p_views\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE\r\n    site_level2 IN $siteArrayWeb\r\n    --AND NOT (site_level2 LIKE '%app%')\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(year from  date) = $Jahr\r\n    AND (av_content_type = 'Audio' OR av_content_type = 'audio')#\r\n    and bi_av_broadcasting_type = 'ondemand'\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 1, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with aktuell as (\r\n  with by_day as(\r\n  SELECT\r\n    MAX(m_visits) as visits\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.total_visits`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(\r\n      year\r\n      from\r\n        date\r\n    ) = $Jahr\r\n  GROUP BY\r\n    date, site_level2\r\n)\r\nSELECt\r\n  SUM(visits) as visits,'$Sicht' as LRA\r\nfrom\r\n  by_day\r\n),\r\nvormonat as (\r\n  with by_day as(\r\n  SELECT\r\n    MAX(m_visits) as visits\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.total_visits`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date_add(date, INTERVAL 1 MONTH)) = $Monat\r\n    AND EXTRACT(\r\n      year\r\n      from\r\n        date_add(date, INTERVAL 1 MONTH)\r\n    ) = $Jahr\r\n  GROUP BY\r\n    date, site_level2\r\n)\r\nSELECt\r\n  SUM(visits) as visits,\r\n  '$Sicht' as LRA\r\nfrom\r\n  by_day\r\n)\r\nSELECT --(aktuell.visits - vormonat.visits)/vormonat.visits as differenz,\r\nCASE\r\nWHEN aktuell.visits / vormonat.visits - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell.visits / vormonat.visits - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell.visits / vormonat.visits - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END as differenz\r\nFROM aktuell\r\njoin vormonat on vormonat.LRA = aktuell.LRA\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with aktuell as (\r\n  \r\n  SELECT\r\n    avg(m_bounce_rate) as entry,'$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.total_visits`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(\r\n      year\r\n      from\r\n        date\r\n    ) = $Jahr\r\n),\r\nvormonat as (\r\n  SELECT\r\n    avg(m_bounce_rate) as entry,\r\n    '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.total_visits`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date_add(date, INTERVAL 1 MONTH)) = $Monat\r\n    AND EXTRACT(\r\n      year\r\n      from\r\n        date_add(date, INTERVAL 1 MONTH)) = $Jahr\r\n)\r\nSELECT --(aktuell.visits - vormonat.visits)/vormonat.visits as differenz,\r\nCASE\r\nWHEN aktuell.entry / vormonat.entry - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell.entry / vormonat.entry - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell.entry / vormonat.entry - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END as differenz\r\nFROM aktuell\r\njoin vormonat on vormonat.LRA = aktuell.LRA"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with aktuell as (\r\n  SELECT\r\n    AVG(m_time_spent_per_visits)/1000 AS time_spent,\r\n    '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.NDR_total_visits_site`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(year from  date) = $Jahr\r\n),\r\nvormonat as (\r\n  SELECT\r\n    AVG(m_time_spent_per_visits)/1000 AS time_spent,\r\n    '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.NDR_total_visits_site`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date_add(date, INTERVAL 1 MONTH)) = $Monat\r\n    AND EXTRACT(year from  date_add(date, INTERVAL 1 MONTH)) = $Jahr\r\n)\r\nSELECt CASE \r\n WHEN aktuell.time_spent / vormonat.time_spent - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell.time_spent / vormonat.time_spent - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell.time_spent / vormonat.time_spent - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END as differenz\r\nFROM aktuell join vormonat on aktuell.LRA = vormonat.LRA"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with aktuell as (\r\n    SELECT\r\n    SUM(m_page_loads)/SUM(m_visits) as p_views, '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.NDR_total_visits_site`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    --    AND CONTAINS_SUBSTR(page_chapter1, 'Alle Kapitel 1') \r\n    --AND CONTAINS_SUBSTR(page_chapter2, 'Alle Kapitel 2'  )\r\n    --AND CONTAINS_SUBSTR(sendungs_id, 'Alle Sendungs-ID')\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(year from  date) = $Jahr\r\n\r\n),\r\nvormonat as (\r\n    SELECT\r\n    SUM(m_page_loads)/SUM(m_visits) as p_views, '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.NDR_total_visits_site`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    --    AND CONTAINS_SUBSTR(page_chapter1, 'Alle Kapitel 1') \r\n    --AND CONTAINS_SUBSTR(page_chapter2, 'Alle Kapitel 2'  )\r\n    --AND CONTAINS_SUBSTR(sendungs_id, 'Alle Sendungs-ID')\r\n    AND EXTRACT(MONTH from date_add(date, INTERVAL 1 MONTH)) = $Monat\r\n    AND EXTRACT(year from  date_add(date, INTERVAL 1 MONTH)) = $Jahr\r\n)\r\nSELECt CASE \r\n WHEN aktuell.p_views / vormonat.p_views - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell.p_views / vormonat.p_views - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell.p_views / vormonat.p_views - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END as differenz\r\nFROM aktuell join vormonat on aktuell.LRA = vormonat.LRA"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with aktuell as (\r\n    SELECT\r\n    SUM(m_av_playbacks) as p_views, '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE\r\n    site_level2 IN $siteArrayWeb\r\n    --AND NOT (site_level2 LIKE '%app%')\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(year from  date) = $Jahr\r\n    AND (av_content_type = 'Video' OR av_content_type = 'video')\r\n    and bi_av_broadcasting_type = 'ondemand'\r\n\r\n),\r\nvormonat as (\r\n    SELECT\r\n    SUM(m_av_playbacks) as p_views, '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE\r\n    site_level2 IN $siteArrayWeb\r\n    AND EXTRACT(MONTH from date_add(date, INTERVAL 1 MONTH)) = $Monat\r\n    AND EXTRACT(year from  date_add(date, INTERVAL 1 MONTH)) = $Jahr\r\n    AND (av_content_type = 'Video' OR av_content_type = 'video')\r\n    and bi_av_broadcasting_type = 'ondemand'\r\n)\r\nSELECt CASE \r\n WHEN aktuell.p_views / vormonat.p_views - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell.p_views / vormonat.p_views - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell.p_views / vormonat.p_views - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END as differenz\r\nFROM aktuell join vormonat on aktuell.LRA = vormonat.LRA"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with aktuell as (\r\n  SELECT\r\n    SUM(m_av_playbacks) as p_views, '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE\r\n    site_level2 IN $siteArrayWeb\r\n    --AND NOT (site_level2 LIKE '%app%')\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(year from  date) = $Jahr\r\n    AND (av_content_type = 'Audio' OR av_content_type = 'audio')\r\n    and bi_av_broadcasting_type = 'ondemand'\r\n\r\n),\r\nvormonat as (\r\n    SELECT\r\n    SUM(m_av_playbacks) as p_views, '$Sicht' as LRA\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE\r\n    site_level2 IN $siteArrayWeb\r\n    AND EXTRACT(MONTH from date_add(date, INTERVAL 1 MONTH)) = $Monat\r\n    AND EXTRACT(year from  date_add(date, INTERVAL 1 MONTH)) = $Jahr\r\n    AND (av_content_type = 'Audio' OR av_content_type = 'audio')\r\n    and bi_av_broadcasting_type = 'ondemand'\r\n)\r\nSELECt CASE \r\n WHEN aktuell.p_views / vormonat.p_views - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell.p_views / vormonat.p_views - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell.p_views / vormonat.p_views - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END as differenz\r\nFROM aktuell join vormonat on aktuell.LRA = vormonat.LRA"
    }
   ]
  },
  { "type": "timeseries", "gridPos": { "h": 1, "w": 6, "x": 14, "y": 13 } },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 22, "x": 0, "y": 14 },
   "options": {
    "content": "<center><font size=\"8\" style=\"font-weight:bold;\"></font></center>\r\n"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 12, "x": 1, "y": 15 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with by_day as(\r\n  SELECT\r\n    MAX(m_visits) as visits,\r\n    date\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.total_visits`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND EXTRACT(MONTH from date) = $Monat\r\n    AND EXTRACT(\r\n      year\r\n      from\r\n        date\r\n    ) = $Jahr\r\n  GROUP BY\r\n    date, site_level2\r\n)\r\nSELECt\r\n sum(visits) as Visits,\r\n date,\r\n '$Sicht' as LRA,\r\n CONCAT('${Monat:text}',' ','$Jahr') as zeit\r\n --timestamp(date)\r\nfrom\r\n  by_day\r\ngroup by date\r\norder by date asc"
    }
   ]
  },
  {
   "title": "Top 5 Videos Web nach Sophora-ID",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 15 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT bi_av_content_id, sum(m_av_playbacks) as pb\r\nFROM `ndr-code-bi-dashboard.Piano.av`\r\nWHERE site_level2 IN $siteArrayWeb \r\nAND (av_content_type = 'Video' or av_content_type = 'video')\r\nAND EXTRACT(month from date) = $Monat\r\nAND EXTRACT(year from date) = $Jahr\r\nand bi_av_broadcasting_type = 'ondemand'\r\ngroup by bi_av_content_id\r\nORDER by pb DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Top 5 Audios Web nach Sophora-ID",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 23 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT bi_av_content_id, sum(m_av_playbacks) as pb\r\nFROM `ndr-code-bi-dashboard.Piano.av`\r\nWHERE site_level2 IN $siteArrayWeb \r\nAND (av_content_type = 'Audio' or av_content_type = 'audio')\r\nAND EXTRACT(month from date) = $Monat\r\nAND EXTRACT(year from date) = $Jahr\r\nand bi_av_broadcasting_type = 'ondemand'\r\ngroup by bi_av_content_id\r\nORDER by pb DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 1, "y": 24 },
   "options": {
    "content": "</br><center><font size=\"5\" style=\"font-weight:bold;\">Endgeräte nach Visits in %</font></center>\r\n"
   }
  },
  {
   "title": "Web + App + HbbTV",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 1, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(m_visits) as visits, \r\n  device_type \r\nFROM\r\n  --Piano.distro_joined_daily\r\n  Piano.NDR_distro\r\nWHERE \r\nsite_level2 IN $siteArray \r\nAND EXTRACT(month from date) = $Monat AND EXTRACT(year from date) = $Jahr\r\nAND device_type NOT LIKE '%N/A%'\r\nGROUP BY device_type \r\nORDER BY visits DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Web",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(m_visits) as visits, \r\n  device_type \r\nFROM\r\n  --Piano.distro_joined_daily\r\n  Piano.NDR_distro\r\nWHERE \r\nsite_level2 IN $siteArrayWeb \r\nAND EXTRACT(month from date) = $Monat AND EXTRACT(year from date) = $Jahr\r\nAND device_type NOT LIKE '%N/A%'\r\nGROUP BY device_type \r\nORDER BY visits DESC\r\nLIMIT 5"
    }
   ]
  },
  { "title": "Tabellen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 2, "y": 37 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Top 10 Inhaltsseiten (ohne Indexseiten)</font></center>\r\n"
   }
  },
  {
   "title": "nach Titel",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 2, "y": 39 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT content_titel, ANY_VALUE(content_id_sophora) as sophora, sum(m_visits) as m_visits\r\nFROM `ndr-code-bi-dashboard.Piano.articles`\r\nWHERE site_level2 IN $siteArray \r\nAND EXTRACT(month from date) = $Monat\r\nANd EXTRACT(year from date) = $Jahr\r\nAND objekt_typ NOT LIKE 'indexPage'\r\n    AND content_id_sophora NOT LIKE '%index%'\r\n    AND content_id_sophora NOT LIKE '%N/A%'\r\n    AND content_id_sophora NOT LIKE '%verteilseite%'\r\n    AND content_id_sophora NOT LIKE '%nachrichtenfeed%'\r\n    AND content_id_sophora NOT LIKE '%Aktueller-Titel%'\r\nGROUP BY content_titel\r\nORDER BY m_visits DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "nach Sophora-ID",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 14, "y": 39 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT content_id_sophora as sophora, sum(m_visits) as m_visits\r\nFROM `ndr-code-bi-dashboard.Piano.articles`\r\nWHERE site_level2 IN $siteArray \r\nAND EXTRACT(month from date) = $Monat\r\nANd EXTRACT(year from date) = $Jahr\r\nAND objekt_typ NOT LIKE 'indexPage'\r\n    AND content_id_sophora NOT LIKE '%index%'\r\n    AND content_id_sophora NOT LIKE '%N/A%'\r\n    AND content_id_sophora NOT LIKE '%verteilseite%'\r\n    AND content_id_sophora NOT LIKE '%nachrichtenfeed%'\r\n    AND content_id_sophora NOT LIKE '%Aktueller-Titel%'\r\nGROUP BY content_id_sophora\r\nORDER BY m_visits DESC\r\nLIMIT 10"
    }
   ]
  },
  { "title": "Langzeittrends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  { "title": "Datensicht", "type": "volkovlabs-variable-panel", "gridPos": { "h": 3, "w": 4, "x": 2, "y": 52 } },
  { "title": "Visualisierung", "type": "volkovlabs-variable-panel", "gridPos": { "h": 3, "w": 6, "x": 6, "y": 52 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 52 },
   "options": {
    "content": "</br></br><font size=\"2\" >$fussnote</font>\r\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 2, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "location": "europe-west3", "project": "ndr-code-bi-dashboard", "rawSql": "SELECt '$Datensicht'" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 5, "x": 18, "y": 55 },
   "options": {
    "content": "Zu klären:\r\n\r\nVerortungssicht:\r\n- **Nachrichten Startseite**\r\n  - Indexseiten werden nicht von Piano in bigQuery ingestiert\r\n- **Nachrichten Übergreifend**\r\n  - bekomme ich einfach nicht reproduziert, bei identisch zu Data Query gesetzten Filtern starke Abweichung\r\n  - vergleiche in Data Query summe Visits Sep. 2024 3.322.826 vs. in Big Query, Tabelle articles 1.115.985\r\n  - Workaround nicht möglich wegen o.g. fehlerhafter Daten\r\n  - beste Näherung aktuell: Filterung nach Kapitel 1 &2 aber nicht nach Content ID\r\n\r\n\r\nErstellersicht:\r\n- **NDR Info Crossmediale Marke Web**\r\n  - Marke bzw. crossbrand läuft nicht in bigQuery ein"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 15, "w": 16, "x": 2, "y": 57 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with by_day as(\r\n  SELECT\r\n    CASE '$Datensicht'\r\n      WHEn 'Verortungssicht' THEN \r\n        CASE WHEN '$Trend' = 'Nachrichten übergreifend' THEN MAX(m_visits)\r\n        ELSE MAX(m_visits) \r\n        END\r\n      WHEN 'Erstellersicht' THEN SUM(m_visits)\r\n    END as visits,\r\n    date\r\n  FROM\r\n    `ndr-code-bi-dashboard.Piano.${tableVisits}`\r\n  WHERE\r\n    site_level2 IN $siteArray\r\n    AND $visualisierung\r\n    --ANd date >= DATE(2023,04,01)\r\n    AND $startDate\r\n    ANd date <= LAST_DAY(DATE($Jahr,$Monat,01), MONTH)\r\n  GROUP BY\r\n    $grouper\r\n)\r\nSELECT\r\n sum(visits) as Visits,\r\n DATE_TRUNC(date, MONTH) as date,\r\n '$Trend' as trend\r\nfrom\r\n  by_day\r\ngroup by date\r\norder by date asc"
    }
   ]
  },
  { "type": "timeseries", "gridPos": { "h": 9, "w": 6, "x": 7, "y": 72 } }
 ]
}