{
 "title": "Google Trends Erweiterung",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Category",
    "query": {}
   },
   {
    "name": "Keyword",
    "query": {}
   }
  ]
 },
 "panels": [
  { "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": "<font size=\"8\" style=\"color:rgb(255, 0, 0);\">Google Trends</font><font size=\"8\"></font>"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Schlagzeilen",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT timestamp, volume, keyword \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_timelines_r` \nWHERE category = \"$Category\"\nAND keyword = \"$Keyword\"\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Schlagzeilen",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_r` \nWHERE \n--  category ='Business'\n  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND timestamp = \n  (SELECT MAX(timestamp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_r`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Suchtrends des Tages | gestern",
   "type": "table",
   "gridPos": { "h": 29, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  keyword as trend, rank\nFROM\n  `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_r`\n--timestamp = DATE_SUB(CURRENT_DATE(), INTERVAL 0 DAY) \nWHERE  EXTRACT(DATE FROM DATETIME(timestamp, \"Europe/Berlin\")) = EXTRACT(DATE FROM DATETIME_SUB(CURRENT_DATE(\"Europe/Berlin\"), INTERVAL 1 DAY))  \nAND category = \"Headlines\"\n--DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY),\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Business",
   "type": "table",
   "gridPos": { "h": 19, "w": 14, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Sport",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Unterhaltung",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 54 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trend | Echtzeit | Wissen & Technik",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 65 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Gesundheit",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 76 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  }
 ]
}