{
 "title": "Podcast NDR",
 "description": "New Version, 2.0 (Abfragen Optimieren)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "label": "LRA:",
    "query": {}
   },
   {
    "name": "datenstand",
    "query": {}
   },
   {
    "name": "Podcast_title",
    "query": {}
   },
   {
    "name": "AllePodcastsCondition",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "Bereich",
    "label": "Bereich:",
    "query": {}
   },
   {
    "name": "Podcast",
    "label": "Podcast:",
    "query": {}
   },
   {
    "name": "Episode",
    "label": "Episode:",
    "query": {}
   },
   { "name": "filled_size_big", "query": "10" },
   { "name": "filled_size", "query": "20" },
   {
    "name": "filled_size_headline",
    "query": {}
   },
   {
    "name": "filled_size_headline_small",
    "query": {}
   },
   {
    "name": "broadcast_id_branding",
    "query": {}
   },
   {
    "name": "Image",
    "query": {}
   },
   {
    "name": "type",
    "query": {}
   },
   {
    "name": "NDR_default_image",
    "query": {}
   },
   {
    "name": "lastUpdate",
    "query": {}
   },
   {
    "name": "mapping_dataset",
    "query": {}
   },
   {
    "name": "MDR_default_image",
    "query": {}
   },
   {
    "name": "AllePodcasts",
    "label": "Podcastsuche:",
    "query": {}
   },
   {
    "name": "number_of_days",
    "query": {}
   },
   {
    "name": "dataset_suffix",
    "query": {}
   },
   {
    "name": "episode_dataset",
    "query": {}
   },
   {
    "name": "platform_dataset",
    "query": {}
   },
   {
    "name": "profiles_dataset",
    "query": {}
   },
   {
    "name": "hinweis",
    "query": {}
   },
   {
    "name": "fromDay",
    "query": {}
   },
   {
    "name": "toDay_NDR",
    "query": {}
   },
   {
    "name": "zeitraum_NDR",
    "query": {}
   },
   {
    "name": "HeuteDatum",
    "query": {}
   },
   {
    "name": "episodenschnitt_condition",
    "query": {}
   },
   {
    "name": "delay_text",
    "query": {}
   },
   {
    "name": "zeitraum_MDR",
    "query": {}
   },
   {
    "name": "zeitraum",
    "query": {}
   },
   {
    "name": "toDay_MDR",
    "query": {}
   },
   {
    "name": "toDay",
    "query": {}
   },
   {
    "name": "datenstand_not_formated",
    "query": {}
   },
   {
    "name": "Plattformen",
    "query": {}
   },
   { "name": "import_check", "query": "check" },
   {
    "name": "episodes_lim",
    "query": {}
   },
   {
    "name": "max_date",
    "query": {}
   },
   {
    "name": "Tage",
    "label": "Anzahl Tage nach VÖ",
    "query": "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99"
   },
   {
    "name": "Tage_content_lifetime",
    "label": "Anzahl Tage nach VÖ",
    "query": "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99"
   },
   {
    "name": "avgEpisodesQueryCols",
    "query": {}
   },
   {
    "name": "avg_avgEpisodesQueryCols",
    "query": {}
   },
   {
    "name": "avgEpisodesQuery",
    "label": "query_test",
    "query": {}
   },
   {
    "name": "avgEpisodesQueryForPodcastTable",
    "label": "query_test",
    "query": {}
   },
   {
    "name": "copy_of_avgEpisodesQueryForPodcastTable",
    "label": "query_test",
    "query": {}
   },
   {
    "name": "avgOfavgEpisodesQuery",
    "label": "query_test",
    "query": {}
   },
   { "name": "PubDate", "label": "Pub Date Version", "query": "Pub Date 6" },
   {
    "name": "pub_date_field",
    "query": {}
   },
   {
    "name": "podcast_ids",
    "query": {}
   },
   {
    "name": "src_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:rgba(38, 113, 198); color: white; text-align: center; vertical-align: middle; padding: 20px 0; margin-top: 0px; font-size: 15pt;\">\n  <font color=\"#FFFFFF\" size=\"5\">Servicemeldung:</font> <br>\n  <font color=\"#FFFFFF\" size=\"3\">\n    Informationen zu Auffälligkeiten und Datenproblemen dokumentieren wir bei uns im Audio-Blog: \n    <a href=\"https://ndr.coyocloud.com/pages/medienforschung-hoerfunk/apps/blog/blog\" style=\"color: white;\">LINK</a> <br>\n  </font>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 1, "x": 12, "y": 4 },
   "options": {
    "content": "<img \n  src=\"${src_url}\" \n  alt=\"Tracking Pixel\" \n  width=\"1\" \n  height=\"1\" \n  style=\"display:none;\"\n/>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 13, "y": 4 }, "options": { "content": " ${hinweis}" } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$Image\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('$Podcast_title'))), '$Podcast_title'), \nFROM(\nSELECT '$Podcast_title' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('QApps'),0)), 'Apps')\nFROM(\nSELECT 'Apps' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt im Analysezeitraum",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT \n    SUM(m_zugriffe_1) AS summe \n  FROM \n    $episode_dataset\n  WHERE \n    broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT\n    SUM(m_zugriffe_1) AS summe,\n  FROM \n    $episode_dataset as ed\n  LEFT JOIN \n    $profiles_dataset AS pd\n  USING(podcast_title)\n  LEFT JOIN \n    Piano.NDR_podcast_episode_publication_dates \n  USING (headline)\n  WHERE \n    ed.broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    AND $episodenschnitt_condition\n    AND DATE(publication_date_6) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "description": "Nutzungsverteilung im Nutzungszeitraum neu veröffentlichter\nEpisoden vs. älterer Episoden (Longtail) an Zugriffen gesamt.",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 9 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SUM(CASE WHEN DATE(publication_date_6) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\") THEN m_zugriffe_1 ELSE 0 END) AS new_episode_sum,\n  SUM(CASE WHEN DATE(publication_date_6) NOT BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\") THEN m_zugriffe_1 ELSE 0 END) AS longtail_sum,\nFROM \n  $episode_dataset as ed\nLEFT JOIN \n  $profiles_dataset AS pd\nUSING(podcast_title)\nLEFT JOIN \n  Piano.NDR_podcast_episode_publication_dates \nUSING (headline)\nWHERE \n  ed.broadcast_id IN ($podcast_ids)\n  AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n  AND $episodenschnitt_condition"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('ARD Audiothek')), 'ARD Audiothek')\nFROM(\nSELECT 'ARD Audiothek' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Spotify-Daten ab 01.01.2021 verfügbar (ab August 2023 auf Basis von Serverlogfiles, für ältere Zeiträume auf Basis von Streams ab 60 Sekunden)",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('Spotify')), 'Spotify')\nFROM(\nSELECT 'Spotify' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size - CHAR_LENGTH('Apple Podcasts'))), 'Apple Podcasts')\nFROM(\nSELECT 'Apple Podcasts' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT\n    SUM(m_zugriffe_1) AS summe\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND platform = \"ARD Audiothek\" \n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT\n    SUM(m_zugriffe_1) AS summe\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND platform = \"Spotify\" \n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT\n    SUM(m_zugriffe_1) AS summe\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND platform = \"Apple Podcasts\" \n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": {
    "content": "Letztes Update: <br> \r\n${lastUpdate}\r\n<br> <br> \r\nDatenstand: <br> \r\n01.01.2021 – ${datenstand}"
   }
  },
  {
   "type": "stat",
   "description": "Durchschnitt pro Episode für die im ausgewählten Analysezeitraum veröffentlichten Episoden.",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT\n    SUM(m_zugriffe_1)/COUNT(DISTINCT headline) AS summe,\n  FROM \n    $episode_dataset as ed\n  LEFT JOIN \n    $profiles_dataset AS pd\n  USING(podcast_title)\n  LEFT JOIN \n    Piano.NDR_podcast_episode_publication_dates \n  USING (headline)\n  WHERE \n    ed.broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    AND $episodenschnitt_condition\n    AND DATE(publication_date_6) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "description": "Zugriffe über ausgewählte Apps auf Basis von User Agents. Im Vergleich zu den eigenen Metriken der jeweiligen Plattform-Anbieter kann es aufgrund verschiedener Messmethoden zu Abweichungen kommen.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n    SUM(m_zugriffe_1) AS summe,\n    platform\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT\n    COUNT(DISTINCT headline) AS summe,\n  FROM \n    $episode_dataset as ed\n  LEFT JOIN \n    $profiles_dataset AS pd\n  USING(podcast_title)\n  LEFT JOIN \n    Piano.NDR_podcast_episode_publication_dates \n  USING (headline)\n  WHERE \n    ed.broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    AND $episodenschnitt_condition\n    AND DATE(publication_date_6) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Nutzungsanteil der im Analysezeitraum neu veröffentlichten Episoden an den gesamten Zugriffen.",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"), \"%\")FROM\n(\n  SELECT\n    (SUM(CASE WHEN DATE(publication_date_6) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\") THEN m_zugriffe_1 ELSE 0 END)/SUM(m_zugriffe_1)) * 100 AS summe,\n  FROM \n    $episode_dataset as ed\n  LEFT JOIN \n    $profiles_dataset AS pd\n  USING(podcast_title)\n  LEFT JOIN \n    Piano.NDR_podcast_episode_publication_dates \n  USING (headline)\n  WHERE \n    ed.broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    AND $episodenschnitt_condition\n)"
    }
   ]
  },
  {
   "title": "Ø neue Episoden nach Tagen",
   "type": "volkovlabs-echarts-panel",
   "description": "Durchschnitt pro Episode für die im ausgewählten Analysezeitraum neu veröffentlichten Episoden nach X Tagen. ACHTUNG: Die Stichprobe der Episoden variiert je nach betrachtetem Zeitintervall. So ist unter Umständen auch ein kleinerer Wert für 56 Tage als für 28 Tage möglich. Für robuste Ergebnisse bitte einen möglichst langen Analysezeitraum wählen.",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 15 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH raw_data AS (\n  -- This is the raw data, including either all episodes or only the selected ones, ensuring their podcasts are included in the average calculation, and the publication date falls within the selected time period\n  SELECT \n    date,\n    headline, \n    SUM(IFNULL(m_zugriffe_1,0)) AS zugriffe,\n    publication_date_6,\n  FROM $episode_dataset AS episode_dataset\n  LEFT JOIN $profiles_dataset AS pd\n  USING(podcast_title)\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates \n  USING (headline)\n  WHERE \n    (\"$Bereich\" = \"Alle Bereiche\" OR episode_dataset.branding = \"$Bereich\")\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    AND publication_date_6 BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    AND $episodenschnitt_condition \n  GROUP BY date, headline, publication_date_6\n), ranked_episodes AS(\n  -- This step ranks episodes according to their total zugriffe across the entire period\n  SELECT\n    headline,\n    publication_date_6,\n    RANK() OVER(ORDER BY zugriffe DESC) AS rang\n  FROM (\n  SELECT \n    headline,\n    publication_date_6,\n    SUM(zugriffe) AS zugriffe,\n  FROM raw_data\n  GROUP BY headline, publication_date_6\n  )\n), date_range AS (\n  -- Create a full date range to handle cases where episodes have no zugriffe on some days\n  SELECT \n    date \n  FROM UNNEST(GENERATE_DATE_ARRAY(DATE('${__from:date}', \"Europe/Berlin\"), DATE('${__to:date}', \"Europe/Berlin\"))) AS date\n), filtered_date_range AS (\n  -- Join date range with episodes, keeping only dates between publication and max date (to include the 5-day delay) \n  SELECT date, headline, publication_date_6, rang\n  FROM date_range\n  JOIN ranked_episodes\n  ON date >= publication_date_6 AND date <= \"$max_date\"\n), cumulative_sum_ranked_episodes AS (\nSELECT \n  -- Calculate the cumulative sum of zugriffe and the number of days since publication for each episode\n  filtered_date_range.headline, \n  DATE_DIFF(filtered_date_range.date, filtered_date_range.publication_date_6, DAY) + 1 AS days_since_pub,\n  SUM(IFNULL(zugriffe, 0)) OVER (PARTITION BY filtered_date_range.headline ORDER BY filtered_date_range.date) AS summe, \n  \"${type}\" AS type, \n  filtered_date_range.rang\nFROM filtered_date_range\nLEFT JOIN raw_data\nON filtered_date_range.date = raw_data.date AND REPLACE(filtered_date_range.headline, \"'\", \"\") = REPLACE(raw_data.headline, \"'\", \"\")\n), avg_data AS (\n  -- Compute the daily average zugriffe across all episodes for days up to max_day_since_pub\n  SELECT \n    \"Durchschnitt alle neuen Episoden\" AS headline,\n    days_since_pub,\n    AVG(summe) AS summe,\n    \"${type}\" AS type,\n    0 AS rang\n  FROM cumulative_sum_ranked_episodes\n  GROUP BY days_since_pub\n)\nSELECT CONCAT(\"nach \", days_since_pub, \" Tagen\") AS period, ROUND(summe) AS value, days_since_pub AS rank  FROM avg_data\nWHERE days_since_pub IN (7, 14, 28, 56, 91)\nORDER by rank DESC\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 }, "options": { "content": "${delay_text}" } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Bereich: $Bereich'),0)), 'Bereich: $Bereich')\nFROM(\nSELECT 'Bereich: $Bereich' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Ausgewählte Episoden'),0)), 'Ausgewählte Episoden')\nFROM(\nSELECT 'Ausgewählte Episoden' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt aller Podcast-Reihen im ausgewählten Bereich",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT\n    SUM(m_zugriffe_1) AS summe\n  FROM \n    $episode_dataset\n  WHERE\n    (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt für die in der Navigation unter Episode ausgewählten Audios",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT \n    SUM(m_zugriffe_1) AS summe \n  FROM \n    $episode_dataset\n  WHERE \n    (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Durchschnitt pro Episode für die die in der Navigation unter Episode ausgewählten Audios ",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT \n    SAFE_DIVIDE(SUM(m_zugriffe_1),COUNT(DISTINCT headline)) AS summe \n  FROM \n    $episode_dataset\n  WHERE \n    (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "title": "Zugriffe pro Tag für \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n    date,\n    SUM(CASE WHEN platform = 'ARD Audiothek' THEN m_zugriffe_1 ELSE 0 END) AS ard_summe,\n    SUM(CASE WHEN platform = 'Apple Podcasts' THEN m_zugriffe_1 ELSE 0 END) AS apple_summe,\n    SUM(CASE WHEN platform = 'Spotify' THEN m_zugriffe_1 ELSE 0 END) AS spotify_summe,\n    SUM(CASE WHEN platform NOT IN ('ARD Audiothek', 'Spotify', 'Apple Podcasts') THEN m_zugriffe_1 ELSE 0 END) AS rest_summe,\n    SUM(m_zugriffe_1) as zugriffe,\n    \"${type}\" as type,\n    DATE_DIFF(DATE('${__to:date}', \"Europe/Berlin\"),DATE('${__from:date}', \"Europe/Berlin\"),DAY) + 1 as timeRange\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY date\nORDER BY date ASC"
    }
   ]
  },
  {
   "title": "Top 3 Episoden von \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  headline,\n  SUM(m_zugriffe_1) AS zugriffe,\nFROM $episode_dataset\nWHERE \n  broadcast_id IN ($podcast_ids)\n  AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY headline\nORDER BY zugriffe DESC\nLIMIT 3"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 38 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Zugriffe pro Tag für ausgewählte Episoden von \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "description": "Abgetragen sind die absoluten Zugriffe der jeweiligen Episode am\njeweiligen Tag. Als Standard werden die Top 8 Episoden ausgewiesen; über die Episodenauswahl\nim Filtermenü können stattdessen bis zu 8 spezifische Episoden ausgewiesen werden.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH raw_data AS (\r\n  SELECT \r\n    date,\r\n    headline, \r\n    SUM(IFNULL(m_zugriffe_1,0)) AS zugriffe,\r\n    publication_date_6,\r\n  FROM $episode_dataset\r\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates \r\n  USING (headline)\r\n  WHERE \r\n    (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\r\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\r\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n  GROUP BY date, headline, publication_date_6\r\n), ranked_episodes AS(\r\n  SELECT\r\n    headline,\r\n    publication_date_6,\r\n    RANK() OVER(ORDER BY zugriffe DESC) AS rang\r\n  FROM (\r\n  SELECT \r\n    headline,\r\n    publication_date_6,\r\n    SUM(zugriffe) AS zugriffe,\r\n  FROM raw_data\r\n  GROUP BY headline, publication_date_6\r\n  )\r\n  QUALIFY rang <= 8\r\n), date_range AS (\r\n  SELECT \r\n    date \r\n  FROM UNNEST(GENERATE_DATE_ARRAY(DATE('${__from:date}', \"Europe/Berlin\"), DATE('${__to:date}', \"Europe/Berlin\"))) AS date\r\n), filtered_date_range AS (\r\n  SELECT date, headline, rang\r\n  FROM date_range\r\n  JOIN ranked_episodes\r\n  ON date >= publication_date_6 AND date <= \"$max_date\"\r\n)\r\nSELECT \r\n  filtered_date_range.headline, \r\n  filtered_date_range.date, \r\n  IFNULL(zugriffe,0) AS zugriffe, \r\n  \"${type}\" AS type, \r\n  filtered_date_range.rang\r\nFROM filtered_date_range\r\nLEFT JOIN raw_data\r\nON filtered_date_range.date = raw_data.date AND REPLACE(filtered_date_range.headline, \"'\", \"\") = REPLACE(raw_data.headline, \"'\", \"\")\r\nORDER BY headline, date ASC"
    }
   ]
  },
  {
   "title": "Tage nach Erstveröffentlichung für ausgewählte Episoden von \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "description": "Abgetragen sind die kumulierten Zugriffe nach 1, 2, ..., X Tagen für im\nausgewählten Analysezeitraum neu veröffentlichte Episoden. Der Durchschnitt bezieht sich auf\nsämtliche neue Episoden, nicht nur auf die in der Grafik einzeln dargestellten. Als Standard\nwerden die Top 8 neuen Episoden ausgewiesen; über die Episodenauswahl im Filtermenü können\nstattdessen bis zu 8 spezifische Episoden ausgewiesen werden.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH raw_data AS (\r\n  -- This is the raw data, including either all episodes or only the selected ones, ensuring their podcasts are included in the average calculation, and the publication date falls within the selected time period\r\n  SELECT \r\n    date,\r\n    headline, \r\n    SUM(IFNULL(m_zugriffe_1,0)) AS zugriffe,\r\n    publication_date_6,\r\n  FROM $episode_dataset AS episode_dataset\r\n  LEFT JOIN $profiles_dataset AS pd\r\n  USING(podcast_title)\r\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates \r\n  USING (headline)\r\n  WHERE \r\n    (\"$Bereich\" = \"Alle Bereiche\" OR episode_dataset.branding = \"$Bereich\")\r\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\r\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n    AND publication_date_6 BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n    AND $episodenschnitt_condition \r\n  GROUP BY date, headline, publication_date_6\r\n), ranked_episodes AS(\r\n  -- This step ranks episodes according to their total zugriffe across the entire period\r\n  SELECT\r\n    headline,\r\n    publication_date_6,\r\n    RANK() OVER(ORDER BY zugriffe DESC) AS rang\r\n  FROM (\r\n  SELECT \r\n    headline,\r\n    publication_date_6,\r\n    SUM(zugriffe) AS zugriffe,\r\n  FROM raw_data\r\n  GROUP BY headline, publication_date_6\r\n  )\r\n), date_range AS (\r\n  -- Create a full date range to handle cases where episodes have no zugriffe on some days\r\n  SELECT \r\n    date \r\n  FROM UNNEST(GENERATE_DATE_ARRAY(DATE('${__from:date}', \"Europe/Berlin\"), DATE('${__to:date}', \"Europe/Berlin\"))) AS date\r\n), filtered_date_range AS (\r\n  -- Join date range with episodes, keeping only dates between publication and max date (to include the 5-day delay) \r\n  SELECT date, headline, publication_date_6, rang\r\n  FROM date_range\r\n  JOIN ranked_episodes\r\n  ON date >= publication_date_6 AND date <= \"$max_date\"\r\n), cumulative_sum_ranked_episodes AS (\r\nSELECT \r\n  -- Calculate the cumulative sum of zugriffe and the number of days since publication for each episode\r\n  filtered_date_range.headline, \r\n  DATE_DIFF(filtered_date_range.date, filtered_date_range.publication_date_6, DAY) + 1 AS days_since_pub,\r\n  SUM(IFNULL(zugriffe, 0)) OVER (PARTITION BY filtered_date_range.headline ORDER BY filtered_date_range.date) AS summe, \r\n  \"${type}\" AS type, \r\n  filtered_date_range.rang\r\nFROM filtered_date_range\r\nLEFT JOIN raw_data\r\nON filtered_date_range.date = raw_data.date AND REPLACE(filtered_date_range.headline, \"'\", \"\") = REPLACE(raw_data.headline, \"'\", \"\")\r\n), top_episodes AS (\r\n  -- Top episodes\r\n  SELECT * FROM cumulative_sum_ranked_episodes\r\n  WHERE rang <= 8\r\n), max_days_since_pub_top_episodes AS(\r\n  -- Retrieve the highest days_since_pub value from top episodes\r\n  SELECT MAX(days_since_pub) AS max_day_since_pub\r\n  FROM top_episodes\r\n), avg_data AS (\r\n  -- Compute the daily average zugriffe across all episodes for days up to max_day_since_pub\r\n  SELECT \r\n    \"Durchschnitt alle neuen Episoden\" AS headline,\r\n    days_since_pub,\r\n    AVG(summe) AS summe,\r\n    \"${type}\" AS type,\r\n    0 AS rang\r\n  FROM cumulative_sum_ranked_episodes\r\n  --JOIN max_days_since_pub_top_episodes\r\n  --ON days_since_pub <= max_day_since_pub\r\n  GROUP BY days_since_pub\r\n), final_data AS(\r\n  -- Final data\r\n  SELECT * FROM top_episodes\r\n  WHERE days_since_pub <= $Tage_content_lifetime\r\n  UNION ALL\r\n  SELECT * FROM avg_data\r\n  WHERE days_since_pub <= $Tage_content_lifetime\r\n), day_zero AS(\r\n  -- Create day zero to ensure all episodes and the average start at 0\r\n  SELECT DISTINCT\r\n    headline, \r\n    0 AS days_since_pub,\r\n    0 AS summe, \r\n    \"${type}\" AS type, \r\n    rang\r\n  FROM final_data\r\n)\r\nSELECT * FROM final_data\r\nUNION DISTINCT\r\nSELECT * FROM day_zero\r\nORDER BY headline, days_since_pub ASC"
    }
   ]
  },
  {
   "title": "Episoden",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  podcast_title,\n  headline,\n  publication_date_6,\n  SUM(m_zugriffe_1) as zugriffe\nFROM $episode_dataset\nLEFT JOIN Piano.NDR_podcast_episode_publication_dates \nUSING (headline)\nWHERE \n  (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n  AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\n  AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY podcast_title, headline, publication_date_6\nORDER BY zugriffe DESC"
    }
   ]
  },
  {
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n    podcast_title AS Title,\n    SUM(CASE WHEN platform = 'ARD Audiothek' THEN m_zugriffe_1 ELSE NULL END) AS ard_summe,\n    SUM(CASE WHEN platform = 'Apple Podcasts' THEN m_zugriffe_1 ELSE NULL END) AS apple_summe,\n    SUM(CASE WHEN platform = 'Spotify' THEN m_zugriffe_1 ELSE NULL END) AS spotify_summe,\n    SUM(m_zugriffe_1) AS zugriffe,\nFROM \n    $platform_dataset AS platform_table\nLEFT JOIN $profiles_dataset AS profiles_table\nON platform_table.broadcast_id = profiles_table.broadcast_id[0]\nWHERE\n    platform_table.broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY podcast_title\nORDER BY zugriffe DESC"
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 74 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Durchschnitt pro Episode für neu veröffentlichte Episoden",
   "type": "table",
   "description": "Abgetragen sind die kumulierten Zugriffe nach 7, 14, 28, 56 und 91 Tagen\nfür im ausgewählten Analysezeitraum neu veröffentlichte Episoden aller ausgewählten Podcasts.\nÜber das Dropdown-Menü oben links kann ein individueller Zeitraum zwischen 1 und 99 Tagen\ndefiniert werden. ACHTUNG: Die Stichprobe der Episoden variiert je nach betrachtetem\nZeitintervall. So ist unter Umständen auch ein kleinerer Wert für 56 Tage als für 28 Tage möglich.\nFür robuste Ergebnisse bitte einen möglichst langen Analysezeitraum wählen.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH raw_data AS (\r\n  -- This is the raw data, including either all episodes or only the selected ones, ensuring their podcasts are included in the average calculation, and the publication date falls within the selected time period\r\n  SELECT \r\n    date,\r\n    podcast_title,\r\n    headline, \r\n    SUM(IFNULL(m_zugriffe_1,0)) AS zugriffe,\r\n    publication_date_6,\r\n  FROM $episode_dataset AS episode_dataset\r\n  LEFT JOIN $profiles_dataset AS pd\r\n  USING(podcast_title)\r\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates \r\n  USING (headline)\r\n  WHERE \r\n    (\"$Bereich\" = \"Alle Bereiche\" OR episode_dataset.branding = \"$Bereich\")\r\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\r\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n    AND publication_date_6 BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n    AND $episodenschnitt_condition \r\n  GROUP BY date, podcast_title, headline, publication_date_6\r\n), ranked_episodes AS(\r\n  -- This step ranks episodes according to their total zugriffe across the entire period\r\n  SELECT\r\n    podcast_title,\r\n    headline,\r\n    publication_date_6,\r\n    RANK() OVER(ORDER BY zugriffe DESC) AS rang\r\n  FROM (\r\n  SELECT\r\n    podcast_title, \r\n    headline,\r\n    publication_date_6,\r\n    SUM(zugriffe) AS zugriffe,\r\n  FROM raw_data\r\n  GROUP BY podcast_title, headline, publication_date_6\r\n  )\r\n), date_range AS (\r\n  -- Create a full date range to handle cases where episodes have no zugriffe on some days\r\n  SELECT \r\n    date \r\n  FROM UNNEST(GENERATE_DATE_ARRAY(DATE('${__from:date}', \"Europe/Berlin\"), DATE('${__to:date}', \"Europe/Berlin\"))) AS date\r\n), filtered_date_range AS (\r\n  -- Join date range with episodes, keeping only dates between publication and max date (to include the 5-day delay) \r\n  SELECT date, podcast_title, headline, publication_date_6, rang\r\n  FROM date_range\r\n  JOIN ranked_episodes\r\n  ON date >= publication_date_6 AND date <= \"$max_date\"\r\n), cumulative_sum_ranked_episodes AS (\r\nSELECT \r\n  -- Calculate the cumulative sum of zugriffe and the number of days since publication for each episode\r\n  filtered_date_range.podcast_title,\r\n  filtered_date_range.headline, \r\n  DATE_DIFF(filtered_date_range.date, filtered_date_range.publication_date_6, DAY) + 1 AS days_since_pub,\r\n  SUM(IFNULL(zugriffe, 0)) OVER (PARTITION BY filtered_date_range.headline ORDER BY filtered_date_range.date) AS summe, \r\n  \"${type}\" AS type, \r\n  filtered_date_range.rang\r\nFROM filtered_date_range\r\nLEFT JOIN raw_data\r\nON filtered_date_range.date = raw_data.date AND REPLACE(filtered_date_range.headline, \"'\", \"\") = REPLACE(raw_data.headline, \"'\", \"\")\r\n), avg_data AS (\r\n  -- Compute the daily average zugriffe across all episodes for days up to max_day_since_pub\r\n  SELECT \r\n    podcast_title,\r\n    days_since_pub,\r\n    AVG(summe) AS summe,\r\n    \"${type}\" AS type,\r\n    0 AS rang\r\n  FROM cumulative_sum_ranked_episodes\r\n  GROUP BY podcast_title,days_since_pub\r\n)\r\nSELECT \r\n  podcast_title,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 7 THEN summe END)) AS days7,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 14 THEN summe END)) AS days14,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 28 THEN summe END)) AS days28,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 56 THEN summe END)) AS days56,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 91 THEN summe END)) AS days91,\r\n  ROUND(MAX(CASE WHEN days_since_pub = $Tage THEN summe END)) AS daysCustom,\r\nFROM avg_data\r\nGROUP BY podcast_title\r\nORDER BY podcast_title\r\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH raw_data AS (\r\n  -- This is the raw data, including either all episodes or only the selected ones, ensuring their podcasts are included in the average calculation, and the publication date falls within the selected time period\r\n  SELECT \r\n    date,\r\n    podcast_title,\r\n    headline, \r\n    SUM(IFNULL(m_zugriffe_1,0)) AS zugriffe,\r\n    publication_date_6,\r\n  FROM $episode_dataset AS episode_dataset\r\n  LEFT JOIN $profiles_dataset AS pd\r\n  USING(podcast_title)\r\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates \r\n  USING (headline)\r\n  WHERE \r\n    (\"$Bereich\" = \"Alle Bereiche\" OR episode_dataset.branding = \"$Bereich\")\r\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\r\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n    AND publication_date_6 BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n    AND $episodenschnitt_condition \r\n  GROUP BY date, podcast_title, headline, publication_date_6\r\n), ranked_episodes AS(\r\n  -- This step ranks episodes according to their total zugriffe across the entire period\r\n  SELECT\r\n    podcast_title,\r\n    headline,\r\n    publication_date_6,\r\n    RANK() OVER(ORDER BY zugriffe DESC) AS rang\r\n  FROM (\r\n  SELECT\r\n    podcast_title, \r\n    headline,\r\n    publication_date_6,\r\n    SUM(zugriffe) AS zugriffe,\r\n  FROM raw_data\r\n  GROUP BY podcast_title, headline, publication_date_6\r\n  )\r\n), date_range AS (\r\n  -- Create a full date range to handle cases where episodes have no zugriffe on some days\r\n  SELECT \r\n    date \r\n  FROM UNNEST(GENERATE_DATE_ARRAY(DATE('${__from:date}', \"Europe/Berlin\"), DATE('${__to:date}', \"Europe/Berlin\"))) AS date\r\n), filtered_date_range AS (\r\n  -- Join date range with episodes, keeping only dates between publication and max date (to include the 5-day delay) \r\n  SELECT date, podcast_title, headline, publication_date_6, rang\r\n  FROM date_range\r\n  JOIN ranked_episodes\r\n  ON date >= publication_date_6 AND date <= \"$max_date\"\r\n), cumulative_sum_ranked_episodes AS (\r\nSELECT \r\n  -- Calculate the cumulative sum of zugriffe and the number of days since publication for each episode\r\n  filtered_date_range.podcast_title,\r\n  filtered_date_range.headline, \r\n  DATE_DIFF(filtered_date_range.date, filtered_date_range.publication_date_6, DAY) + 1 AS days_since_pub,\r\n  SUM(IFNULL(zugriffe, 0)) OVER (PARTITION BY filtered_date_range.headline ORDER BY filtered_date_range.date) AS summe, \r\n  \"${type}\" AS type, \r\n  filtered_date_range.rang\r\nFROM filtered_date_range\r\nLEFT JOIN raw_data\r\nON filtered_date_range.date = raw_data.date AND REPLACE(filtered_date_range.headline, \"'\", \"\") = REPLACE(raw_data.headline, \"'\", \"\")\r\n), avg_data AS (\r\n  -- Compute the daily average zugriffe across all episodes for days up to max_day_since_pub\r\n  SELECT \r\n    podcast_title,\r\n    days_since_pub,\r\n    AVG(summe) AS summe,\r\n    \"${type}\" AS type,\r\n    0 AS rang\r\n  FROM cumulative_sum_ranked_episodes\r\n  GROUP BY podcast_title,days_since_pub\r\n), avg_per_podcast AS(\r\nSELECT \r\n  podcast_title,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 7 THEN summe END)) AS days7,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 14 THEN summe END)) AS days14,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 28 THEN summe END)) AS days28,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 56 THEN summe END)) AS days56,\r\n  ROUND(MAX(CASE WHEN days_since_pub = 91 THEN summe END)) AS days91,\r\n  ROUND(MAX(CASE WHEN days_since_pub = $Tage THEN summe END)) AS daysCustom,\r\nFROM avg_data\r\nGROUP BY podcast_title)\r\nSELECT\r\n  \"Durchschnitt $Podcast_title\",\r\n  ROUND(AVG(days7)) AS days7,\r\n  ROUND(AVG(days14)) AS days14,\r\n  ROUND(AVG(days28)) AS days28,\r\n  ROUND(AVG(days56)) AS days56,\r\n  ROUND(AVG(days91)) AS days91,\r\n  ROUND(AVG(daysCustom)) AS daysCustom,\r\n  FROM avg_per_podcast\r\n "
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zugriffe pro Tag für \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n    date,\n    \"${type}\" as type,\n    SUM(m_zugriffe_1) AS zugriffe,\n    \"$Plattformen\" as platform,\n    DATE_DIFF(DATE('${__to:date}', \"Europe/Berlin\"),DATE('${__from:date}', \"Europe/Berlin\"),DAY) + 1 as timeRange\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND (\"$Plattformen\" = \"Alle Plattformen\" OR platform = \"$Plattformen\")\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY date\nORDER BY date ASC"
    }
   ]
  }
 ]
}