{
 "title": "Piano App Desktop last hour",
 "time": { "from": "2023-05-01T00:00:00.000Z", "to": "2023-05-09T16:12:25.000Z" },
 "templating": {
  "list": [
   { "name": "filled_size", "query": "13" },
   {
    "name": "Vergleichszeitraumlabels",
    "query": {}
   },
   {
    "name": "Vergleichszeitraum",
    "query": {}
   },
   {
    "name": "LRA",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "time_shift",
    "query": {}
   },
   {
    "name": "App",
    "query": {}
   },
   {
    "name": "app_name",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": "Letzte Stunde : CAST(tmstp AS DATE) = CURRENT_DATE(), Heute : date = CURRENT_DATE(), Gestern : date = DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY), Letztes Wochenende :  date >= (SELECT saturday FROM(SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 2 DAY) as saturday)) AND date <= (SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 1 DAY) as sunday), Letzte 7 Tage : date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  7 DAY) AND date < CURRENT_DATE(), Letzte 30 Tage : date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  30 DAY) AND date < CURRENT_DATE()"
   },
   {
    "name": "table",
    "query": {}
   },
   {
    "name": "dataset_visits_zeitraum",
    "query": {}
   },
   {
    "name": "dataset_vergleichs_zeitraum",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Visits | $Zeitraum",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- SELECT\n--   TIMESTAMP(date), sum(m_visits) as currentsum\n-- FROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\n-- WHERE site_level2 = '${app_name}'\n--   AND page_chapter1 = \"Alle Kapitel 1\"\n--   AND page_chapter2 = \"Alle Kapitel 2\"\n--   AND sendungs_id = \"Alle Sendungs-ID\"\n--   AND $Zeitraum\n-- GROUP BY date\n\n\n\nIF ${LRA:doublequote} = \"NDR\"\nTHEN\nSELECT\n  TIMESTAMP(date), sum(m_visits) as currentsum\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n  group by date\n;\nELSE\nSELECT\n  TIMESTAMP(date), sum(m_visits) as currentsum\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n  AND distribution LIKE '%${app_name}%'\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\n  -- AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n  GROUP BY date\n;\nEND IF;"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- SELECT\n--   TIMESTAMP(date), sum(m_visits) as paststum\n-- FROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\n-- WHERE site_level2 = '${app_name}'\n--   AND page_chapter1 = \"Alle Kapitel 1\"\n--   AND page_chapter2 = \"Alle Kapitel 2\"\n--   AND sendungs_id = \"Alle Sendungs-ID\"\n--   AND $Vergleichszeitraum\n-- GROUP BY date\n\n\n\nIF ${LRA:doublequote} = \"NDR\"\nTHEN\nSELECT\n  TIMESTAMP(date), sum(m_visits) as paststum\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n    group by date\n\n;\nELSE\nSELECT\n  TIMESTAMP(date), sum(m_visits) as paststum\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_2_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n  AND distribution LIKE '%${app_name}%'\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\n  -- AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n  GROUP BY date\n;\nEND IF;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "options": { "content": " " } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Visits')), 'Visits')\r\nFROM(\r\nSELECT 'Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Bounce Rate in %')), 'Bounce Rate in %')\r\nFROM(\r\nSELECT 'Bounce Rate in %' as Bounce\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Page Views / Visits')), 'Page Views / Visits')\r\nFROM(\r\nSELECT 'Page Views / Visits' as pi_visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Time spent / Visit in s')), 'Time spent / Visit in s')\r\nFROM(\r\nSELECT 'Time spent / Visit in s' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ${LRA:doublequote} = \"NDR\"\nTHEN\nSELECT\n  SUM(COALESCE(m_visits,0)) AS summe\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n;\nELSE\nSELECT\n  SUM(COALESCE(m_visits,0)) AS summe\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n  AND distribution LIKE '%${app_name}%'\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\n  -- AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n;\nEND IF;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ${LRA:doublequote} = \"NDR\"\r\nTHEN\r\nSELECT\r\n  SUM(COALESCE(m_visits,0)) AS summe\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND $Zeitraum\r\n;\r\nELSE\r\nSELECT\r\n  SUM(COALESCE(m_visits,0)) AS summe\r\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_2_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\nWHERE site_level2 = \"mdr.de\"\r\n  AND distribution LIKE '%${app_name}%'\r\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\r\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\r\n  -- AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND $Zeitraum\r\n;\r\nEND IF;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- SELECT \r\n--   SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\n-- FROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\n--   AND page_chapter1 = \"Alle Kapitel 1\"\r\n--   AND page_chapter2 = \"Alle Kapitel 2\"\r\n--   AND sendungs_id = \"Alle Sendungs-ID\"\r\n--   AND $Zeitraum\r\n  \r\nIF ${LRA:doublequote} = \"NDR\"\r\nTHEN\r\nSELECT\r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND $Zeitraum\r\n;\r\nELSE\r\nSELECT\r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\nWHERE site_level2 = \"mdr.de\"\r\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\r\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND distribution LIKE '%${app_name}%'\r\n  AND $Zeitraum\r\n;\r\nEND IF;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- SELECT \r\n--   SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\n-- FROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\n--   AND page_chapter1 = \"Alle Kapitel 1\"\r\n--   AND page_chapter2 = \"Alle Kapitel 2\"\r\n--   AND sendungs_id = \"Alle Sendungs-ID\"\r\n--   AND $Zeitraum\r\n  \r\nIF ${LRA:doublequote} = \"NDR\"\r\nTHEN\r\nSELECT\r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND $Zeitraum\r\n;\r\nELSE\r\nSELECT\r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_2_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\nWHERE site_level2 = \"mdr.de\"\r\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\r\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND distribution LIKE '%${app_name}%'\r\n  AND $Zeitraum\r\n;\r\nEND IF;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- SELECT\n--   SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\n-- FROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\n-- WHERE site_level2 = '${app_name}'\n--   AND page_chapter1 = \"Alle Kapitel 1\"\n--   AND page_chapter2 = \"Alle Kapitel 2\"\n--   AND sendungs_id = \"Alle Sendungs-ID\"\n--   AND $Zeitraum\n\n\n\nIF ${LRA:doublequote} = \"NDR\"\nTHEN\nSELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n;\nELSE\nSELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n--  AND page_chapter1 = \"Alle Kapitel 1\"\n--   AND page_chapter2 = \"Alle Kapitel 2\"\n  AND distribution LIKE '%${app_name}%'\n  AND $Zeitraum\n;\nEND IF;\n\n\n\n-- SELECT\n--   SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\n-- FROM\n--   (\n--     SELECT\n--       --publishing_date,\n--       FIRST_VALUE(publishing_date) OVER (\n--         PARTITION BY uuid\n--         ORDER BY\n--           publishing_date DESC\n--       ) as publishing_date,\n--       FIRST_VALUE(content_id_sophora) OVER (\n--         PARTITION BY uuid\n--         ORDER BY\n--           publishing_date DESC\n--       ) as content_id_sophora,\n--       m_visits,\n--       m_page_loads,\n--       FIRST_VALUE(content_titel) OVER (\n--         PARTITION BY uuid\n--         ORDER BY\n--           publishing_date DESC\n--       ) as content_titel\n--     FROM\n--       `ndr-code-bi-dashboard.Piano.articles_joined_last_hour`\n--     WHERE\n--       site_level2 = '${app_name}'\n--       AND content_id_sophora NOT LIKE '%index%'\n--       AND content_id_sophora NOT LIKE '%N/A%'\n--       AND (\n--         CASE\n--           WHEN \"$LRA\" = 'NDR' THEN content_titel NOT LIKE '%Video Livestream%'\n--           AND content_titel NOT LIKE '%Startteaser%'\n--           AND content_titel NOT LIKE '%startteaser%'\n--           AND content_titel NOT LIKE '%-Anmelden%'\n--           AND content_titel NOT LIKE '%_Start'\n--           AND content_titel != 'Anmelden'\n--           AND content_titel != 'Jetzt läuft'\n--           ELSE TRUE\n--         END\n--       )\n--       AND $Zeitraum\n--   )"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- SELECT\r\n--   SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\n-- FROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\n--   AND page_chapter1 = \"Alle Kapitel 1\"\r\n--   AND page_chapter2 = \"Alle Kapitel 2\"\r\n--   AND sendungs_id = \"Alle Sendungs-ID\"\r\n--   AND $Zeitraum\r\n\r\n\r\n\r\nIF ${LRA:doublequote} = \"NDR\"\r\nTHEN\r\nSELECT\r\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND $Zeitraum\r\n;\r\nELSE\r\nSELECT\r\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_2_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\nWHERE site_level2 = \"mdr.de\"\r\n--  AND page_chapter1 = \"Alle Kapitel 1\"\r\n--   AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND distribution LIKE '%${app_name}%'\r\n  AND $Zeitraum\r\n;\r\nEND IF;\r\n\r\n\r\n\r\n-- SELECT\r\n--   SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\n-- FROM\r\n--   (\r\n--     SELECT\r\n--       --publishing_date,\r\n--       FIRST_VALUE(publishing_date) OVER (\r\n--         PARTITION BY uuid\r\n--         ORDER BY\r\n--           publishing_date DESC\r\n--       ) as publishing_date,\r\n--       FIRST_VALUE(content_id_sophora) OVER (\r\n--         PARTITION BY uuid\r\n--         ORDER BY\r\n--           publishing_date DESC\r\n--       ) as content_id_sophora,\r\n--       m_visits,\r\n--       m_page_loads,\r\n--       FIRST_VALUE(content_titel) OVER (\r\n--         PARTITION BY uuid\r\n--         ORDER BY\r\n--           publishing_date DESC\r\n--       ) as content_titel\r\n--     FROM\r\n--       `ndr-code-bi-dashboard.Piano.articles_joined_last_hour`\r\n--     WHERE\r\n--       site_level2 = '${app_name}'\r\n--       AND content_id_sophora NOT LIKE '%index%'\r\n--       AND content_id_sophora NOT LIKE '%N/A%'\r\n--       AND (\r\n--         CASE\r\n--           WHEN \"$LRA\" = 'NDR' THEN content_titel NOT LIKE '%Video Livestream%'\r\n--           AND content_titel NOT LIKE '%Startteaser%'\r\n--           AND content_titel NOT LIKE '%startteaser%'\r\n--           AND content_titel NOT LIKE '%-Anmelden%'\r\n--           AND content_titel NOT LIKE '%_Start'\r\n--           AND content_titel != 'Anmelden'\r\n--           AND content_titel != 'Jetzt läuft'\r\n--           ELSE TRUE\r\n--         END\r\n--       )\r\n--       AND $Zeitraum\r\n--   )"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- SELECT\n--   SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\n--   FROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\n-- WHERE site_level2 = '${app_name}'\n--   AND page_chapter1 = \"Alle Kapitel 1\"\n--   AND page_chapter2 = \"Alle Kapitel 2\"\n--   AND sendungs_id = \"Alle Sendungs-ID\"\n--   AND $Zeitraum\n\n\n\n\nIF ${LRA:doublequote} = \"NDR\"\nTHEN\nSELECT\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n;\nELSE\nSELECT\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\nFROM `ndr-code-bi-dashboard.Piano.MDR_total_visits_site_app_last_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n-- AND page_chapter1 = \"Alle Kapitel 1\"\n -- AND page_chapter2 = \"Alle Kapitel 2\"\n  AND distribution LIKE '%${app_name}%'\n  AND $Zeitraum\n;\nEND IF;\n\n\n\n\n\n\n\n-- FROM\n--   (\n--     SELECT\n--       --publishing_date,\n--       FIRST_VALUE(publishing_date) OVER (\n--         PARTITION BY uuid\n--         ORDER BY\n--           publishing_date DESC\n--       ) as publishing_date,\n--       FIRST_VALUE(content_id_sophora) OVER (\n--         PARTITION BY uuid\n--         ORDER BY\n--           publishing_date DESC\n--       ) as content_id_sophora,\n--       m_visits,\n--       m_page_loads,\n--       FIRST_VALUE(content_titel) OVER (\n--         PARTITION BY uuid\n--         ORDER BY\n--           publishing_date DESC\n--       ) as content_titel\n--     FROM\n--       `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\n--     WHERE\n--       site_level2 = '${app_name}'\n--       AND content_id_sophora NOT LIKE '%index%'\n--       AND content_id_sophora NOT LIKE '%N/A%'\n--       AND (\n--         CASE\n--           WHEN \"$LRA\" = 'NDR' THEN content_titel NOT LIKE '%Video Livestream%'\n--           AND content_titel NOT LIKE '%Startteaser%'\n--           AND content_titel NOT LIKE '%startteaser%'\n--           AND content_titel NOT LIKE '%-Anmelden%'\n--           AND content_titel NOT LIKE '%_Start'\n--           AND content_titel != 'Anmelden'\n--           AND content_titel != 'Jetzt läuft'\n--           ELSE TRUE\n--         END\n--       )\n--       AND $Zeitraum\n--   )"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nIF ${LRA:doublequote} = \"NDR\"\r\nTHEN\r\nSELECT\r\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND $Zeitraum\r\n;\r\nELSE\r\nSELECT\r\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\r\nFROM `ndr-code-bi-dashboard.Piano.MDR_total_visits_site_app_last_2_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\nWHERE site_level2 = \"mdr.de\"\r\n --AND page_chapter1 = \"Alle Kapitel 1\"\r\n  --AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND distribution LIKE '%${app_name}%'\r\n  AND $Zeitraum\r\n;\r\nEND IF;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ${LRA:doublequote} = \"NDR\"\nTHEN\nWITH past_value as(\nSELECT\n  SUM(COALESCE(m_visits,0)) AS past_sum\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n), current_value AS (SELECT\n  SUM(COALESCE(m_visits,0)) AS current_sum\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n)\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference\n\n;\n\nElSE\n\nWITH past_value as(\nSELECT\n  SUM(COALESCE(m_visits,0)) AS past_sum\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_2_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n  AND distribution LIKE '%${app_name}%'\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\n  -- AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n), current_value AS (SELECT\n  SUM(COALESCE(m_visits,0)) AS current_sum\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n  AND distribution LIKE '%${app_name}%'\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\n  -- AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n)\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference\n\n\n;\nEND IF;\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ${LRA:doublequote} = \"NDR\"\r\nTHEN\r\nWITH past_value as(\r\nSELECT \r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0)) as past_sum,\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND $Zeitraum), current_value AS (\r\nSELECT \r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0)) as current_sum,\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND $Zeitraum\r\n  )\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference\r\n;\r\nELSE\r\nWITH past_value as(\r\nSELECT\r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as past_sum,\r\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_2_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\nWHERE site_level2 = \"mdr.de\"\r\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\r\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND distribution LIKE '%${app_name}%'\r\n  AND $Zeitraum), current_value AS (\r\nSELECT\r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as current_sum,\r\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_hour`\r\n-- WHERE site_level2 = '${app_name}'\r\nWHERE site_level2 = \"mdr.de\"\r\n  --   AND page_chapter1 = \"Alle Kapitel 1\"\r\n  -- AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND distribution LIKE '%${app_name}%'\r\n  AND $Zeitraum\r\n  )\r\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference\r\n;\r\nEND IF;\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\nIF ${LRA:doublequote} = \"NDR\"\nTHEN\nWITH past_value as(SELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as past_sum,\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_2_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum), current_value AS (SELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as current_sum,\nFROM `ndr-code-bi-dashboard.Piano.total_visits_last_hour`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum)\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference\n;\nELSE\nWITH past_value as(SELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as past_sum,\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_2_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n--  AND page_chapter1 = \"Alle Kapitel 1\"\n--   AND page_chapter2 = \"Alle Kapitel 2\"\n  AND distribution LIKE '%${app_name}%'\n  AND $Zeitraum), current_value AS (SELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as current_sum,\nFROM `ndr-code-bi-dashboard.Piano.MDR_app_last_hour`\n-- WHERE site_level2 = '${app_name}'\nWHERE site_level2 = \"mdr.de\"\n--  AND page_chapter1 = \"Alle Kapitel 1\"\n--   AND page_chapter2 = \"Alle Kapitel 2\"\n  AND distribution LIKE '%${app_name}%'\n  AND $Zeitraum)\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference\n;\nEND IF;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ${LRA:doublequote} = \"NDR\"\nTHEN\nWITH past_value as(\nSELECT \n   SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS past_sum,\nFROM \n  Piano.total_visits\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\nAND $Vergleichszeitraum), current_value AS (\nSELECT \n   SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS current_sum,\nFROM \n  Piano.total_visits\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\nAND $Zeitraum\n)\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference\n;\nELSE\nWITH past_value as(\nSELECT \n   SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS past_sum,\nFROM `ndr-code-bi-dashboard.Piano.MDR_total_visits_site_app_last_2_hour`\nWHERE site_level2 = \"mdr.de\"\n  AND distribution LIKE '%${app_name}%'\n  AND $Zeitraum), current_value AS (\nSELECT \n   SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS current_sum,\nFROM `ndr-code-bi-dashboard.Piano.MDR_total_visits_site_app_last_hour`\nWHERE site_level2 = \"mdr.de\"\n  AND distribution LIKE '%${app_name}%'\n  AND $Zeitraum\n)\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference\n;\nEND IF;\n\n\n\n\n\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "options": { "content": " " } },
  { "title": "Top Inhalte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  tmstp as Datum,\n  content_titel as Artikel,\n  sum(m_visits) as Visits,\n  sum(m_page_loads) as page_views,\n  content_id_sophora,\n  '' as Type\nFROM\n  (\n    SELECT\n      --tmstp,\n      FIRST_VALUE(tmstp) OVER (PARTITION BY uuid ORDER BY tmstp DESC) as tmstp, \n      FIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY tmstp DESC) as content_id_sophora, \n      m_visits,\n      m_page_loads,\n      FIRST_VALUE(content_titel) OVER ( PARTITION BY uuid ORDER BY tmstp DESC) as content_titel\n    FROM\n      ndr-code-bi-dashboard.Piano.articles_joined_last_hour\n    WHERE\n      site_level2 = '${app_name}'\n      AND content_id_sophora NOT LIKE '%index%'\n      AND content_id_sophora NOT LIKE '%N/A%'\n      AND (\n        CASE \n            WHEN \"$LRA\" = 'NDR' THEN\n                content_titel NOT LIKE '%Video Livestream%'\n            AND content_titel NOT LIKE '%Startteaser%'\n            AND content_titel NOT LIKE '%startteaser%'\n            AND content_titel NOT LIKE '%-Anmelden%'\n            AND content_titel NOT LIKE '%_Start'\n            AND content_titel != 'Anmelden'\n            AND content_titel != 'Jetzt läuft'\n        ELSE\n          TRUE\n        END)\n      AND $Zeitraum\n  )\nGROUP BY\n  content_id_sophora,\n  content_titel,\n  tmstp\nORDER BY\n  3 DESC\nLIMIT\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "options": { "content": " " } },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "App | Distribution | $Zeitraum",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\nSELECT \n  SUM(m_visits), os_group \nFROM \n  Piano.distro${dataset_visits_zeitraum:raw}\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n  AND device_type NOT LIKE '%N/A%'\nGROUP BY os_group\nORDER BY 1 DESC\n"
    }
   ]
  },
  {
   "title": "App | Devices | $Zeitraum",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\ndevice_type,\nSUM(m_visits) as visits\nFROM\n Piano.distro${dataset_visits_zeitraum:raw}\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum \n  AND device_type NOT LIKE '%N/A%'\nGROUP BY device_type \nORDER BY visits DESC \nLIMIT 10"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "options": { "content": " " } }
 ]
}