{
 "title": "Web & App Dashboard fester Zeitraum",
 "description": "old web & app dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "LRA", "query": "NDR,MDR" },
   {
    "name": "Redaktionen",
    "query": {}
   },
   {
    "name": "Unterkapitel",
    "query": {}
   },
   {
    "name": "Sendung",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": "Heute :  date = CURRENT_DATE(),Gestern :  date = DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY), Letztes Wochenende :    date >= (SELECT saturday FROM(SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 2 DAY) as saturday))  AND   date <= (SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 1 DAY) as sunday), Letzte 7 Tage : date >= DATE_SUB(CURRENT_DATE()\\, INTERVAL  7 DAY) AND date < CURRENT_DATE(), Letzte 30 Tage : date >= DATE_SUB(CURRENT_DATE()\\, INTERVAL  30 DAY) AND date <= CURRENT_DATE()"
   },
   {
    "name": "Vergleichszeitraum",
    "query": {}
   },
   {
    "name": "Tage",
    "query": {}
   },
   {
    "name": "app_name",
    "query": {}
   },
   {
    "name": "site_level2",
    "query": {}
   },
   {
    "name": "page_chapter1",
    "query": {}
   },
   {
    "name": "page_chapter2",
    "query": {}
   },
   {
    "name": "sendungsid",
    "query": {}
   },
   {
    "name": "av_condition",
    "query": {}
   },
   {
    "name": "app_name_long",
    "query": {}
   },
   {
    "name": "Einheit",
    "query": {}
   },
   {
    "name": "av_table_fever_curve",
    "query": {}
   },
   {
    "name": "fromDay",
    "query": {}
   },
   {
    "name": "toDay",
    "query": {}
   },
   {
    "name": "av_page_chapter2",
    "query": {}
   },
   {
    "name": "webFilter",
    "query": {}
   },
   {
    "name": "avwebFilter",
    "query": {}
   },
   {
    "name": "articleTable",
    "query": {}
   },
   {
    "name": "listwebFilter",
    "query": {}
   },
   {
    "name": "list_page_chapter2",
    "query": {}
   },
   {
    "name": "appFilter",
    "query": {}
   },
   {
    "name": "avzeitraumListe",
    "query": {}
   },
   {
    "name": "comp_var",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "lim",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "feverCurveDataset",
    "query": {}
   },
   {
    "name": "type",
    "query": {}
   },
   {
    "name": "Zeitraumlabels",
    "query": {}
   },
   {
    "name": "Zeitraumfever",
    "query": {}
   },
   {
    "name": "Vergleichszeitraum_var",
    "query": {}
   },
   {
    "name": "time_shift",
    "query": {}
   },
   {
    "name": "Vergleichszeitraumlabels",
    "query": {}
   },
   {
    "name": "Zeitraumfever_app",
    "query": {}
   },
   {
    "name": "Uhrzeit",
    "query": {}
   },
   {
    "name": "comp_fever",
    "query": {}
   },
   {
    "name": "dataset_kpi",
    "query": {}
   },
   { "name": "filled_size_big", "query": "10" },
   {
    "name": "av_table_fever_curve_comp",
    "query": {}
   },
   {
    "name": "av_app_condition_video",
    "query": {}
   },
   {
    "name": "av_app_condition_audio",
    "query": {}
   },
   {
    "name": "av_pub_date",
    "query": {}
   },
   {
    "name": "av_content_id",
    "query": {}
   },
   {
    "name": "av_content",
    "query": {}
   },
   {
    "name": "av_on_demand_filter",
    "query": {}
   },
   {
    "name": "av_live_stream_filter",
    "query": {}
   },
   {
    "name": "distro_table",
    "query": {}
   },
   {
    "name": "bq_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_timeframe_end",
    "query": {}
   },
   {
    "name": "bq_comp_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_comp_timeframe_end",
    "query": {}
   },
   {
    "name": "bq_fever",
    "query": {}
   },
   {
    "name": "sendungsListe",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# 📊 Hinweis\n\n- Audio- und Video-Daten ohne Livestream-Nutzung, mit Ausnahme der Livestream-Tabelle."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  { "title": "Verlaufsdiagramme", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Visits - Web - Verlaufsdiagramm",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH lagged_data AS (\r\n  SELECT\r\n    TIMESTAMP(tmstp) as time,\r\n    SUM(m_visits) as m_visits,\r\n    LAG(SUM(m_visits)) OVER (ORDER BY tmstp) as prev_m_visits,\r\n    LAG(TIMESTAMP(tmstp)) OVER (ORDER BY tmstp) as pre_timestamp\r\n  FROM\r\n    `Piano.total_visits_today_append`\r\n  WHERE\r\n    $webFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n    AND source != \"mdr_app\"\r\n    GROUP BY tmstp\r\n    ORDER by time DESC\r\n    ${lim}\r\n\r\n    -- 09:00     --> 09:20. --- > 09:30\r\n\r\n),\r\nmin_time_from_base AS (\r\n  -- This with statement will used in order to find out which is the last valid upload(e.g. the one with valid successor)\r\n  SELECT MIN(pre_timestamp) min_time FROM lagged_data\r\n  WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10\r\n), \r\nmax_time_from_base AS (\r\n    -- THis with statement will be used if no gap exists\r\n    SELECT MAX(time) as max_time FROM lagged_data\r\n    WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10\r\n),\r\ncleaned_lagged_data AS (\r\n  SELECT * from lagged_data \r\n  WHERE\r\n  time <= (SELECT COALESCE( min_time_from_base.min_time, max_time_from_base.max_time )\r\n  FROM max_time_from_base, min_time_from_base)\r\n),\r\ndaily_data AS (\r\n  SELECT\r\n     TIMESTAMP(date, \"Europe/Berlin\") as time,\r\n    TIMESTAMP_SUB(TIMESTAMP(date,  \"Europe/Berlin\"), INTERVAL 10 MINUTE) as pre_timestamp,\r\n    m_visits as visits_past_5_minutes_adjusted,\r\n    \"${type}\" as type, \"${Zeitraumlabels:text}\" as refId\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`\r\n  WHERE\r\n    $webFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n    ORDER BY time DESC\r\n),\r\nadjusted_lagged_data AS (\r\n  SELECT\r\n    DATE_SUB(time, INTERVAL 2 hour) as time,\r\n    DATE_SUB(pre_timestamp, INTERVAL 2 hour) as pre_timestamp,\r\n    -- Calculate time difference in minutes\r\n    TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) as time_diff,\r\n    -- Adjust visits count based on time difference\r\n    CASE\r\n      WHEN FALSE AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10 OR TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) < 0 AND \"${Glaettung:text}\" = \"Glätten\" THEN\r\n        (m_visits - prev_m_visits) / TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) * 10\r\n      ELSE\r\n        m_visits - prev_m_visits\r\n    END as visits_past_5_minutes_adjusted,\r\n    \"${type}\" as type, \r\n    \"${Zeitraumlabels:text}\" as refId\r\n  FROM\r\n    cleaned_lagged_data\r\n)\r\nSELECT\r\n TIMESTAMP_ADD(time, INTERVAL 1 SECOND) as time,\r\n  TIMESTAMP_ADD(pre_timestamp, INTERVAL 1 SECOND) as pre_timestamp,\r\n  MAX(ROUND(visits_past_5_minutes_adjusted)) as visits_past_5_minutes,\r\n  type,\r\n  refId,\r\n   \"${Glaettung:text}\" as glaettung,\r\n   \"Zeitraum\" as zeitraum\r\nFROM\r\n  ${dataset}\r\nWHERE\r\n  visits_past_5_minutes_adjusted IS NOT NULL\r\n  AND visits_past_5_minutes_adjusted > 0\r\n  AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10 OR TIMESTAMP_DIFF(time, pre_timestamp, HOUR) = 1\r\n  GROUP BY time, pre_timestamp, type, refId\r\nORDER BY\r\n  time ASC\r\n  ${lim}\r\n"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH min_time AS ( \r\n      SELECT\r\n        MIN(tmstp) as min_tmstp,\r\n        MAX(tmstp) as max_tmstp\r\n        FROM\r\n      (SELECT tmstp\r\n      from\r\n        `Piano.total_visits${feverCurveDataset:raw}`\r\n      WHERE\r\n        date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n        AND $webFilter\r\n        ORDER BY tmstp DESC\r\n        ${lim}\r\n        )\r\n    )\r\n    , lagged_data AS (\r\n    SELECT\r\n        TIMESTAMP(tmstp) as time,\r\n        SUM(m_visits) as m_visits,\r\n        LAG(SUM(m_visits)) OVER (ORDER BY tmstp) as prev_m_visits,\r\n        LAG(TIMESTAMP(tmstp)) OVER (ORDER BY tmstp) as pre_timestamp\r\n  FROM\r\n     `Piano.total_visits_today_append`\r\n  WHERE\r\n     date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND $Zeitraumfever \r\n    AND source != \"mdr_app\"\r\n    AND $webFilter\r\n    GROUP BY tmstp\r\n),\r\nmin_time_from_base AS (\r\n  -- This with statement will used in order to find out which is the last valid upload(e.g. the one with valid successor)\r\n  SELECT MIN(pre_timestamp) min_time FROM lagged_data\r\n  WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10\r\n), \r\nmax_time_from_base AS (\r\n    -- THis with statement will be used if no gap exists\r\n    SELECT MAX(time) as max_time FROM lagged_data\r\n    WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10\r\n),\r\ncleaned_lagged_data AS (\r\n  SELECT * from lagged_data \r\n  WHERE\r\n  time <= (SELECT COALESCE(min_time_from_base.min_time,max_time_from_base.max_time )\r\n  FROM max_time_from_base, min_time_from_base)\r\n),\r\nadjusted_lagged_data AS (\r\n    SELECT\r\n        time,\r\n        pre_timestamp,\r\n        -- Calculate time difference in minutes\r\n        TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) as time_diff,\r\n        -- Adjust visits count based on time difference\r\n        CASE\r\n            WHEN FALSE AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10 THEN\r\n                (m_visits - prev_m_visits) / TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) * 10\r\n            ELSE\r\n                m_visits - prev_m_visits\r\n        END as visits_past_5_minutes_adjusted\r\n    FROM\r\n        cleaned_lagged_data\r\n),\r\ndaily_data AS (\r\n  SELECT\r\n    TIMESTAMP(date) as time,\r\n    m_visits as visits_past_5_minutes_adjusted,\r\n    TIMESTAMP_SUB(TIMESTAMP(date), INTERVAL 10 MINUTE) as pre_timestamp\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`\r\n  WHERE\r\n    date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND $webFilter\r\n)\r\nSELECT\r\n    DATE_SUB(DATE_ADD(TIMESTAMP_ADD(time, INTERVAL 1 SECOND), INTERVAL ${time_shift} DAY), INTERVAL 2 HOUR) as time,\r\n    DATE_SUB(DATE_ADD(TIMESTAMP_ADD(pre_timestamp, INTERVAL 1 SECOND), INTERVAL ${time_shift} DAY), INTERVAL 2 HOUR) as pre_timestamp,\r\n    MAX(visits_past_5_minutes_adjusted) as visits_past_5_minutes,\r\n    \"${type}\" as type,\r\n    \"${Vergleichszeitraumlabels:text}\" as refId,\r\n    \"${Glaettung:text}\" as glaettung,\r\n    \"Vergleichszeitraum\" as zeitraum\r\nFROM\r\n    ${dataset}\r\nWHERE\r\n    visits_past_5_minutes_adjusted IS NOT NULL\r\n    AND visits_past_5_minutes_adjusted > 0\r\n     AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10 OR TIMESTAMP_DIFF(time, pre_timestamp, HOUR) = 1\r\n     AND  CASE \"${Zeitraum:text}\"\r\n     WHEN \"Gestern\" THEN EXTRACT(date from time) = \"$bq_fever\"\r\n     WHEN \"Heute\" THEN EXTRACT(date from time) = \"$bq_fever\"\r\n      WHEN \"Heute -7d\" THEN EXTRACT(date from time) = \"$bq_fever\"\r\n     ELSE True\r\n     END\r\n     \r\nGROUP BY time, pre_timestamp, type, refId\r\nORDER BY\r\n    time ASC\r\n\r\n  ${lim}\r\n"
    }
   ]
  },
  {
   "title": "Wiedergaben - Web - Verlaufsdiagramm",
   "type": "volkovlabs-echarts-panel",
   "description": "Hinweis: Momentan keine Web-AV-Messung für die NDR Länder möglich.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT sum(COALESCE(m_av_playbacks,0)) as m_av_playbacks , date as time, '${Zeitraum:text}' as Zeitraum\r\nFROM  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\nWHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND $avwebFilter\r\nGROUP BY date\r\nORDER BY date\r\n"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT sum(COALESCE(m_av_playbacks,0)) as m_av_playbacks, \r\ndate_ADD(date, INTERVAL $Tage $Einheit) as time,\r\n '${Vergleichszeitraum:text}' as Zeitraum\r\nFROM `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\nWHERE date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND $avwebFilter\r\nGROUP BY date\r\nORDER BY date"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Visits - Web & App | ${Zeitraum:text}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH lagged_data AS (\r\n  SELECT\r\n    TIMESTAMP(tmstp) as time,\r\n    SUM(m_visits) as m_visits,\r\n    LAG(SUM(m_visits)) OVER (ORDER BY tmstp) as prev_m_visits,\r\n    LAG(TIMESTAMP(tmstp)) OVER (ORDER BY tmstp) as pre_timestamp\r\n  FROM\r\n    `Piano.total_visits_today_append`\r\n  WHERE\r\n    $webFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n    AND source != \"mdr_app\"\r\n    GROUP BY tmstp\r\n    ORDER by time DESC\r\n    ${lim}\r\n\r\n    -- 09:00     --> 09:20. --- > 09:30\r\n\r\n),\r\nmin_time_from_base AS (\r\n  -- This with statement will used in order to find out which is the last valid upload(e.g. the one with valid successor)\r\n  SELECT MIN(pre_timestamp) min_time FROM lagged_data\r\n  WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10\r\n), \r\nmax_time_from_base AS (\r\n    -- THis with statement will be used if no gap exists\r\n    SELECT MAX(time) as max_time FROM lagged_data\r\n    WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10\r\n),\r\ncleaned_lagged_data AS (\r\n  SELECT * from lagged_data \r\n  WHERE\r\n  time <= (SELECT COALESCE( min_time_from_base.min_time, max_time_from_base.max_time )\r\n  FROM max_time_from_base, min_time_from_base)\r\n),\r\ndaily_data AS (\r\n  SELECT\r\n     TIMESTAMP(date, \"Europe/Berlin\") as time,\r\n    TIMESTAMP_SUB(TIMESTAMP(date,  \"Europe/Berlin\"), INTERVAL 10 MINUTE) as pre_timestamp,\r\n    m_visits as visits_past_5_minutes_adjusted,\r\n    \"${type}\" as type, \"${Zeitraumlabels:text}\" as refId\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`\r\n  WHERE\r\n    $webFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n    ORDER BY time DESC\r\n),\r\nadjusted_lagged_data AS (\r\n  SELECT\r\n    DATE_SUB(time, INTERVAL 2 hour) as time,\r\n    DATE_SUB(pre_timestamp, INTERVAL 2 hour) as pre_timestamp,\r\n    -- Calculate time difference in minutes\r\n    TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) as time_diff,\r\n    -- Adjust visits count based on time difference\r\n    CASE\r\n      WHEN FALSE AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10 OR TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) < 0 AND \"${Glaettung:text}\" = \"Glätten\" THEN\r\n        (m_visits - prev_m_visits) / TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) * 10\r\n      ELSE\r\n        m_visits - prev_m_visits\r\n    END as visits_past_5_minutes_adjusted,\r\n    \"${type}\" as type, \r\n    \"${Zeitraumlabels:text}\" as refId\r\n  FROM\r\n    cleaned_lagged_data\r\n)\r\nSELECT\r\n  TIMESTAMP_ADD(time, INTERVAL 1 SECOND) as time,\r\n  TIMESTAMP_ADD(pre_timestamp, INTERVAL 1 SECOND) as pre_timestamp,\r\n  MAX(ROUND(visits_past_5_minutes_adjusted)) as visits_past_5_minutes,\r\n  type,\r\n  refId,\r\n   \"${Glaettung:text}\" as glaettung,\r\n   \"Web\" as zeitraum,\r\nFROM\r\n  ${dataset}\r\nWHERE\r\n  visits_past_5_minutes_adjusted IS NOT NULL\r\n  AND visits_past_5_minutes_adjusted > 0\r\n  AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10 OR TIMESTAMP_DIFF(time, pre_timestamp, HOUR) = 1\r\n  GROUP BY time, pre_timestamp, type, refId\r\nORDER BY\r\n  time ASC\r\n  ${lim}\r\n"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH sumdata AS (\r\n  SELECT\r\n    TIMESTAMP(tmstp) as tmstp,\r\n    CASE \"$LRA\"\r\n    WHEN \"NDR\" THEN MAX(m_visits)\r\n    ELSE SUM(DISTINCT m_visits)\r\n    END\r\n     as m_visits FROM\r\n     `Piano.total_visits${feverCurveDataset:raw}`\r\n  WHERE\r\n  $appFilter \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  GROUP by tmstp\r\n  ORDER BY tmstp DESC\r\n  ${lim}\r\n),\r\nlagged_data AS (\r\n  SELECT\r\n    TIMESTAMP(tmstp) as time,\r\n    m_visits - LAG(m_visits) OVER (\r\n      ORDER BY\r\n        tmstp\r\n    ) as visits_past_5_minutes,\r\n    LAG(m_visits) OVER (ORDER BY tmstp) as prev_m_visits,\r\n    LAG(TIMESTAMP(tmstp)) OVER (ORDER BY tmstp) as pre_timestamp,\r\n    m_visits\r\n  FROM\r\n    sumdata\r\n    \r\n),\r\nmin_time_from_base AS (\r\n  -- This with statement will used in order to find out which is the last valid upload(e.g. the one with valid successor)\r\n  SELECT MIN(pre_timestamp) min_time FROM lagged_data\r\n  WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10\r\n), \r\nmax_time_from_base AS (\r\n    -- THis with statement will be used if no gap exists\r\n    SELECT MAX(time) as max_time FROM lagged_data\r\n    WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10\r\n),\r\ncleaned_lagged_data AS (\r\n  SELECT * from lagged_data \r\n  WHERE\r\n  time <= (SELECT COALESCE(max_time_from_base.max_time, min_time_from_base.min_time )\r\n  FROM max_time_from_base, min_time_from_base)\r\n),\r\nadjusted_lagged_data AS (\r\n    SELECT\r\n        time,\r\n        pre_timestamp,\r\n        -- Calculate time difference in minutes\r\n        TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) as time_diff,\r\n        -- Adjust visits count based on time difference\r\n           CASE\r\n      WHEN FALSE AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10 OR TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) < 10 AND \"${Glaettung:text}\" = \"Glätten\" THEN\r\n        (m_visits - prev_m_visits) / TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) * 10\r\n      ELSE\r\n        m_visits - prev_m_visits\r\n        END as visits_past_5_minutes\r\n    FROM\r\n        cleaned_lagged_data\r\n        WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) >= 10\r\n      ORDER BY time DESC\r\n      ${lim}\r\n),\r\n\r\ndaily_data AS (\r\n  SELECT\r\n     TIMESTAMP(date) as time,\r\n    SUM(m_visits) as visits_past_5_minutes\r\n  FROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`\r\n  WHERE\r\n  $appFilter \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  GROUP BY date\r\n)\r\n\r\nSELECT\r\n    DATE_SUB(TIMESTAMP_ADD(time, INTERVAL 1 SECOND), INTERVAL 2 hour) as time,\r\n  visits_past_5_minutes, \"${type}\" as type, \"${Zeitraumlabels:text}\" as refId,\r\n     \"${Glaettung:text}\" as glaettung,\r\n   \"App\" as zeitraum\r\nFROM\r\n  ${dataset}\r\nWHERE\r\n  visits_past_5_minutes IS NOT NULL\r\n  AND $Zeitraumfever_app \r\nORDER BY\r\n  time ASC\r\n${lim}\r\n"
    }
   ]
  },
  {
   "title": "Wiedergaben - Web & App | ${Zeitraum:text}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT sum(m_av_playbacks) as m_av_playbacks , date as time, 'Web' AS Zeitraum,'${Zeitraum:text}' as Darstellung\r\nFROM  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\nWHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND $avwebFilter\r\nGROUP BY date\r\nORDER BY date\r\n"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as m_av_playbacks,\r\n  date as time,\r\n'App' as Zeitraum,\r\n '${Vergleichszeitraum:text}' as Darstellung\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio OR $av_app_condition_video)\r\nGROUP BY date\r\nORDER BY date"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 } },
  { "title": "KPI Boxes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Visits')), 'Visits')\r\nFROM(\r\nSELECT 'Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Pageviews / Visits')), 'Pageviews / Visits')\r\nFROM(\r\nSELECT 'Pageviews / Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Time spent / Visit in Sec.')), 'Time spent / Visit in Sec.')\r\nFROM(\r\nSELECT 'Time spent / Visit in Sec.' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio- & Videostarts')), 'Audio- & Videostarts')\r\nFROM(\r\nSELECT 'Audio- & Videostarts' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Web & App')), 'Web & App')\r\nFROM(\r\nSELECT 'Web & App' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}),\r\na as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\r\nSELECT  w.m_visits + a.m_visits as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    GROUP BY site_level2, tmstp\r\n    ORDER BY tmstp DESC\r\n    LIMIT 1), daily_data AS(\r\n       SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    )\r\n    SELECT * FROM ${dataset_kpi}),\r\na as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY m_visits DESC\r\n  LIMIT 1),\r\n  daily_data AS(\r\n    SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote})\r\n  SELECT * FROM ${dataset_kpi}\r\n  )\r\n\r\n\r\nSELECT  w.m_visits + a.m_visits as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($webFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n    ) \r\n),\r\na as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter\r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n)\r\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \r\n(\r\nSELECT ROUND(SUM(w.m_page_loads+a.m_page_loads)/SUM(w.m_visits + a.m_visits),1) as summe\r\nFROM w \r\nJOIN a ON w.id = a.id)\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, SUM(COALESCE(m_page_loads,0)) as m_page_loads,1 as id\r\n    FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    GROUP BY site_level2, tmstp\r\n    ORDER BY tmstp DESC\r\n    LIMIT 1), daily_data AS(\r\n       SELECT  m_visits, m_page_loads, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    )\r\n    SELECT * FROM ${dataset_kpi}),\r\na as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT   SUM(COALESCE(m_visits,0)) as m_visits,  SUM(COALESCE(m_page_loads,0)) as m_page_loads, 1 as id\r\n  FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY m_visits DESC\r\n  LIMIT 1),\r\n  daily_data AS(\r\n    SELECT  m_visits, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote})\r\n  SELECT * FROM ${dataset_kpi}\r\n  )\r\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \r\n(\r\nSELECT ROUND(SUM(w.m_page_loads+a.m_page_loads)/SUM(w.m_visits + a.m_visits),1) as summe\r\nFROM w \r\nJOIN a ON w.id = a.id)\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM  `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n   AND $webFilter\r\n),\r\na as(\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits`  \r\n   WHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n   AND $appFilter\r\n)\r\nSELECT  CONCAT(REPLACE(CAST(ROUND((a.time_spent + w.time_spent)/(a.visits + w.visits),1) as STRING), '.', ','), ' Sek.') as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n    FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    GROUP BY site_level2, tmstp\r\n    ORDER BY tmstp DESC\r\n    LIMIT 1), daily_data AS(\r\n       SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    )\r\n    SELECT * FROM ${dataset_kpi}),\r\na as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT   SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY visits DESC\r\n  LIMIT 1),\r\n  daily_data AS(\r\n    SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote})\r\n  SELECT * FROM ${dataset_kpi}\r\n  )\r\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), summe) as Zeitraum FROM \r\n(\r\nSELECT CONCAT(REPLACE(CAST(ROUND((a.time_spent + w.time_spent)/(a.visits + w.visits),1) as STRING), '.', ','), ' Sek.') as summe\r\nFROM w \r\nJOIN a ON w.id = a.id)\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as \r\n(\r\n  SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n  WHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} AND $avwebFilter\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n),\r\napp as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum, 1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio OR $av_app_condition_video)\r\nAND ($av_app_condition_audio OR $av_app_condition_video)\r\n  AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n\r\n )\r\nSELECT COALESCE(SUM(web.Zeitraum),0) + COALESCE(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as \r\n(\r\n  SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}`  \r\n  WHERE date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} AND $avwebFilter\r\n      AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n),\r\napp as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum, 1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio OR $av_app_condition_video)\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n\r\n )\r\nSELECT COALESCE(SUM(web.Zeitraum),0) + COALESCE(SUM(app.Zeitraum),0) as Zeitraum\r\n\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\n  with w as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    GROUP BY site_level2, tmstp\r\n    ORDER BY tmstp DESC\r\n    LIMIT 1), daily_data AS(\r\n       SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    )\r\n    SELECT * FROM ${dataset_kpi}),\r\na as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY m_visits DESC\r\n  LIMIT 1),\r\n  daily_data AS(\r\n    SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote})\r\n  SELECT * FROM ${dataset_kpi}\r\n  )\r\n\r\n\r\nSELECT  w.m_visits + a.m_visits as past_sum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n),\r\ncurrent_value AS (\r\nwith w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}),\r\na as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\r\nSELECT  w.m_visits + a.m_visits as current_sum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n  )\r\nSELECT CASE\r\n    WHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\") END,\r\nFROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\n  with w as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, SUM(COALESCE(m_page_loads,0)) as m_page_loads,1 as id\r\n    FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    GROUP BY site_level2, tmstp\r\n    ORDER BY tmstp DESC\r\n    LIMIT 1), daily_data AS(\r\n       SELECT  m_visits, m_page_loads, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    )\r\n    SELECT * FROM ${dataset_kpi}),\r\na as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT   SUM(COALESCE(m_visits,0)) as m_visits,  SUM(COALESCE(m_page_loads,0)) as m_page_loads, 1 as id\r\n  FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY m_visits DESC\r\n  LIMIT 1),\r\n  daily_data AS(\r\n    SELECT  m_visits, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote})\r\n  SELECT * FROM ${dataset_kpi}\r\n  )\r\nSELECT ROUND(SUM(w.m_page_loads+a.m_page_loads)/SUM(w.m_visits + a.m_visits),1) as past_sum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n),\r\ncurrent_value AS (\r\nwith w as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($webFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n    ) \r\n),\r\na as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter\r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n)\r\nSELECT ROUND(SUM(w.m_page_loads+a.m_page_loads)/SUM(w.m_visits + a.m_visits),1) as current_sum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n  )\r\nSELECT CASE\r\n    WHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\") END,\r\nFROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\n with w as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n    FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n    GROUP BY site_level2, tmstp\r\n    ORDER BY tmstp DESC\r\n    LIMIT 1), daily_data AS(\r\n       SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n    )\r\n    SELECT * FROM ${dataset_kpi}),\r\na as (\r\n  with adjusted_lagged_data AS(\r\n  SELECT   SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM  `Piano.total_visits${feverCurveDataset:raw}` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp  <= DATETIME_SUB(\"${comp_fever}\", INTERVAL $time_shift DAY)\r\n  GROUP BY site_level2, tmstp\r\n  ORDER BY visits DESC\r\n  LIMIT 1),\r\n  daily_data AS(\r\n    SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote})\r\n  SELECT * FROM ${dataset_kpi}\r\n  )\r\nSELECT ROUND((a.time_spent + w.time_spent)/(a.visits + w.visits),1) as past_sum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n),\r\ncurrent_value AS (\r\nwith w as (\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM  `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n   AND $webFilter\r\n),\r\na as(\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits`  \r\n   WHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n   AND $appFilter\r\n)\r\nSELECT  ROUND((a.time_spent + w.time_spent)/(a.visits + w.visits),1) as current_sum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n  )\r\nSELECT CASE\r\n    WHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\") END AS Differenz,\r\nFROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\n  with web as \r\n(\r\n  SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}`  \r\n  WHERE date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} AND $avwebFilter\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n),\r\napp as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum, 1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio OR $av_app_condition_video) \r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n )\r\nSELECT  COALESCE(SUM(web.Zeitraum),0) + COALESCE(SUM(app.Zeitraum),0) as past_sum\r\n\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n),\r\ncurrent_value AS (\r\nwith web as \r\n(\r\n  SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n  WHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} AND $avwebFilter\r\n),\r\napp as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum, 1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio OR $av_app_condition_video)\r\n )\r\nSELECT COALESCE(SUM(web.Zeitraum),0) + COALESCE(SUM(app.Zeitraum),0) as current_sum\r\n\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n  )\r\nSELECT CASE\r\n    WHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\") END AS Differenz,\r\nFROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Web')), 'Web')\r\nFROM(\r\nSELECT 'Web' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  SUM(COALESCE(m_visits,0)) as m_visits\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}),\r\na as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\r\nSELECT  w.m_visits as Web, a.m_visits as App\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "  SELECT ROUND(SUM(m_page_loads)/SUM(m_visits),1) as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($webFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n    ) "
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT SUM(m_page_loads)/SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $webFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n),\r\na as (\r\n  SELECT SUM(m_page_loads)/SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter\r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n)\r\nSELECT  w.m_visits as Web, a.m_visits as App\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  SUM(m_time_spent_per_visits/1000 * m_visits)/SUM(m_visits) as id\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} AND $webFilter "
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits)/SUM(m_visits) as Zeitraum, 1 as id\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} AND $webFilter \r\n),\r\na as(\r\n   SELECT  SUM(m_time_spent_per_visits/1000 * m_visits)/SUM(m_visits) as Zeitraum, 1 as id\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} AND $appFilter \r\n)\r\nSELECT  w.Zeitraum as Web, a.Zeitraum as App\r\nFROM w \r\nJOIN a ON w.id = a.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n  WHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} AND $avwebFilter\r\n      AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as \r\n(\r\n  SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`  \r\n  WHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} AND $avwebFilter\r\n      AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n),\r\napp as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum, 1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio OR $av_app_condition_video)\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n )\r\nSELECT SUM(web.Zeitraum) as Web, SUM(app.Zeitraum) as App\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('App')), 'App')\r\nFROM(\r\nSELECT 'App' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  SUM(m_visits) as m_visits\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "  SELECT ROUND(SUM(m_page_loads)/SUM(m_visits),1) as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($appFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n    ) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  SUM(m_time_spent_per_visits/1000 * m_visits)/SUM(m_visits) as id\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} AND $appFilter "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio OR $av_app_condition_video)\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 37 },
   "options": {
    "content": "Hinweis: Momentan keine Web-AV-Messung für die NDR Länder möglich."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 } },
  { "title": "Top Artikel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Top Artikel",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT publishing_date, content_id_sophora, content_titel, url, IFNULL(SUM(m_visits),0) as m_visits, IFNULL(SUM(m_page_loads),0) as m_page_loads, uuid, page_chapter1 as Kapitel FROM(\r\n  SELECT   \r\n    FIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as publishing_date,\r\n    FIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_id_sophora,\r\n    FIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_titel, \r\n    FIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as url, \r\n    m_visits,\r\n    m_page_loads, \r\n    uuid,\r\n    page_chapter1\r\n  from `ndr-code-bi-dashboard.Piano.articles${articleTable}` \r\n  WHERE \r\n    $listwebFilter \r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n    AND objekt_typ NOT LIKE 'indexPage'\r\n    AND content_id_sophora NOT LIKE '%index%'\r\n    AND content_id_sophora NOT LIKE '%N/A%'\r\n    AND content_id_sophora NOT LIKE '%verteilseite%'\r\n    AND content_id_sophora NOT LIKE '%nachrichtenfeed%'\r\n    )\r\n    GROUP BY uuid, publishing_date, content_id_sophora, content_titel, url, page_chapter1\r\n),\r\napp as (\r\n  SELECT IFNULL(SUM(m_visits),0) as m_visits, publishing_date, content_id_sophora, content_titel, url, IFNULL(SUM(m_page_loads),0) as m_page_loads, uuid FROM (\r\n  SELECT \r\n    m_visits, \r\n    FIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as publishing_date,\r\n    FIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_id_sophora,\r\n    FIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_titel, \r\n    FIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as url, \r\n    m_page_loads, \r\n    uuid\r\n  from `ndr-code-bi-dashboard.Piano.articles${articleTable}` \r\n  WHERE CONTAINS_SUBSTR(site_level2, '$app_name')\r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n  AND content_id_sophora NOT LIKE '%index%'\r\n  AND content_id_sophora NOT LIKE '%N/A%'\r\n   AND (\r\n        CASE \r\n            WHEN \"$LRA\" = 'NDR' THEN\r\n                content_titel NOT LIKE '%Video Livestream%'\r\n            AND content_titel NOT LIKE '%Startteaser%'\r\n            AND content_titel NOT LIKE '%startteaser%'\r\n            AND content_titel NOT LIKE '%-Anmelden%'\r\n            AND content_titel NOT LIKE '%_Start'\r\n            AND content_titel != 'Anmelden'\r\n            AND content_titel != 'Jetzt läuft'\r\n        ELSE\r\n          TRUE\r\n        END))\r\n  GROUP BY uuid, publishing_date, content_id_sophora, content_titel, url\r\n  ),\r\nsum_raw as (\r\n  SELECT \r\n  IFNULL(web.publishing_date, app.publishing_date) as publishing_date,\r\n  IFNULL(web.content_titel, app.content_titel) as content_titel, \r\n  IFNULL(web.content_id_sophora,app.content_id_sophora) as content_id_sophora, \r\n  IFNULL(web.url, app.url) as url,\r\n  IFNULL(web.uuid, app.uuid) as uuid,\r\n  IFNULL(web.m_visits,0) as visits_web, \r\n  IFNULL(app.m_visits,0) as visits_app, \r\n  IFNULL(web.m_page_loads,0) as page_web, \r\n  IFNULL(app.m_page_loads,0) as page_app, \r\n  Kapitel\r\n  FROM web\r\n  FULL JOIN app \r\n  ON web.uuid = app.uuid\r\n)\r\nSELECT \r\n  IF(LENGTH(MAX(publishing_date)) > 4,FORMAT_DATETIME('%d.%m.%Y | %R Uhr', DATETIME(MAX(publishing_date))),MAX(publishing_date)) as Datum, \r\n  content_titel as Artikel, \r\n  content_id_sophora as Sophora, \r\n  MAX(url) as url, \r\n  visits_web + visits_app as Visits, \r\n  visits_web as visits_web, \r\n  visits_app as visits_app, \r\n  page_web + page_app as page_views, \r\n  page_web as page_web, \r\n  page_app as page_app, \r\n  Kapitel\r\nFROM sum_raw\r\nGROUP BY content_titel,  content_id_sophora, uuid, Visits, visits_web, visits_app, page_views, page_web, page_app, Kapitel\r\nORDER BY Visits DESC\r\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 } },
  { "title": "AV KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 58 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 4, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Video - Wiedergaben')), 'Video - Wiedergaben')\r\nFROM(\r\nSELECT 'Video - Wiedergaben' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio - Wiedergaben')), 'Audio - Wiedergaben')\r\nFROM(\r\nSELECT 'Audio - Wiedergaben' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Bei den Ländern vom NDR: Keine Web-AV-Messung möglich.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Web & App')), 'Web & App')\r\nFROM(\r\nSELECT 'Web & App' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "NDR Länder: Keine Web-AV-Messung möglich.",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND $av_app_condition_video\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND $av_app_condition_video\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND $av_app_condition_audio\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND $av_app_condition_audio\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\n  with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND $av_app_condition_video\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as past_sum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n),\r\ncurrent_value AS (\r\n  with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND $av_app_condition_video\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as current_sum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n  )\r\nSELECT CASE\r\n    WHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\") END,\r\nFROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\r\n  with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve_comp}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND $av_app_condition_audio\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as past_sum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n),\r\ncurrent_value AS (\r\nwith web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND $av_app_condition_audio\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as current_sum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n  )\r\nSELECT CASE\r\n    WHEN current_sum / past_sum - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\")\r\n    ELSE CONCAT(REPLACE(CAST(ROUND((current_sum / past_sum - 1) * 100,1) AS STRING),\".\",\",\"),\"%\") END,\r\nFROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Web')), 'Web')\r\nFROM(\r\nSELECT 'Web' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "NDR Länder: Keine Web-AV-Messung möglich.",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND $av_app_condition_video\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) AS Web, IFNULL(SUM(app.Zeitraum),0) as App\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}` \r\nWHERE \r\n$avwebFilter And\r\ndate >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND $av_app_condition_audio\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) AS Web, IFNULL(SUM(app.Zeitraum),0) as App\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('App')), 'App')\r\nFROM(\r\nSELECT 'App' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND $av_app_condition_video\r\n    AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE ${av_condition} \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\nAND $av_app_condition_audio\r\n\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 75 },
   "options": {
    "content": "Hinweis: Momentan keine Web-AV-Messung für die NDR Länder möglich."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 77 } },
  { "title": "Top AV on Demand", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Top AV on Demand",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT bi_av_publication_date,\r\n  bi_av_content, \r\n  bi_av_content_id,\r\n  bi_av_url as url,\r\n  sum(m_av_playbacks) as wiedergabe,\r\n  CONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nSUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n   FROM(\r\n  SELECT \r\n    FIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date,\r\n    CAST(FIRST_VALUE(av_content_duration) OVER (PARTITION BY bi_av_content_id ORDER BY bi_av_publication_date DESC)/1000 AS INT) as av_content_duration,\r\n    m_av_playbacks,\r\n    --CAST(av_content_duration/1000 AS INT) as av_content_duration,\r\n    bi_av_content_id,\r\n    m_av_average_playback_completion_rate,\r\n    bi_av_broadcasting_type,\r\n    FIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\n    FIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n    av_content_type\r\n  from\r\n    `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE\r\n    $avwebFilter\r\n    AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n    AND bi_av_content_id NOT LIKE '%index%'\r\n    AND bi_av_broadcasting_type = \"ondemand\"\r\n    )\r\n    WHERE m_av_playbacks > 0\r\n  GROUP By\r\n    bi_av_publication_date,bi_av_content,av_content_duration, av_content_type,\r\n    bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n),\r\napp as (\r\nSELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe, \r\nCONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nCASE \"$LRA\"\r\nWHEN \"NDR\" THEN NULL\r\nELSE 100*SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) END as wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE($av_pub_date) OVER (PARTITION BY bi_av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_publication_date,  \r\nCOALESCE(m_playbutton,m_av_playbacks) as m_av_playbacks, \r\nCASE  \r\n      WHEN av_content_duration is NULL THEN NULL\r\n      ELSE CAST((av_content_duration/1000) AS INT) END av_content_duration,\r\n--CAST((av_content_duration/1000) AS INT) as av_content_duration,  \r\nm_av_average_playback_completion_rate, \r\nCOALESCE(objekt_typ, av_content_type) as av_content_type,  --objekt_typ ist die neue Variable anstelle content_typ\r\nCOALESCE(content_id_sophora, bi_av_content_id) as bi_av_content_id,  \r\nCOALESCE(objekt_typ ,bi_av_broadcasting_type) as bi_av_broadcasting_type ,  \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_url,  \r\n\r\n--device_type,\r\nFIRST_VALUE($av_content) OVER (PARTITION BY COALESCE(content_id_sophora,bi_av_content_id) ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_content  \r\nFROM \r\n`ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\nWHERE ${av_condition}\r\nAND COALESCE(content_id_sophora, bi_av_content_id) NOT LIKE '%index%'  \r\nAND COALESCE(objekt_typ, bi_av_broadcasting_type) IN $av_on_demand_filter  \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})  \r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,av_content_duration,av_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n),\r\nsum_raw as (\r\n  SELECT\r\n    IFNULL(\r\n      web.bi_av_publication_date,\r\n      app.bi_av_publication_date\r\n    ) as Publiziert,\r\n    IFNULL(web.bi_av_content, app.bi_av_content) as Titel,\r\n    IFNULL(web.bi_av_content_id, app.bi_av_content_id) as bi_av_content_id,\r\n    IFNULL(web.av_content_duration, app.av_content_duration) as av_content_duration,\r\n    IFNULL(web.url, app.url) as url,\r\n    IFNULL(web.wiedergabe, 0) as playbacks_web,\r\n    IFNULL(web.wiedergabe, 0) + IFNULL(app.wiedergabe, 0) as playbacks,\r\n    IFNULL(app.wiedergabe, 0) as playbacks_app,\r\n    IFNULL(web.av_content_type, app.av_content_type) as av_content_type\r\n  FROM\r\n    web FULL\r\n    JOIN app ON web.bi_av_content_id = app.bi_av_content_id \r\n)\r\nSELECT\r\n  *\r\nFROM\r\nsum_raw\r\nORDER BY\r\n  playbacks DESC\r\nLIMIT\r\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 93 } },
  { "title": "Top AV Livestream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Top AV Livestream",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date, \r\nm_av_playbacks,\r\nav_content_type, bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\nCAST(av_content_duration/1000 AS INT) as av_content_duration,\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\nWHERE $avwebFilter\r\nAND bi_av_content_id NOT LIKE '%index%'\r\nAND bi_av_broadcasting_type = \"live\"\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url, av_content_duration\r\n),\r\napp_raw as (\r\n  SELECT\r\n    DATETIME(date) as time,\r\n    bi_av_publication_date,\r\n    av_content_duration,\r\n    bi_av_content_id,\r\n    IFNULL(m_av_playbacks, 0) as m_av_playbacks,\r\n    bi_av_content,\r\n    bi_av_url as url,\r\n    av_content_type\r\n  from\r\n    `ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\n  WHERE\r\n    ${av_condition}\r\n    AND (\r\n      bi_av_broadcasting_type LIKE 'live'\r\n      OR bi_av_broadcasting_type LIKE 'Live'\r\n    )\r\n    AND bi_av_content_id NOT LIKE '%index%'\r\n    AND $avzeitraumListe\r\n),\r\napp as (\r\n  SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE($av_pub_date) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_publication_date, \r\nCOALESCE(m_playbutton,m_av_playbacks) as m_av_playbacks,\r\nCOALESCE(content_typ, av_content_type) as av_content_type, $av_content_id as bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY $av_content ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_url, \r\nCAST(av_content_duration/1000 AS INT) as av_content_duration,\r\n\r\n--device_type,\r\nFIRST_VALUE($av_content) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_content, \r\nFROM \r\n`ndr-code-bi-dashboard.Piano.av${av_table_fever_curve}`\r\nWHERE ${av_condition}\r\nAND $av_content_id NOT LIKE '%index%'\r\nAND COALESCE(objekt_typ, bi_av_broadcasting_type) IN $av_live_stream_filter\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url, av_content_duration\r\n),\r\nsum_raw as (\r\n  SELECT\r\n    IFNULL(\r\n      web.bi_av_publication_date,\r\n      app.bi_av_publication_date\r\n    ) as bi_av_publication_date,\r\n    IFNULL(web.bi_av_content, app.bi_av_content) as content_titel,\r\n    --IFNULL(web.av_content_duration, app.av_content_duration) as av_content_duration,\r\n    IFNULL(web.bi_av_content_id, app.bi_av_content_id) as bi_av_content_id,\r\n    IFNULL(web.url, app.url) as url,\r\n    IFNULL(web.wiedergabe, 0) as playbacks_web,\r\n    IFNULL(app.wiedergabe, 0) as playbacks_app,\r\n    IFNULL(web.wiedergabe, 0) + IFNULL(app.wiedergabe, 0) as playbacks,\r\n    IFNULL(web.av_content_type, app.av_content_type) as av_content_type\r\n  FROM\r\n    web FULL\r\n    JOIN app ON web.bi_av_content_id = app.bi_av_content_id\r\n)\r\nSELECT\r\n  *\r\nFROM\r\nsum_raw\r\nORDER BY\r\n  playbacks DESC\r\nLIMIT\r\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 109 } },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Distribution nach Gerätetyp - $Zeitraum",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 14, "x": 5, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\nSELECT \r\n  SUM(m_visits) as visits, \r\n  device_type \r\nFROM\r\n  ${distro_table:raw}\r\nWHERE $webFilter \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND device_type NOT LIKE '%N/A%'\r\nAND CASE WHEN \r\n      site_level2 = \"mdr.de\" \r\n      THEN (distribution = \"web\" OR distribution =\"amp\")\r\n      ELSE 1=1 END \r\nGROUP BY device_type),\r\napp as (\r\nSELECT\r\ndevice_type,\r\nSUM(m_visits) as visits\r\nFROM\r\n  ${distro_table:raw}\r\nWHERE $appFilter\r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \r\n  AND device_type NOT LIKE '%N/A%'\r\nGROUP BY device_type \r\n)\r\nSELECT IFNULL(web.visits,0) + IFNULL(app.visits,0) as visits, IFNULL(web.device_type,app.device_type) as device_type\r\nFROM web\r\nFULL JOIN app\r\nUSING(device_type)\r\n"
    }
   ]
  }
 ]
}