{
 "title": "Podcast MDR - Abfragen Optimieren (30.04.2025)",
 "description": "Mapping included",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "label": "LRA:",
    "query": {}
   },
   {
    "name": "datenstand",
    "query": {}
   },
   {
    "name": "Podcast_title",
    "query": {}
   },
   {
    "name": "AllePodcastsCondition",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "Bereich",
    "label": "Bereich:",
    "query": {}
   },
   {
    "name": "Podcast",
    "label": "Podcast:",
    "query": {}
   },
   {
    "name": "Episode",
    "label": "Episode:",
    "query": {}
   },
   { "name": "filled_size_big", "query": "10" },
   { "name": "filled_size", "query": "20" },
   {
    "name": "filled_size_headline",
    "query": {}
   },
   {
    "name": "filled_size_headline_small",
    "query": {}
   },
   {
    "name": "broadcast_id_branding",
    "query": {}
   },
   {
    "name": "Image",
    "query": {}
   },
   {
    "name": "type",
    "query": {}
   },
   {
    "name": "NDR_default_image",
    "query": {}
   },
   {
    "name": "lastUpdate",
    "query": {}
   },
   {
    "name": "mapping_dataset",
    "query": {}
   },
   {
    "name": "MDR_default_image",
    "query": {}
   },
   {
    "name": "AllePodcasts",
    "label": "Podcastsuche:",
    "query": {}
   },
   {
    "name": "number_of_days",
    "query": {}
   },
   {
    "name": "dataset_suffix",
    "query": {}
   },
   {
    "name": "episode_dataset",
    "query": {}
   },
   {
    "name": "platform_dataset",
    "query": {}
   },
   {
    "name": "profiles_dataset",
    "query": {}
   },
   {
    "name": "hinweis",
    "query": {}
   },
   {
    "name": "fromDay",
    "query": {}
   },
   {
    "name": "toDay_NDR",
    "query": {}
   },
   {
    "name": "zeitraum_NDR",
    "query": {}
   },
   {
    "name": "HeuteDatum",
    "query": {}
   },
   {
    "name": "episodenschnitt_condition",
    "query": {}
   },
   {
    "name": "delay_text",
    "query": {}
   },
   {
    "name": "zeitraum_MDR",
    "query": {}
   },
   {
    "name": "zeitraum",
    "query": {}
   },
   {
    "name": "toDay_MDR",
    "query": {}
   },
   {
    "name": "toDay",
    "query": {}
   },
   {
    "name": "datenstand_not_formated",
    "query": {}
   },
   {
    "name": "Plattformen",
    "query": {}
   },
   {
    "name": "podcast_ids",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:rgba(38, 113, 198); color: white; text-align: center; vertical-align: middle; padding: 20px 0; margin-top: 0px; font-size: 15pt;\">\n  <font color=\"#FFFFFF\" size=\"5\">Servicemeldung:</font> <br>\n  <font color=\"#FFFFFF\" size=\"3\">\n    Seit Ende Januar 2025  – im Zuge der Veröffentlichung der neuen Android-App-Versionen für die ARD Audiothek – keine korrekte Zuordnung über UserAgent (Probleme über IOS bereits seit September). Die Audiotheks-Zugriffe sind weiterhin in der Gesamtsumme aller validen Downloads enthalten, die dezidiert für die Audiothek ausgewiesenen VD werden allerdings derzeit massiv unterschätzt.\n  </font>\n</div>\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 13, "y": 5 }, "options": { "content": " ${hinweis}" } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$Image\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('$Podcast_title'))), '$Podcast_title'), \nFROM(\nSELECT '$Podcast_title' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('QApps'),0)), 'Apps')\nFROM(\nSELECT 'Apps' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt im Analysezeitraum",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT \n    SUM(m_zugriffe_1) AS summe \n  FROM \n    $episode_dataset\n  WHERE \n    broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Durchschnitt pro Episode für die im ausgewählten Analysezeitraum veröffentlichten Episoden.",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT\n    SUM(m_zugriffe_1)/COUNT(DISTINCT headline) AS summe,\n  FROM \n    $episode_dataset as ed\n  LEFT JOIN \n    $profiles_dataset AS pd\n  USING(podcast_title)\n  WHERE \n    ed.broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    AND $episodenschnitt_condition\n    AND DATE(publication_date_1) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    AND publication_date_1 != '22-11-07 14:57:28.000'\n)"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "description": "Zugriffe über ausgewählte Apps auf Basis von User Agents. Im Vergleich zu den eigenen Metriken der jeweiligen Plattform-Anbieter kann es aufgrund verschiedener Messmethoden zu Abweichungen kommen.",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 10 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n    SUM(m_zugriffe_1) AS summe,\n    platform\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('ARD Audiothek')), 'ARD Audiothek')\nFROM(\nSELECT 'ARD Audiothek' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Spotify-Daten ab August 2023 verfügbar",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('Spotify')), 'Spotify')\nFROM(\nSELECT 'Spotify' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size - CHAR_LENGTH('Apple Podcasts'))), 'Apple Podcasts')\nFROM(\nSELECT 'Apple Podcasts' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE \n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset AS pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"ARD Audiothek\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"ARD Audiothek\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"Spotify\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"Spotify\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"Apple Podcasts\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"Apple Podcasts\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": {
    "content": "Letztes Update: <br> \r\n${lastUpdate}\r\n<br> <br> \r\nDatenstand: <br> \r\n${fromDay} – ${datenstand}"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Bereich: $Bereich'),0)), 'Bereich: $Bereich')\nFROM(\nSELECT 'Bereich: $Bereich' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Ausgewählte Episoden'),0)), 'Ausgewählte Episoden')\nFROM(\nSELECT 'Ausgewählte Episoden' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt aller Podcast-Reihen im ausgewählten Bereich",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT\n    SUM(m_zugriffe_1) AS summe\n  FROM \n    $episode_dataset\n  WHERE\n    (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt für die in der Navigation unter Episode ausgewählten Audios",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT \n    SUM(m_zugriffe_1) AS summe \n  FROM \n    $episode_dataset\n  WHERE \n    (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Durchschnitt pro Episode für die die in der Navigation unter Episode ausgewählten Audios ",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT \n    SAFE_DIVIDE(SUM(m_zugriffe_1),COUNT(DISTINCT headline)) AS summe \n  FROM \n    $episode_dataset\n  WHERE \n    (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n    AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 }, "options": { "content": "${delay_text}" } },
  {
   "title": "Zugriffe pro Tag für \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n    date,\n    SUM(CASE WHEN platform = 'ARD Audiothek' THEN m_zugriffe_1 ELSE 0 END) AS ard_summe,\n    SUM(CASE WHEN platform = 'Apple Podcasts' THEN m_zugriffe_1 ELSE 0 END) AS apple_summe,\n    SUM(CASE WHEN platform = 'Spotify' THEN m_zugriffe_1 ELSE 0 END) AS spotify_summe,\n    SUM(CASE WHEN platform NOT IN ('ARD Audiothek', 'Spotify', 'Apple Podcasts') THEN m_zugriffe_1 ELSE 0 END) AS rest_summe,\n    SUM(m_zugriffe_1) as zugriffe,\n    \"${type}\" as type,\n    DATE_DIFF(DATE('${__to:date}', \"Europe/Berlin\"),DATE('${__from:date}', \"Europe/Berlin\"),DAY) + 1 as timeRange\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY date\nORDER BY date ASC"
    }
   ]
  },
  {
   "title": "Top 3 Episoden von \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  headline,\n  SUM(m_zugriffe_1) AS zugriffe,\nFROM $episode_dataset\nWHERE \n  broadcast_id IN ($podcast_ids)\n  AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY headline\nORDER BY zugriffe DESC\nLIMIT 3"
    }
   ]
  },
  {
   "title": "Episoden",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  podcast_title,\n  headline,\n  publication_date_1,\n  SUM(m_zugriffe_1) as zugriffe\nFROM $episode_dataset\nWHERE \n  (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n  AND (\"\"\"$Podcast\"\"\" = \"All titles\" OR REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY[$Episode]))\n  AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY podcast_title, headline, publication_date_1\nORDER BY zugriffe DESC"
    }
   ]
  },
  {
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n    podcast_title AS Title,\n    SUM(CASE WHEN platform = 'ARD Audiothek' THEN m_zugriffe_1 ELSE NULL END) AS ard_summe,\n    SUM(CASE WHEN platform = 'Apple Podcasts' THEN m_zugriffe_1 ELSE NULL END) AS apple_summe,\n    SUM(CASE WHEN platform = 'Spotify' THEN m_zugriffe_1 ELSE NULL END) AS spotify_summe,\n    SUM(m_zugriffe_1) AS zugriffe,\nFROM \n    $platform_dataset AS platform_table\nLEFT JOIN $profiles_dataset AS profiles_table\nON platform_table.broadcast_id = profiles_table.broadcast_id[0]\nWHERE\n    platform_table.broadcast_id IN ($podcast_ids)\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY podcast_title\nORDER BY zugriffe DESC"
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zugriffe pro Tag für \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n    date,\n    \"${type}\" as type,\n    SUM(m_zugriffe_1) AS zugriffe,\n    \"$Plattformen\" as platform,\n    DATE_DIFF(DATE('${__to:date}', \"Europe/Berlin\"),DATE('${__from:date}', \"Europe/Berlin\"),DAY) + 1 as timeRange\nFROM \n    $platform_dataset\nWHERE\n    broadcast_id IN ($podcast_ids)\n    AND (\"$Plattformen\" = \"Alle Plattformen\" OR platform = \"$Plattformen\")\n    AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY date\nORDER BY date ASC"
    }
   ]
  }
 ]
}