{
 "title": "Social Media Report YouTube",
 "time": { "from": "2023-08-01T09:02:19.304Z", "to": "2023-09-02T09:02:19.304Z" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "lastMonth",
    "query": {}
   },
   {
    "name": "lastMonthShort",
    "query": {}
   },
   {
    "name": "earliestLastUpdate",
    "query": {}
   },
   {
    "name": "Monat",
    "query": "Januar : 1, Februar :  2, März : 3, April : 4, Mai : 5, Juni : 6, Juli : 7, August : 8, September : 9, Oktober : 10, November : 11, Dezember : 12, Jahr : 13"
   },
   {
    "name": "Jahr",
    "query": "2022 : 2022, 2023 : 2023, 2024 : 2024"
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "profiles",
    "query": {}
   },
   {
    "name": "query0",
    "query": {}
   },
   {
    "name": "query1",
    "query": {}
   },
   {
    "name": "Month",
    "query": {}
   },
   {
    "name": "Month_1",
    "query": {}
   },
   {
    "name": "Day_number",
    "query": {}
   },
   {
    "name": "Monat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastMonat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastJahr",
    "query": {}
   },
   {
    "name": "YearFromLastMonth",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "MonatMinusOne",
    "query": {}
   },
   {
    "name": "MonatMinusOneName",
    "query": {}
   },
   {
    "name": "stichtagmonat",
    "query": {}
   },
   {
    "name": "Vergleich",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": {}
   },
   {
    "name": "Stichtag",
    "query": {}
   },
   {
    "name": "Vormonat",
    "query": {}
   },
   {
    "name": "topvideos_dataset",
    "query": {}
   },
   {
    "name": "comp_dataset",
    "query": {}
   },
   {
    "name": "dataset_suffix",
    "query": {}
   },
   {
    "name": "table_suffix",
    "query": {}
   },
   {
    "name": "topvideos_suffix",
    "query": {}
   },
   {
    "name": "comp_dataset_suffix",
    "query": {}
   },
   {
    "name": "comp_table_suffix",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Hinweise",
   "type": "text",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "- Durch nachträgliche Importe und Speicherung der Daten kann es im Vergleich mit anderen Stichtags-Erhebungen (z.B. den Berichten der Medienforschungen) Abweichungen bei den Daten geben."
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--IF ${LRA:doublequote} = \"MDR\"\n--THEN \n--SELECT COUNT(profile) FROM `ndr-code-bi-dashboard.Quintly.profiles` WHERE LRA = 'MDR' AND youtubeId != 0 \n--;\n--ELSE\n--SELECT COUNT(profile) FROM `ndr-code-bi-dashboard.Quintly.profiles` WHERE LRA = 'NDR' AND youtubeId != 0\n--;\n--END IF\n\nSELECT COUNT(DISTINCT profile) \nFROM `ndr-code-bi-dashboard.Quintly.profiles` \nWHERE LRA = '$LRA' AND youtubeId != 0 \n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "Letzter Datenstand: </br>\n${stichtagmonat}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [
         { "name": "total_video_10s_views", "type": "functionParameter" }
        ],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "facebookInsightsOwnVideos"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 4 },
   "options": {
    "content": "# YouTube Report | ${Month}\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Entwicklung: Videostarts für Videos im Zeitraum genutzt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Summe Videostarts für Videos im Zeitraum genutzt (in Mio.)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(IFNULL(views,0))/1000000 as videoViews10sMill,\r\n  DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1) as month,\r\n \r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\nWHERE CASE \"${Monat:text}\"\r\n      WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr\r\n      ELSE DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1) <= DATE($Jahr, $Monat, 1) AND DATE(EXTRACT(YEAR from time),EXTRACT(MONTH from time), 1)  >= DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 12 MONTH) END \r\nGROUP BY month\r\nORDER BY month ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 10, "y": 7 },
   "options": {
    "content": "### Anteil Videostarts für Videos im Zeitraum genutzt | Top 8 | $Month\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "options": {
    "content": "### Videostarts für Videos im Zeitraum genutzt (in Mio.)\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- WITH filter_month_profiles as (SELECT\r\n--    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n--    SUM(IFNULL(page_video_views_10s,0)) as videoViews10s,\r\n--    CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) as month_year\r\n--  FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.facebookInsights${table_suffix}` AS facebook\r\n--  JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n--    ON facebook.profileId = profiles.facebookID\r\n--  WHERE profiles.LRA = \"$LRA\"\r\n--    AND EXTRACT(MONTH from time) = $Monat\r\n--    AND EXTRACT(YEAR from time) = $Jahr\r\n--  GROUP BY profile, month_year), filter_month_top_profiles as (\r\n--  SELECT\r\n--    month_year,\r\n--    profile,\r\n--    videoViews10s,\r\n--    ROW_NUMBER() OVER (PARTITION BY month_year ORDER BY videoViews10s DESC) AS profile_rank\r\n--  FROM filter_month_profiles\r\n-- ), filter_month_top_8_profiles AS (\r\n--  SELECT\r\n--    month_year,\r\n--    profile,\r\n--    videoViews10s\r\n--  FROM filter_month_top_profiles\r\n--  WHERE profile_rank <= 8\r\n--  ), filter_month_rest AS (\r\n--  SELECT\r\n--    month_year,\r\n--    'Rest' AS profile,\r\n--    SUM(videoViews10s) AS videoViews10s\r\n--  FROM filter_month_top_profiles\r\n--  WHERE profile_rank > 8\r\n--  GROUP BY month_year\r\n-- ), filter_month_top_8_rest_profiles AS (\r\n--   SELECT\r\n--    month_year,\r\n--    profile,\r\n--    videoViews10s\r\n--  FROM filter_month_top_8_profiles\r\n--  UNION ALL\r\n--  SELECT\r\n--    month_year,\r\n--    profile,\r\n--    videoViews10s\r\n--  FROM filter_month_rest\r\n--  ORDER BY month_year DESC, profile\r\n-- )\r\n-- SELECT profile, videoViews10s FROM filter_month_top_8_rest_profiles\r\n\r\n\r\n\r\nWITH filter_month_profiles as (SELECT\r\n   REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\n   SUM(IFNULL(views,0)) as Views,\r\n   CASE \"${Monat:text}\"\r\n   WHEN \"Jahr\" THEN \"year\"\r\n   ELSE CONCAT(EXTRACT(MONTH from time),'-',EXTRACT(YEAR from time)) END as month_year,\r\n   COUNT(DISTINCT time) as days\r\n FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` AS youtube\r\n JOIN `ndr-code-bi-dashboard.Quintly.profiles` AS profiles\r\n   ON youtube.profileId = profiles.youtubeID\r\n WHERE profiles.LRA = \"$LRA\"\r\n   AND $Zeitraum \r\n GROUP BY profile, month_year), filter_month_top_profiles as (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   Views,\r\n   days,\r\n   ROW_NUMBER() OVER (PARTITION BY month_year ORDER BY Views DESC) AS profile_rank\r\n FROM filter_month_profiles\r\n), filter_month_top_8_profiles AS (\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   Views,\r\n   days\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank <= 8\r\n ), filter_month_rest AS (\r\n SELECT\r\n   month_year,\r\n   'Rest' AS profile,\r\n   SUM(Views) AS Views,\r\n   MAX(days) AS days\r\n FROM filter_month_top_profiles\r\n WHERE profile_rank > 8\r\n GROUP BY month_year\r\n), filter_month_top_8_rest_profiles AS (\r\n  SELECT\r\n   month_year,\r\n   profile,\r\n   Views,\r\n   days\r\n FROM filter_month_top_8_profiles\r\n UNION ALL\r\n SELECT\r\n   month_year,\r\n   profile,\r\n   Views,\r\n   days\r\n FROM filter_month_rest\r\n ORDER BY month_year DESC, profile\r\n)\r\nSELECT profile, ROUND(Views) as Views FROM filter_month_top_8_rest_profiles"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 16, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Summe')), 'Summe')\r\nFROM(\r\nSELECT 'Summe' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Ø Pro Tag')), 'Ø Pro Tag')\r\nFROM(\r\nSELECT 'Ø Pro Tag' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "options": {
    "content": "## $Monat_abkuerzung\r\n## $Jahr"
   },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nvideoViews10sMill,\r\nvideoViews10sMill/days as videoViews10sMillPerDay\r\nFROM\r\n(SELECT\r\nSUM(IFNULL(views,0))/1000000 as videoViews10sMill,\r\nCOUNT(DISTINCT time) as days\r\n\r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND $Zeitraum\r\n)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
   "options": { "content": "${Vergleich}" },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS (\r\n  SELECT\r\n  SUM(IFNULL(views,0))/1000000 as past_sum_in_mil,\r\n  COUNT(DISTINCT time) as days\r\n  FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as youtube\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\n \r\n  WHERE True\r\n  AND CASE $Monat\r\n  WHEN 13 THEN TRUE\r\n  ELSE EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) END\r\n), past_value_per_day AS (\r\n  SELECT past_sum_in_mil/days as past_sum_per_day\r\n  FROM past_value_in_mil\r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(IFNULL(views,0))/1000000 as current_sum_in_mil,\r\n  COUNT(DISTINCT time) as days\r\n  FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as youtube\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr\r\n), current_value_per_day AS(\r\n  SELECT current_sum_in_mil/days as current_sum_per_day\r\n  FROM current_value_in_mil\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil, current_value_per_day, past_value_per_day"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 17 },
   "options": {
    "content": "## $Monat_abkuerzung\r\n## $LastJahr"
   },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))), CONCAT(\"$Monat_abkuerzung\", \" $Jahr\"))\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" $Jahr\") as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS (\r\n  SELECT\r\n  SUM(IFNULL(views,0))/1000000 as past_sum_in_mil,\r\n  COUNT(DISTINCT time) as days\r\n  FROM `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalytics${comp_table_suffix}` as youtube\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND CASE \"${Monat:text}\"\r\n  WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n  ELSE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr - 1 END\r\n), past_value_per_day AS (\r\n  SELECT past_sum_in_mil/days as past_sum_per_day\r\n  FROM past_value_in_mil\r\n), current_value_in_mil AS(\r\n  SELECT\r\n  SUM(IFNULL(views,0))/1000000 as current_sum_in_mil,\r\n  COUNT(DISTINCT time) as days\r\n  FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as youtube\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n  WHERE True\r\n  AND $Zeitraum \r\n), current_value_per_day AS(\r\n  SELECT current_sum_in_mil/days as current_sum_per_day\r\n  FROM current_value_in_mil\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil, current_value_per_day, past_value_per_day"
    }
   ]
  },
  { "title": "Abonnenten | ${Month}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Abonnements | Stichtag: $Stichtag ",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- IF $Monat <= $MonatMinusOne then\r\nSELECT\r\nprofile as Profil,\r\nsubscriberslifetime as Abonnements\r\nFROM `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n            WHERE $Zeitraum)\r\n\r\nORDER BY Abonnements desc\r\n-- ;\r\n-- else\r\n-- SELECT\r\n-- profile as Profil,\r\n-- subscribers as Abonnements\r\n-- FROM `ndr-code-bi-dashboard.Quintly.youtube` as youtube\r\n-- JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\n-- WHERE True\r\n-- AND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.Quintly.youtube` as youtube\r\n--             WHERE EXTRACT(MONTH from time) = $Monat AND EXTRACT(YEAR from time) = $Jahr)\r\n\r\n-- ORDER BY Abonnements desc\r\n-- ;\r\n-- end if\r\n-- ;"
    }
   ]
  },
  {
   "title": "Veränderung zum ${Vormonat} in %",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nlm.Profil,\r\n(lm_follower/llm_follower - 1)*100 as FollowerVeraenderung\r\nFROM\r\n(SELECT\r\nsubscribersLifetime as lm_follower,\r\nprofile as Profil\r\nFROM `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\nLEFT JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND time = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n            WHERE $Zeitraum)\r\n\r\nORDER BY subscribersLifetime desc) as lm\r\n\r\nRIGHT JOIN\r\n\r\n(SELECT\r\nsubscribersLifetime as llm_follower,\r\nprofile as Profil\r\nFROM `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n-- FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtube${table_suffix}` as youtube\r\nRIGHT JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\nAND\r\ntime = (SELECT MAX(time) FROM `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n            WHERE CASE \"${Monat:text}\"\r\n            WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n            ELSE EXTRACT(MONTH from time) = EXTRACT(MONTH from DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH) ) AND EXTRACT(YEAR from time) = EXTRACT(YEAR from DATE_SUB(DATE($Jahr,$Monat,1), INTERVAL 1 MONTH)) END)\r\nORDER BY subscribersLifetime desc) as llm ON llm.Profil = lm.Profil\r\nORDER BY lm.lm_follower DESC\r\n"
    }
   ]
  },
  {
   "title": "Videostarts für Videos im Zeitraum genutzt |  ${Month}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Videostarts für Videos im Zeitraum genutzt",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nprofile as Profil,\r\nSUM(IFNULL(views,0))/1 as videoViews\r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE True\r\n\r\nAND $Zeitraum\r\nGROUP BY profile\r\nORDER BY videoViews desc\r\n"
    }
   ]
  },
  {
   "title": "Gesamte Wiedergabedauer für Videos im Zeitraum genutzt | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "Gesamte Wiedergabedauer in Stunden für Videos im Zeitraum genutzt",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  CAST(\r\n    ROUND(SUM(estimatedMinutesWatched) /(60)) as INT64\r\n  ) as sehVolumen,\r\n  profile as Profil\r\n\r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE\r\n  True\r\n  AND $Zeitraum\r\nGROUP BY\r\n  profile\r\nORDER BY\r\n  sehVolumen desc "
    }
   ]
  },
  {
   "title": "Top Videos nach Videostarts (Videos im Zeitraum genutzt) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "Top Videos im Zeitraum genutzt | ${Month}",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nprofile as Profil,\r\nyoutube.time as Datum,\r\nCONCAT(\r\n  CASE WHEN LENGTH(CAST(DIV(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(duration,60) AS String)) ELSE CAST(DIV(duration,60) AS String)  END ,\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(duration,60) AS String)) ELSE CAST(MOD(duration,60) AS String)  END) as Dauer,\r\n  CONCAT(\r\n  CASE WHEN LENGTH(CAST(DIV(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(averageViewDuration,60) AS String)) ELSE CAST(DIV(averageViewDuration,60) AS String)  END ,\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(averageViewDuration,60) AS String)) ELSE CAST(MOD(averageViewDuration,60) AS String)  END) as averageViewTime,\r\n  Round(estimatedMinutesWatched/60,0) as sehVolumen,\r\n   title,\r\nviews, \r\nlink,\r\nlikes + \r\ndislikes +\r\ncomments +\r\nshares as interactions,\r\nREGEXP_REPLACE(FORMAT('%0.1f', averageViewPercentage), r'\\.', ',') AS averageViewPercentage,\r\nabo_change,\r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsTopVideos${topvideos_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\nAND True\r\nORDER BY views DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Top One Video je Kanal (Videos im Zeitraum genutzt) |  $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "Top One Video im Zeitraum genutzt je Kanal | $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DISTINCT\r\n  Profil,\r\n  Datum,\r\n  Titel,\r\n  Wiedergaben,\r\n  link,\r\n  Dauer,\r\n  Round(sehVolumen,0) as sehVolumen,\r\n  -- averageViewPercentage,\r\n  REGEXP_REPLACE(FORMAT('%0.1f', averageViewPercentage), r'\\.', ',') AS averageViewPercentage,\r\nFROM (\r\n  SELECT \r\n  profile as Profil,\r\n  time as Datum,\r\nCONCAT(\r\n  CASE WHEN LENGTH(CAST(DIV(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(duration,60) AS String)) ELSE CAST(DIV(duration,60) AS String)  END ,\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(duration,60) AS String)) ELSE CAST(MOD(duration,60) AS String)  END) as Dauer,\r\n  CONCAT(\r\n  CASE WHEN LENGTH(CAST(DIV(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(averageViewDuration,60) AS String)) ELSE CAST(DIV(averageViewDuration,60) AS String)  END ,\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(averageViewDuration,60) AS String)) ELSE CAST(MOD(averageViewDuration,60) AS String)  END) as averageViewTime,\r\n  estimatedMinutesWatched/60 as sehVolumen,\r\n  title as Titel,\r\n  views as Wiedergaben,\r\n  youtube.link,\r\n  averageViewPercentage,\r\n    ROW_NUMBER() OVER (PARTITION BY profiles.youtubeID ORDER BY \r\n      views DESC) as row_num\r\n  FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsTopVideos${topvideos_suffix}` as youtube\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n  \r\n  -- WHERE True\r\n  AND True\r\n) as subquery\r\nWHERE row_num = 1\r\nORDER BY Wiedergaben DESC\r\n"
    }
   ]
  },
  {
   "title": "Zusammenfassung aller Kanäle (Videos im Zeitraum genutzt) | $Monat $Jahr ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 }
  },
  {
   "title": "Zusammenfassung aller Kanäle | $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH followers as (\r\n  SELECT\r\n    lm.Profil,\r\n    lm_follower as followers,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE IFNULL(lm_follower - llm_follower,lm_follower) END  as FollowerVeraenderungAbsolut,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE (SAFE_DIVIDE(lm_follower, llm_follower) -1) * 100 END as FollowerVeraenderung\r\n  FROM\r\n    (\r\n      SELECT\r\n        subscriberslifetime lm_follower,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND time = (\r\n          SELECT\r\n            MAX(time)\r\n          FROM\r\n            `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n          WHERE $Zeitraum \r\n        )\r\n      ORDER BY\r\n        subscriberslifetime desc\r\n    ) as lm\r\n    LEFT JOIN (\r\n      SELECT\r\n        subscriberslifetime as llm_follower,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalytics${comp_table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND time = (\r\n          SELECT\r\n            MAX(time)\r\n          FROM\r\n            `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalytics${comp_table_suffix}` as youtube\r\n          WHERE CASE \"${Monat:text}\"\r\n          WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n          ELSE\r\n            EXTRACT(\r\n              MONTH\r\n              from\r\n                time\r\n            ) = EXTRACT(\r\n              MONTH\r\n              from\r\n                DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n            )\r\n            AND EXTRACT(\r\n              YEAR\r\n              from\r\n                time\r\n            ) = EXTRACT(\r\n              YEAR\r\n              from\r\n                DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n            ) END\r\n        )\r\n      ORDER BY\r\n        subscriberslifetime desc\r\n    ) as llm ON llm.Profil = lm.Profil\r\n  ORDER BY\r\n    lm.lm_follower DESC\r\n),\r\nvideo_start as (\r\n  SELECT\r\n    lm.Profil,\r\n    lm_videoViews10s as videoViews10s,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE IFNULL(lm_videoViews10s - llm_videoViews10s, lm_videoViews10s) END as videoViews10sVeraenderungAbsolut,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE (\r\n      SAFE_DIVIDE(lm_videoViews10s, llm_videoViews10s) -1\r\n    ) * 100 END as videoViews10sVeraenderung\r\n  FROM\r\n    (\r\n      SELECT\r\n        SUM(views) as lm_videoViews10s,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND $Zeitraum\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        lm_videoViews10s DESC\r\n    ) as lm\r\n    LEFT JOIN (\r\n      SELECT\r\n        profile as Profil,\r\n        SUM(views) as llm_videoViews10s,\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalytics${comp_table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND CASE \"${Monat:text}\" \r\n        WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n        ELSE EXTRACT(\r\n          MONTH\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          MONTH\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        )\r\n        AND EXTRACT(\r\n          YEAR\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          YEAR\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        ) END \r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        llm_videoViews10s DESC\r\n    ) as llm ON llm.Profil = lm.Profil\r\n  ORDER BY\r\n    lm.lm_videoViews10s DESC\r\n),\r\nsehVolumen as (\r\n  SELECT\r\n    lm.Profil,\r\n    lm_sehVolumenVariable as sehVolumenVariable,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE IFNULL(lm_sehVolumenVariable - llm_sehVolumenVariable, lm_sehVolumenVariable) END as sehVolumenVariableVeraenderungAbsolut,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE\r\n    (\r\n      SAFE_DIVIDE(lm_sehVolumenVariable, llm_sehVolumenVariable) -1\r\n    ) * 100 END as sehVolumenVariableVeraenderung\r\n  FROM\r\n    (\r\n      SELECT\r\n        CAST(ROUND(SUM(estimatedMinutesWatched) /(60)) as INT64\r\n  ) as lm_sehVolumenVariable,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND $Zeitraum\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        lm_sehVolumenVariable\r\n        DESC\r\n    ) as lm\r\n    LEFT JOIN (\r\n      SELECT\r\n        profile as Profil,\r\n        CAST(\r\n    ROUND(SUM(estimatedMinutesWatched) /(60)) as INT64\r\n  ) as llm_sehVolumenVariable,\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalytics${comp_table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND CASE \"${Monat:text}\"\r\n        WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n        ELSE EXTRACT(\r\n          MONTH\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          MONTH\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        )\r\n        AND EXTRACT(\r\n          YEAR\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          YEAR\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        ) END\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        llm_sehVolumenVariable\r\n        DESC\r\n    ) as llm ON llm.Profil = lm.Profil\r\n  ORDER BY\r\n    lm.lm_sehVolumenVariable\r\n    DESC\r\n),\r\ninteractionen as (\r\n  SELECT\r\n    lm.Profil,\r\n    lm_interactionenVariable as interactionenVariable,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE\r\n    IFNULL(lm_interactionenVariable - llm_interactionenVariable,lm_interactionenVariable) END as interactionenVariableVeraenderungAbsolut,\r\n    CASE WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE\r\n    (\r\n      SAFE_DIVIDE(lm_interactionenVariable, llm_interactionenVariable) -1\r\n    ) * 100 END as interactionenVariableVeraenderung\r\n  FROM\r\n    (\r\n      SELECT\r\n       IFNULL(SUM(likes + dislikes + comments + shares),0)as lm_interactionenVariable,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND $Zeitraum\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        lm_interactionenVariable\r\n        DESC\r\n    ) as lm\r\n    LEFT JOIN (\r\n      SELECT\r\n        profile as Profil,\r\n        IFNULL(SUM(likes + dislikes + comments + shares),0) as llm_interactionenVariable,\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalytics${comp_table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND CASE \"${Monat:text}\"\r\n        WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n        ELSE EXTRACT(\r\n          MONTH\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          MONTH\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        )\r\n        AND EXTRACT(\r\n          YEAR\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          YEAR\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        ) END\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        llm_interactionenVariable\r\n        DESC\r\n    ) as llm ON llm.Profil = lm.Profil\r\n  ORDER BY\r\n    lm.lm_interactionenVariable\r\n    DESC\r\n) \r\nSELECT\r\n  followers.Profil,\r\n  followers.followers,\r\n  followers.FollowerVeraenderungAbsolut,\r\n  followers.FollowerVeraenderung,\r\n  video_start.videoViews10s,\r\n  video_start.videoViews10sVeraenderungAbsolut,\r\n  video_start.videoViews10sVeraenderung,\r\n  sehVolumen.sehVolumenVariable,\r\n  sehVolumen.sehVolumenVariableVeraenderungAbsolut,\r\n  sehVolumen.sehVolumenVariableVeraenderung,\r\n  interactionen.interactionenVariable,\r\n  interactionen.interactionenVariableVeraenderungAbsolut,\r\n  interactionen.interactionenVariableVeraenderung,\r\nFROM\r\n  followers\r\n  JOIN video_start ON followers.Profil = video_start.Profil\r\n  JOIN sehVolumen ON followers.Profil = sehVolumen.Profil\r\n  JOIN interactionen ON followers.Profil = interactionen.Profil\r\n\r\n\r\n "
    }
   ]
  },
  {
   "title": "Videostarts für Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 }
  },
  {
   "title": "Videostarts für Videos im Zeitraum veröffentlicht",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nSELECT \r\nprofile as Profil,\r\nSUM(IFNULL(views,0)) as videoViews\r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n-- WHERE True\r\nAND $Zeitraum\r\nGROUP BY profile\r\nORDER BY videoViews desc\r\n"
    }
   ]
  },
  {
   "title": "Veröffentlichte Videos | $Monat $Jahr​",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "Select Profil, profileIdSum\r\nFrom(\r\nSELECT \r\nprofile as Profil,\r\nSUM(IFNULL(views,0)) as videoViews,\r\nCOUNT(DISTINCT externalId) as profileIdSum\r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\nWHERE True\r\nAND $Zeitraum\r\nAND duration > 0\r\nGROUP by Profil\r\nOrder by videoViews Desc\r\n)\r\n-- GROUP BY Profil\r\n-- ORDER BY profileIdSum desc\r\n--Order by anzahlPosts ASC\r\n\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Gesamte Wiedergabedauer für Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 }
  },
  {
   "title": "Gesamte Wiedergabedauer in Stunden für Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat)​",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\n  SELECT\r\n  CAST(\r\n    ROUND(SUM(estimatedMinutesWatched) /(60)) as INT64\r\n  ) as sehVolumen,\r\n  profile as Profil\r\n\r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\nWHERE\r\n  True\r\n  AND $Zeitraum\r\nGROUP BY\r\n  profile\r\nORDER BY\r\n  sehVolumen desc \r\n  -- ;\r\n  -- END IF;"
    }
   ]
  },
  {
   "title": "Top Videos nach Videostarts Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 }
  },
  {
   "title": "Top Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nprofile as Profil,\r\nyoutube.time as Datum,\r\nCONCAT(\r\n  CASE WHEN LENGTH(CAST(DIV(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(duration,60) AS String)) ELSE CAST(DIV(duration,60) AS String)  END ,\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(duration,60) AS String)) ELSE CAST(MOD(duration,60) AS String)  END) as Dauer,\r\n  CONCAT(\r\n  CASE WHEN LENGTH(CAST(DIV(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(averageViewDuration,60) AS String)) ELSE CAST(DIV(averageViewDuration,60) AS String)  END ,\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(averageViewDuration,60) AS String)) ELSE CAST(MOD(averageViewDuration,60) AS String)  END) as averageViewTime,\r\n  Round(estimatedMinutesWatched/60,0) as sehVolumen,\r\n   title,\r\nviews,\r\nlink,\r\nlikes +\r\ndislikes +\r\ncomments +\r\nshares as interactions,\r\n-- averageViewPercentage,\r\nREGEXP_REPLACE(FORMAT('%0.1f', averageViewPercentage), r'\\.', ',') AS averageViewPercentage,\r\nabo_change,\r\nFROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\nJOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n\r\nAND $Zeitraum\r\nORDER BY views DESC LIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "Top One Video  je Kanal Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 }
  },
  {
   "title": "Top One Video im Zeitraum veröffentlicht je Profil (Nutzung bis zum Stichtag $stichtagmonat) |  $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 181 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- If $Monat >= 5\r\n-- THEN\r\n-- SELECT DISTINCT\r\n--   Profil,\r\n--   Datum,\r\n--   Titel,\r\n--   Wiedergaben,\r\n--   link,\r\n--   Dauer,\r\n--   sehVolumen,\r\n--   averageViewPercentage,\r\n-- FROM (\r\n--   SELECT \r\n--   profile as Profil,\r\n--   youtube.time as Datum,\r\n-- CONCAT(\r\n--   CASE WHEN LENGTH(CAST(DIV(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(duration,60) AS String)) ELSE CAST(DIV(duration,60) AS String)  END ,\r\n--   \":\",CASE WHEN LENGTH(CAST(MOD(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(duration,60) AS String)) ELSE CAST(MOD(duration,60) AS String)  END) as Dauer,\r\n--   CONCAT(\r\n--   CASE WHEN LENGTH(CAST(DIV(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(averageViewDuration,60) AS String)) ELSE CAST(DIV(averageViewDuration,60) AS String)  END ,\r\n--   \":\",CASE WHEN LENGTH(CAST(MOD(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(averageViewDuration,60) AS String)) ELSE CAST(MOD(averageViewDuration,60) AS String)  END) as averageViewTime,\r\n--   estimatedMinutesWatched/60 as sehVolumen,\r\n--   title as Titel,\r\n--   views as Wiedergaben,\r\n--   youtube.link,\r\n--   averageViewPercentage,\r\n--   -- likes,\r\n--   -- dislikes,\r\n--   -- comments,\r\n--   -- shares,\r\n--   -- averageViewPercentage,\r\n--   -- abo_change,\r\n--     ROW_NUMBER() OVER (PARTITION BY profiles.youtubeID ORDER BY \r\n--       views DESC) as row_num\r\n--   FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\n--   JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n--   -- JOIN `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as profiles1 ON (youtube.profileId = profiles1.youtubeID AND profiles1.LRA = \"$LRA\")\r\n  \r\n--   WHERE True\r\n--   AND EXTRACT(MONTH from youtube.time) = 5 \r\n--   AND EXTRACT(YEAR from youtube.time) = $Jahr\r\n-- ) as subquery\r\n-- WHERE row_num = 1\r\n-- ORDER BY Wiedergaben DESC\r\n-- ;\r\n-- ELSE\r\nSELECT DISTINCT\r\n  Profil,\r\n  Datum,\r\n  Titel,\r\n  Wiedergaben,\r\n  link,\r\n  Dauer,\r\n  Round(sehVolumen,0) as sehVolumen,\r\n  -- averageViewPercentage,\r\n  REGEXP_REPLACE(FORMAT('%0.1f', averageViewPercentage), r'\\.', ',') AS averageViewPercentage,\r\nFROM (\r\n  SELECT \r\n  profile as Profil,\r\n  youtube.time as Datum,\r\nCONCAT(\r\n  CASE WHEN LENGTH(CAST(DIV(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(duration,60) AS String)) ELSE CAST(DIV(duration,60) AS String)  END ,\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(duration,60) AS String)) ELSE CAST(MOD(duration,60) AS String)  END) as Dauer,\r\n  CONCAT(\r\n  CASE WHEN LENGTH(CAST(DIV(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(averageViewDuration,60) AS String)) ELSE CAST(DIV(averageViewDuration,60) AS String)  END ,\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(averageViewDuration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(averageViewDuration,60) AS String)) ELSE CAST(MOD(averageViewDuration,60) AS String)  END) as averageViewTime,\r\n  estimatedMinutesWatched/60 as sehVolumen,\r\n  title as Titel,\r\n  views as Wiedergaben,\r\n  youtube.link,\r\n  averageViewPercentage,\r\n  -- likes,\r\n  -- dislikes,\r\n  -- comments,\r\n  -- shares,\r\n  -- averageViewPercentage,\r\n  -- abo_change,\r\n    ROW_NUMBER() OVER (PARTITION BY profiles.youtubeID ORDER BY \r\n      views DESC) as row_num\r\n  FROM `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\n  JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (youtube.profileId = profiles.youtubeID AND profiles.LRA = \"$LRA\")\r\n  -- JOIN `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalytics${table_suffix}` as profiles1 ON (youtube.profileId = profiles1.youtubeID AND profiles1.LRA = \"$LRA\")\r\n  \r\n  -- WHERE True\r\n  AND $Zeitraum\r\n) as subquery\r\nWHERE row_num = 1\r\nORDER BY Wiedergaben DESC\r\n-- ;\r\n-- END IF\r\n-- ;"
    }
   ]
  },
  {
   "title": "Zusammenfassung aller Kanäle Videos im Zeitraum veröffentlicht (Nutzung bis zum Stichtag $stichtagmonat) | $Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 }
  },
  {
   "title": "Zusammenfassung aller Kanäle Videos im Zeitraum veröffentlicht | $Month",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 200 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH followers as (\r\n  SELECT\r\n    lm.Profil,\r\n    lm_follower as followers,\r\n    CASE \r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE IFNULL(lm_follower - llm_follower, lm_follower) END as FollowerVeraenderungAbsolut,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE\r\n    (SAFE_DIVIDE(lm_follower, llm_follower) -1) * 100 END as FollowerVeraenderung\r\n  FROM\r\n    (\r\n      SELECT\r\n        subscriberslifetime lm_follower,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND time = (\r\n          SELECT\r\n            MAX(time)\r\n          FROM\r\n            `ndr-code-bi-dashboard.Quintly.youtubeAnalytics` as youtube\r\n          WHERE $Zeitraum \r\n        )\r\n      ORDER BY\r\n        subscriberslifetime desc\r\n    ) as lm\r\n    LEFT JOIN (\r\n      SELECT\r\n        subscriberslifetime as llm_follower,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalytics${comp_table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND time = (\r\n          SELECT\r\n            MAX(time)\r\n          FROM\r\n            `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalytics${comp_table_suffix}` as youtube\r\n          WHERE CASE \"${Monat:text}\"\r\n          WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n          ELSE \r\n            EXTRACT(\r\n              MONTH\r\n              from\r\n                time\r\n            ) = EXTRACT(\r\n              MONTH\r\n              from\r\n                DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n            )\r\n            AND EXTRACT(\r\n              YEAR\r\n              from\r\n                time\r\n            ) = EXTRACT(\r\n              YEAR\r\n              from\r\n                DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n            ) END\r\n        )\r\n      ORDER BY\r\n        subscriberslifetime desc\r\n    ) as llm ON llm.Profil = lm.Profil\r\n  ORDER BY\r\n    lm.lm_follower DESC\r\n),\r\nvideo_start as (\r\n  SELECT\r\n    lm.Profil,\r\n    lm_videoViews10s as videoViews10s,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE  Round(IFNULL(lm_videoViews10s - IFNULL(llm_videoViews10s,0),lm_videoViews10s),0) END as videoViews10sVeraenderungAbsolut,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE\r\n    IFNULL((\r\n      SAFE_DIVIDE(lm_videoViews10s, llm_videoViews10s) -1\r\n    ) * 100,0) END as videoViews10sVeraenderung\r\n  FROM\r\n    (\r\n      SELECT\r\n        SUM(views) as lm_videoViews10s,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND $Zeitraum\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        lm_videoViews10s DESC\r\n    ) as lm\r\n    LEFT JOIN (\r\n      SELECT\r\n        profile as Profil,\r\n        SUM(views) as llm_videoViews10s,\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalyticsVideos${comp_table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND CASE \"${Monat:text}\" \r\n        WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n        ELSE EXTRACT(\r\n          MONTH\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          MONTH\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        )\r\n        AND EXTRACT(\r\n          YEAR\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          YEAR\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        ) END\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        llm_videoViews10s DESC\r\n    ) as llm ON llm.Profil = lm.Profil\r\n  ORDER BY\r\n    lm.lm_videoViews10s DESC\r\n),\r\nsehVolumen as (\r\n  SELECT\r\n    lm.Profil,\r\n    lm_sehVolumenVariable as sehVolumenVariable,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE \r\n    IFNULL(lm_sehVolumenVariable - llm_sehVolumenVariable,lm_sehVolumenVariable) END as sehVolumenVariableVeraenderungAbsolut,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE\r\n    IFNULL((\r\n      SAFE_DIVIDE(lm_sehVolumenVariable, llm_sehVolumenVariable) -1\r\n    ) * 100,0) END as sehVolumenVariableVeraenderung\r\n  FROM\r\n    (\r\n      SELECT\r\n        CAST(ROUND(SUM(estimatedMinutesWatched) /(60)) as INT64\r\n  ) as lm_sehVolumenVariable,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND $Zeitraum\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        lm_sehVolumenVariable\r\n        DESC\r\n    ) as lm\r\n    LEFT JOIN (\r\n      SELECT\r\n        profile as Profil,\r\n        CAST(\r\n    ROUND(SUM(estimatedMinutesWatched) /(60)) as INT64\r\n  ) as llm_sehVolumenVariable,\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalyticsVideos${comp_table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND CASE \"${Monat:text}\"\r\n        WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n        ELSE EXTRACT(\r\n          MONTH\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          MONTH\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        )\r\n        AND EXTRACT(\r\n          YEAR\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          YEAR\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        ) END\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        llm_sehVolumenVariable\r\n        DESC\r\n    ) as llm ON llm.Profil = lm.Profil\r\n  ORDER BY\r\n    lm.lm_sehVolumenVariable\r\n    DESC\r\n),\r\ninteractionen as (\r\n  SELECT\r\n    lm.Profil,\r\n    lm_interactionenVariable as interactionenVariable,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE \r\n    IFNULL(lm_interactionenVariable - llm_interactionenVariable,lm_interactionenVariable) END as interactionenVariableVeraenderungAbsolut,\r\n    CASE\r\n    WHEN \"${Monat:text}\" = \"Jahr\" AND $Jahr = 2022 THEN CAST(NULL AS INT64)\r\n    ELSE\r\n    IFNULL((\r\n      SAFE_DIVIDE(lm_interactionenVariable, llm_interactionenVariable) -1\r\n    ) * 100,0) END as interactionenVariableVeraenderung\r\n  FROM\r\n    (\r\n      SELECT\r\n       IFNULL(SUM(likes + dislikes + comments + shares),0)as lm_interactionenVariable,\r\n        profile as Profil\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${dataset_suffix}.youtubeAnalyticsVideos${table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND $Zeitraum\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        lm_interactionenVariable\r\n        DESC\r\n    ) as lm\r\n    LEFT JOIN (\r\n      SELECT\r\n        profile as Profil,\r\n        IFNULL(SUM(likes + dislikes + comments + shares),0) as llm_interactionenVariable,\r\n      FROM\r\n        `ndr-code-bi-dashboard.Quintly${comp_dataset_suffix}.youtubeAnalyticsVideos${comp_table_suffix}` as youtube\r\n        JOIN `ndr-code-bi-dashboard.Quintly.profiles` as profiles ON (\r\n          youtube.profileId = profiles.youtubeID\r\n          AND profiles.LRA = \"$LRA\"\r\n        )\r\n      WHERE\r\n        True\r\n        AND CASE \"${Monat:text}\"\r\n        WHEN \"Jahr\" THEN EXTRACT(YEAR from time) = $Jahr - 1\r\n        ELSE EXTRACT(\r\n          MONTH\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          MONTH\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        )\r\n        AND EXTRACT(\r\n          YEAR\r\n          from\r\n            time\r\n        ) = EXTRACT(\r\n          YEAR\r\n          from\r\n            DATE_SUB(DATE($Jahr, $Monat, 1), INTERVAL 1 MONTH)\r\n        ) END\r\n      GROUP BY\r\n        profile\r\n      ORDER BY\r\n        llm_interactionenVariable\r\n        DESC\r\n    ) as llm ON llm.Profil = lm.Profil\r\n  ORDER BY\r\n    lm.lm_interactionenVariable\r\n    DESC\r\n) \r\nSELECT\r\n  followers.Profil,\r\n  followers.followers,\r\n  followers.FollowerVeraenderungAbsolut,\r\n  followers.FollowerVeraenderung,\r\n  video_start.videoViews10s,\r\n  video_start.videoViews10sVeraenderungAbsolut,\r\n  video_start.videoViews10sVeraenderung,\r\n  sehVolumen.sehVolumenVariable,\r\n  sehVolumen.sehVolumenVariableVeraenderungAbsolut,\r\n  sehVolumen.sehVolumenVariableVeraenderung,\r\n  interactionen.interactionenVariable,\r\n  interactionen.interactionenVariableVeraenderungAbsolut,\r\n  interactionen.interactionenVariableVeraenderung,\r\nFROM\r\n  followers\r\n  JOIN video_start ON followers.Profil = video_start.Profil\r\n  JOIN sehVolumen ON followers.Profil = sehVolumen.Profil\r\n  JOIN interactionen ON followers.Profil = interactionen.Profil\r\n\r\n\r\n \r\n-- ;\r\n-- END IF;\r\n\r\n "
    }
   ]
  }
 ]
}