{
 "title": "Podcast Monatsbericht NDR - Abfragen Optimieren (01.05.2025)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Monat",
    "label": "Zeitraum",
    "query": {}
   },
   {
    "name": "month_as_number",
    "query": {}
   },
   {
    "name": "Jahr",
    "query": {}
   },
   {
    "name": "Plattformen",
    "query": {}
   },
   {
    "name": "Bereich",
    "query": {}
   },
   {
    "name": "Podcast",
    "query": {}
   },
   {
    "name": "Genre",
    "query": {}
   },
   { "name": "filled_size", "query": "20" },
   { "name": "filled_size_big", "query": "10" },
   { "name": "filled_size_headline", "query": "10" },
   {
    "name": "NDR_default_image",
    "query": {}
   },
   {
    "name": "NDR_branding_images",
    "query": {}
   },
   {
    "name": "NDR_podcast_images",
    "query": {}
   },
   {
    "name": "MDR_default_image",
    "query": {}
   },
   {
    "name": "plattformen_images",
    "query": {}
   },
   {
    "name": "dashboard_image",
    "query": {}
   },
   {
    "name": "branding_images",
    "query": {}
   },
   {
    "name": "podcast_images",
    "query": {}
   },
   {
    "name": "mdr_ard_kultur_podcasts",
    "query": {}
   },
   {
    "name": "date_condition",
    "query": {}
   },
   {
    "name": "vormonat_date_condition",
    "query": {}
   },
   {
    "name": "vorjahresmonat_date_condition",
    "query": {}
   },
   {
    "name": "current_timestamp",
    "query": {}
   },
   {
    "name": "today_date",
    "query": {}
   },
   {
    "name": "aktueller_monat",
    "query": {}
   },
   {
    "name": "vormonat",
    "query": {}
   },
   {
    "name": "vorjahresmonat",
    "query": {}
   },
   {
    "name": "max_available_date_per_month",
    "query": {}
   },
   {
    "name": "platform_table",
    "query": {}
   },
   {
    "name": "episode_table",
    "query": {}
   },
   {
    "name": "profiles_table",
    "query": {}
   },
   {
    "name": "ausgewerteteZeitraum_start",
    "query": {}
   },
   {
    "name": "ausgewerteteZeitraum_end",
    "query": {}
   },
   {
    "name": "datenstand_start",
    "query": {}
   },
   {
    "name": "datenstand_end",
    "query": {}
   },
   {
    "name": "KPI_comp_vormonat_field",
    "query": {}
   },
   {
    "name": "lastUpdate",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# Podcast Report | ${Monat} ${Jahr}\n\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [
         { "name": "total_video_10s_views", "type": "functionParameter" }
        ],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "facebookInsightsOwnVideos"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 3 },
   "options": {
    "content": "## Der ausgewertete Zeitraum lautet: ${ausgewerteteZeitraum_start} - ${ausgewerteteZeitraum_end}"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Übersicht ${LRA} Gesamt |  ${Monat} ${Jahr}'))), 'Übersicht ${LRA} Gesamt |  ${Monat} ${Jahr}')"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$dashboard_image\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('$LRA - Gesamt'))), '$LRA - Gesamt')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 17, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Apps'))), 'Apps')"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt aller Podcast-Reihen im ausgewählten Bereich",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n    SELECT \n        SUM(zugriffe) AS summe\n    FROM \n        $episode_table\n    WHERE $date_condition\n          AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('ARD Audiothek')), 'ARD Audiothek')\nFROM(\nSELECT 'ARD Audiothek' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "NDR: Spotify-Daten ab 01.01.2021 verfügbar (ab August 2023 auf Basis von Serverlogfiles, für ältere Zeiträume auf Basis von Streams ab 60 Sekunden)",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('Spotify')), 'Spotify')\nFROM(\nSELECT 'Spotify' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size - CHAR_LENGTH('Apple Podcasts'))), 'Apple Podcasts')\nFROM(\nSELECT 'Apple Podcasts' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n    SUM(zugriffe) AS summe,\n    platform\nFROM \n    $platform_table\nWHERE $date_condition\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY platform"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\n    SELECT \n        SUM(zugriffe) AS summe\n    FROM \n        $platform_table\n    WHERE platform = \"ARD Audiothek\" \n          AND $date_condition\n          AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\n    SELECT \n        SUM(zugriffe) AS summe\n    FROM \n        $platform_table\n    WHERE platform = \"Spotify\" \n          AND $date_condition\n          AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\n    SELECT \n        SUM(zugriffe) AS summe\n    FROM \n        $platform_table\n    WHERE platform = \"Apple Podcasts\" \n          AND $date_condition\n          AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": {
    "content": "Letztes Update: <br> \r\n${lastUpdate}\r\n<br> <br> \r\nDatenstand: <br> \r\n${datenstand_start} – ${datenstand_end}"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", 0), 'Veränderung im Vergleich zu:')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF $month_as_number > 12 THEN\r\n  SELECT \"$vorjahresmonat\";\r\nELSE\r\n  SELECT \"$vormonat\", \"$vorjahresmonat\";\r\nEND IF"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF $month_as_number > 12 THEN\n  SELECT \"$vorjahresmonat\";\nELSE\n  SELECT \"$vormonat\", \"$vorjahresmonat\";\nEND IF"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF $month_as_number > 12 THEN\n  SELECT \"$vorjahresmonat\";\nELSE\n  SELECT \"$vormonat\", \"$vorjahresmonat\";\nEND IF"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF $month_as_number > 12 THEN\n  SELECT \"$vorjahresmonat\";\nELSE\n  SELECT \"$vormonat\", \"$vorjahresmonat\";\nEND IF"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH aktuell AS (\n  SELECT \n    SUM(zugriffe) AS aktuell_summe\n  FROM\n    $episode_table\n  WHERE $date_condition\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n), vormonat AS (\n  SELECT \n    SUM(zugriffe) AS vormonat_summe\n  FROM\n    $episode_table\n  WHERE $vormonat_date_condition\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts) \n), vorjahresmonat AS (\n  SELECT \n    SUM(zugriffe) AS vorjahresmonat_summe\n  FROM\n    $episode_table\n  WHERE $vorjahresmonat_date_condition\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\nSELECT\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    $KPI_comp_vormonat_field\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN aktuell_summe / vorjahresmonat_summe - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell_summe / vorjahresmonat_summe - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell_summe / vorjahresmonat_summe - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\nFROM aktuell, vormonat, vorjahresmonat"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH aktuell AS (\n  SELECT \n    SUM(zugriffe) AS aktuell_summe\n  FROM\n    $platform_table\n  WHERE $date_condition \n        AND platform = \"ARD Audiothek\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n), vormonat AS (\n  SELECT \n    SUM(zugriffe) AS vormonat_summe\n  FROM\n    $platform_table\n  WHERE $vormonat_date_condition\n        AND platform = \"ARD Audiothek\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n), vorjahresmonat AS (\n  SELECT \n    SUM(zugriffe) AS vorjahresmonat_summe\n  FROM\n    $platform_table\n  WHERE $vorjahresmonat_date_condition\n        AND platform = \"ARD Audiothek\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\nSELECT\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    $KPI_comp_vormonat_field\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN aktuell_summe / vorjahresmonat_summe - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell_summe / vorjahresmonat_summe - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell_summe / vorjahresmonat_summe - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\nFROM aktuell, vormonat, vorjahresmonat"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH aktuell AS (\n  SELECT \n    SUM(zugriffe) AS aktuell_summe\n  FROM\n    $platform_table\n  WHERE $date_condition \n        AND platform = \"Spotify\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n), vormonat AS (\n  SELECT \n    SUM(zugriffe) AS vormonat_summe\n  FROM\n    $platform_table\n  WHERE $vormonat_date_condition\n        AND platform = \"Spotify\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n), vorjahresmonat AS (\n  SELECT \n    SUM(zugriffe) AS vorjahresmonat_summe\n  FROM\n    $platform_table\n  WHERE $vorjahresmonat_date_condition\n        AND platform = \"Spotify\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\nSELECT\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    $KPI_comp_vormonat_field\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN aktuell_summe / vorjahresmonat_summe - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell_summe / vorjahresmonat_summe - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell_summe / vorjahresmonat_summe - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\nFROM aktuell, vormonat, vorjahresmonat"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH aktuell AS (\n  SELECT \n    SUM(zugriffe) AS aktuell_summe\n  FROM\n    $platform_table\n  WHERE $date_condition \n        AND platform = \"Apple Podcasts\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n), vormonat AS (\n  SELECT \n    SUM(zugriffe) AS vormonat_summe\n  FROM\n    $platform_table\n  WHERE $vormonat_date_condition\n        AND platform = \"Apple Podcasts\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n), vorjahresmonat AS (\n  SELECT \n    SUM(zugriffe) AS vorjahresmonat_summe\n  FROM\n    $platform_table\n  WHERE $vorjahresmonat_date_condition\n        AND platform = \"Apple Podcasts\"\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n)\nSELECT\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    $KPI_comp_vormonat_field\n    -- add \"+\" (if it is positive), reformat it to a german number, and add \"%\"\n    CASE\n    WHEN aktuell_summe / vorjahresmonat_summe - 1 > 0 THEN CONCAT(\"+\",REPLACE(CAST(ROUND((aktuell_summe / vorjahresmonat_summe - 1) * 100,0) AS STRING),\".\",\",\"),\"%\")\n    ELSE CONCAT(REPLACE(CAST(ROUND((aktuell_summe / vorjahresmonat_summe - 1) * 100,0) AS STRING),\".\",\",\"),\"%\") END,\nFROM aktuell, vormonat, vorjahresmonat"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$plattformen_images\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Plattformen | Zugriffe",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH last_12_months AS (\r\n  SELECT\r\n    LAST_DAY(DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL x MONTH)) AS month_end\r\n  FROM \r\n    UNNEST(GENERATE_ARRAY(1, 12)) AS x\r\n  UNION All\r\n  SELECT \r\n    \"$max_available_date_per_month\"\r\n)\r\n\r\nSELECT \r\n  date as Monat, \r\n  SUM(zugriffe) AS Zugriffe\r\nFROM \r\n  $platform_table\r\nWHERE CASE\r\n        WHEN $month_as_number > 12 THEN $date_condition \r\n        ELSE date IN (SELECT month_end FROM last_12_months)\r\n      END\r\n      AND (\"$Plattformen\" = \"Alle Plattformen\" OR platform = \"$Plattformen\")\r\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\nGROUP BY Monat\r\nORDER BY Monat ASC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Zusammensetzung Zugriffe ${LRA} Gesamt |  ${Monat} ${Jahr}'))), 'Zusammensetzung Zugriffe ${LRA} Gesamt |  ${Monat} ${Jahr}')"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Bereiche'))), 'Bereiche'), \nFROM(\nSELECT 'Bereiche' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Podcastreihen'))), 'Podcastreihen'), \nFROM(\nSELECT 'Podcastreihen' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Genres'))), 'Genres'), \nFROM(\nSELECT 'Genres' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SUM(zugriffe) AS summe,\n  branding\nFROM \n  $episode_table\nWHERE $date_condition\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY branding"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_podcasts AS (\n  SELECT\n    SUM(zugriffe) AS summe,\n    podcast_title\n  FROM\n    $episode_table \n  WHERE $date_condition\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\n  GROUP BY podcast_title\n), top_100 AS (\n  SELECT \n    * \n  FROM\n    all_podcasts\n  ORDER BY summe DESC\n  LIMIT 100\n), rest AS (\n  SELECT\n    SUM(summe) AS summe,\n    \"Sonstige\" AS podcast_title\n  FROM \n    all_podcasts\n  WHERE podcast_title NOT IN (SELECT DISTINCT podcast_title FROM top_100)\n)\nSELECT \n  summe,\n  CASE \n    WHEN LENGTH(podcast_title) <= 20 THEN podcast_title\n    ELSE CONCAT(SUBSTR(podcast_title,0,20),\"...\") \n  END\nFROM \n  top_100\nUNION ALL\nSELECT \n  * \nFROM rest\nORDER BY summe DESC"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SUM(zugriffe) AS summe,\n  genre\nFROM \n  $episode_table\nWHERE $date_condition\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY genre"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Bereiche |  ${Monat_text} ${Jahr}'))), 'Bereiche |  ${Monat:text} ${Jahr}'), \nFROM(\nSELECT 'Bereiche |  ${Monat:text} ${Jahr}' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 70 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$branding_images\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Bereich | Summe aller Podcastreihen",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH last_12_months AS (\r\n  SELECT\r\n    LAST_DAY(DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL x MONTH)) AS month_end\r\n  FROM \r\n    UNNEST(GENERATE_ARRAY(1, 12)) AS x\r\n  UNION All\r\n  SELECT \r\n    \"$max_available_date_per_month\"\r\n)\r\nSELECT \r\n  date as Monat, \r\n  SUM(zugriffe) AS Zugriffe\r\nFROM \r\n  $episode_table\r\nWHERE CASE\r\n        WHEN $month_as_number > 12 THEN $date_condition \r\n        ELSE date IN (SELECT month_end FROM last_12_months)\r\n      END\r\n      AND (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\r\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\nGROUP BY Monat\r\nORDER BY Monat ASC"
    }
   ]
  },
  {
   "title": "$Bereich | Alle Podcastreihen",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH vormonat AS (\r\n  SELECT\r\n    branding,\r\n    podcast_title,\r\n    broadcast_id,\r\n    SUM(zugriffe) AS zugriffe,\r\n    genre\r\n  FROM $episode_table\r\n  WHERE $vormonat_date_condition \r\n        AND (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\r\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title, broadcast_id, genre\r\n), vorjahresmonat AS (\r\n  SELECT\r\n    branding,\r\n    podcast_title,\r\n    broadcast_id,\r\n    SUM(zugriffe) AS zugriffe,\r\n    genre\r\n  FROM $episode_table\r\n  WHERE $vorjahresmonat_date_condition \r\n        AND (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\r\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title, broadcast_id, genre\r\n), aktuell AS (\r\n  SELECT\r\n    branding,\r\n    podcast_title,\r\n    broadcast_id,\r\n    SUM(zugriffe) AS zugriffe,\r\n    genre\r\n  FROM $episode_table\r\n  WHERE $date_condition \r\n        AND (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\r\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title, broadcast_id, genre\r\n),\r\njoined_zugriffe AS (\r\n  SELECT \r\n  aktuell.branding, \r\n  aktuell.podcast_title, \r\n  aktuell.zugriffe AS aktuelle_zugriffe,\r\n  vormonat.zugriffe AS vormonat_zugriffe, \r\n  vorjahresmonat.zugriffe AS vorjahresmonat_zugriffe\r\n  FROM aktuell\r\n  LEFT JOIN vormonat USING(broadcast_id)\r\n  LEFT JOIN vorjahresmonat USING(broadcast_id)\r\n)\r\nSELECT \r\n  branding AS Bereich,\r\n  podcast_title AS Podcast,\r\n  aktuelle_zugriffe AS Zugriffe,\r\n  CASE \r\n    WHEN $month_as_number > 12 THEN CAST(NULL AS INT64)\r\n    ELSE aktuelle_zugriffe - vormonat_zugriffe\r\n  END AS AbsoluteAenderungVormonat,\r\n  CASE\r\n    WHEN $month_as_number > 12 THEN CAST(NULL AS INT64)\r\n    ELSE (aktuelle_zugriffe / vormonat_zugriffe - 1) * 100\r\n  END AS ProzentAenderungVormonat,\r\n  aktuelle_zugriffe - vorjahresmonat_zugriffe AS AbsoluteAenderungVorjahresmonat,\r\n  (aktuelle_zugriffe / vorjahresmonat_zugriffe - 1) * 100 AS ProzentAenderungVorjahresmonat\r\nFROM joined_zugriffe\r\nORDER BY aktuelle_zugriffe DESC"
    }
   ]
  },
  {
   "title": "$Bereich | Alle Episoden",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  podcast_title,\n  headline,\n  publication_date,\n  SUM(zugriffe) AS zugriffe\nFROM \n  $episode_table\nWHERE $date_condition \n      AND (\"$Bereich\" = \"Alle Bereiche\" OR branding = \"$Bereich\")\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY podcast_title, headline, publication_date\nORDER BY zugriffe DESC\nLIMIT 1000"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Podcastreihen |  ${Monat} ${Jahr}'))), 'Podcastreihen |  ${Monat} ${Jahr}')"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 120 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$podcast_images\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Podcast",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH last_12_months AS (\r\n  SELECT\r\n    LAST_DAY(DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL x MONTH)) AS month_end\r\n  FROM \r\n    UNNEST(GENERATE_ARRAY(1, 12)) AS x\r\n  UNION All\r\n  SELECT \r\n    \"$max_available_date_per_month\"\r\n)\r\nSELECT \r\n  date as Monat, \r\n  SUM(zugriffe) AS Zugriffe\r\nFROM \r\n  $episode_table\r\nWHERE CASE\r\n        WHEN $month_as_number > 12 THEN $date_condition \r\n        ELSE date IN (SELECT month_end FROM last_12_months)\r\n      END\r\n      AND (\"$Podcast\" = \"Alle Titel\" OR podcast_title = \"$Podcast\")\r\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\nGROUP BY Monat\r\nORDER BY Monat ASC"
    }
   ]
  },
  {
   "title": "$Podcast | Alle Episoden",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  podcast_title,\n  headline,\n  publication_date,\n  SUM(zugriffe) AS zugriffe\nFROM \n  $episode_table\nWHERE $date_condition \n      AND (\"$Podcast\" = \"Alle Titel\" OR podcast_title = \"$Podcast\")\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY podcast_title, headline, publication_date\nORDER BY zugriffe DESC\nLIMIT 1000"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('Genres |  ${Monat} ${Jahr}'))), 'Genres |  ${Monat} ${Jahr}')"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 156 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Genre",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH last_12_months AS (\r\n  SELECT\r\n    LAST_DAY(DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL x MONTH)) AS month_end\r\n  FROM \r\n    UNNEST(GENERATE_ARRAY(1, 12)) AS x\r\n  UNION All\r\n  SELECT \r\n    \"$max_available_date_per_month\"\r\n)\r\nSELECT \r\n  date as Monat, \r\n  SUM(zugriffe) AS Zugriffe\r\nFROM \r\n  $episode_table\r\nWHERE CASE\r\n        WHEN $month_as_number > 12 THEN $date_condition \r\n        ELSE date IN (SELECT month_end FROM last_12_months)\r\n      END\r\n      AND (\"$Genre\" = \"Alle Genres\" OR genre = \"$Genre\")\r\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\nGROUP BY Monat\r\nORDER BY Monat ASC\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "$Genre | Alle Podcastreihen",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 169 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH vormonat AS (\r\n  SELECT\r\n    branding,\r\n    podcast_title,\r\n    broadcast_id,\r\n    SUM(zugriffe) AS zugriffe,\r\n    genre\r\n  FROM $episode_table\r\n  WHERE $vormonat_date_condition \r\n        AND (\"$Genre\" = \"Alle Genres\" OR genre = \"$Genre\")\r\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title, broadcast_id, genre\r\n), vorjahresmonat AS (\r\n  SELECT\r\n    branding,\r\n    podcast_title,\r\n    broadcast_id,\r\n    SUM(zugriffe) AS zugriffe,\r\n    genre\r\n  FROM $episode_table\r\n  WHERE $vorjahresmonat_date_condition \r\n        AND (\"$Genre\" = \"Alle Genres\" OR genre = \"$Genre\")\r\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title, broadcast_id, genre\r\n), aktuell AS (\r\n  SELECT\r\n    branding,\r\n    podcast_title,\r\n    broadcast_id,\r\n    SUM(zugriffe) AS zugriffe,\r\n    genre\r\n  FROM $episode_table\r\n  WHERE $date_condition \r\n        AND (\"$Genre\" = \"Alle Genres\" OR genre = \"$Genre\")\r\n        AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\r\n  GROUP BY branding, podcast_title, broadcast_id, genre\r\n),\r\njoined_zugriffe AS (\r\n  SELECT \r\n  aktuell.branding, \r\n  aktuell.podcast_title,\r\n  aktuell.genre, \r\n  aktuell.zugriffe AS aktuelle_zugriffe,\r\n  vormonat.zugriffe AS vormonat_zugriffe, \r\n  vorjahresmonat.zugriffe AS vorjahresmonat_zugriffe\r\n  FROM aktuell\r\n  LEFT JOIN vormonat USING(broadcast_id)\r\n  LEFT JOIN vorjahresmonat USING(broadcast_id)\r\n)\r\nSELECT \r\n  branding AS Bereich,\r\n  podcast_title AS Podcast,\r\n  genre AS Genre,\r\n  aktuelle_zugriffe AS Zugriffe,\r\n  CASE \r\n    WHEN $month_as_number > 12 THEN CAST(NULL AS INT64)\r\n    ELSE aktuelle_zugriffe - vormonat_zugriffe\r\n  END AS AbsoluteAenderungVormonat,\r\n  CASE\r\n    WHEN $month_as_number > 12 THEN CAST(NULL AS INT64)\r\n    ELSE (aktuelle_zugriffe / vormonat_zugriffe - 1) * 100\r\n  END AS ProzentAenderungVormonat,\r\n  aktuelle_zugriffe - vorjahresmonat_zugriffe AS AbsoluteAenderungVorjahresmonat,\r\n  (aktuelle_zugriffe / vorjahresmonat_zugriffe - 1) * 100 AS ProzentAenderungVorjahresmonat\r\nFROM joined_zugriffe\r\nORDER BY aktuelle_zugriffe DESC"
    }
   ]
  },
  {
   "title": "$Genre | Alle Episoden",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  podcast_title,\n  genre,\n  headline,\n  publication_date,\n  SUM(zugriffe) AS zugriffe\nFROM \n  $episode_table\nWHERE $date_condition \n      AND (\"$Genre\" = \"Alle Genres\" OR genre = \"$Genre\")\n      AND broadcast_id NOT IN ($mdr_ard_kultur_podcasts)\nGROUP BY podcast_title, genre, headline, publication_date\nORDER BY zugriffe DESC\nLIMIT 1000"
    }
   ]
  }
 ]
}