{
 "title": "Podcast NDR",
 "description": "New Version, 2.0 Backup 14.04.2025",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "label": "LRA:",
    "query": {}
   },
   {
    "name": "datenstand",
    "query": {}
   },
   {
    "name": "Podcast_title",
    "query": {}
   },
   {
    "name": "AllePodcastsCondition",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "Bereich",
    "label": "Bereich:",
    "query": {}
   },
   {
    "name": "Podcast",
    "label": "Podcast:",
    "query": {}
   },
   {
    "name": "Episode",
    "label": "Episode:",
    "query": {}
   },
   { "name": "filled_size_big", "query": "10" },
   { "name": "filled_size", "query": "20" },
   {
    "name": "filled_size_headline",
    "query": {}
   },
   {
    "name": "filled_size_headline_small",
    "query": {}
   },
   {
    "name": "broadcast_id_branding",
    "query": {}
   },
   {
    "name": "Image",
    "query": {}
   },
   {
    "name": "type",
    "query": {}
   },
   {
    "name": "NDR_default_image",
    "query": {}
   },
   {
    "name": "lastUpdate",
    "query": {}
   },
   {
    "name": "mapping_dataset",
    "query": {}
   },
   {
    "name": "MDR_default_image",
    "query": {}
   },
   {
    "name": "AllePodcasts",
    "label": "Podcastsuche:",
    "query": {}
   },
   {
    "name": "number_of_days",
    "query": {}
   },
   {
    "name": "dataset_suffix",
    "query": {}
   },
   {
    "name": "episode_dataset",
    "query": {}
   },
   {
    "name": "platform_dataset",
    "query": {}
   },
   {
    "name": "profiles_dataset",
    "query": {}
   },
   {
    "name": "hinweis",
    "query": {}
   },
   {
    "name": "fromDay",
    "query": {}
   },
   {
    "name": "toDay_NDR",
    "query": {}
   },
   {
    "name": "zeitraum_NDR",
    "query": {}
   },
   {
    "name": "HeuteDatum",
    "query": {}
   },
   {
    "name": "episodenschnitt_condition",
    "query": {}
   },
   {
    "name": "delay_text",
    "query": {}
   },
   {
    "name": "zeitraum_MDR",
    "query": {}
   },
   {
    "name": "zeitraum",
    "query": {}
   },
   {
    "name": "toDay_MDR",
    "query": {}
   },
   {
    "name": "toDay",
    "query": {}
   },
   {
    "name": "datenstand_not_formated",
    "query": {}
   },
   {
    "name": "Plattformen",
    "query": {}
   },
   { "name": "import_check", "query": "check" },
   {
    "name": "episodes_lim",
    "query": {}
   },
   {
    "name": "Tage",
    "label": "Anzahl Tage nach VÖ",
    "query": "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99"
   },
   {
    "name": "Tage_content_lifetime",
    "label": "Anzahl Tage nach VÖ",
    "query": "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99"
   },
   {
    "name": "avgEpisodesQueryCols",
    "query": {}
   },
   {
    "name": "avg_avgEpisodesQueryCols",
    "query": {}
   },
   {
    "name": "avgEpisodesQuery",
    "label": "query_test",
    "query": {}
   },
   {
    "name": "avgEpisodesQueryForPodcastTable",
    "label": "query_test",
    "query": {}
   },
   {
    "name": "copy_of_avgEpisodesQueryForPodcastTable",
    "label": "query_test",
    "query": {}
   },
   {
    "name": "avgOfavgEpisodesQuery",
    "label": "query_test",
    "query": {}
   },
   { "name": "PubDate", "label": "Pub Date Version", "query": "Pub Date 6" },
   {
    "name": "pub_date_field",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:rgba(38, 113, 198); color: white; text-align: center; vertical-align: middle; padding: 20px 0; margin-top: 0px; font-size: 15pt;\">\n  <font color=\"#FFFFFF\" size=\"5\">Servicemeldung:</font> <br>\n  <font color=\"#FFFFFF\" size=\"3\">\n    Fehlerhafte Identifikation der Audiotheks-App in den Logfiles. Weitere Informationen findet ihr hier im Audio Blog: \n    <a href=\"https://ndr.coyocloud.com/pages/medienforschung-hoerfunk/apps/blog/blog/view/387df756-ac8a-4fb6-bff1-36f67da9cdf9\" style=\"color: white;\">LINK</a> <br>\n  </font>\n</div>\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 13, "y": 4 }, "options": { "content": " ${hinweis}" } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$Image\n\" />\n\n<!-- src=${Image} />"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size_headline - CHAR_LENGTH('$Podcast_title'))), '$Podcast_title'), \nFROM(\nSELECT '$Podcast_title' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('QApps'),0)), 'Apps')\nFROM(\nSELECT 'Apps' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt im Analysezeitraum",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \n  SUM(m_zugriffe_1) AS summe \nFROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END \nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE  broadcast_id = \"$broadcast_id_branding\" END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT\n  SUM(zugriffe) as summe,\nFROM (\n  SELECT\n    FIRST_VALUE($pub_date_field) OVER (PARTITION BY headline ORDER BY $pub_date_field DESC) AS publication_date,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n  FROM $episode_dataset as ed\n  LEFT JOIN (SELECT DISTINCT podcast_title, episodenschnitt FROM $profiles_dataset) as pd\n  ON ed.podcast_title = pd.podcast_title\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates USING (headline)\nWHERE CASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE ed.branding = \"$Bereich\" END\nAND  CASE \"$Podcast\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(ed.podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND $episodenschnitt_condition\n  GROUP BY\n    $pub_date_field,\n    headline\n  ORDER BY\n    zugriffe DESC )\n    WHERE DATE(publication_date) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "description": "Nutzungsverteilung im Nutzungszeitraum neu veröffentlichter\nEpisoden vs. älterer Episoden (Longtail) an Zugriffen gesamt.",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 9 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH new_episodes AS (\n    SELECT\n    DISTINCT\n  SUM(IFNULL(zugriffe,0))  OVER() as summe,\n  headline\nFROM (\n  SELECT\n    FIRST_VALUE($pub_date_field) OVER (PARTITION BY headline ORDER BY $pub_date_field DESC) AS publication_date,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n  FROM $episode_dataset as ed\n  LEFT JOIN (SELECT DISTINCT podcast_title, episodenschnitt FROM $profiles_dataset) as pd\n  ON ed.podcast_title = pd.podcast_title\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates USING (headline)\nWHERE CASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE ed.branding = \"$Bereich\" END\nAND  CASE \"$Podcast\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(ed.podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND $episodenschnitt_condition\n  GROUP BY\n    $pub_date_field,\n    headline\n  ORDER BY\n    zugriffe DESC )\n    WHERE DATE(publication_date) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n    UNION ALL \n  SELECT 0 AS summe, \"0-wert\" as headline\n), \nall_episodes AS (\nSELECT \n  SUM(m_zugriffe_1) AS summe \nFROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END \nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE  broadcast_id = \"$broadcast_id_branding\" END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND headline NOT IN (SELECT headline from new_episodes)--DATE(publication_date_1) <= DATE('${__from:date}', \"Europe/Berlin\")\n), all_episodes_sum AS(\nSELECT DISTINCT summe from new_episodes\n), longtail_sum AS(\nSELECT IFNULL(summe,0) as summe from all_episodes\nUNION ALL\nSELECT 0 as summe\n)\nSELECT MAX(GREATEST(all_episodes_sum.summe,0)) as new_episode_sum, MAX(GREATEST(longtail_sum.summe, 0)) as longtail_sum\nFROM all_episodes_sum, longtail_sum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('ARD Audiothek')), 'ARD Audiothek')\nFROM(\nSELECT 'ARD Audiothek' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Spotify-Daten ab 01.01.2021 verfügbar (ab August 2023 auf Basis von Serverlogfiles, für ältere Zeiträume auf Basis von Streams ab 60 Sekunden)",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH('Spotify')), 'Spotify')\nFROM(\nSELECT 'Spotify' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST(0,$filled_size - CHAR_LENGTH('Apple Podcasts'))), 'Apple Podcasts')\nFROM(\nSELECT 'Apple Podcasts' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE \n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset AS pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"ARD Audiothek\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"ARD Audiothek\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"Spotify\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"Spotify\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE platform = \"Apple Podcasts\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND platform = \"Apple Podcasts\" AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \n(\nSELECT summe FROM ${dataset}\n)\n\n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": {
    "content": "Letztes Update: <br> \r\n${lastUpdate}\r\n<br> <br> \r\nDatenstand: <br> \r\n01.01.2021 – ${datenstand}"
   }
  },
  {
   "type": "stat",
   "description": "Durchschnitt pro Episode für die im ausgewählten Analysezeitraum veröffentlichten Episoden.",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT\n  SUM(zugriffe)/COUNT(DISTINCT headline) as summe,\nFROM (\n  SELECT\n    FIRST_VALUE($pub_date_field) OVER (PARTITION BY headline ORDER BY $pub_date_field DESC) AS publication_date,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n  FROM $episode_dataset as ed\n  LEFT JOIN (SELECT DISTINCT podcast_title, episodenschnitt FROM $profiles_dataset) as pd\n  ON ed.podcast_title = pd.podcast_title\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates USING (headline)\nWHERE CASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE ed.branding = \"$Bereich\" END\nAND  CASE \"$Podcast\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(ed.podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND $episodenschnitt_condition\n  GROUP BY\n    $pub_date_field,\n    headline\n  ORDER BY\n    zugriffe DESC )\n    WHERE DATE(publication_date) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "description": "Zugriffe über ausgewählte Apps auf Basis von User Agents. Im Vergleich zu den eigenen Metriken der jeweiligen Plattform-Anbieter kann es aufgrund verschiedener Messmethoden zu Abweichungen kommen.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform\nFROM $platform_dataset as podcast_platform\nINNER JOIN broadcastids ON podcast_platform.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform\n)\nSELECT * FROM ${dataset}\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT\n  COUNT(DISTINCT headline) as summe,\nFROM (\n  SELECT\n    FIRST_VALUE($pub_date_field) OVER (PARTITION BY headline ORDER BY $pub_date_field DESC) AS publication_date,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n  FROM $episode_dataset as ed\n  LEFT JOIN $profiles_dataset as pd\n  ON ed.podcast_title = pd.podcast_title\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates USING (headline)\nWHERE CASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE ed.branding = \"$Bereich\" END\nAND  CASE \"$Podcast\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(ed.podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND $episodenschnitt_condition\n  GROUP BY\n    $pub_date_field,\n    headline\n  ORDER BY\n    zugriffe DESC )\n    WHERE DATE(publication_date) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Nutzungsanteil der im Analysezeitraum neu veröffentlichten Episoden an den gesamten Zugriffen.",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH new_episodes AS(\n  SELECT\n  SUM(zugriffe) as new_episodes_sum,\nFROM (\n  SELECT \n    FIRST_VALUE($pub_date_field) OVER (PARTITION BY headline ORDER BY $pub_date_field DESC) AS publication_date,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n  FROM $episode_dataset as ed\n  LEFT JOIN (SELECT distinct podcast_title, episodenschnitt FROM $profiles_dataset) as pd\n  ON ed.podcast_title = pd.podcast_title\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates USING (headline)\nWHERE CASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE ed.branding = \"$Bereich\" END\nAND  CASE \"$Podcast\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(ed.podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND $episodenschnitt_condition\n  GROUP BY\n    $pub_date_field,\n    headline\n  ORDER BY\n    zugriffe DESC )\n    WHERE DATE(publication_date) BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n), all_episodes AS(\n  SELECT \n  SUM(m_zugriffe_1) AS all_episodes_sum \n  FROM $episode_dataset\n  WHERE \n  CASE \"$Bereich\"\n  WHEN \"Alle Bereiche\" THEN TRUE\n  ELSE branding = \"$Bereich\" END \n  AND CASE \"\"\"${Podcast:text}\"\"\"\n  WHEN \"All titles\" THEN TRUE\n  ELSE  broadcast_id = \"$broadcast_id_branding\" END\n  AND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)\nSELECT CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"), \"%\")FROM\n(\n  SELECT (new_episodes_sum/all_episodes_sum)*100 as summe FROM new_episodes, all_episodes\n)\n"
    }
   ]
  },
  {
   "title": "Ø neue Episoden nach Tagen",
   "type": "volkovlabs-echarts-panel",
   "description": "Durchschnitt pro Episode für die im ausgewählten Analysezeitraum neu veröffentlichten Episoden nach X Tagen. ACHTUNG: Die Stichprobe der Episoden variiert je nach betrachtetem Zeitintervall. So ist unter Umständen auch ein kleinerer Wert für 56 Tage als für 28 Tage möglich. Für robuste Ergebnisse bitte einen möglichst langen Analysezeitraum wählen.",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 15 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH avg_episode_values AS (\n  SELECT $avg_avgEpisodesQueryCols\n  FROM ($avgEpisodesQueryForPodcastTable) \n)\nSELECT * FROM (\nSELECT CASE period\nWHEN \"days7\" THEN \"nach 7 Tagen\"\nWHEN \"days14\" THEN \"nach 14 Tagen\"\nWHEN \"days28\" THEN \"nach 28 Tagen\"\nWHEN \"days56\" THEN \"nach 56 Tagen\"\nWHEN \"days91\" THEN \"nach 91 Tagen\" \nEND as period\n, ROUND(value) as value,\n CASE period\nWHEN \"days7\" THEN 0\nWHEN \"days14\" THEN 1\nWHEN \"days28\" THEN 2 \nWHEN \"days56\" THEN 3\nWHEN \"days91\" THEN 4\nEND as rank\nFROM avg_episode_values\nUNPIVOT(value FOR period IN ($avgEpisodesQueryCols))\n)\nWHERE CONTAINS_SUBSTR(period, \"nach\")\nORDER by rank DESC\n\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 }, "options": { "content": "${delay_text}" } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Bereich: $Bereich'),0)), 'Bereich: $Bereich')\nFROM(\nSELECT 'Bereich: $Bereich' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", GREATEST($filled_size_headline_small - CHAR_LENGTH('Ausgewählte Episoden'),0)), 'Ausgewählte Episoden')\nFROM(\nSELECT 'Ausgewählte Episoden' as Interaktionen\nFROM `ndr-code-bi-dashboard.Quintly.facebook`\nLIMIT 1\n)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt aller Podcast-Reihen im ausgewählten Bereich",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT\n  SUM(m_zugriffe_1) AS summe\nFROM $episode_dataset\nWHERE\nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END\nAND headline != \"All headlines\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Zugriffe gesamt für die in der Navigation unter Episode ausgewählten Audios",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \n  SUM(m_zugriffe_1) AS summe \nFROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END \nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE  broadcast_id = \"$broadcast_id_branding\" END\nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(headline,\"'\",\"\") IN UNNEST(ARRAY_CONCAT(ARRAY[$Episode], ARRAY['None'])) END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Durchschnitt pro Episode für die die in der Navigation unter Episode ausgewählten Audios ",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(ROUND(summe,0) as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT \n  SAFE_DIVIDE(SUM(m_zugriffe_1),COUNT(DISTINCT headline)) as summe \nFROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END \nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE  broadcast_id = \"$broadcast_id_branding\" END\nAND CASE \"\"\"${Podcast:text}\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(headline,\"'\",\"\") IN UNNEST(ARRAY_CONCAT(ARRAY[$Episode], ARRAY['None'])) END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\"))"
    }
   ]
  },
  {
   "title": "Zugriffe pro Tag für \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform,\n    date\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform, date),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform,\n  date\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\ngroup by platform, date\n),\nard_data AS (\n  SELECT summe, date FROM \n  ${dataset}\n  WHERE platform = \"ARD Audiothek\"\n),\napple_data AS\n(\n    SELECT summe, date FROM \n  ${dataset}\n  WHERE platform = \"Apple Podcasts\"\n),\nspotify_data AS\n(\n  SELECT summe as summe, date FROM \n  ${dataset}\n  WHERE platform = \"Spotify\"\n),\nrest AS(\n  SELECT SUM(summe) as summe, date FROM \n  ${dataset}\n  WHERE platform != \"ARD Audiothek\" AND platform != \"Apple Podcasts\" AND platform != \"Spotify\"\n  GROUP BY date\n)\nSELECT\n  ${dataset}.date,\n  ard_data.summe as ard_summe, \n  apple_data.summe as apple_summe, \n  spotify_data.summe as spotify_summe,\n  rest.summe as rest_summe,\n  COALESCE(ard_data.summe,0) + COALESCE(apple_data.summe, 0) + COALESCE(spotify_data.summe,0) + COALESCE(rest.summe,0) as zugriffe,\n  \"${type}\" as type,\n  DATE_DIFF(DATE('${__to:date}', \"Europe/Berlin\"),DATE('${__from:date}', \"Europe/Berlin\"),DAY) + 1 as timeRange\nFROM ${dataset}\nLEFT JOIN ard_data ON ${dataset}.date = ard_data.date\nLEFT JOIN apple_data ON ${dataset}.date = apple_data.date\nLEFT JOIN spotify_data ON ${dataset}.date = spotify_data.date\nLEFT JOIN rest ON ${dataset}.date = rest.date\nGROUP BY ${dataset}.date, ard_data.summe, apple_data.summe, spotify_data.summe, rest.summe\nORDER by date ASC"
    }
   ]
  },
  {
   "title": "Top 3 Episoden von \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  headline,\n  SUM(zugriffe) as zugriffe,\nFROM (\n  SELECT\n    FIRST_VALUE(publication_date_1) OVER (PARTITION BY headline ORDER BY publication_date_1 DESC) AS publication_date_2,\n    REPLACE(podcast_title,'\"','') as podcast_title,\n      broadcast_id,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n    SUM(m_technische_nutzer) AS technische_nutzer,\n  FROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END\nAND CASE \"\"\"${Podcast}\"\"\"\nWHEN \"All titles\" THEN True\nELSE REPLACE(podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND  headline != \"All headlines\" \nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n  GROUP BY\n    publication_date_1,\n    podcast_title,\n    headline,\n      broadcast_id\n  ORDER BY\n    zugriffe DESC )\nGROUP BY\n  publication_date_2,\n  podcast_title,\n  headline, \n  broadcast_id\n\nORDER BY 2 DESC\nLIMIT 3"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \" \""
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 38 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Zugriffe pro Tag für ausgewählte Episoden von \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "description": "Abgetragen sind die absoluten Zugriffe der jeweiligen Episode am\njeweiligen Tag. Als Standard werden die Top 8 Episoden ausgewiesen; über die Episodenauswahl\nim Filtermenü können stattdessen bis zu 8 spezifische Episoden ausgewiesen werden.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH date_range AS (\r\n  SELECT date \r\n  FROM UNNEST(GENERATE_DATE_ARRAY(\r\n    DATE('${__from:date}', \"Europe/Berlin\"), \r\n    DATE('${__to:date}', \"Europe/Berlin\")\r\n  )) AS date\r\n),\r\nepisodes_headline AS (\r\n  SELECT headline, first_date, RANK() OVER(ORDER BY zugriffe DESC) as rang FROM(\r\n  SELECT \r\n    headline, \r\n    MIN($pub_date_field) AS first_date,\r\n    SUM(IFNULL(m_zugriffe_1,0)) as zugriffe\r\n  FROM $episode_dataset\r\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates USING (headline)\r\n  WHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n  AND CASE \"$Bereich\"\r\n      WHEN \"Alle Bereiche\" THEN TRUE\r\n      ELSE branding = \"$Bereich\" \r\n  END\r\n  AND CASE \"$Podcast\"\r\n      WHEN \"All titles\" THEN TRUE\r\n      ELSE REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY_CONCAT(ARRAY[$Episode], ARRAY['None']))\r\n  END\r\n  GROUP BY headline\r\n  ORDER BY zugriffe DESC)\r\n  ORDER BY rang ASC\r\n  ${episodes_lim}\r\n),\r\nfiltered_date_range AS (\r\n  SELECT d.date, e.headline, e.rang\r\n  FROM date_range d\r\n  JOIN episodes_headline e \r\n    ON d.date >= e.first_date\r\n),\r\nfinal_data AS (\r\n  SELECT \r\n    f.date, \r\n    f.headline,\r\n    IFNULL(SUM(m_zugriffe_1), 0) AS summe, \r\n    \"${type}\" AS type,\r\n    MAX(f.rang) as rang\r\n  FROM filtered_date_range f\r\n  LEFT JOIN $episode_dataset p\r\n    ON f.date = p.date\r\n    AND REPLACE(p.headline, \"'\", \"\") = REPLACE(f.headline, \"'\", \"\")\r\n  GROUP BY f.date, f.headline\r\n)\r\nSELECT * FROM final_data\r\nWHERE date <= DATE_SUB(\"$HeuteDatum\", INTERVAL 5 DAY)\r\nAND rang <=8\r\nORDER BY headline, date ASC"
    }
   ]
  },
  {
   "title": "Tage nach Erstveröffentlichung für ausgewählte Episoden von \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "description": "Abgetragen sind die kumulierten Zugriffe nach 1, 2, ..., X Tagen für im\nausgewählten Analysezeitraum neu veröffentlichte Episoden. Der Durchschnitt bezieht sich auf\nsämtliche neue Episoden, nicht nur auf die in der Grafik einzeln dargestellten. Als Standard\nwerden die Top 8 neuen Episoden ausgewiesen; über die Episodenauswahl im Filtermenü können\nstattdessen bis zu 8 spezifische Episoden ausgewiesen werden.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH episodes_headline AS (\r\n  SELECT headline, first_pub_date, RANK() OVER(ORDER BY zugriffe DESC) as rang FROM(\r\n  \r\n  SELECT headline, MIN($pub_date_field) AS first_pub_date, SUM(IFNULL(m_zugriffe_1,0)) as zugriffe\r\n  FROM `$episode_dataset`\r\n  JOIN Piano.NDR_podcast_episode_publication_dates USING (headline)\r\n  WHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n    AND $pub_date_field BETWEEN  DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\r\n    AND CASE \"$Bereich\"\r\n      WHEN \"Alle Bereiche\" THEN TRUE\r\n      ELSE branding = \"$Bereich\"\r\n    END\r\n    AND CASE \"$Podcast\"\r\n      WHEN \"All titles\" THEN TRUE\r\n      ELSE REPLACE(headline, \"'\", \"\") IN UNNEST(ARRAY_CONCAT(ARRAY[$Episode], ARRAY['None'])) -- \r\n    END\r\n  GROUP BY headline\r\n  ORDER BY zugriffe DESC)\r\n  ORDER BY rang ASC\r\n  \r\n  --${episodes_lim}\r\n),\r\ndate_range AS (\r\n SELECT\r\n  headline,\r\n  DATE_ADD(first_pub_date, INTERVAL seq DAY) AS date\r\nFROM episodes_headline\r\nCROSS JOIN UNNEST(\r\n  GENERATE_ARRAY(0, LEAST(98, DATE_DIFF(CURRENT_DATE(), first_pub_date, DAY)))\r\n) AS seq\r\n),\r\ncumulative_data AS (\r\n  SELECT\r\n    d.headline,\r\n    DATE_DIFF(d.date, e.first_pub_date, DAY) AS days_since_pub,\r\n    SUM(IFNULL(p.m_zugriffe_1, 0)) OVER (PARTITION BY d.headline ORDER BY d.date) AS cumulative_zugriffe, \r\n    e.rang\r\n  FROM date_range d\r\n  JOIN episodes_headline e USING (headline)\r\n  LEFT JOIN `$episode_dataset` p \r\n    ON d.headline = p.headline \r\n    AND d.date = p.date\r\n), day_zero AS(\r\n  SELECT distinct headline, rang, days_since_pub, cumulative_zugriffe\r\n  FROM episodes_headline\r\n  CROSS JOIN (SELECT 0 as days_since_pub, 0 as cumulative_zugriffe)\r\n)\r\nSELECT DISTINCT * FROM (\r\nSELECT \r\n  days_since_pub + 1 as days_since_pub,\r\n  headline,\r\n  cumulative_zugriffe AS summe,\r\n  \"${type}\" AS type, \r\n  rang,\r\nFROM cumulative_data\r\nWHERE days_since_pub <= $Tage_content_lifetime\r\nAND rang <=8\r\nUNION ALL \r\nSELECT days_since_pub + 1 as days_since_pub, \r\n\"Durchschnitt alle neuen Episoden\" as headline, \r\nAVG(cumulative_zugriffe) as summe, \r\n\"${type}\" AS type,\r\n0 as rang FROM cumulative_data\r\n  GROUP BY days_since_pub\r\n  HAVING days_since_pub <= $Tage_content_lifetime\r\nUNION ALL\r\nSELECT\r\n0 as days_since_pub,\r\n\"Durchschnitt alle neuen Episoden\" as headline,\r\n0 as summe,\r\n\"${type}\" as type,\r\n8 as rang\r\nUNION ALL \r\nSELECT\r\ndays_since_pub,\r\nheadline,\r\ncumulative_zugriffe as summe,\r\n\"${type}\" as type,\r\nrang\r\nFROM day_zero\r\nWHERE rang <=8\r\nORDER BY headline, days_since_pub ASC\r\n)\r\nWHERE days_since_pub <= (SELECT MAX(days_since_pub) + 1  \r\nFROM cumulative_data\r\nWHERE days_since_pub + 1 <= $Tage_content_lifetime\r\nAND rang <=8)\r\n"
    }
   ]
  },
  {
   "title": "Episoden",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  DATE(publication_date_new) as publication_date_new,\n  podcast_title,\n    broadcast_id,\n  headline,\n  SUM(zugriffe) as zugriffe\n  --SUM(technische_nutzer)\nFROM (\n  SELECT\n    FIRST_VALUE($pub_date_field) OVER (PARTITION BY headline ORDER BY $pub_date_field DESC) AS publication_date_new,\n    REPLACE(podcast_title,'\"','') AS podcast_title,\n      broadcast_id,\n    headline,\n    SUM(m_zugriffe_1) AS zugriffe,\n    SUM(m_technische_nutzer) AS technische_nutzer\n  FROM $episode_dataset\n  LEFT JOIN Piano.NDR_podcast_episode_publication_dates USING (headline)\nWHERE CASE \"$Bereich\"\nWHEN \"Alle Bereiche\" THEN TRUE\nELSE branding = \"$Bereich\" END\nAND  CASE \"$Podcast\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(podcast_title,'\"','') = \"\"\"$Podcast\"\"\" END\nAND CASE \"${Podcast:text}\"\nWHEN \"All titles\" THEN TRUE\nELSE REPLACE(headline,\"'\",\"\") IN UNNEST(ARRAY_CONCAT(ARRAY[$Episode], ARRAY['None'])) END\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\n  GROUP BY\n  publication_date_1,\n    $pub_date_field,\n    podcast_title,\n    headline,\n      broadcast_id\n  ORDER BY\n    zugriffe DESC )\nGROUP BY\n  publication_date_new,\n  podcast_title,\n  headline, \n  broadcast_id\n\nORDER BY zugriffe DESC\n--LIMIT 1000"
    }
   ]
  },
  {
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id, podcast_title\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE \n    ELSE branding = \"$Bereich\" END \n    AND CASE \"\"\"$Podcast\"\"\"\nWHEN \"All titles\" THEN TRUE\nELSE CAST(broadcast_id[0] AS STRING) = \"$broadcast_id_branding\" END\n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(SELECT \npodcast_title as Title,\n1 as join_key,\nsum(m_zugriffe_1) as zugriffe,\nplatform\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY platform, podcast_title),\ntechnische_nutzer_summe AS(\n  SELECT podcast_title as Title,\n  1 as join_key,\n  ROUND(sum(m_technische_nutzer)/$number_of_days) as technische_nutzer\n  FROM $episode_dataset\nWHERE \nCASE \"$Bereich\"\n  WHEN \"Alle Bereiche\"\n  THEN TRUE \n  ELSE \nbranding = \"$Bereich\" END\nAND CASE \"\"\"$Podcast\"\"\"\nWHEN \"All titles\" THEN True\nELSE podcast_title = \"\"\"$Podcast\"\"\" END \nAND headline != \"All headlines\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nGROUP BY podcast_title),\nmain_data AS(\nSELECT Title, join_key, sum(zugriffe) as zugriffe\nFROM all_titles_platforms\nGROUP BY Title, join_key),\nard_data AS (\n  SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"ARD Audiothek\"\n),\napple_data AS\n(\n    SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"Apple Podcasts\"\n),\nspotify_data AS\n(\n  SELECT Title, zugriffe, join_key FROM \n  all_titles_platforms\n  WHERE platform = \"Spotify\"\n)\nSELECT\n  main_data.Title, \n  main_data.zugriffe,\n  --technische_nutzer_summe.technische_nutzer, \n  ard_data.zugriffe as ard_summe, \n  apple_data.zugriffe as apple_summe, \n  spotify_data.zugriffe as spotify_summe\nFROM main_data\nLEFT JOIN ard_data ON (main_data.join_key = ard_data.join_key AND main_data.Title = ard_data.Title)\nLEFT JOIN apple_data ON (main_data.join_key = apple_data.join_key AND main_data.Title = apple_data.Title)\nLEFT JOIN spotify_data ON (main_data.join_key = spotify_data.join_key AND main_data.Title = spotify_data.Title)\n--LEFT JOIN technische_nutzer_summe on (main_data.join_key = technische_nutzer_summe.join_key AND main_data.Title = technische_nutzer_summe.Title)\nORDER BY main_data.zugriffe DESC"
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 74 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Durchschnitt pro Episode für neu veröffentlichte Episoden",
   "type": "table",
   "description": "Abgetragen sind die kumulierten Zugriffe nach 7, 14, 28, 56 und 91 Tagen\nfür im ausgewählten Analysezeitraum neu veröffentlichte Episoden aller ausgewählten Podcasts.\nÜber das Dropdown-Menü oben links kann ein individueller Zeitraum zwischen 1 und 99 Tagen\ndefiniert werden. ACHTUNG: Die Stichprobe der Episoden variiert je nach betrachtetem\nZeitintervall. So ist unter Umständen auch ein kleinerer Wert für 56 Tage als für 28 Tage möglich.\nFür robuste Ergebnisse bitte einen möglichst langen Analysezeitraum wählen.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nSELECT $avgEpisodesQueryCols, podcast_title\r\n\r\n        FROM ($avgEpisodesQuery)\r\nORDER BY podcast_title ASC"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  \"Durchschnitt $Podcast_title\", *  FROM (\r\nSELECT $avg_avgEpisodesQueryCols\r\n        FROM ($avgEpisodesQuery)\r\n)"
    }
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zugriffe pro Tag für \"$Podcast_title\"",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH broadcastids AS (\n    SELECT DISTINCT CAST(broadcast_id[0] AS STRING) AS broadcast_id\n    FROM $profiles_dataset\n    WHERE CASE \"$Bereich\"\n    WHEN \"Alle Bereiche\" THEN TRUE\n    ELSE branding = \"$Bereich\" END \n    ORDER BY broadcast_id DESC\n),\nall_titles_platforms AS(\nSELECT \n    SUM(m_zugriffe_1) AS summe, \n    platform,\n    date\nFROM $platform_dataset as pd\nINNER JOIN broadcastids ON pd.broadcast_id = broadcastids.broadcast_id\nWHERE date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND CASE \"$Plattformen\"\nWHEN \"Alle Plattformen\" THEN TRUE\nELSE platform = \"$Plattformen\" END\nGROUP BY platform, date),\nnot_all_titles_platforms AS(\n    SELECT\n  sum(m_zugriffe_1) AS summe, platform,\n  date\nFROM $platform_dataset\nWHERE\nbroadcast_id = \"$broadcast_id_branding\"\nAND date BETWEEN DATE('${__from:date}', \"Europe/Berlin\") AND DATE('${__to:date}', \"Europe/Berlin\")\nAND CASE \"$Plattformen\"\nWHEN \"Alle Plattformen\" THEN TRUE\nELSE platform = \"$Plattformen\" END\ngroup by platform, date\n)\nSELECT\n  ${dataset}.date,\n  \"${type}\" as type,\n  SUM(summe) as zugriffe,\n  \"$Plattformen\" as platform,\n  DATE_DIFF(DATE('${__to:date}', \"Europe/Berlin\"),DATE('${__from:date}', \"Europe/Berlin\"),DAY) + 1 as timeRange\nFROM ${dataset}\nGROUP BY ${dataset}.date\nORDER by date ASC"
    }
   ]
  }
 ]
}