{
 "title": "SEO CacheTest",
 "time": { "from": "2023-10-25T00:00:00.000Z", "to": "2023-10-30T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": "MDR : mdr, NDR : ndr, Brisant : brisant, KiKA : kika, KiKANiNCHEN : kikaninchen, Eurovision : eurovision"
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "searchconUrlTable",
    "query": {}
   },
   {
    "name": "Property",
    "query": {}
   },
   {
    "name": "Redaktionen",
    "query": {}
   },
   {
    "name": "Unterkapitel",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": "Letzte 7 Tage : data_date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  9 DAY) AND data_date < DATE_SUB(CURRENT_DATE()\\, INTERVAL 2 DAY), Letzte 28 Tage : data_date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  28 DAY) AND data_date < CURRENT_DATE(), Letzte 3 Monate : data_date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  3 MONTH) AND data_date < CURRENT_DATE(), Letzte 6 Monate : data_date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  6 MONTH) AND data_date < CURRENT_DATE()"
   },
   {
    "name": "searchconTopQueryTable",
    "query": {}
   },
   {
    "name": "searchconTopUrlTable",
    "query": {}
   },
   {
    "name": "bq_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_timeframe_end",
    "query": {}
   },
   {
    "name": "distroRefTable",
    "query": {}
   },
   {
    "name": "sophora",
    "query": {}
   },
   {
    "name": "bq_gsc_timeframe_start",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Hinweise",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "options": {
      "content": "**Piano-Daten**\n\n- Die Daten werden für die letzten abgeschlossenen Tage des gewählten Zeitraums angegeben.\n- Der heutige Tag wird also nicht einbezogen.\n- Daten können von Piano-Daten bei den Dashboards von AT Internet abweichen, wenn die Sophora-ID geändert wurde.\n- App-Daten sind nicht enthalten, zu sehen sind nur die Web-Daten."
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
     "options": {
      "content": "**GSC-Daten**\n\n- Die neuesten Daten aus der Google Search Console sind grundsätzlich drei Tage alt, da Google keine aktuelleren Daten anbietet.\n- Es fehlen also stets die Daten von heute, gestern und vorgestern.\n- Betrachtet werden die letzten sieben Tage ab diesem Zeitpunkt. "
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
     "options": {
      "content": "**Vergleichbarkeit der Daten**\n\n- In Piano wird der Traffic in Visits gezählt, in der Google Search Console in Klicks. Die zwei Metriken sind nicht identisch und weichen deshalb voneinander ab.\n"
     }
    }
   ]
  },
  { "title": "Leistungsübersicht (GSC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Leistung (Clicks)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT\n  DATE(data_date) as time,\n  SUM(IF(search_type IN (\"IMAGE\", \"WEB\", \"VIDEO\", \"NEWS\"), clicks, 0)) as search,\n  SUM(IF(search_type IN (\"DISCOVER\"), clicks, 0)) as discover,\n  SUM(IF(search_type IN (\"GOOGLE_NEWS\"), clicks, 0)) as news,\n  SUM(clicks) as total,\n  CASE \"${Zeitraum:text}\"\n    WHEN \"Letzte 7 Tage\" THEN \"7 Tage\"\n    WHEN \"Letzte 28 Tage\" THEN \"28 Tage\"\n    WHEN \"Letzte 3 Monate\" THEN \"3 Monate\"\n    WHEN \"Letzte 6 Monate\" THEN \"6 Monate\"\n  END AS timeRange\nFROM\n  $searchconUrlTable\nWHERE\n  url_property LIKE ${Property:doublequote}\n  AND data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\nGROUP BY data_date\nORDER BY data_date"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "location": "europe-west3", "project": "ndr-code-bi-dashboard", "rawSql": "SELECt ' ' as value" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT 'Clicks Total' as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT 'Impressions Total' as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT \"CTR Total\" as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT \"Total\" as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  SUM(clicks) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  --AND search_type IN (\"WEB\", \"NEWS\", \"DISCOVER\", \"GOOGLE_NEWS\", \"IMAGE\", \"VIDEO\")\r\n  AND url_property LIKE ${Property:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  SUM(impressions) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  url_property LIKE ${Property:doublequote}\r\n  AND data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  AVG(CTR)\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND url_property LIKE ${Property:doublequote}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT \"Suche (Web, Bilder, Videos & News)\" as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  SUM(clicks) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND search_type IN (\"WEB\", \"IMAGE\", \"VIDEO\", \"NEWS\")\r\n  AND url_property LIKE ${Property:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  SUM(impressions) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  search_type IN (\"WEB\", \"IMAGE\", \"VIDEO\", \"NEWS\")\r\n  AND url_property LIKE ${Property:doublequote}\r\n  AND data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  AVG(CTR)\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND search_type IN (\"IMAGE\", \"WEB\", \"VIDEO\", \"NEWS\")\r\n  AND url_property LIKE ${Property:doublequote}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT 'Google News' as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  SUM(clicks) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND search_type IN(\"GOOGLE_NEWS\")\r\n  AND url_property LIKE ${Property:doublequote}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  SUM(impressions) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND url_property LIKE ${Property:doublequote}\r\n  AND search_type = \"GOOGLE_NEWS\"\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  AVG(CTR) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND search_type = \"GOOGLE_NEWS\"\r\n  AND url_property LIKE ${Property:doublequote}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(value)), value)\r\nFROM(\r\nSELECT 'Google Discover' as value\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  SUM(clicks) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND search_type = \"DISCOVER\"\r\n  AND url_property LIKE ${Property:doublequote}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  SUM(impressions) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND search_type = \"DISCOVER\"\r\n  AND url_property LIKE ${Property:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\r\nSELECT\r\n  AVG(CTR) as summe\r\nFROM\r\n  $searchconUrlTable\r\nWHERE\r\n  data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\r\n  AND search_type = \"DISCOVER\"\r\n  AND url_property LIKE ${Property:doublequote}\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 }, "options": { "content": " " } },
  { "title": "Top 100 Visits (Piano)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Top Web Artikel | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT\nveroeffDatum,\ncontent_titel,\nsum(m_visits) as visits,\nsum(m_page_loads) as page_views,\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_bounce_rate*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_bounce_rate,\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_suchmaschinen_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_suchmaschinen_anteil_visits,\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_homepage_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_homepage_anteil_visits,\ncontent_id_sophora, url\nFROM\n(\nSELECT\nFIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY date DESC) as veroeffDatum,\nFIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY date DESC) as content_id_sophora, \npage_chapter2, page_chapter1,\nm_visits,\nm_page_loads,\nm_bounce_rate,\nm_suchmaschinen_anteil_visits,\nm_homepage_anteil_visits, \n--FIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY date DESC) as url,\nFIRST_VALUE(CASE WHEN url != \"N/A\" THEN url ELSE NULL END) OVER (PARTITION BY uuid ORDER BY (CASE WHEN url != \"N/A\" THEN date END) DESC) as url,\nFIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY date DESC) as content_titel, \nFROM \n`ndr-code-bi-dashboard.Piano.articles_joined_daily`\nWHERE\n--site_level2 LIKE \"${LRA}.de\"\n--AND CASE\n  --WHEN \"${Redaktionen:text}\" != \"None\" THEN page_chapter1 = \"$Redaktionen\"\n  --ELSE page_chapter1 IS NOT NULL\n--END\n--AND CASE\n  --WHEN \"${Unterkapitel:text}\" != \"None\" THEN page_chapter2 = \"$Unterkapitel\"\n  --ELSE page_chapter2 IS NOT NULL\n--END\n\nCASE    \n    WHEN \"${LRA:text}\" = \"Brisant\" THEN page_chapter1 = \"Brisant\"\n    ELSE\n      site_level2 LIKE \"${LRA}.de\"\n      AND CASE\n        WHEN \"${Redaktionen:text}\" != \"None\" THEN page_chapter1 = \"$Redaktionen\"\n        ELSE page_chapter1 IS NOT NULL\n      END\n      AND CASE\n        WHEN \"${Unterkapitel:text}\" != \"None\" THEN page_chapter2 = \"$Unterkapitel\"\n        ELSE page_chapter2 IS NOT NULL\n      END\nEND\n\n--AND CASE\n  --WHEN \"${Redaktionen:text}\" = \"None\" THEN \"Alle Kapitel 1\" IN UNNEST(page_chapter1_tags)\n  --ELSE \"${Redaktionen:text}\" IN UNNEST(page_chapter1_tags)\n--END\n--AND CASE\n  --WHEN \"${Unterkapitel:text}\" = \"None\" THEN \"Alle Kapitel 2\" IN UNNEST(page_chapter2_tags)\n  --ELSE \"${Unterkapitel:text}\" IN UNNEST(page_chapter2_tags)\n--END\n\nAND content_id_sophora NOT LIKE \"%index%\"\nAND content_id_sophora NOT LIKE \"%N/A%\"\nAND content_id_sophora NOT LIKE \"%verteilseite%\"\nAND content_id_sophora NOT LIKE \"%nachrichtenfeed%\"\nAND content_id_sophora NOT LIKE \"nachrichten%\"\nAND content_id_sophora NOT LIKE \"verkehrszentrum%\"\nAND content_id_sophora NOT LIKE \"radiostream%\"\nAND page_chapter1 NOT LIKE \"CONT\"\nAND objekt_typ NOT LIKE \"indexPage\"\n--AND content_titel NOT LIKE \"Live\"\n--AND content_titel NOT LIKE \"%Programmübersicht%\"\n--AND content_titel NOT LIKE \"%Tippspiel%\"\n--AND content_titel NOT LIKE \"%N/A%\"\n--AND content_titel NOT LIKE \"Wetter\"\n--AND url NOT LIKE \"%.json%\"\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\nGROUP BY content_id_sophora, content_titel, veroeffDatum, page_chapter2, page_chapter1, url\nORDER BY 4 DESC\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 }, "options": { "content": " " } },
  { "title": "Top 100 Referrer (Piano)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Web | Top Referrer (nach Artikeln) | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT \n  content_titel,\n  SUM(m_visits) as Visits,\n  referrer,\n  $sophora as content_id_sophora,\n  distribution as Distribution\nFROM\n(\n  SELECT\n  FIRST_VALUE(content_titel) OVER (PARTITION BY $sophora ORDER BY date DESC) as content_titel,\n  --content_titel,\n  m_visits, \n  referrer,\n  $sophora,\n  distribution,\n  date\n  FROM `$distroRefTable`\n  WHERE\n    CASE WHEN \"${LRA:text}\" = \"Brisant\" THEN site_level2 = \"Brisant\"\n    ELSE\n      site_level2 LIKE \"${LRA}.de\"\n      AND CASE\n        WHEN \"${Redaktionen:text}\" != \"None\" THEN page_chapter1 = \"$Redaktionen\"\n        ELSE page_chapter1 IS NOT NULL\n      END\n      AND CASE\n        WHEN \"${Unterkapitel:text}\" != \"None\" THEN page_chapter2 = \"$Unterkapitel\"\n        ELSE page_chapter2 IS NOT NULL\n      END\n    END\n  AND CAST(date as DATE) >= ${bq_timeframe_start:doublequote} AND CAST(date as DATE) <= ${bq_timeframe_end:doublequote}\n  AND referrer NOT LIKE \"%N/A%\"\n  --AND CASE WHEN \n    --    site_level2 = \"mdr.de\" \n      --  THEN (distribution = \"web\" OR distribution =\"amp\")\n        --ELSE 1=1 END\n  --AND NOT distribution IS null AND NOT distribution = \"N/A\" AND NOT distribution = \"404\"\n)\nGROUP BY \nDistribution, \nreferrer,\ncontent_titel,\ncontent_id_sophora\nORDER BY Visits DESC\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 }, "options": { "content": " " } },
  {
   "title": "Web | Top Referrer (Domains) | $Zeitraum",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 1, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT \n  SUM(m_visits), \n  src_referrer_site_domain,\nFROM `Piano.distro_joined_daily`\nWHERE \nCASE WHEN \"${LRA:text}\" = \"Brisant\" THEN page_chapter1 = \"Brisant\"\nELSE\n  site_level2 = \"${LRA}.de\"\n  --AND page_chapter1 = \"$Redaktionen\"\n  --AND page_chapter2 = \"$Unterkapitel\"\n  AND CASE\n    WHEN \"${Redaktionen:text}\" = \"None\" THEN page_chapter1 = \"Alle Kapitel 1\"\n    ELSE page_chapter1 = \"${Redaktionen:text}\"\n  END\n  AND CASE\n    WHEN \"${Unterkapitel:text}\" = \"None\" THEN page_chapter2 = \"Alle Kapitel 2\"\n    ELSE page_chapter2 = \"${Unterkapitel:text}\"\n  END\nEND\nAND sendungs_id = \"Alle Sendungs-ID\"\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\nAND src_referrer_site_domain NOT LIKE \"%N/A%\"\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END\nGROUP BY\nsrc_referrer_site_domain \nORDER BY 1 DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Web | Traffic Quellen | $Zeitraum",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 11, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT \n  SUM(m_visits), \n  CASE \n    WHEN src IN (\"qr\", \"QR-Code\", \"qrcode\") THEN \"QR-Code\"\n    WHEN src IN (\"Social Media\", \"Social media\", \"social media\", \"Socialmedia\") THEN \"Social Media\"\n    ELSE src\n  END AS grouped_src\nFROM `Piano.distro_joined_daily`\nWHERE \n  CASE WHEN \"${LRA:text}\" = \"Brisant\" THEN page_chapter1 = \"Brisant\"\n  ELSE\n    site_level2 = \"${LRA}.de\"\n    AND CASE\n    WHEN \"${Redaktionen:text}\" = \"None\" THEN page_chapter1 = \"Alle Kapitel 1\"\n    ELSE page_chapter1 = \"${Redaktionen:text}\"\n    END\n  AND CASE\n    WHEN \"${Unterkapitel:text}\" = \"None\" THEN page_chapter2 = \"Alle Kapitel 2\"\n    ELSE page_chapter2 = \"${Unterkapitel:text}\"\n    END\n  END\nAND sendungs_id = \"Alle Sendungs-ID\"\n--AND page_chapter1 = \"$Redaktionen\"\n--AND page_chapter2 = \"$Unterkapitel\"\n--AND sendungs_id = \"$Sendung\"\nAND src NOT LIKE \"%N/A%\"\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\nGROUP BY grouped_src\nHAVING SUM(m_visits) > 0\nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 74 }, "options": { "content": " " } },
  { "title": "Top 100 Suchanfragen (GSC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Top Suchanfragen | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT\nsuchanfragen AS Suchanfragen,\nSUM(clicks) AS Clicks,\nAVG(position) AS Position\n--(ROUND((sum(position) / sum(impressions))) + 1.0) AS Position\nFROM $searchconTopQueryTable\nWHERE \nsuchanfragen != \"\"\nAND url_property LIKE \"${Property:value}\"\nAND data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\nGROUP BY suchanfragen\nORDER BY Clicks DESC\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 }, "options": { "content": " " } },
  { "title": "Top 100 URLs (GSC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Top URLs | Gesamt | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT\n  sum(clicks) AS Clicks,\n  url\nFROM $searchconTopUrlTable\nWHERE data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\nAND CASE WHEN url like \"%brisant.de%\" OR url like \"%kika.de%\" or url like \"%kikaninchen.de%\" or url like \"%eurovision.de%\"\n  THEN url LIKE \"${Property:value}%\"\n  ELSE url LIKE \"${Property:value}/%\"\nEND \nAND url IS NOT null\nGROUP BY url\nORDER BY Clicks DESC\nLIMIT 100\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 106 }, "options": { "content": " " } },
  {
   "title": "Top URLs | Suche (Web, Bilder, Videos & News) | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT\n  sum(clicks) AS Clicks,\n  url\nFROM $searchconTopUrlTable\nWHERE data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\nAND CASE WHEN url like \"%brisant.de%\" OR url like \"%kika.de%\" or url like \"%kikaninchen.de%\" or url like \"%eurovision.de%\"\n  THEN url LIKE \"${Property:value}%\"\n  ELSE url LIKE \"${Property:value}/%\"\nEND \nAND search_type IN (\"WEB\", \"IMAGE\", \"VIDEO\", \"NEWS\")\nAND url IS NOT null\nGROUP BY url\nORDER BY Clicks DESC\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 121 }, "options": { "content": " " } },
  {
   "title": "Top URLs | Discover | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT\n  sum(clicks) AS Clicks,\n  url\nFROM $searchconTopUrlTable\nWHERE data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\nAND CASE WHEN url like \"%brisant.de%\" OR url like \"%kika.de%\" or url like \"%kikaninchen.de%\" or url like \"%eurovision.de%\"\n  THEN url LIKE \"${Property:value}%\"\n  ELSE url LIKE \"${Property:value}/%\"\nEND \nAND search_type = \"DISCOVER\"\nAND url IS NOt null\nGROUP BY url\nORDER BY Clicks DESC\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 136 }, "options": { "content": " " } },
  {
   "title": "Top URLs | Google News | $Zeitraum",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT\n  sum(clicks) AS Clicks,\n  url\nFROM $searchconTopUrlTable\nWHERE data_date >= ${bq_gsc_timeframe_start:doublequote} AND data_date <= ${bq_timeframe_end:doublequote}\nAND CASE WHEN url like \"%brisant.de%\" OR url like \"%kika.de%\" or url like \"%kikaninchen.de%\" or url like \"%eurovision.de%\"\n  THEN url LIKE \"${Property:value}%\"\n  ELSE url LIKE \"${Property:value}/%\"\nEND \nAND search_type = \"GOOGLE_NEWS\"\nAND url IS NOt null\nGROUP BY url\nORDER BY Clicks DESC\nLIMIT 100"
    }
   ]
  }
 ]
}