{
 "title": "TDI Telemedienampel - André",
 "description": "Eine Version, die den Zeitraum \"25-27.10\" beinhaltet.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Zeitraum",
    "query": "Heute : CAST(date AS DATE) = CURRENT_DATE(), Gestern : CAST(date AS DATE) = DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY), Vorgestern : CAST(date AS DATE) = DATE_SUB(CURRENT_DATE()\\, INTERVAL  2 DAY), 25-27.10 : CAST(date AS DATE) BETWEEN DATE(2023\\,10\\,25) AND DATE(2023\\,10\\,27)"
   },
   {
    "name": "Redaktion",
    "query": "TDI : Nachrichten, Sport, Wissen, Kultur, Medienkompetenz, Brisant"
   },
   {
    "name": "HauptknotenKlassifikation",
    "query": {}
   },
   {
    "name": "HauptknotenArtikel",
    "query": {}
   },
   {
    "name": "Unterknoten",
    "query": {}
   },
   {
    "name": "bq_six_months",
    "query": {}
   },
   {
    "name": "bq_date",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "last_update_condition",
    "query": {}
   },
   {
    "name": "Stats_text",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Beschreibung",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "A Grün",
     "type": "text",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "options": {
      "content": "- Kurzer News-Artikel, mit Audio/Video ohne Sendebezug\n- Kurzer News-Artikel, mit Sendebezug und Audio/Video\n- Langer Newsartikel mit Sendebezug und Audio/Video\n- Langer Newsartikel mit aktuellen Video/Audio\n- Langer Nachrichtenartikel mit Sendebezug und ausgelaufen Videos/Audio\n- Artikel ohne Sendebezug mit aktuellen Audios/Video\n- Artikel ohne Sendebezug mit Animation, Datenvisualisierung"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "B Gelb",
     "type": "text",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
     "options": {
      "content": "- Kurzer News-Artikel ohne Sendebezug, ohne Audios/Video\n- Kurzer News-Artikel mit Sendebezug, ohne Audio und Video\n- Langer Newsartikel ohne Sendebezug\n- Langer Newsartikel nur mit Sendebezug\n- Langer Newsartikel mit älteren Video/Audio nur"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "C Rot ",
     "type": "text",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
     "options": {
      "content": "- Andere Kombinationen Typ A\n- Andere Kombinationen Typ B"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Aktualität",
     "type": "text",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
     "options": {
      "content": "Die Daten werden stündlich zwischen 06:00 Uhr und 21:00 Uhr aktualisiert. "
     },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Artikelklassifikation Insgesamt | $Zeitraum",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MDR",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH max_timestamp AS (\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_${Redaktion:raw}`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n)\n\nSELECT A, B, C\nFROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_${Redaktion:raw}`\nWHERE last_update = (SELECT latest_timestamp FROM max_timestamp)\n  AND structureNodePath = \"main_${Redaktion:raw}\";\n\n"
    }
   ]
  },
  {
   "title": "Artikelklassifikationen pro Kategorie | $Zeitraum",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "dataset": "MDR",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH max_timestamp AS (\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_$dataset`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n), \nmax_timestamp_ratgeber AS(\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_Ratgeber`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n\n)\nSELECT structureNodePath, A, B, C\nFROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_$dataset`\nWHERE $last_update_condition\nAND structureNodePath != \"main_${Redaktion:raw}\"\n"
    }
   ]
  },
  {
   "title": "Statistik | $Stats_text",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  FORMAT_DATE('%Y/%m', PARSE_DATE('%Y-%m-%d', date)) AS YearMonth, -- Combines year and month into a single string 'YYYY-MM'\n  SUM(A) AS A,\n  SUM(B) AS B,\n  SUM(C) AS C\nFROM\n  `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_${Redaktion:raw}_daily`\nWHERE\n  CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date >= ${bq_six_months:doublequote} END\n  \n  AND structureNodePath = \"main_${Redaktion:raw}\"\nGROUP BY\n  YearMonth\nORDER BY\n  YearMonth;"
    }
   ]
  },
  {
   "title": "Artikel der Kategorie C",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH max_timestamp AS (\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_$dataset`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n), \nmax_timestamp_ratgeber AS(\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_Ratgeber`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n\n)\n\nSELECT \n       article.item.classificationDescription AS Klassifikationsbeschreibung,\n       article.item.sophoraId AS SophoraID,\n       structureNodePath AS Unterknoten,\n       article.item.url AS URL\nFROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_${Redaktion:raw}`,\n      UNNEST(articlesC.list) as article\nWHERE $last_update_condition \n  AND structureNodePath != \"main_${Redaktion:raw}\";\n"
    }
   ]
  },
  {
   "title": "Artikel der Kategorie B",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH max_timestamp AS (\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_$dataset`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n), \nmax_timestamp_ratgeber AS(\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_Ratgeber`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n\n)\n\nSELECT \n       article.item.classificationDescription AS Klassifikationsbeschreibung,\n       article.item.sophoraId AS SophoraID,\n       structureNodePath AS Unterknoten,\n       article.item.url as URL,\n\nFROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_${Redaktion:raw}`,\n      UNNEST(articlesB.list) as article\nWHERE $last_update_condition \n  AND structureNodePath != \"main_${Redaktion:raw}\";\n"
    }
   ]
  },
  {
   "title": "Artikel der Kategorie A ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH max_timestamp AS (\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_$dataset`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n), \nmax_timestamp_ratgeber AS(\n  SELECT MAX(last_update) AS latest_timestamp\n  FROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_Ratgeber`\n  WHERE CASE \"${Zeitraum:text}\" \n  WHEN \"25-27.10\" THEN $Zeitraum\n  ELSE date = ${bq_date:doublequote} END\n\n)\n\nSELECT \n       article.item.classificationDescription AS Klassifikationsbeschreibung,\n       article.item.sophoraId AS SophoraID,\n       structureNodePath as Unterknoten,\n       article.item.url AS URL\nFROM `ndr-code-bi-dashboard.MDR.gcs_telemedienampel_$dataset`,\n      UNNEST(articlesA.list) as article\nWHERE $last_update_condition\n  AND structureNodePath != \"main_${Redaktion:raw}\";\n"
    }
   ]
  }
 ]
}