{
 "title": "Social Media Report Facebook",
 "description": "Anpassungen September 2024",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Monat",
    "query": {}
   },
   {
    "name": "Jahr",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "query1",
    "query": {}
   },
   {
    "name": "Month",
    "query": {}
   },
   {
    "name": "Monat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastMonat_abkuerzung",
    "query": {}
   },
   {
    "name": "LastJahr",
    "query": {}
   },
   {
    "name": "YearFromLastMonth",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": {}
   },
   {
    "name": "profile_Zeitraum",
    "query": {}
   },
   {
    "name": "Vormonat",
    "query": {}
   },
   {
    "name": "Stichtag",
    "query": {}
   },
   {
    "name": "stichtagmonat",
    "query": {}
   },
   {
    "name": "table_suffix",
    "query": {}
   },
   {
    "name": "dataset_suffix",
    "query": {}
   },
   {
    "name": "last_month",
    "query": {}
   },
   {
    "name": "year_from_last_month",
    "query": {}
   },
   {
    "name": "last_year",
    "query": {}
   },
   {
    "name": "month_from_last_year",
    "query": {}
   },
   {
    "name": "Vergleich",
    "query": {}
   },
   {
    "name": "month_as_number",
    "query": {}
   },
   {
    "name": "LRA_mapping",
    "query": {}
   },
   {
    "name": "src_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# 📊 Hinweis\n\n- Durch nachträgliche Importe und Speicherung der Daten kann es im Vergleich mit anderen Stichtags-Erhebungen (z.B. den Berichten der Medienforschungen) Abweichungen bei den Daten geben.\n- Dashboard-Anpassungen aufgrund von Änderungen bei Facebook: Aktive Nutzer und Interaktionen werden bis einschließlich März 2024 auf Page Ebene ausgewiesen, ab April 2024 wurden sie ersetzt durch die Werte auf Post Ebene."
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [
         { "name": "total_video_10s_views", "type": "functionParameter" }
        ],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "facebookInsightsOwnVideos"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "Letzter Datenstand: </br>\n${stichtagmonat}\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 1, "x": 16, "y": 2 },
   "options": {
    "content": "<img \n  src=\"${src_url}\" \n  alt=\"Tracking Pixel\" \n  width=\"1\" \n  height=\"1\" \n  style=\"display:none;\"\n/>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "options": {
    "content": "# Facebook Report | ${Month} ${Jahr}\n\n"
   }
  },
  {
   "title": "Entwicklung: Potenzielle Reichweite",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "type": "barchart",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE profiles STRING;\r\nSET profiles = (\"$query1\");\r\nEXECUTE IMMEDIATE format(\"\"\"WITH all_data AS(\r\nSELECT DATE(jahr,monat,1) as month_year, REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile, pot_reichweite_pro_tag as impressionsUnique FROM Quintly_frozen.facebook_metrics\r\nWHERE LRA = \"$LRA_mapping\" AND \r\nCASE $month_as_number\r\nWHEN 19 THEN jahr = $Jahr AND monat < 13\r\nELSE monat < 13 AND DATE(jahr,monat,1) BETWEEN DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL 1 YEAR) AND DATE($Jahr,$month_as_number,1) END\r\nORDER BY month_year ASC),\r\nmax_date AS(\r\nSELECT MAX(month_year) as max_datum FROM all_data\r\n),\r\ntop_8_profiles_current_month AS(\r\nSELECT profile FROM all_data\r\nWHERE month_year = (SELECT max_datum FROM max_date)\r\nORDER BY impressionsUnique DESC\r\nLIMIT 8\r\n), top_8_profiles AS(\r\nSELECT * FROM all_data\r\nWHERE profile IN (SELECT profile FROM top_8_profiles_current_month)),\r\nrest AS(\r\nSELECT month_year, \"Rest\" as profile, SUM(impressionsUnique) as impressionsUnique\r\nFROM all_data\r\nWHERE profile NOT IN (SELECT profile FROM top_8_profiles_current_month)\r\nGROUP BY month_year)\r\nSELECT * FROM(\r\nSELECT * FROM top_8_profiles\r\nUNION ALL\r\nSELECT * FROM rest\r\nWHERE CASE \r\nWHEN profile = \"Rest\" THEN impressionsUnique IS NOT NULL \r\nELSE TRUE END\r\nORDER BY month_year, profile)\r\nPIVOT (\r\n  SUM(impressionsUnique) FOR profile IN (%s)\r\n)\r\nORDER BY DATE(month_year) ASC\r\n\"\"\", profiles);"
    }
   ]
  },
  {
   "title": "Anteil Top 8 + Rest | $Monat $Jahr",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH top_8_profiles AS(\r\n  SELECT profile, pot_reichweite_pro_tag as impressionsUnique\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY pot_reichweite_pro_tag DESC\r\nLIMIT 8\r\n), rest AS(\r\n  SELECT \"Rest\" as profile, SUM(pot_reichweite_pro_tag) as impressionsUnique\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nAND profile NOT IN (SELECT profile FROM top_8_profiles)\r\n)\r\nSELECT REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\nimpressionsUnique FROM(\r\nSELECT profile, impressionsUnique FROM top_8_profiles\r\nUNION ALL\r\nSELECT profile, impressionsUnique FROM rest\r\nWHERE CASE \r\nWHEN profile = \"Rest\" THEN impressionsUnique IS NOT NULL \r\nELSE TRUE END)"
    }
   ]
  },
  { "title": "Entwicklung: Interaktionen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Summe Interaktionen $LRA Profile in Mio.",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DATE(jahr,monat,1) as month, SUM(interactions)/1000000 as lm_interactions FROM Quintly_frozen.facebook_metrics\r\nWHERE LRA = \"$LRA_mapping\" AND \r\nCASE $month_as_number\r\nWHEN 19 THEN jahr = $Jahr AND monat < 13\r\nELSE monat < 13 AND DATE(jahr,monat,1) BETWEEN DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL 1 YEAR) AND DATE($Jahr,$month_as_number,1) END\r\nGROUP BY month\r\nORDER BY month ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 9, "y": 23 },
   "options": {
    "content": "### Zusammensetzung Interaktionen | ${Monat:text}  ${Jahr} \n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 23 }, "options": { "content": "### Interaktionen in Mio.\n" } },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT SUM(reactions) AS Reaktionen, SUM(comments) AS Kommentare, SUM(shares) as Shares FROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number  AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 16, "y": 25 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Summe')), 'Summe')\r\nFROM(\r\nSELECT 'Summe' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" \", $Jahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT SUM(interactions)/1000000 as lm_interactions FROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CASE $month_as_number\r\n            WHEN 19 THEN \"\"\r\n            ELSE \"$LastMonat_abkuerzung $YearFromLastMonth\"\r\n            END As Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE Monat INT64;\r\nSET Monat = $month_as_number;\r\n\r\nIF Monat = 19 THEN \r\n  EXECUTE IMMEDIATE \"SELECT '' \";\r\nELSE \r\n  EXECUTE IMMEDIATE \"\"\"\r\n    WITH past_value_in_mil AS (\r\n      SELECT SUM(interactions)/1000000 as past_sum_in_mil FROM Quintly_frozen.facebook_metrics\r\n      WHERE monat = $last_month AND jahr = $year_from_last_month AND LRA = \"$LRA_mapping\"\r\n    ),\r\n    current_value_in_mil AS (\r\n      SELECT SUM(interactions)/1000000 as current_sum_in_mil FROM Quintly_frozen.facebook_metrics\r\n      WHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n    )\r\n\r\n    SELECT (current_sum_in_mil / past_sum_in_mil - 1) * 100 AS diff_mil, \r\n    FROM past_value_in_mil, current_value_in_mil\r\n  \"\"\";\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" \", $LastJahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS (\r\n      SELECT SUM(interactions)/1000000 as past_sum_in_mil FROM Quintly_frozen.facebook_metrics\r\n      WHERE monat = $month_from_last_year AND jahr = $last_year AND LRA = \"$LRA_mapping\"\r\n    ),\r\n    current_value_in_mil AS (\r\n      SELECT SUM(interactions)/1000000 as current_sum_in_mil FROM Quintly_frozen.facebook_metrics\r\n      WHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n    )\r\n\r\n    SELECT (current_sum_in_mil / past_sum_in_mil - 1) * 100 AS diff_mil, \r\n    FROM past_value_in_mil, current_value_in_mil"
    }
   ]
  },
  {
   "title": "Entwicklung: 10 Sek. Videostarts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Summe Videostarts (10 Sek.) $LRA Profile in Mio.",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DATE(jahr,monat,1) as month, SUM(views_10s)/1000000 as videoViews10sMill FROM Quintly_frozen.facebook_metrics\r\nWHERE LRA = \"$LRA_mapping\" AND \r\nCASE $month_as_number\r\nWHEN 19 THEN jahr = $Jahr AND monat < 13\r\nELSE monat < 13 AND DATE(jahr,monat,1) BETWEEN DATE_SUB(DATE($Jahr,$month_as_number,1), INTERVAL 1 YEAR) AND DATE($Jahr,$month_as_number,1) END\r\nGROUP BY month\r\nORDER BY month ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 9, "y": 37 },
   "options": {
    "content": "### Anteil Videostarts (10 Sek.) Top 8 | ${Monat:text} ${Jahr}\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 37 }, "options": { "content": "### Videostarts in Mio.\n" } },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH top_8_profiles AS(\r\n  SELECT profile, views_10s as videoViews10s\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY videoViews10s DESC\r\nLIMIT 8\r\n), rest AS(\r\n  SELECT \"Rest\" as profile, SUM(views_10s) as videoViews10s\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nAND profile NOT IN (SELECT profile FROM top_8_profiles)\r\n)\r\nSELECT REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(profile,'-',''),' ',''),',',''),'ä','ae'),'Ä','Ae'),'ö','oe'),'Ö','Oe'),'ü','ue'),'Ü','Ue'),'.',''),'!',''),'&',''),\"'\",\"\"),'#',''),'🍀',''),'ß','ss') as profile,\r\nvideoViews10s FROM(\r\nSELECT profile, videoViews10s FROM top_8_profiles\r\nUNION ALL\r\nSELECT profile, videoViews10s FROM rest\r\nWHERE CASE \r\nWHEN profile = \"Rest\" THEN videoViews10s IS NOT NULL \r\nELSE TRUE END)\r\n\r\n\r\n\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 16, "y": 39 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Summe')), 'Summe')\r\nFROM(\r\nSELECT 'Summe' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Ø Pro Tag')), 'Ø Pro Tag')\r\nFROM(\r\nSELECT 'Ø Pro Tag' as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" \", $Jahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT SUM(views_10s)/1000000 as videoViews10sMill,  (SUM(views_10s)/1000000)/MAX(anzahltage) as videoViews10sMillPerDay FROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CASE $month_as_number\r\n            WHEN 19 THEN \"\"\r\n            ELSE \"$LastMonat_abkuerzung $YearFromLastMonth\"\r\n            END As Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS (\r\n  SELECT SUM(views_10s)/1000000 as past_sum_in_mil,  (SUM(views_10s)/1000000)/MAX(anzahltage) as past_sum_per_day FROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $last_month AND jahr = $year_from_last_month AND LRA = \"$LRA_mapping\"\r\n), current_value_in_mil AS(\r\n  SELECT SUM(views_10s)/1000000 as current_sum_in_mil,  (SUM(views_10s)/1000000)/MAX(anzahltage) as current_sum_per_day FROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\" AND monat != 19\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH(Gesamt)), Gesamt)\r\nFROM(\r\nSELECT CONCAT(\"$Monat_abkuerzung\", \" \", $LastJahr) as Gesamt\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value_in_mil AS (\r\n  SELECT SUM(views_10s)/1000000 as past_sum_in_mil,  (SUM(views_10s)/1000000)/MAX(anzahltage) as past_sum_per_day FROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_from_last_year AND jahr = $last_year AND LRA = \"$LRA_mapping\"\r\n), current_value_in_mil AS(\r\n  SELECT SUM(views_10s)/1000000 as current_sum_in_mil,  (SUM(views_10s)/1000000)/MAX(anzahltage) as current_sum_per_day FROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT (current_sum_in_mil/past_sum_in_mil - 1)*100 as diff_mil, (current_sum_per_day/past_sum_per_day - 1)*100 as diff_per_day FROM past_value_in_mil, current_value_in_mil"
    }
   ]
  },
  {
   "title": "Potenzielle Reichweite |  ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "Ø Potenzielle Reichweite pro Tag | $Monat $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT\r\nprofile, profileId, pot_reichweite_pro_tag as impressions_unique_PerDay\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(impressions_unique_PerDay,0) as impressions_unique_PerDay FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY impressions_unique_PerDay DESC"
    }
   ]
  },
  {
   "title": "Ø Potenzielle Reichweite pro Post | $Monat $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT\r\nprofile, profileId, pot_reichweite_pro_post as impressions_unique_PerDay\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(impressions_unique_PerDay,0) as impressions_unique_PerDay FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY impressions_unique_PerDay DESC"
    }
   ]
  },
  { "title": "Follower | ${Monat} ${Jahr}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Follower | Stichtag: $Stichtag",
   "type": "bargauge",
   "gridPos": { "h": 28, "w": 16, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT\r\nprofile, profileId, page_follows as followers\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(followers,0) as followers FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY followers DESC"
    }
   ]
  },
  {
   "title": "Veränderung zum ${Vormonat} in %",
   "type": "barchart",
   "gridPos": { "h": 28, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\nSELECT \r\nlm.Profil as profile,\r\nprofileId,\r\nlm.lm_follower,\r\n(lm_follower/llm_follower - 1)*100 as FollowerVeraenderung\r\nFROM\r\n(SELECT\r\nprofile as Profil, profileId, page_follows as lm_follower\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY lm_follower desc) as lm\r\nLEFT JOIN\r\n(SELECT\r\nprofile as Profil, page_follows as llm_follower\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE LRA = \"$LRA_mapping\" AND \r\nCASE $month_as_number\r\nWHEN 19 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nORDER BY llm_follower desc) as llm ON llm.Profil = lm.Profil)\r\n\r\nSELECT all_profiles.profile, IFNULL(FollowerVeraenderung,0) as FollowerVeraenderung FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY lm_follower DESC"
    }
   ]
  },
  {
   "title": "Videostarts |  ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 }
  },
  {
   "title": "Videostarts (10 Sek.)",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT profile, profileId, views_10s as videoViews10s \r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(videoViews10s,0) as videoViews10s FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY videoViews10s DESC"
    }
   ]
  },
  {
   "title": "Videostarts (3 Sek.)",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, views_3s as videoViews3s \r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(videoViews3s,0) as videoViews3s FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY videoViews3s DESC"
    }
   ]
  },
  {
   "title": "Wiedergabedauer gesamt in Stunden |  ${Monat} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 }
  },
  {
   "title": "Wiedergabedauer gesamt in Stunden",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, Sehvolumen \r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(Sehvolumen,0) as Sehvolumen FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY Sehvolumen DESC"
    }
   ]
  },
  {
   "title": "Interaktionen |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 }
  },
  {
   "title": "Interaktionen | $Monat $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 15, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, interactions as InteraktionenProPost \r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(InteraktionenProPost,0) as InteraktionenProPost FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY InteraktionenProPost DESC"
    }
   ]
  },
  {
   "title": "Anzahl Posts | $Monat $Jahr",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 9, "x": 15, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile, facebookID as profileId\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), all_data AS(\r\n  SELECT \r\nprofile, profileId, interactions as InteraktionenProPost, anzahlPosts \r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\n)\r\nSELECT all_profiles.profile, IFNULL(anzahlPosts,0) as anzahlPosts FROM all_profiles\r\nLEFT JOIN all_data\r\nUSING(profile,profileId)\r\nORDER BY InteraktionenProPost DESC"
    }
   ]
  },
  {
   "title": "Top Posts nach Interaktionen |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 175 },
   "options": {
    "content": "<p style=\"text-align: right\"><font size=\"2\">Legende: &nbsp;🖼️ = Bild &nbsp;&nbsp; 🎥 = Video &nbsp;&nbsp; 🔗 = Link &nbsp;&nbsp; 📕 = Album &nbsp;&nbsp; 📄 = Status </font><font size=\"6\"> </font>"
   }
  },
  {
   "title": "Top Posts nach Interaktionen |  ${Monat} ${Jahr}",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 178 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\nprofile as Profil,\r\ntime as PostDatum,\r\nmessage as Post,\r\nlink,\r\ntype as Typ,\r\ninteractions as Interaktionen,\r\npot_reichweite,\r\ntotal_video_10s_views\r\n\r\nFROM Quintly_frozen.top_posts_nach_interaktionen\r\n\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY Interaktionen DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Top One Post je Profil |  ${Month} ${Jahr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 197 },
   "options": {
    "content": "<p style=\"text-align: right\"><font size=\"2\">Legende: &nbsp;🖼️ = Bild &nbsp;&nbsp; 🎥 = Video &nbsp;&nbsp; 🔗 = Link &nbsp;&nbsp; 📕 = Album &nbsp;&nbsp; 📄 = Status </font><font size=\"6\"> </font>"
   }
  },
  {
   "title": "Top One Post je Profil |  ${Monat} ${Jahr}",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 200 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT DISTINCT\r\n  profile,\r\n  PostDatum,\r\n  Post,\r\n  link,\r\n  Typ,\r\n  Interaktionen,\r\n  pot_reichweite,\r\n  total_video_10s_views \r\nFROM Quintly_frozen.top_one_post_je_profil\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"\r\nORDER BY Interaktionen DESC\r\n"
    }
   ]
  },
  {
   "title": "Zusammenfassung aller Profile | $Monat $Jahr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 }
  },
  {
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 219 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH all_profiles AS(\r\n    SELECT profile\r\n  FROM Quintly_frozen.profiles\r\n  WHERE LRA = \"$LRA_mapping\" AND facebookID != 0 AND monat = $profile_Zeitraum AND jahr = $Jahr\r\n), current_values AS(\r\nSELECT profile, page_follows as current_followers, anzahlPosts as current_anzahlPosts, interactions as current_interactions, pot_reichweite_pro_tag as current_pot_reichweite_pro_tag, views_10s as current_views_10s, views_3s as current_views_3s,\r\npot_reichweite_pro_post as current_pot_reichweite_pro_post, sehVolumen as current_wiedergabendauer_in_std\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE monat = $month_as_number AND jahr = $Jahr AND LRA = \"$LRA_mapping\"),\r\npast_values AS(\r\nSELECT profile, page_follows as past_followers, anzahlPosts as past_anzahlPosts, interactions as past_interactions, pot_reichweite_pro_tag as past_pot_reichweite_pro_tag, views_10s as past_views_10s, views_3s as past_views_3s,\r\npot_reichweite_pro_post as past_pot_reichweite_pro_post, sehVolumen as past_wiedergabendauer_in_std\r\nFROM Quintly_frozen.facebook_metrics\r\nWHERE CASE $month_as_number\r\nWHEN 19 THEN monat = $month_from_last_year AND jahr = $last_year\r\nELSE monat = $last_month AND jahr = $year_from_last_month END\r\nAND LRA = \"$LRA_mapping\"\r\n), joined_data AS(\r\nSELECT * FROM all_profiles\r\nLEFT JOIN\r\ncurrent_values\r\nUSING(profile)\r\nLEFT JOIN \r\npast_values\r\nUSING(profile))\r\nSELECT profile as Profil,\r\nCASE current_followers\r\nWHEN 0 THEN NULL\r\nELSE current_followers END as followers,\r\nCASE current_followers - past_followers\r\nWHEN 0 THEN NULL \r\nELSE current_followers - past_followers END as FollowerVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_followers,past_followers)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_followers,past_followers)-1)*100 END as FollowerVeraenderung,\r\nCASE current_anzahlPosts\r\nWHEN 0 THEN NULL \r\nELSE current_anzahlPosts END as Anzahlposts,\r\nCASE current_interactions\r\nWHEN 0 THEN NULL \r\nELSE current_interactions END as Interaktionen,\r\nCASE current_interactions - past_interactions\r\nWHEN 0 THEN NULL \r\nELSE current_interactions - past_interactions END as InteraktionenVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_interactions,past_interactions)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_interactions,past_interactions)-1)*100 END as InteraktionenVeraenderung,\r\nCASE current_pot_reichweite_pro_tag\r\nWHEN 0 THEN NULL\r\nELSE current_pot_reichweite_pro_tag END as PotenzielleReichweite,\r\nCASE current_pot_reichweite_pro_tag - past_pot_reichweite_pro_tag\r\nWHEN 0 THEN NULL\r\nELSE current_pot_reichweite_pro_tag - past_pot_reichweite_pro_tag END as PotenzielleReichweiteVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_pot_reichweite_pro_tag,past_pot_reichweite_pro_tag)-1)*100\r\nWHEN 0 THEN NULL \r\nELSE (SAFE_DIVIDE(current_pot_reichweite_pro_tag,past_pot_reichweite_pro_tag)-1)*100 END as PotenzielleReichweiteVeraenderung,\r\nCASE current_pot_reichweite_pro_post \r\nWHEN 0 THEN NULL\r\nELSE current_pot_reichweite_pro_post END as PotenzielleReichweiteProPost,\r\nCASE current_pot_reichweite_pro_post - past_pot_reichweite_pro_post\r\nWHEN 0 THEN NULL\r\nELSE current_pot_reichweite_pro_post - past_pot_reichweite_pro_post END as PotenzielleReichweiteProPostVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_pot_reichweite_pro_post,past_pot_reichweite_pro_post)-1)*100\r\nWHEN 0 THEN NULL \r\nELSE (SAFE_DIVIDE(current_pot_reichweite_pro_post,past_pot_reichweite_pro_post)-1)*100 END as PotenzielleReichweiteProPostVeraenderung,\r\nCASE current_views_10s\r\nWHEN 0 THEN NULL\r\nELSE current_views_10s END as videoViews10s,\r\nCASE current_views_10s - past_views_10s\r\nWHEN 0 THEN NULL\r\nELSE current_views_10s - past_views_10s END as videoViews10sVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_views_10s,past_views_10s)-1)*100 \r\nWHEN 0 THEN NULL \r\nELSE (SAFE_DIVIDE(current_views_10s,past_views_10s)-1)*100 END as videoViews10sVeraenderung,\r\nCASE current_views_3s\r\nWHEN 0 THEN NULL \r\nELSE current_views_3s END as videoViews3s,\r\nCASE current_views_3s - past_views_3s\r\nWHEN 0 THEN NULL\r\nELSE current_views_3s - past_views_3s END as videoViews3sVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_views_3s,past_views_3s)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_views_3s,past_views_3s)-1)*100 END as videoViews3sVeraenderung,\r\nCASE current_wiedergabendauer_in_std\r\nWHEN 0 THEN NULL\r\nELSE current_wiedergabendauer_in_std END as sehVolumen,\r\nCASE current_wiedergabendauer_in_std - past_wiedergabendauer_in_std \r\nWHEN 0 THEN NULL\r\nELSE current_wiedergabendauer_in_std - past_wiedergabendauer_in_std END as sehVolumenVeraenderungAbsolut,\r\nCASE (SAFE_DIVIDE(current_wiedergabendauer_in_std,past_wiedergabendauer_in_std)-1)*100\r\nWHEN 0 THEN NULL\r\nELSE (SAFE_DIVIDE(current_wiedergabendauer_in_std,past_wiedergabendauer_in_std)-1)*100 END as sehVolumenVeraenderung,\r\nFROM joined_data\r\nORDER BY Profil DESC"
    }
   ]
  }
 ]
}