{
 "title": "Web & App Dashboard Kalender",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "LRA", "query": "NDR,MDR" },
   {
    "name": "Redaktionen",
    "query": {}
   },
   {
    "name": "Unterkapitel",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": {}
   },
   {
    "name": "app_name",
    "query": {}
   },
   {
    "name": "site_level2",
    "query": {}
   },
   {
    "name": "page_chapter1",
    "query": {}
   },
   {
    "name": "page_chapter2",
    "query": {}
   },
   {
    "name": "sendungsid",
    "query": {}
   },
   {
    "name": "av_condition",
    "query": {}
   },
   {
    "name": "app_name_long",
    "query": {}
   },
   {
    "name": "fromDay",
    "query": {}
   },
   {
    "name": "toDay",
    "query": {}
   },
   {
    "name": "av_page_chapter2",
    "query": {}
   },
   {
    "name": "webFilter",
    "query": {}
   },
   {
    "name": "avwebFilter",
    "query": {}
   },
   {
    "name": "listwebFilter",
    "query": {}
   },
   {
    "name": "list_page_chapter2",
    "query": {}
   },
   {
    "name": "appFilter",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "Uhrzeit",
    "query": {}
   },
   { "name": "filled_size_big", "query": "10" },
   {
    "name": "av_app_condition_video",
    "query": {}
   },
   {
    "name": "av_app_condition_audio",
    "query": {}
   },
   {
    "name": "av_pub_date",
    "query": {}
   },
   {
    "name": "av_content_id",
    "query": {}
   },
   {
    "name": "av_content",
    "query": {}
   },
   {
    "name": "av_on_demand_filter",
    "query": {}
   },
   {
    "name": "av_live_stream_filter",
    "query": {}
   },
   {
    "name": "HeuteDatum",
    "query": {}
   },
   {
    "name": "hinweis",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# 📊 Hinweis\n\n- Audio- und Video-Daten ohne Livestream-Nutzung, mit Ausnahme der Livestream-Tabelle."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 }, "options": { "content": " ${hinweis}" } },
  { "title": "Verlaufsdiagramme", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Visits | Web | Time Picker",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\n  SELECT \n  TIMESTAMP(date), \n  SUM(m_visits) as m_visits\n  FROM Piano.total_visits\n  WHERE $webFilter\n  AND $Zeitraum\n  GROUP BY date\n  ORDER by date ASC\n"
    }
   ]
  },
  {
   "title": "Wiedergaben | Web | Time Picker",
   "type": "barchart",
   "description": "Hinweis: Momentan keine Web-AV-Messung für die NDR Länder möglich.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT date as time, sum(COALESCE(m_av_playbacks,0)) as m_av_playbacks\nFROM  `ndr-code-bi-dashboard.Piano.av_joined_daily`\nWHERE $Zeitraum\nAND $avwebFilter\nGROUP BY date\nORDER BY date\n "
    }
   ]
  },
  {
   "title": "Visits | App | Time Picker",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT \n  TIMESTAMP(date), \n  SUM(m_visits) as m_visits\n  FROM Piano.total_visits\n  WHERE $appFilter\n  AND $Zeitraum\n  GROUP BY date\n  ORDER BY date asc"
    }
   ]
  },
  {
   "title": "Wiedergaben | App | Time Picker",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT date as time, SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as m_av_playbacks\nFROM  `ndr-code-bi-dashboard.Piano.av_joined_daily`\nWHERE $Zeitraum\nAND ${av_condition}\nAND ($av_app_condition_audio OR $av_app_condition_video)\n\nGROUP BY date\nORDER BY date\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 } },
  { "title": "KPI Boxes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Visits')), 'Visits')\r\nFROM(\r\nSELECT 'Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Pageviews / Visits')), 'Pageviews / Visits')\r\nFROM(\r\nSELECT 'Pageviews / Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Time spent / Visit in Sec.')), 'Time spent / Visit in Sec.')\r\nFROM(\r\nSELECT 'Time spent / Visit in Sec.' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio- & Videostarts')), 'Audio- & Videostarts')\r\nFROM(\r\nSELECT 'Audio- & Videostarts' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Web & App')), 'Web & App')\r\nFROM(\r\nSELECT 'Web & App' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND $Zeitraum),\r\na as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND $Zeitraum)\r\nSELECT  w.m_visits + a.m_visits as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($webFilter\r\n    AND $Zeitraum \r\n    ) \r\n),\r\na as (\r\n  SELECT m_visits, date, m_page_loads, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter\r\n  AND $Zeitraum\r\n)\r\nSELECT  CONCAT(REPEAT(\" \", $filled_size_big - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\")) FROM \r\n(\r\nSELECT ROUND(SUM(w.m_page_loads+a.m_page_loads)/SUM(w.m_visits + a.m_visits),1) as summe\r\nFROM w \r\nJOIN a ON w.id = a.id)\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM  `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $Zeitraum\r\n   AND $webFilter\r\n),\r\na as(\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits) as time_spent, SUM(m_visits)as visits, 2 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits`  \r\n   WHERE $Zeitraum \r\n   AND $appFilter\r\n)\r\nSELECT  CONCAT(REPLACE(CAST(ROUND((a.time_spent + w.time_spent)/(a.visits + w.visits),1) as STRING), '.', ','), ' Sek.') as Zeitraum\r\nFROM w \r\nJOIN a ON w.id = a.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as \r\n(\r\n  SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily`  \r\n  WHERE $Zeitraum AND $avwebFilter\r\n  AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n  \r\n),\r\napp as (\r\n  SELECT \r\n    SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily`  \r\n  WHERE $Zeitraum AND ${av_condition} \r\n  AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n  AND ($av_app_condition_audio OR $av_app_condition_video)\r\n\r\n )\r\nSELECT COALESCE(SUM(web.Zeitraum),0) + COALESCE(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Web')), 'Web')\r\nFROM(\r\nSELECT 'Web' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  SUM(COALESCE(m_visits,0)) as m_visits\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND $Zeitraum"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(COALESCE(m_visits,0)) as m_visits, 1 as id\r\n    FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n    WHERE $webFilter AND $Zeitraum),\r\na as (\r\n  SELECT  SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND $Zeitraum)\r\nSELECT  w.m_visits as Web, a.m_visits as App\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "  SELECT ROUND(SUM(m_page_loads)/SUM(m_visits),1) as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($webFilter\r\n    AND $Zeitraum \r\n    ) "
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT SUM(m_page_loads)/SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $webFilter\r\n    AND $Zeitraum\r\n),\r\na as (\r\n  SELECT SUM(m_page_loads)/SUM(m_visits) as m_visits, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter\r\n  AND $Zeitraum\r\n)\r\nSELECT  w.m_visits as Web, a.m_visits as App\r\nFROM w \r\nJOIN a ON w.id = a.id\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  SUM(m_time_spent_per_visits/1000 * m_visits)/SUM(m_visits) as id\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE $Zeitraum AND $webFilter "
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with w as (\r\n  SELECT  SUM(m_time_spent_per_visits/1000 * m_visits)/SUM(m_visits) as Zeitraum, 1 as id\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE $Zeitraum  AND $webFilter \r\n),\r\na as(\r\n   SELECT  SUM(m_time_spent_per_visits/1000 * m_visits)/SUM(m_visits) as Zeitraum, 1 as id\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE $Zeitraum  AND $appFilter \r\n)\r\nSELECT  w.Zeitraum as Web, a.Zeitraum as App\r\nFROM w \r\nJOIN a ON w.id = a.id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily`  \r\n  WHERE $Zeitraum AND $avwebFilter\r\n  AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as \r\n(\r\n  SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily`  \r\n  WHERE $Zeitraum  AND $avwebFilter\r\n  AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n),\r\napp as (\r\n  SELECT \r\n    SUM(COALESCE(m_av_playbacks,0)) as Zeitraum, 1 as id\r\n  FROM `ndr-code-bi-dashboard.Piano.av_joined_daily`  \r\n  WHERE $Zeitraum AND ${av_condition} \r\n  AND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n\r\n )\r\nSELECT SUM(web.Zeitraum) as Web, SUM(app.Zeitraum) as App\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('App')), 'App')\r\nFROM(\r\nSELECT 'App' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  SUM(m_visits) as m_visits\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE $appFilter AND $Zeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "  SELECT ROUND(SUM(m_page_loads)/SUM(m_visits),1) as id\r\n  FROM `ndr-code-bi-dashboard.Piano.total_visits` \r\n  WHERE \r\n    ($appFilter\r\n    AND $Zeitraum\r\n    ) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  SUM(m_time_spent_per_visits/1000 * m_visits)/SUM(m_visits) as id\r\nFROM `ndr-code-bi-dashboard.Piano.total_visits` \r\nWHERE $Zeitraum AND $appFilter "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum\r\nFROM `ndr-code-bi-dashboard.Piano.av_joined_daily`  \r\nWHERE $Zeitraum  AND ${av_condition}\r\nAND ($av_app_condition_audio OR $av_app_condition_video)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 38 },
   "options": {
    "content": "Hinweis: Momentan keine Web-AV-Messung für die NDR Länder möglich."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 } },
  { "title": "Top Artikel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Top Artikel",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT publishing_date, content_id_sophora, content_titel, url, IFNULL(SUM(m_visits),0) as m_visits, IFNULL(SUM(m_page_loads),0) as m_page_loads, uuid, page_chapter1 as Kapitel FROM(\r\n  SELECT   \r\n    FIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as publishing_date,\r\n    FIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_id_sophora,\r\n    FIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_titel, \r\n    FIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as url, \r\n    m_visits,\r\n    m_page_loads, \r\n    uuid,\r\n    page_chapter1\r\n  from `ndr-code-bi-dashboard.Piano.articles_joined_daily` \r\n  WHERE \r\n    $listwebFilter \r\n    AND $Zeitraum\r\n    AND objekt_typ NOT LIKE 'indexPage'\r\n    AND content_id_sophora NOT LIKE '%index%'\r\n    AND content_id_sophora NOT LIKE '%N/A%'\r\n    AND content_id_sophora NOT LIKE '%verteilseite%'\r\n    AND content_id_sophora NOT LIKE '%nachrichtenfeed%'\r\n    )\r\n    GROUP BY uuid, publishing_date, content_id_sophora, content_titel, url, page_chapter1\r\n),\r\napp as (\r\n  SELECT IFNULL(SUM(m_visits),0) as m_visits, publishing_date, content_id_sophora, content_titel, url, IFNULL(SUM(m_page_loads),0) as m_page_loads, uuid FROM (\r\n  SELECT \r\n    m_visits, \r\n    FIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as publishing_date,\r\n    FIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_id_sophora,\r\n    FIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_titel, \r\n    FIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as url, \r\n    m_page_loads, \r\n    uuid\r\n  from `ndr-code-bi-dashboard.Piano.articles_joined_daily` \r\n  WHERE CONTAINS_SUBSTR(site_level2, '$app_name')\r\n  AND $Zeitraum\r\n  AND content_id_sophora NOT LIKE '%index%'\r\n  AND content_id_sophora NOT LIKE '%N/A%'\r\n   AND (\r\n        CASE \r\n            WHEN \"$LRA\" = 'NDR' THEN\r\n                content_titel NOT LIKE '%Video Livestream%'\r\n            AND content_titel NOT LIKE '%Startteaser%'\r\n            AND content_titel NOT LIKE '%startteaser%'\r\n            AND content_titel NOT LIKE '%-Anmelden%'\r\n            AND content_titel NOT LIKE '%_Start'\r\n            AND content_titel != 'Anmelden'\r\n            AND content_titel != 'Jetzt läuft'\r\n        ELSE\r\n          TRUE\r\n        END))\r\n  GROUP BY uuid, publishing_date, content_id_sophora, content_titel, url\r\n  ),\r\nsum_raw as (\r\n  SELECT \r\n  IFNULL(web.publishing_date, app.publishing_date) as publishing_date,\r\n  IFNULL(web.content_titel, app.content_titel) as content_titel, \r\n  IFNULL(web.content_id_sophora,app.content_id_sophora) as content_id_sophora, \r\n  IFNULL(web.url, app.url) as url,\r\n  IFNULL(web.uuid, app.uuid) as uuid,\r\n  IFNULL(web.m_visits,0) as visits_web, \r\n  IFNULL(app.m_visits,0) as visits_app, \r\n  IFNULL(web.m_page_loads,0) as page_web, \r\n  IFNULL(app.m_page_loads,0) as page_app, \r\n  Kapitel\r\n  FROM web\r\n  FULL JOIN app \r\n  ON web.uuid = app.uuid\r\n)\r\nSELECT \r\n  IF(LENGTH(MAX(publishing_date)) > 4,FORMAT_DATETIME('%d.%m.%Y | %R Uhr', DATETIME(MAX(publishing_date))),MAX(publishing_date)) as Datum, \r\n  content_titel as Artikel, \r\n  content_id_sophora as Sophora, \r\n  MAX(url) as url, \r\n  visits_web + visits_app as Visits, \r\n  visits_web as visits_web, \r\n  visits_app as visits_app, \r\n  page_web + page_app as page_views, \r\n  page_web as page_web, \r\n  page_app as page_app, \r\n  Kapitel\r\nFROM sum_raw\r\nGROUP BY content_titel,  content_id_sophora, uuid, Visits, visits_web, visits_app, page_views, page_web, page_app, Kapitel\r\nORDER BY Visits DESC\r\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 } },
  { "title": "AV KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  { "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 59 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 4, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Video - Wiedergaben')), 'Video - Wiedergaben')\r\nFROM(\r\nSELECT 'Video - Wiedergaben' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio - Wiedergaben')), 'Audio - Wiedergaben')\r\nFROM(\r\nSELECT 'Audio - Wiedergaben' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Web & App')), 'Web & App')\r\nFROM(\r\nSELECT 'Web & App' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\nWHERE \r\n$avwebFilter And\r\n$Zeitraum\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE ${av_condition} \r\n  AND $Zeitraum \r\nAND $av_app_condition_video\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 9, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\nWHERE \r\n$avwebFilter And\r\n$Zeitraum\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE ${av_condition} \r\n  AND $Zeitraum\r\nAND $av_app_condition_video\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) AS Web, IFNULL(SUM(app.Zeitraum),0) as App\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\nWHERE \r\n$avwebFilter And\r\n$Zeitraum\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE ${av_condition} \r\n  AND $Zeitraum\r\nAND $av_app_condition_audio\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) + IFNULL(SUM(app.Zeitraum),0) as Zeitraum\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\n  1 as id\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\nWHERE \r\n$avwebFilter And\r\n$Zeitraum\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n), app as (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\n  1 as id\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE ${av_condition} \r\n  AND $Zeitraum \r\nAND $av_app_condition_audio\r\n)\r\nSELECT IFNULL(SUM(web.Zeitraum),0) AS Web, IFNULL(SUM(app.Zeitraum),0) as App\r\nFROM web\r\nJOIN app\r\nON web.id = app.id\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Web')), 'Web')\r\nFROM(\r\nSELECT 'Web' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\nWHERE \r\n$avwebFilter And\r\n$Zeitraum\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND bi_av_broadcasting_type NOT IN ('live', 'Live')\r\n--AND bi_av_broadcasting_type = \"ondemand\"\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as Zeitraum,\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily` \r\nWHERE \r\n$avwebFilter And\r\n$Zeitraum\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('App')), 'App')\r\nFROM(\r\nSELECT 'App' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE ${av_condition} \r\n  AND $Zeitraum \r\nAND $av_app_condition_video\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as Zeitraum,\r\nFROM  \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE ${av_condition} \r\n  AND $Zeitraum\r\nAND $av_app_condition_audio\r\n\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 76 },
   "options": {
    "content": "Hinweis: Momentan keine Web-AV-Messung für die NDR Länder möglich."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 78 } },
  { "title": "Top AV on Demand", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Top AV on Demand",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT bi_av_publication_date,\r\n  bi_av_content, \r\n  bi_av_content_id,\r\n  bi_av_url as url,\r\n  sum(m_av_playbacks) as wiedergabe,\r\n  CONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nSUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n   FROM(\r\n  SELECT \r\n    FIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date,\r\n    m_av_playbacks,\r\n     CAST(FIRST_VALUE(av_content_duration) OVER (PARTITION BY bi_av_content_id ORDER BY bi_av_publication_date DESC)/1000 AS INT) as av_content_duration,\r\n    bi_av_content_id,\r\n    m_av_average_playback_completion_rate,\r\n    bi_av_broadcasting_type,\r\n    FIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\n    FIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n    av_content_type\r\n  from\r\n    `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\n  WHERE\r\n    $avwebFilter\r\n    AND $Zeitraum\r\n    AND bi_av_content_id NOT LIKE '%index%'\r\n    AND bi_av_broadcasting_type = \"ondemand\"\r\n    )\r\n    WHERE m_av_playbacks > 0\r\n  GROUP By\r\n    bi_av_publication_date,bi_av_content,av_content_duration,av_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n),\r\napp as (\r\nSELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe, \r\nCONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nCASE \"$LRA\"\r\nWHEN \"NDR\" THEN NULL\r\nELSE 100*SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) END as wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE($av_pub_date) OVER (PARTITION BY bi_av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_publication_date,  \r\nCOALESCE(m_playbutton,m_av_playbacks) as m_av_playbacks, \r\nCASE  \r\n      WHEN av_content_duration is NULL THEN NULL\r\n      ELSE CAST((av_content_duration/1000) AS INT) END av_content_duration,\r\n--CAST((av_content_duration/1000) AS INT) as av_content_duration,  \r\nm_av_average_playback_completion_rate, \r\nCOALESCE(objekt_typ, av_content_type) as av_content_type, COALESCE(content_id_sophora, bi_av_content_id) as bi_av_content_id,  \r\nCOALESCE(objekt_typ ,bi_av_broadcasting_type) as bi_av_broadcasting_type ,  \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_url,  \r\n\r\n--device_type,\r\nFIRST_VALUE($av_content) OVER (PARTITION BY COALESCE(content_id_sophora,bi_av_content_id) ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_content  \r\nFROM \r\n`ndr-code-bi-dashboard.Piano.av_joined_daily`\r\nWHERE ${av_condition}\r\nAND COALESCE(content_id_sophora, bi_av_content_id) NOT LIKE '%index%'  \r\nAND COALESCE(objekt_typ, bi_av_broadcasting_type) IN $av_on_demand_filter  \r\nAND $Zeitraum)  \r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,av_content_duration,av_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n),\r\nsum_raw as (\r\n  SELECT\r\n    IFNULL(\r\n      web.bi_av_publication_date,\r\n      app.bi_av_publication_date\r\n    ) as Publiziert,\r\n    IFNULL(web.bi_av_content, app.bi_av_content) as Titel,\r\n    IFNULL(web.bi_av_content_id, app.bi_av_content_id) as bi_av_content_id,\r\n    IFNULL(web.av_content_duration, app.av_content_duration) as av_content_duration,\r\n    IFNULL(web.url, app.url) as url,\r\n    IFNULL(web.wiedergabe, 0) as playbacks_web,\r\n    IFNULL(web.wiedergabe, 0) + IFNULL(app.wiedergabe, 0) as playbacks,\r\n    IFNULL(app.wiedergabe, 0) as playbacks_app,\r\n    IFNULL(web.av_content_type, app.av_content_type) as av_content_type\r\n  FROM\r\n    web FULL\r\n    JOIN app ON web.bi_av_content_id = app.bi_av_content_id\r\n)\r\nSELECT\r\n  *\r\nFROM\r\nsum_raw\r\nORDER BY\r\n  playbacks DESC\r\nLIMIT\r\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 94 } },
  { "title": "Top AV Livestream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Top AV Livestream",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\n  SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date, \r\nm_av_playbacks,\r\nav_content_type, bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\nCAST(av_content_duration/1000 AS INT) as av_content_duration,\r\nFROM \r\n  `ndr-code-bi-dashboard.Piano.av_joined_daily`\r\nWHERE $avwebFilter\r\nAND bi_av_content_id NOT LIKE '%index%'\r\nAND bi_av_broadcasting_type = \"live\"\r\nAND $Zeitraum)\r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url, av_content_duration\r\n),\r\napp as (\r\n  SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE($av_pub_date) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_publication_date, \r\nCOALESCE(m_playbutton,m_av_playbacks) as m_av_playbacks,\r\nCOALESCE(content_typ, av_content_type) as av_content_type, $av_content_id as bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY $av_content ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_url, \r\nCAST(av_content_duration/1000 AS INT) as av_content_duration,\r\n\r\n--device_type,\r\nFIRST_VALUE($av_content) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_content, \r\nFROM \r\n`ndr-code-bi-dashboard.Piano.av_joined_daily`\r\nWHERE ${av_condition}\r\nAND $av_content_id NOT LIKE '%index%'\r\nAND COALESCE(objekt_typ, bi_av_broadcasting_type) IN $av_live_stream_filter\r\nAND $Zeitraum)\r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url, av_content_duration\r\n),\r\nsum_raw as (\r\n  SELECT\r\n    IFNULL(\r\n      web.bi_av_publication_date,\r\n      app.bi_av_publication_date\r\n    ) as bi_av_publication_date,\r\n    IFNULL(web.bi_av_content, app.bi_av_content) as content_titel,\r\n    --IFNULL(web.av_content_duration, app.av_content_duration) as av_content_duration,\r\n    IFNULL(web.bi_av_content_id, app.bi_av_content_id) as bi_av_content_id,\r\n    IFNULL(web.url, app.url) as url,\r\n    IFNULL(web.wiedergabe, 0) as playbacks_web,\r\n    IFNULL(app.wiedergabe, 0) as playbacks_app,\r\n    IFNULL(web.wiedergabe, 0) + IFNULL(app.wiedergabe, 0) as playbacks,\r\n    IFNULL(web.av_content_type, app.av_content_type) as av_content_type\r\n  FROM\r\n    web FULL\r\n    JOIN app ON web.bi_av_content_id = app.bi_av_content_id\r\n)\r\nSELECT\r\n  *\r\nFROM\r\nsum_raw\r\nORDER BY\r\n  playbacks DESC\r\nLIMIT\r\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110 } },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Distribution nach Gerätetyp",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 14, "x": 5, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "with web as (\r\nSELECT \r\n  SUM(m_visits) as visits, \r\n  device_type \r\nFROM\r\n  Piano.distro_joined_daily\r\nWHERE $webFilter \r\nAND $Zeitraum\r\nAND device_type NOT LIKE '%N/A%'\r\nAND CASE WHEN \r\n      site_level2 = \"mdr.de\" \r\n      THEN (distribution = \"web\" OR distribution =\"amp\")\r\n      ELSE 1=1 END \r\nGROUP BY device_type),\r\napp as (\r\nSELECT\r\ndevice_type,\r\nSUM(m_visits) as visits\r\nFROM\r\n  Piano.distro_joined_daily\r\nWHERE $appFilter\r\n  AND $Zeitraum\r\n  AND device_type NOT LIKE '%N/A%'\r\nGROUP BY device_type \r\n)\r\nSELECT IFNULL(web.visits,0) + IFNULL(app.visits,0) as visits, IFNULL(web.device_type,app.device_type) as device_type\r\nFROM web\r\nFULL JOIN app\r\nUSING(device_type)\r\n"
    }
   ]
  }
 ]
}