{
 "title": "Piano Web Kalender Copy",
 "description": "Datepicker V 02/2024",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "media_house",
    "query": {}
   },
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Redaktionen",
    "query": {}
   },
   {
    "name": "Unterkapitel",
    "query": {}
   },
   {
    "name": "Sendung",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "time_shift",
    "query": {}
   },
   {
    "name": "day_count",
    "query": {}
   },
   {
    "name": "month_count",
    "query": {}
   },
   {
    "name": "zeitraum",
    "query": {}
   },
   {
    "name": "hinweis",
    "query": {}
   },
   {
    "name": "toDay",
    "query": {}
   },
   {
    "name": "fromDay",
    "query": {}
   },
   {
    "name": "HeuteDatum",
    "query": {}
   },
   {
    "name": "distroRefTable",
    "query": {}
   },
   {
    "name": "sophora",
    "query": {}
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 }, "options": { "content": " ${hinweis}" } },
  {
   "title": "Visits | Time Picker",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\n  SELECT \n  TIMESTAMP(date), \n  SUM(m_visits) as m_visits\n  FROM Piano.total_visits\n  WHERE site_level2 = \"$LRA\" \n  AND page_chapter1 = \"$Redaktionen\" \n  AND page_chapter2 = \"$Unterkapitel\" \n  AND sendungs_id = \"$Sendung\" \n  AND $zeitraum\n  GROUP BY date\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "options": { "content": " " } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Visits')), 'Visits')\r\nFROM(\r\nSELECT 'Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Bounce Rate in %')), 'Bounce Rate in %')\r\nFROM(\r\nSELECT 'Bounce Rate in %' as Bounce\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Page Views / Visits')), 'Page Views / Visits')\r\nFROM(\r\nSELECT 'Page Views / Visits' as pi_visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Time spent/Visit in s')), 'Time spent/Visit in s')\r\nFROM(\r\nSELECT 'Time spent/Visit in s' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio- & Videostarts')), 'Audio- & Videostarts')\r\nFROM(\r\nSELECT 'Audio- & Videostarts' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_visits,0)) as summe\r\nFROM \r\n  Piano.total_visits\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND $zeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\nFROM \r\n  Piano.total_visits\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\n--AND ${ZeitraumNew:raw} \r\n  AND $zeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM \r\n  Piano.total_visits\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\n  AND $zeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\r\nFROM \r\n  Piano.total_visits\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\n  AND $zeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  Piano.av_joined_daily\r\nWHERE \r\nsite_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\n  AND $zeitraum"
    }
   ]
  },
  { "title": "Kapitel Visits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Kapitel Visits ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nWITH nachrichten AS (\r\n  SELECT \r\n  CASE page_chapter2 WHEN \"thueringen\" THEN \"Thüringen\" WHEN \"sachsen\" THEN \"Sachsen\" WHEN \"sachsen-anhalt\" THEN \"Sachsen-Anhalt\" WHEN \"deutschland\" THEN \"Deutschland\" WHEN \"welt\" THEN \"Welt\" ELSE page_chapter2 END as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM   `Piano.total_visits`\r\n  WHERE page_chapter1 = \"nachrichten\" AND page_chapter2 IN (\"sachsen\",\"sachsen-anhalt\",\"thueringen\",\"deutschland\",\"welt\", \"hamburg\", \"info\", \"mecklenburg-vorpommern\", \"niedersachsen\", \"schleswig-holstein\") AND site_level2 = \"$LRA\" AND sendungs_id = \"$Sendung\" AND $zeitraum\r\n  GROUP BY page_chapter2\r\n), ratgeber AS(\r\n  SELECT \r\n  \"Ratgeber\" as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM   `Piano.total_visits`\r\n  WHERE page_chapter1 = \"ratgeber\" AND site_level2 = \"$LRA\" AND page_chapter2 = \"Alle Kapitel 2\" AND sendungs_id = \"$Sendung\" AND $zeitraum\r\n  GROUP BY Chapter\r\n--), app_aktuell AS (\r\n--  SELECT\r\n--  \"App Aktuell\" as Chapter,\r\n--  SUM(COALESCE(m_visits,0)) as summe\r\n--  FROM Piano.total_visits\r\n--  WHERE page_chapter1 = \"nachrichten\" AND page_chapter2 IN (\"app_aktuell\",\"app-aktuell\") AND site_level2 = \"$LRA\" AND sendungs_id = \"$Sendung\" AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\n), ndr_kapitel as (\r\n  SELECT CASE page_chapter1 \r\n    WHEN \"nachrichten\" THEN \"Nachrichten\" \r\n    WHEN \"kultur\" THEN \"Kultur\" \r\n    WHEN \"sport\" THEN \"Sport\" \r\n    WHEN \"geschichte\" THEN \"Geschichte\"\r\n    WHEN \"ratgeber\" THEN \"Ratgeber\"\r\n    END as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM  `Piano.total_visits`\r\n  WHERE   site_level2 = \"$LRA\" AND page_chapter1 IN (\"nachrichten\",\"kultur\",\"sport\", \"geschichte\", \"ratgeber\") AND page_chapter2 = \"$Unterkapitel\" AND sendungs_id = \"$Sendung\" AND $zeitraum\r\n  GROUP BY Chapter ), mdr as(\r\n SELECT * FROM(\r\nSELECT\r\nChapter,\r\nsumme FROM nachrichten\r\n  WHERE Chapter IN (\"Thüringen\", \"Sachsen\" ,\"Sachsen-Anhalt\",\"Deutschland\", \"Welt\" ) \r\nUNION ALL\r\nSELECT\r\nChapter,\r\nsumme FROM ratgeber\r\n--UNION ALL \r\n--SELECT\r\n--Chapter,\r\n--summe FROM app_aktuell\r\n)), mdr_kapitel AS (\r\n  SELECT CASE \r\n    WHEN page_chapter1 = \"sport\" THEN \"Sport\" \r\n    WHEN page_chapter1 = \"kultur\" THEN \"Kultur\" \r\n    WHEN page_chapter1 = \"wissen\" THEN \"Wissen\" \r\n    ELSE page_chapter1\r\n    END as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM  `Piano.total_visits`\r\n  WHERE   site_level2 = \"$LRA\" AND page_chapter1 IN (\"sport\",\"wissen\",\"kultur\") AND page_chapter2 = \"$Unterkapitel\" AND sendungs_id = \"$Sendung\" AND $zeitraum \r\n  GROUP BY Chapter\r\n), mdr_not_nachrichten AS (\r\n  SELECT * FROM mdr_kapitel\r\n  UNION ALL\r\n  SELECT * FROM nachrichten\r\n  WHERE Chapter IN (\"Thüringen\", \"Sachsen\" ,\"Sachsen-Anhalt\",\"Deutschland\", \"Welt\" )\r\n)\r\nSELECT \r\n    Chapter, \r\n    summe \r\nFROM \r\n    (SELECT \r\n         'ndr_kapitel' as source_table, \r\n         Chapter, \r\n         summe \r\n     FROM ndr_kapitel\r\n     UNION ALL\r\n     SELECT \r\n         'mdr' as source_table, \r\n         Chapter, \r\n         summe \r\n      FROM mdr\r\n      UNION ALL\r\n     SELECT \r\n         'nachrichten' as source_table, \r\n         Chapter, \r\n         summe \r\n     FROM nachrichten\r\n     UNION ALL\r\n     SELECT\r\n     'mdr_not_nachrichten' as source_table,\r\n     Chapter,\r\n     summe\r\n     FROM mdr_not_nachrichten) as unified_table\r\nWHERE \r\n    source_table = CASE WHEN '$LRA' = 'ndr.de' AND \"$Redaktionen\" = \"nachrichten\" THEN 'nachrichten'\r\n                        WHEN '$LRA' = 'ndr.de' AND \"$Redaktionen\"!= \"nachrichten\" THEN 'ndr_kapitel'\r\n                        WHEN '$LRA' = 'mdr.de' AND \"$Redaktionen\" = \"nachrichten\" THEN 'mdr'\r\n                        WHEN '$LRA' = 'mdr.de' AND \"$Redaktionen\" != \"nachrichten\" THEN 'mdr_not_nachrichten'\r\n                    END\r\nORDER BY \r\n    summe DESC"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "options": { "content": " " } },
  { "title": "Top Artikel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Top 100 Web Artikel",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\npublishing_date, \r\ncontent_titel,\r\nsum(m_visits) as visits,\r\nsum(m_page_loads) as page_views,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_bounce_rate*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS bounce_rate,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_suchmaschinen_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_suchmaschinen_anteil_visits,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_homepage_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_homepage_anteil_visits,\r\nCASE \r\n  WHEN \"$Redaktionen\" = \"Alle Kapitel 1\"  THEN page_chapter1 \r\n  WHEN \"$Redaktionen\" = \"nachrichten\"  THEN page_chapter2 \r\nEND AS Kapitel,\r\ncontent_id_sophora, url\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as publishing_date, \r\nFIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_id_sophora, \r\npage_chapter2, page_chapter1,\r\nm_visits,\r\nm_page_loads,\r\nm_bounce_rate,\r\nm_suchmaschinen_anteil_visits,\r\nm_homepage_anteil_visits, \r\nFIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as url, \r\nFIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_titel, \r\nFROM \r\nPiano.articles_joined_daily\r\nWHERE site_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(page_chapter1_tags) \r\nAND \"$Unterkapitel\" IN UNNEST(page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND content_id_sophora NOT LIKE '%index%'\r\nAND content_id_sophora NOT LIKE '%N/A%'\r\nAND content_id_sophora NOT LIKE '%verteilseite%'\r\nAND content_id_sophora NOT LIKE '%nachrichtenfeed%'\r\nAND page_chapter1 NOT LIKE \"CONT\"\r\nAND objekt_typ NOT LIKE 'indexPage'\r\nAND $zeitraum) \r\nGROUP BY content_id_sophora, content_titel, publishing_date, page_chapter2, page_chapter1, url, publishing_date ORDER BY 4 DESC \r\n\r\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "options": { "content": " " } },
  { "title": "Top Audios & Videos ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), '')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaben')), 'Wiedergaben')\r\nFROM(\r\nSELECT 'Wiedergaben' as Wiedergaben\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaberate')), 'Wiedergaberate')\r\nFROM(\r\nSELECT 'Wiedergaberate' as Wiedergaberate\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Video')), 'Video')\r\nFROM(\r\nSELECT 'Video' as Video\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  Piano.av_joined_daily\r\nWHERE \r\nsite_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND $zeitraum\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ohne Live-Videos",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as summe\r\nFROM \r\n  Piano.av_joined_daily\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND (av_content_type = \"video\" OR av_content_type = \"Video\")\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'\r\nAND $zeitraum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), 'Audio')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  Piano.av_joined_daily\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND $zeitraum\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  --AVG(m_av_average_playback_completion_rate) as summe\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as summe\r\nFROM \r\n  Piano.av_joined_daily\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND (av_content_type = \"audio\" OR av_content_type = \"Audio\")AND $zeitraum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }, "options": { "content": " " } },
  {
   "title": "Top 100 Web Audios & Videos on Demand",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nCONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nROUND(AVG(m_av_average_playback_completion_rate),4) wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date, \r\nm_av_playbacks,\r\nCAST(av_content_duration/1000 AS INT) as av_content_duration,\r\nm_av_average_playback_completion_rate,\r\nav_content_type, bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\nFROM \r\nPiano.av_joined_daily\r\nWHERE site_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND bi_av_content_id NOT LIKE '%index%'\r\nAND bi_av_broadcasting_type = \"ondemand\"\r\nAND $zeitraum) GROUP BY bi_av_publication_date,bi_av_content,av_content_duration,av_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  {
   "title": "Top 100 Web Audios & Videos Livestreams",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\n--CONCAT(CONCAT(\r\n\r\n -- CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n-- \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\n--AVG(m_av_average_playback_completion_rate) wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date, \r\n\r\nm_av_playbacks,\r\n--CAST(av_content_duration/1000 AS INT) as av_content_duration,\r\n--m_av_average_playback_completion_rate,\r\nav_content_type, bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n--device_type,\r\nFIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\nFROM \r\nPiano.av_joined_daily\r\nWHERE site_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND bi_av_content_id NOT LIKE '%index%'\r\nAND bi_av_broadcasting_type = \"live\"\r\n  AND $zeitraum)\r\n GROUP BY bi_av_publication_date,bi_av_content,\r\n--av_content_duration,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }, "options": { "content": " " } },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Web | Top Verweiser Domains",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  src_referrer_site_domain \nFROM `ndr-code-bi-dashboard.Piano.distro_joined_daily` \nWHERE \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\n  AND $zeitraum\nAND src_referrer_site_domain NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY src_referrer_site_domain \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Web | Devices",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  device_type \nFROM `ndr-code-bi-dashboard.Piano.distro_joined_daily` \nWHERE \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\n  AND $zeitraum\nAND device_type NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY device_type \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Web | Traffic Quellen",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  src \nFROM `ndr-code-bi-dashboard.Piano.distro_joined_daily` \nWHERE  \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\n  AND $zeitraum\nAND src NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY src \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Web | Top Referrer (nach Artikeln)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--cached version\nSELECT \n  content_titel,\n  SUM(m_visits) as Visits,\n  referrer,\n  $sophora as content_id_sophora,\n  distribution as Distribution\nFROM\n(\n  SELECT\n  FIRST_VALUE(content_titel) OVER (PARTITION BY $sophora ORDER BY date DESC) as content_titel,\n  --content_titel,\n  m_visits, \n  referrer,\n  $sophora,\n  distribution,\n  date\n  FROM `$distroRefTable`\n  WHERE\n     site_level2 = \"${LRA}\"\n     AND CASE \"${Redaktionen:text}\"\n     WHEN \"Alle Kapitel 1\" THEN TRUE \n     ELSE LOWER(page_chapter1) = LOWER(\"$Redaktionen\") END\n     AND CASE \"${Unterkapitel:text}\"\n     WHEN \"Alle Kapitel 2\" THEN TRUE\n     ELSE LOWER(page_chapter2) = LOWER(\"$Unterkapitel\") END\n    AND $zeitraum\n    AND referrer NOT LIKE \"%N/A%\"\n)\nGROUP BY \nDistribution, \nreferrer,\ncontent_titel,\ncontent_id_sophora\nORDER BY Visits DESC\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 }, "options": { "content": " " } }
 ]
}