{
 "title": "Last Month Time Range - Piano Web Desktop",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "media_house",
    "query": {}
   },
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Redaktionen",
    "query": {}
   },
   {
    "name": "Unterkapitel",
    "query": {}
   },
   {
    "name": "Sendung",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "time_shift",
    "query": {}
   },
   {
    "name": "day_count",
    "query": {}
   },
   {
    "name": "month_count",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Visits | Time Picker",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\n  SELECT \n  TIMESTAMP(date), \n  SUM(m_visits) as m_visits\n  FROM Piano.total_visits\n  WHERE site_level2 = \"$LRA\" \n  AND page_chapter1 = \"$Redaktionen\" \n  AND page_chapter2 = \"$Unterkapitel\" \n  AND sendungs_id = \"$Sendung\" \n  AND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\n  GROUP BY date\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "options": { "content": " " } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Visits')), 'Visits')\r\nFROM(\r\nSELECT 'Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Bounce Rate in %')), 'Bounce Rate in %')\r\nFROM(\r\nSELECT 'Bounce Rate in %' as Bounce\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Page Views / Visits')), 'Page Views / Visits')\r\nFROM(\r\nSELECT 'Page Views / Visits' as pi_visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Time spent/Visit in s')), 'Time spent/Visit in s')\r\nFROM(\r\nSELECT 'Time spent/Visit in s' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio- & Videostarts')), 'Audio- & Videostarts')\r\nFROM(\r\nSELECT 'Audio- & Videostarts' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_visits,0)) as summe\r\nFROM \r\n  Piano.total_visits\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_bounce_rate*m_visits,0))/SUM(COALESCE(m_visits,0))*100 as summe,\r\nFROM \r\n  Piano.total_visits\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\n--AND ${ZeitraumNew:raw} \r\nAND date BETWEEN DATE('${__from:date:iso}') AND DATE('${__to:date:iso}')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM \r\n  Piano.total_visits\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date BETWEEN DATE('${__from:date:iso}') AND DATE('${__to:date:iso}')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\r\nFROM \r\n  Piano.total_visits\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND page_chapter1 = \"$Redaktionen\"\r\nAND page_chapter2 = \"$Unterkapitel\"\r\nAND sendungs_id = \"$Sendung\"\r\nAND date BETWEEN DATE('${__from:date:iso}') AND DATE('${__to:date:iso}')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  Piano.av\r\nWHERE \r\nsite_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\r\n-- and av_content_type = \"video\""
    }
   ]
  },
  { "title": "Kapitel Visits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Kapitel Visits ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "\r\nWITH nachrichten AS (\r\n  SELECT \r\n  CASE page_chapter2 WHEN \"thueringen\" THEN \"Thüringen\" WHEN \"sachsen\" THEN \"Sachsen\" WHEN \"sachsen-anhalt\" THEN \"Sachsen-Anhalt\" WHEN \"deutschland\" THEN \"Deutschland\" WHEN \"welt\" THEN \"Welt\" END as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM Piano.total_visits\r\n  WHERE page_chapter1 = \"nachrichten\" AND page_chapter2 IN (\"sachsen\",\"sachsen-anhalt\",\"thueringen\",\"deutschland\",\"welt\") AND site_level2 = \"$LRA\" AND sendungs_id = \"$Sendung\" AND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\r\n  GROUP BY Chapter\r\n), ratgeber AS(\r\n  SELECT \r\n  \"Ratgeber\" as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM Piano.total_visits\r\n  WHERE page_chapter1 = \"ratgeber\" AND site_level2 = \"$LRA\" AND page_chapter2 = \"$Unterkapitel\" AND sendungs_id = \"$Sendung\" AND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\r\n  GROUP BY Chapter\r\n--), app_aktuell AS (\r\n--  SELECT\r\n--  \"App Aktuell\" as Chapter,\r\n--  SUM(COALESCE(m_visits,0)) as summe\r\n--  FROM Piano.total_visits\r\n--  WHERE page_chapter1 = \"nachrichten\" AND page_chapter2 IN (\"app_aktuell\",\"app-aktuell\") AND site_level2 = \"$LRA\" AND sendungs_id = \"$Sendung\" AND $Zeitraum\r\n), ndr_kapitel as (\r\n  SELECT CASE page_chapter1 WHEN \"nachrichten\" THEN \"Nachrichten\" WHEN \"kultur\" THEN \"Kultur\" WHEN \"sport\" THEN \"Sport\" WHEN \"geschichte\" THEN \"Geschichte\" WHEN \"ratgeber\" THEN \"Ratgeber\" END as Chapter,\r\n  SUM(COALESCE(m_visits,0)) as summe\r\n  FROM Piano.total_visits\r\n  WHERE   site_level2 = \"$LRA\" AND page_chapter1 IN (\"geschichte\",\"kultur\",\"nachrichten\",\"ratgeber\",\"sport\") AND page_chapter2 = \"$Unterkapitel\" AND sendungs_id = \"$Sendung\" AND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\r\n  GROUP BY Chapter ), mdr as(\r\n SELECT * FROM(\r\nSELECT\r\nChapter,\r\nsumme FROM nachrichten\r\nUNION ALL\r\nSELECT\r\nChapter,\r\nsumme FROM ratgeber\r\n--UNION ALL \r\n--SELECT\r\n--Chapter,\r\n--summe FROM app_aktuell\r\n))\r\nSELECT DISTINCT \r\nCASE WHEN \"$LRA\" = \"ndr.de\" THEN ndr_kapitel.Chapter\r\nWHEN \"$LRA\" = \"mdr.de\" THEN mdr.Chapter END as Chapter,\r\nCASE WHEN \"$LRA\" = \"ndr.de\" THEN ndr_kapitel.summe\r\nWHEN \"$LRA\" = \"mdr.de\" THEN mdr.summe END as summe \r\nFROM mdr,ndr_kapitel\r\nORDER BY summe desc"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "options": { "content": " " } },
  { "title": "Top Artikel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Top 100 Web Artikel",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\npublishing_date, \r\ncontent_titel,\r\nsum(m_visits) as visits,\r\nsum(m_page_loads) as page_views,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_bounce_rate*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS bounce_rate,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_suchmaschinen_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_suchmaschinen_anteil_visits,\r\nCASE WHEN SUM(IFNULL(m_visits,0))>0 THEN SUM(m_homepage_anteil_visits*m_visits)/SUM(IFNULL(m_visits,0)) ELSE -1 END AS m_homepage_anteil_visits,\r\nCASE \r\n  WHEN \"$Redaktionen\" = \"Alle Kapitel 1\"  THEN page_chapter1 \r\n  WHEN \"$Redaktionen\" = \"nachrichten\"  THEN page_chapter2 \r\nEND AS Kapitel,\r\ncontent_id_sophora, url\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(publishing_date) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as publishing_date, \r\nFIRST_VALUE(content_id_sophora) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_id_sophora, \r\npage_chapter2, page_chapter1,\r\nm_visits,\r\nm_page_loads,\r\nm_bounce_rate,\r\nm_suchmaschinen_anteil_visits,\r\nm_homepage_anteil_visits, \r\nFIRST_VALUE(url) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as url, \r\nFIRST_VALUE(content_titel) OVER (PARTITION BY uuid ORDER BY publishing_date DESC) as content_titel, \r\nFROM \r\nPiano.articles_joined\r\nWHERE site_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(page_chapter1_tags) \r\nAND \"$Unterkapitel\" IN UNNEST(page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND content_id_sophora NOT LIKE '%index%'\r\nAND content_id_sophora NOT LIKE '%N/A%'\r\nAND content_id_sophora NOT LIKE '%verteilseite%'\r\nAND content_id_sophora NOT LIKE '%nachrichtenfeed%'\r\nAND page_chapter1 NOT LIKE \"CONT\"\r\nAND objekt_typ NOT LIKE 'indexPage'\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')) \r\nGROUP BY content_id_sophora, content_titel, publishing_date, page_chapter2, page_chapter1, url, publishing_date ORDER BY 4 DESC \r\n\r\nLIMIT 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "options": { "content": " " } },
  { "title": "Top Audios & Videos ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), '')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaben')), 'Wiedergaben')\r\nFROM(\r\nSELECT 'Wiedergaben' as Wiedergaben\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaberate')), 'Wiedergaberate')\r\nFROM(\r\nSELECT 'Wiedergaberate' as Wiedergaberate\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Video')), 'Video')\r\nFROM(\r\nSELECT 'Video' as Video\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- SELECT \r\n--   SUM(COALESCE(m_av_playbacks,0)) as summe\r\n-- FROM \r\n--   Piano.av\r\n-- WHERE \r\n-- site_level2 = \"$LRA\" AND\r\n-- \"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n-- \"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\n-- AND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\n-- AND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\r\n-- AND av_content_type = \"Video\" or av_content_type = \"video\"  \r\nSELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  Piano.av\r\nWHERE \r\nsite_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\r\nAND av_content_type = \"video\"\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ohne Live-Videos",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as summe\r\nFROM \r\n  Piano.av\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND av_content_type = \"video\"\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), 'Audio')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_av_playbacks,0)) as summe\r\nFROM \r\n  Piano.av\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\r\n-- AND av_content_type = \"Audio\" or \r\nAND av_content_type = \"audio\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  --AVG(m_av_average_playback_completion_rate) as summe\r\n  SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) as summe\r\nFROM \r\n  Piano.av\r\nWHERE \r\nsite_level2 = \"$LRA\"\r\nAND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND av_content_type = \"audio\"\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')"
    }
   ]
  },
  {
   "title": "Top 100 Web Audios & Videos on Demand",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nCONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nROUND(AVG(m_av_average_playback_completion_rate),4) wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date, \r\nm_av_playbacks,\r\nCAST(av_content_duration/1000 AS INT) as av_content_duration,\r\nm_av_average_playback_completion_rate,\r\nav_content_type, bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\nFROM \r\nPiano.av\r\nWHERE site_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND bi_av_content_id NOT LIKE '%index%'\r\nAND bi_av_broadcasting_type = \"ondemand\"\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')) GROUP BY bi_av_publication_date,bi_av_content,av_content_duration,av_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  {
   "title": "Top 100 Web Audios & Videos Livestreams",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\n--CONCAT(CONCAT(\r\n\r\n -- CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n-- \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\n--AVG(m_av_average_playback_completion_rate) wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE(bi_av_publication_date) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_publication_date, \r\n\r\nm_av_playbacks,\r\n--CAST(av_content_duration/1000 AS INT) as av_content_duration,\r\n--m_av_average_playback_completion_rate,\r\nav_content_type, bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_url, \r\n--device_type,\r\nFIRST_VALUE(bi_av_content) OVER (PARTITION BY bi_av_content_id ORDER BY m_av_playbacks DESC) as bi_av_content, \r\nFROM \r\nPiano.av\r\nWHERE site_level2 = \"$LRA\" AND\r\n\"$Redaktionen\" IN UNNEST(bi_av_page_chapter1_tags) AND\r\n\"$Unterkapitel\" IN UNNEST(bi_av_page_chapter2_tags)\r\nAND \"$Sendung\" IN UNNEST(sendungs_id_tags)\r\nAND bi_av_content_id NOT LIKE '%index%'\r\nAND bi_av_broadcasting_type = \"live\"\r\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}'))\r\n GROUP BY bi_av_publication_date,bi_av_content,\r\n--av_content_duration,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }, "options": { "content": " " } },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Web | Top Verweiser Domains",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  src_referrer_site_domain \nFROM `ndr-code-bi-dashboard.Piano.distro` \nWHERE \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\nAND src_referrer_site_domain NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY src_referrer_site_domain \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Web | Devices",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  device_type \nFROM `ndr-code-bi-dashboard.Piano.distro` \nWHERE \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\nAND device_type NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY device_type \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Web | Traffic Quellen",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \n  SUM(m_visits), \n  src \nFROM `ndr-code-bi-dashboard.Piano.distro` \nWHERE  \nsite_level2 = \"$LRA\"\nAND page_chapter1 = \"$Redaktionen\"\nAND page_chapter2 = \"$Unterkapitel\"\nAND sendungs_id = \"$Sendung\"\nAND date BETWEEN DATE('${__from:date}') AND DATE('${__to:date}')\nAND src NOT LIKE '%N/A%'\nAND CASE WHEN \n      site_level2 = \"mdr.de\" \n      THEN (distribution = \"web\" OR distribution =\"amp\")\n      ELSE 1=1 END \nGROUP BY src \nORDER BY 1 DESC\nLIMIT 15"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 }, "options": { "content": " " } },
  { "title": "Google Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Google Trends | Echtzeit | Schlagzeilen",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 92 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | gestern",
   "type": "table",
   "gridPos": { "h": 21, "w": 5, "x": 19, "y": 92 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  *\nFROM\n  `ndr-code-bi-dashboard.GoogleTrends.search_trends_daily`\n\n--timestamp = DATE_SUB(CURRENT_DATE(), INTERVAL 0 DAY) \nWHERE CAST(timestamp as date) = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) \n--DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY),\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Schlagzeilen",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 100 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Business",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 108 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Sport",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 116 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Unterhaltung",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 124 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trend | Echtzeit | Wissen & Technik",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 132 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Gesundheit",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 140 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  }
 ]
}