{
 "title": "Quotenreport Copy Silke",
 "time": { "from": "2023-11-30T10:08:12.740Z", "to": "2023-12-02T10:08:12.740Z" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": "ARD : 0,NDR : 1,Senderreports (NDR FS) : 2"
   },
   {
    "name": "LastDayOfMonth",
    "query": {}
   },
   {
    "name": "LastJahr",
    "query": {}
   },
   {
    "name": "LastLastJahr",
    "query": {}
   },
   {
    "name": "Sendung",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "Jahr",
    "query": {}
   },
   {
    "name": "Monat",
    "query": "Januar : 1,Februar : 2,März : 3,April : 4,Mai : 5,Juni : 6,Juli : 7,August : 8,September : 9,Oktober : 10,November : 11,Dezember : 12"
   },
   {
    "name": "SinusOrder",
    "query": "CASE Zielgruppe\n    WHEN \"Konservativ-Gehobene (KOG)\" THEN 1\n    WHEN \"Postmaterielle (PMA)\" THEN 2\n    WHEN \"Performer (PER)\" THEN 3\n    WHEN \"Expeditive (EPE)\" THEN 4\n    WHEN \"Neo-Ökologische (NÖK)\" THEN 5\n    WHEN \"Adaptiv-Pragmatische (ADA)\" THEN 6\n    WHEN \"Konsum-Hedonisten (HED)\" THEN 7\n    WHEN \"Prekäre (PRE)\" THEN 8\n    WHEN \"Nostalgisch-Bürgerliche (NOB)\" THEN 9\n    WHEN \"Traditionelle (TRA)\" THEN 10\n  END"
   }
  ]
 },
 "panels": [
  { "type": "stat", "gridPos": { "h": 2, "w": 4, "x": 11, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Debugging Panel ",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "options": { "content": "# Dataset:  ${dataset}\n" },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"$dataset\""
    }
   ]
  },
  { "title": "Jahresdaten | ${LRA:text}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 4 },
   "options": {
    "content": "</br><center><font size=\"5\" style=\"font-weight:bold;\">Anzahl Sendungen</font></center>"
   }
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Quotenreport_Sample",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "--SELECT Anzahl_Elemente\r\n--FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\nSELECT COUNT(Datum)\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`\r\nWHERE EXTRACT(YEAR from CAST(LEFT(Datum, 10) as DATE FORMAT \"DD.MM.YYYY\")) = $Jahr\r\n--AND EXTRACT(MONTH from CAST(LEFT(Datum, 10) as DATE FORMAT \"DD.MM.YYYY\")) = $Monat"
    }
   ]
  },
  {
   "title": "$LastJahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(Datum)\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`\r\nWHERE EXTRACT(YEAR from CAST(LEFT(Datum, 10) as DATE FORMAT \"DD.MM.YYYY\")) = $LastJahr\r\n--AND EXTRACT(MONTH from CAST(LEFT(Datum, 10) as DATE FORMAT \"DD.MM.YYYY\")) = $Monat"
    }
   ]
  },
  {
   "title": "$LastLastJahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT COUNT(Datum)\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`\r\nWHERE EXTRACT(YEAR from CAST(LEFT(Datum, 10) as DATE FORMAT \"DD.MM.YYYY\")) =  $LastLastJahr\r\n--AND EXTRACT(MONTH from CAST(LEFT(Datum, 10) as DATE FORMAT \"DD.MM.YYYY\")) = $Monat"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 8 },
   "options": {
    "content": "\n<center><font size=\"5\" style=\"font-weight:bold;\">Sehbeteiligung in Mio.</font></center>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 8 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Marktanteil in %</font></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 8 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Seher in Mio.</font></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 8 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Verweildauer</font></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 8 },
   "options": {
    "content": "<center><font size=\"5\" style=\"font-weight:bold;\">Durchschnittsalter</font></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 10 },
   "options": {
    "content": "<br/><br/>\n<font size=\"6\" color=\"#2671c6\" style=\"font-weight:bold;\">BRD</font>\n<br/>\n<font size=\"6\" color=\"#2671c6\" style=\"font-weight:bold;\"> Gesamt</font>"
   }
  },
  {
   "title": "$Jahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN (\r\n  --SELECT \"\" as Sehbeteiligung\r\n  SELECT \r\n      Sehbeteiligung\r\n    FROM (SELECT  2024 as Jahr, avg(Sehbeteiligung) as Sehbeteiligung\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\n    WHERE Zielgruppe = \"BRD gesamt\"\r\n    GROUP BY Jahr)\r\n    WHERE Jahr = $Jahr\r\n);\r\nELSE (\r\n      SELECT \r\n      Sehbeteiligung\r\n    FROM (SELECT  2024 as Jahr, avg(Sehbeteiligung) as Sehbeteiligung\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n    GROUP BY Jahr)\r\n    WHERE Jahr = $Jahr\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN (\r\n  SELECT Marktanteil\r\n  FROM (SELECT  2024 as Jahr, avg(Marktanteil) as Marktanteil,\r\n  FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n  WHERE Zielgruppe = \"BRD gesamt\"\r\n  GROUP BY Jahr)\r\n  WHERE Jahr = $Jahr \r\n);\r\nELSE (\r\n  SELECT Marktanteil\r\n  FROM (SELECT  2024 as Jahr, avg(Marktanteil) as Marktanteil,\r\n  FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n  GROUP BY Jahr)\r\n  WHERE Jahr = $Jahr\r\n);\r\nEND IF"
    }
   ]
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\nWHERE Zielgruppe = \"BRD gesamt\""
    }
   ]
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT (EXTRACT(HOUR from Verweildauer)*3600)+(EXTRACT(MINUTE from Verweildauer)*60)+(EXTRACT(SECOND from Verweildauer)) as Verweildauer_in_Sec\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Verweildauer` \r\n--WHERE Zielgruppe = \"BRD gesamt\"\r\n"
    }
   ]
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Durchschnittsalter\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\nWHERE Zielgruppe = \"BRD gesamt\""
    }
   ]
  },
  {
   "title": "$LastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN (\r\n  SELECT \"\" as Sehbeteiligung\r\n);\r\nELSE (\r\n      SELECT \r\n      Sehbeteiligung\r\n    FROM (SELECT  2023 as Jahr, avg(Sehbeteiligung) as Sehbeteiligung\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n    GROUP BY Jahr)\r\n    WHERE Jahr = $LastJahr\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$LastLastJahr:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN (\r\n  SELECT \"\" as Sehbeteiligung\r\n);\r\nELSE (\r\n      SELECT \r\n      Sehbeteiligung\r\n    FROM (SELECT  2022 as Jahr, avg(Sehbeteiligung) as Sehbeteiligung\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n    GROUP BY Jahr)\r\n    WHERE Jahr = $LastLastJahr\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$LastJahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN (\r\n  SELECT Marktanteil\r\n  FROM (SELECT  2023 as Jahr, avg(Marktanteil) as Marktanteil,\r\n  FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n  WHERE Zielgruppe = \"BRD gesamt\"\r\n  GROUP BY Jahr)\r\n  WHERE Jahr = $LastJahr \r\n);\r\nELSE (\r\n  SELECT Marktanteil\r\n  FROM (SELECT  2023 as Jahr, avg(Marktanteil) as Marktanteil,\r\n  FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n  GROUP BY Jahr)\r\n  WHERE Jahr = $LastJahr\r\n);\r\nENd IF"
    }
   ]
  },
  {
   "title": "$LastLastJahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN (\r\n  SELECT Marktanteil\r\n  FROM (SELECT  2022 as Jahr, avg(Marktanteil) as Marktanteil,\r\n  FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n  WHERE Zielgruppe = \"BRD gesamt\"\r\n  GROUP BY Jahr)\r\n  WHERE Jahr = $LastLastJahr \r\n);\r\nELSE (\r\n  SELECT Marktanteil\r\n  FROM (SELECT  2022 as Jahr, avg(Marktanteil) as Marktanteil,\r\n  FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n  GROUP BY Jahr)\r\n  WHERE Jahr = $LastLastJahr\r\n);\r\nENd IF"
    }
   ]
  },
  {
   "title": "$LastJahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\nWHERE Zielgruppe = \"BRD gesamt\""
    }
   ]
  },
  {
   "title": "$LastLastJahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\nWHERE Zielgruppe = \"BRD gesamt\""
    }
   ]
  },
  { "title": "$LastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 14, "y": 13 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "$LastLastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 16, "y": 13 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "$LastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 18, "y": 13 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "$LastLastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 13 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 17 },
   "options": {
    "content": "<br/><br/>\n<font size=\"6\" color=\"#2671c6\" style=\"font-weight:bold;\">NDR</font>\n<br/>\n<font size=\"6\" color=\"#2671c6\" style=\"font-weight:bold;\"> Gebiet</font>"
   }
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN (\r\n  --SELECT \"\" as Sehbeteiligung\r\n  SELECT \r\n      Sehbeteiligung\r\n    FROM (SELECT  2024 as Jahr, avg(Sehbeteiligung) as Sehbeteiligung\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\n    WHERE Zielgruppe = \"NDR Gebiet\"\r\n    GROUP BY Jahr)\r\n    WHERE Jahr = $Jahr\r\n);\r\nELSE (\r\n      SELECT \r\n      Sehbeteiligung\r\n    FROM (SELECT  2024 as Jahr, avg(Sehbeteiligung) as Sehbeteiligung\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n    GROUP BY Jahr)\r\n    WHERE Jahr = $Jahr\r\n);\r\nEND IF;\r\n"
    }
   ]
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN (\r\n  SELECT Marktanteil\r\n  FROM (SELECT  2024 as Jahr, avg(Marktanteil) as Marktanteil,\r\n  FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n  WHERE Zielgruppe = \"NDR Gebiet\"\r\n  GROUP BY Jahr)\r\n  WHERE Jahr = $Jahr \r\n);\r\nELSE (\r\n  SELECT Marktanteil\r\n  FROM (SELECT  2024 as Jahr, avg(Marktanteil) as Marktanteil,\r\n  FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Monatswerte` \r\n  GROUP BY Jahr)\r\n  WHERE Jahr = $Jahr\r\n);\r\nENd IF"
    }
   ]
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Seher\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\nWHERE Zielgruppe = \"NDR Gebiet\""
    }
   ]
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT (EXTRACT(HOUR from Verweildauer)*3600)+(EXTRACT(MINUTE from Verweildauer)*60)+(EXTRACT(SECOND from Verweildauer)) as Verweildauer_in_Sec\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Verweildauer` "
    }
   ]
  },
  {
   "title": "$Jahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Durchschnittsalter\r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts` \r\nWHERE Zielgruppe = \"NDR Gebiet\""
    }
   ]
  },
  { "title": "$LastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "$LastLastJahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  { "title": "$LastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 6, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "$LastLastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 8, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "$LastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 10, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "$LastLastJahr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  { "title": "$LastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 14, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "$LastLastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 16, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "$LastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 18, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "$LastLastJahr", "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 20 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Sinusmilieus / DMT | ${LRA:text}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Sinusmilieus / DMT | ${LRA:text} | $Sendung",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 20, "x": 2, "y": 26 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT Zielgruppe, Marktanteil, (Sehbeteiligung*1000000) as Sehbeteiligung\r\n FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts`\r\n WHERE Zielgruppe IN (\r\n    \"Konservativ-Gehobene (KOG)\",\r\n    \"Postmaterielle (PMA)\",\r\n    \"Performer (PER)\",\r\n    \"Expeditive (EPE)\",\r\n    \"Neo-Ökologische (NÖK)\",\r\n    \"Adaptiv-Pragmatische (ADA)\", \r\n    \"Konsum-Hedonisten (HED)\",\r\n    \"Prekäre (PRE)\", \r\n    \"Nostalgisch-Bürgerliche (NOB)\",\r\n    \"Traditionelle (TRA)\"\r\n  )\r\n  ---ORDER BY Zielgruppe ASC\r\n  ORDER BY $SinusOrder"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Sinusmilieus / DMT | ${LRA:text} | $Sendung",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 20, "x": 2, "y": 39 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT Zielgruppe, Seher*1000000 as Seher\r\n FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts`\r\n WHERE Zielgruppe IN (\r\n    \"Konservativ-Gehobene (KOG)\",\r\n    \"Postmaterielle (PMA)\",\r\n    \"Performer (PER)\",\r\n    \"Expeditive (EPE)\",\r\n    \"Neo-Ökologische (NÖK)\",\r\n    \"Adaptiv-Pragmatische (ADA)\", \r\n    \"Konsum-Hedonisten (HED)\",\r\n    \"Prekäre (PRE)\", \r\n    \"Nostalgisch-Bürgerliche (NOB)\",\r\n    \"Traditionelle (TRA)\"\r\n  )\r\n  --ORDER BY Zielgruppe ASC\r\n  ORDER BY $SinusOrder"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 3, "w": 20, "x": 2, "y": 45 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT Zielgruppe, TV_Gesamt*1000000 as TV_Gesamt\r\n FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts`\r\n WHERE Zielgruppe IN (\r\n    \"Konservativ-Gehobene (KOG)\",\r\n    \"Postmaterielle (PMA)\",\r\n    \"Performer (PER)\",\r\n    \"Expeditive (EPE)\",\r\n    \"Neo-Ökologische (NÖK)\",\r\n    \"Adaptiv-Pragmatische (ADA)\", \r\n    \"Konsum-Hedonisten (HED)\",\r\n    \"Prekäre (PRE)\", \r\n    \"Nostalgisch-Bürgerliche (NOB)\",\r\n    \"Traditionelle (TRA)\"\r\n  )\r\n  --ORDER BY Zielgruppe ASC\r\n  ORDER BY $SinusOrder"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 3, "w": 20, "x": 2, "y": 48 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT Zielgruppe, (Sehbeteiligung*1000000) as Sehbeteiligung\r\n FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts`\r\n WHERE Zielgruppe IN (\r\n    \"Konservativ-Gehobene (KOG)\",\r\n    \"Postmaterielle (PMA)\",\r\n    \"Performer (PER)\",\r\n    \"Expeditive (EPE)\",\r\n    \"Neo-Ökologische (NÖK)\",\r\n    \"Adaptiv-Pragmatische (ADA)\", \r\n    \"Konsum-Hedonisten (HED)\",\r\n    \"Prekäre (PRE)\", \r\n    \"Nostalgisch-Bürgerliche (NOB)\",\r\n    \"Traditionelle (TRA)\"\r\n  )\r\n  --ORDER BY Zielgruppe ASC\r\n  ORDER BY $SinusOrder"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 3, "w": 20, "x": 2, "y": 51 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": " SELECT Zielgruppe, Marktanteil\r\n FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_ZielgruppenFacts`\r\n WHERE Zielgruppe IN (\r\n    \"Konservativ-Gehobene (KOG)\",\r\n    \"Postmaterielle (PMA)\",\r\n    \"Performer (PER)\",\r\n    \"Expeditive (EPE)\",\r\n    \"Neo-Ökologische (NÖK)\",\r\n    \"Adaptiv-Pragmatische (ADA)\", \r\n    \"Konsum-Hedonisten (HED)\",\r\n    \"Prekäre (PRE)\", \r\n    \"Nostalgisch-Bürgerliche (NOB)\",\r\n    \"Traditionelle (TRA)\"\r\n  )\r\n  --ORDER BY Zielgruppe ASC\r\n  ORDER BY $SinusOrder "
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 54 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Hitlist von Sendungen | ${LRA:text}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }
  },
  {
   "title": "Hitliste von Sendungen |  ${LRA:text} | $Sendung",
   "type": "table",
   "gridPos": { "h": 12, "w": 20, "x": 2, "y": 57 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "IF ($LRA = 2) THEN ( \r\n  SELECT \r\n    ROW_NUMBER() OVER (ORDER BY -Marktanteil) AS Nummer, \r\n    Sender__kurz_ as Sender, \r\n    Datum_5 as Datum, \r\n    Seher*1000000 as Seher,\r\n    Marktanteil\r\n FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`);\r\nELSE ( \r\n  SELECT \r\n    ROW_NUMBER() OVER (ORDER BY -Sehbeteiligung) AS Nummer, \r\n    Sender__kurz_ as Sender, \r\n    Datum, Titel, \r\n    Sehbeteiligung, \r\n    Marktanteil\r\n FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`);\r\nEND IF;"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 69 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Top 10 Sender zur Sendezeit nach Marktanteil",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }
  },
  {
   "title": "Top 10 Sender zur Sendezeit nach Marktanteil | ${LRA:text}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 20, "x": 2, "y": 72 },
   "targets": [
    {
     "dataset": "Quotenreport_Sample",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Vergleichssender, Marktanteil \r\nFROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Vergleichssender`\r\nORDER BY Marktanteil DESC\r\nLIMIT 10"
    }
   ]
  },
  { "title": "Sendungen im Zeitverlauf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Sendungen im Zeitverlauf |  ${LRA:text} | $Sendung",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 20, "x": 2, "y": 83 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Line chart / time series of all shows with market share (default) and coverage (Reichweite)\r\n\r\nIF ($LRA = 2) THEN ( \r\n    SELECT 0 as Sehbeteiligung, ROUND(Marktanteil, 3) as Marktanteil,  Datum_5 as Datum\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`\r\n    ORDER by Datum_5 ASC);\r\nELSE ( \r\n    SELECT ROUND(Sehbeteiligung*1000,3) as Sehbeteiligung, ROUND(Marktanteil, 3) as Marktanteil,  Datum\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`\r\n    ORDER by Datum ASC);\r\nEND IF;\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Sendungen im Zeitverlauf |  ${LRA:text} | $Sendung",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 20, "x": 2, "y": 93 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- Line chart / time series of all shows with market share (default) and coverage (Reichweite)\r\n\r\nIF ($LRA = 2) THEN ( \r\n    SELECT 0 as Sehbeteiligung, ROUND(Marktanteil, 3) as Marktanteil,  Datum_5 as Datum\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`\r\n    ORDER by Datum_5 ASC);\r\nELSE ( \r\n    SELECT ROUND(Sehbeteiligung*1000,3) as Sehbeteiligung, ROUND(Marktanteil, 3) as Marktanteil,  Datum\r\n    FROM `ndr-code-bi-dashboard.Quotenreport_Sample.${dataset}_Sendungsliste`\r\n    ORDER by Datum ASC);\r\nEND IF;\r\n\r\n\r\n\r\n"
    }
   ]
  }
 ]
}