{
 "title": "Piano App Desktop",
 "description": "V3 Verlaufsiagramm",
 "time": { "from": "2023-05-01T00:00:00.000Z", "to": "2023-05-09T16:12:25.000Z" },
 "templating": {
  "list": [
   { "name": "filled_size", "query": "13" },
   {
    "name": "Vergleichszeitraumlabels",
    "query": {}
   },
   {
    "name": "Vergleichszeitraum",
    "query": {}
   },
   {
    "name": "LRA",
    "query": {}
   },
   { "name": "filled_size_headline", "query": "48" },
   {
    "name": "time_shift",
    "query": {}
   },
   {
    "name": "App",
    "query": {}
   },
   {
    "name": "app_name",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": "Letzte Stunde : CAST(tmstp AS DATE) = CURRENT_DATE() AND date = CURRENT_DATE(), Heute : date = CURRENT_DATE(),  Heute -7d : date  = CURRENT_DATE(), Gestern : date = DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY), Letztes Wochenende :  date >= (SELECT saturday FROM(SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 2 DAY) as saturday)) AND date <= (SELECT DATE(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP()\\,WEEK(MONDAY)) - INTERVAL 1 DAY) as sunday), Letzte 7 Tage : date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  7 DAY) AND date < CURRENT_DATE(), Letzte 30 Tage : date >=  DATE_SUB(CURRENT_DATE()\\, INTERVAL  30 DAY) AND date < CURRENT_DATE()"
   },
   {
    "name": "table",
    "query": {}
   },
   {
    "name": "bq_comp_timeframe_end",
    "query": {}
   },
   {
    "name": "bq_comp_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_timeframe_start",
    "query": {}
   },
   {
    "name": "bq_timeframe_end",
    "query": {}
   },
   {
    "name": "Zeitraumlabels",
    "query": {}
   },
   {
    "name": "feverCurveDataset",
    "query": {}
   },
   {
    "name": "dataset",
    "query": {}
   },
   {
    "name": "type",
    "query": {}
   },
   {
    "name": "lim",
    "query": {}
   },
   { "name": "Glaettung", "query": "Glätten, Nicht Glätten" },
   {
    "name": "comp_fever",
    "query": {}
   },
   {
    "name": "dataset_not_fevercurve",
    "query": {}
   },
   {
    "name": "Uhrzeit",
    "query": {}
   },
   {
    "name": "articles_table",
    "query": {}
   },
   {
    "name": "distro_table",
    "query": {}
   },
   {
    "name": "Vergleichszeitraumfever",
    "query": {}
   },
   {
    "name": "Zeitraumfever",
    "query": {}
   },
   {
    "name": "dataset_zeitraum",
    "query": {}
   },
   {
    "name": "dataset_vergleichs_zeitraum",
    "query": {}
   },
   {
    "name": "av_filter",
    "query": {}
   },
   {
    "name": "dataset_zeitraum_av",
    "query": {}
   },
   {
    "name": "dataset_vergleichs_zeitraum_av",
    "query": {}
   },
   {
    "name": "av_app_condition_video",
    "query": {}
   },
   {
    "name": "av_app_condition_audio",
    "query": {}
   },
   {
    "name": "av_pub_date",
    "query": {}
   },
   {
    "name": "av_content_id",
    "query": {}
   },
   {
    "name": "av_content",
    "query": {}
   },
   {
    "name": "av_on_demand_filter",
    "query": {}
   },
   {
    "name": "av_live_stream_filter",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# 📊 Hinweis\n\n- Audio- und Video-Daten ohne Livestream-Nutzung, mit Ausnahme der Livestream-Tabelle."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Verlaufsdiagramm Visits",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH sumdata AS (\n  SELECT\n    TIMESTAMP(tmstp) as tmstp,\n    CASE \"$LRA\"\n    WHEN \"NDR\" THEN MAX(m_visits)\n    ELSE SUM(DISTINCT m_visits)\n    END\n     as m_visits FROM\n     `Piano.total_visits${feverCurveDataset:raw}`\n  WHERE\n  site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n  GROUP by tmstp\n  ORDER BY tmstp DESC\n  ${lim}\n),\nlagged_data AS (\n  SELECT\n    TIMESTAMP(tmstp) as time,\n    m_visits - LAG(m_visits) OVER (\n      ORDER BY\n        tmstp\n    ) as visits_past_5_minutes,\n    LAG(m_visits) OVER (ORDER BY tmstp) as prev_m_visits,\n    LAG(TIMESTAMP(tmstp)) OVER (ORDER BY tmstp) as pre_timestamp,\n    m_visits\n  FROM\n    sumdata\n    \n),\nmin_time_from_base AS (\n  -- This with statement will used in order to find out which is the last valid upload(e.g. the one with valid successor)\n  SELECT MIN(pre_timestamp) min_time FROM lagged_data\n  WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10\n), \nmax_time_from_base AS (\n    -- THis with statement will be used if no gap exists\n    SELECT MAX(time) as max_time FROM lagged_data\n    WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10\n),\ncleaned_lagged_data AS (\n  SELECT * from lagged_data \n  WHERE\n  time <= (SELECT COALESCE(max_time_from_base.max_time, min_time_from_base.min_time )\n  FROM max_time_from_base, min_time_from_base)\n),\nadjusted_lagged_data AS (\n    SELECT\n        time,\n        pre_timestamp,\n        -- Calculate time difference in minutes\n        TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) as time_diff,\n        -- Adjust visits count based on time difference\n           CASE\n      WHEN FALSE AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10 OR TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) < 10 AND \"${Glaettung:text}\" = \"Glätten\" THEN\n        (m_visits - prev_m_visits) / TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) * 10\n      ELSE\n        m_visits - prev_m_visits\n        END as visits_past_5_minutes\n    FROM\n        cleaned_lagged_data\n        WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) >= 10\n      ORDER BY time DESC\n      ${lim}\n),\n\ndaily_data AS (\n  SELECT\n     TIMESTAMP(date) as time,\n    SUM(m_visits) as visits_past_5_minutes\n  FROM\n    `Piano.total_visits${feverCurveDataset:raw}`\n  WHERE\n  site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n  GROUP BY date\n)\n\nSELECT\n    DATE_SUB(TIMESTAMP_ADD(time, INTERVAL 1 SECOND), INTERVAL 2 hour) as time,\n  visits_past_5_minutes, \"${type}\" as type, \"${Zeitraumlabels:text}\" as refId,\n     \"${Glaettung:text}\" as glaettung,\n   \"Zeitraum\" as zeitraum\nFROM\n  ${dataset}\nWHERE\n  visits_past_5_minutes IS NOT NULL\n  AND $Zeitraumfever \nORDER BY\n  time ASC\n${lim}\n"
    },
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH min_time AS (\n      SELECT\n        DATE_ADD(MIN(tmstp), INTERVAL 10 MINUTE) as min_tmstp,\n        MAX(tmstp) as max_tmstp\n        FROM\n      (SELECT tmstp\n      from\n        `Piano.total_visits${feverCurveDataset:raw}`\n      WHERE\n       site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Zeitraum\n  GROUP by tmstp\n  ORDER BY tmstp DESC\n  ${lim})\n    ),\nsumdata AS (\n  SELECT\n    TIMESTAMP(tmstp) as tmstp,\n      CASE \"$LRA\"\n    WHEN \"NDR\" THEN MAX(m_visits)\n    ELSE SUM(DISTINCT m_visits)\n    END\n     as m_visits FROM\n     `Piano.total_visits${feverCurveDataset:raw}`, min_time\n  WHERE\n  site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND $Vergleichszeitraum \n    AND tmstp <= min_time.min_tmstp\n    AND  CASE \"${Zeitraum:text}\" WHEN \"Gestern\" THEN TRUE ELSE EXTRACT(HOUR from tmstp) <= (SELECT EXTRACT(HOUR FROM MAX(tmstp)) from  `Piano.total_visits${feverCurveDataset:raw}` WHERE $Zeitraum ) END\n    AND    EXTRACT(date from tmstp) >= ${bq_comp_timeframe_start:doublequote} AND EXTRACT(date from tmstp) <= ${bq_comp_timeframe_end:doublequote}\n\n  GROUP by tmstp\n  ORDER BY tmstp DESC\n),\nlagged_data AS (\n  SELECT\n    TIMESTAMP(tmstp) as time,\n    m_visits - LAG(m_visits) OVER (\n      ORDER BY\n        tmstp\n    ) as visits_past_5_minutes,\n    m_visits,\n    LAG(m_visits) OVER (ORDER BY tmstp) as prev_m_visits,\n    LAG(TIMESTAMP(tmstp)) OVER (ORDER BY tmstp) as pre_timestamp\n\n  FROM\n    sumdata\n),\nmin_time_from_base AS (\n  -- This with statement will used in order to find out which is the last valid upload(e.g. the one with valid successor)\n  SELECT MIN(pre_timestamp) min_time FROM lagged_data\n  WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10\n), \nmax_time_from_base AS (\n    -- THis with statement will be used if no gap exists\n    SELECT MAX(time) as max_time FROM lagged_data\n    WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) = 10\n),\ncleaned_lagged_data AS (\n  SELECT * from lagged_data \n  WHERE\n  time <= (SELECT COALESCE(min_time_from_base.min_time,max_time_from_base.max_time )\n  FROM max_time_from_base, min_time_from_base)\n),\nadjusted_lagged_data AS (\n    SELECT\n        time,\n        pre_timestamp,\n        -- Calculate time difference in minutes\n        TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) as time_diff,\n        -- Adjust visits count based on time difference\n           CASE\n      WHEN FALSE AND TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) > 10 OR TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) < 10 AND \"${Glaettung:text}\" = \"Glätten\" THEN\n        (m_visits - prev_m_visits) / TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) * 10\n      ELSE\n        m_visits - prev_m_visits\n        END as visits_past_5_minutes\n    FROM\n        cleaned_lagged_data\n        WHERE TIMESTAMP_DIFF(time, pre_timestamp, MINUTE) >= 10\n),\ndaily_data AS (\n  SELECT\n     TIMESTAMP(date) as time,\n    SUM(m_visits) as visits_past_5_minutes, \n  FROM\n    `Piano.total_visits${feverCurveDataset:raw}`\n  WHERE\n    site_level2 = '${app_name}'\n    AND page_chapter1 = \"Alle Kapitel 1\"\n    AND page_chapter2 = \"Alle Kapitel 2\"\n    AND sendungs_id = \"Alle Sendungs-ID\"\n    AND $Vergleichszeitraum\n    GROUP BY date\n)\n\nSELECT\n  DATE_SUB(DATE_ADD(TIMESTAMP_ADD(time, INTERVAL 1 SECOND), INTERVAL ${time_shift} DAY), INTERVAL 2 HOUR) as time , \n  visits_past_5_minutes, \"${type}\" as type, \n   \"${Vergleichszeitraumlabels:text}\" as refId,\n      \"${Glaettung:text}\" as glaettung,\n   \"Vergleichszeitraum\" as zeitraum\nFROM\n  ${dataset}\nWHERE\n  visits_past_5_minutes IS NOT NULL\n  AND $Vergleichszeitraumfever \nORDER BY\n  time ASC\n${lim}\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Visits')), 'Visits')\r\nFROM(\r\nSELECT 'Visits' as Visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Page Views / Visits')), 'Page Views / Visits')\r\nFROM(\r\nSELECT 'Page Views / Visits' as pi_visits\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Time spent / Visit in s')), 'Time spent / Visit in s')\r\nFROM(\r\nSELECT 'Time spent / Visit in s' as Audio_Videostarts\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH adjusted_lagged_data AS (\n  SELECT\n     SUM(m_visits) as summe FROM\n     `Piano.total_visits${feverCurveDataset:raw}`\n  WHERE\n  site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n    GROUP BY site_level2, tmstp\n  ORDER BY summe DESC\n  LIMIT 1\n),\ndaily_data AS (SELECT\n  sum(m_visits) as summe\nFROM\n  `Piano.total_visits${dataset_zeitraum:raw}`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n  )\nSELECT * FROM ${dataset_not_fevercurve} "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH adjusted_lagged_data AS (\r\n  SELECT\r\n    SUM(COALESCE(m_visits,0)) AS summe FROM\r\n     `Piano.total_visits${feverCurveDataset:raw}`\r\n  WHERE\r\n  site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp <= \"${comp_fever}\"\r\n    GROUP BY site_level2, tmstp\r\n  ORDER BY summe DESC\r\n  LIMIT 1\r\n),\r\ndaily_data AS (SELECT\r\n  SUM(COALESCE(m_visits,0)) AS summe\r\nFROM\r\n `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  )\r\nSELECT * FROM ${dataset_not_fevercurve}\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit\nFROM\n  Piano.total_visits${dataset_zeitraum:raw}\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH adjusted_lagged_data AS (\r\n  SELECT\r\n  MAX(COALESCE(m_page_loads,0))/MAX(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM\r\n  `Piano.total_visits${feverCurveDataset:raw}`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp <= \"${comp_fever}\"\r\n),\r\ndaily_data AS (SELECT\r\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as PI_per_visit,\r\nFROM\r\n  Piano.total_visits${dataset_vergleichs_zeitraum:raw}\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  )\r\nSELECT * FROM ${dataset_not_fevercurve}\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\nFROM\n  Piano.total_visits${dataset_zeitraum:raw}\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH adjusted_lagged_data AS (\r\n SELECT\r\n    MAX(m_visits * m_time_spent_per_visits/1000) / MAX(m_visits) AS time_spent\r\nFROM\r\n    `Piano.total_visits${feverCurveDataset:raw}`\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  AND tmstp <= \"${comp_fever}\"\r\n),\r\ndaily_data AS (SELECT\r\n    SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS time_spent\r\nFROM\r\n    Piano.total_visits${dataset_vergleichs_zeitraum:raw}\r\nWHERE site_level2 = '${app_name}'\r\n  AND page_chapter1 = \"Alle Kapitel 1\"\r\n  AND page_chapter2 = \"Alle Kapitel 2\"\r\n  AND sendungs_id = \"Alle Sendungs-ID\"\r\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\n  )\r\nSELECT * FROM ${dataset_not_fevercurve}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\nWITH adjusted_lagged_data AS (\n  SELECT\n    SUM(COALESCE(m_visits,0)) AS summe FROM\n     `Piano.total_visits${feverCurveDataset:raw}`\n  WHERE\n  site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\n  AND tmstp <= \"${comp_fever}\"\n    GROUP BY site_level2, tmstp,date\n  ORDER BY summe DESC\n  LIMIT 1\n\n),\ndaily_data AS (SELECT\n  SUM(COALESCE(m_visits,0)) AS summe\nFROM\n  Piano.total_visits${dataset_vergleichs_zeitraum:raw}\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\n  )\nSELECT summe as past_sum FROM ${dataset_not_fevercurve}\n), current_value AS (\n  WITH adjusted_lagged_data AS (\n  SELECT\n     SUM(m_visits) as summe FROM\n     `Piano.total_visits${feverCurveDataset:raw}`\n  WHERE\n  site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n    GROUP BY site_level2, tmstp\n  ORDER BY summe DESC\n  LIMIT 1\n),\ndaily_data AS (SELECT\n  sum(m_visits) as summe\nFROM\n  Piano.total_visits${dataset_zeitraum:raw}\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n  )\nSELECT summe as current_sum FROM ${dataset_not_fevercurve}\n)\n\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\nWITH adjusted_lagged_data AS (\n  SELECT\n  MAX(COALESCE(m_page_loads,0))/MAX(COALESCE(m_visits,1)) as summe,\nFROM\n  `Piano.total_visits${feverCurveDataset:raw}`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\n  AND tmstp <= \"${comp_fever}\"\n),\ndaily_data AS (SELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as summe,\nFROM\n    `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\n  )\nSELECT summe as past_sum FROM ${dataset_not_fevercurve}), current_value AS (\nSELECT\n  SUM(COALESCE(m_page_loads,0))/SUM(COALESCE(m_visits,1)) as current_sum,\nFROM\n    `Piano.total_visits${dataset_zeitraum:raw}`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n  )\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH past_value as(\nWITH adjusted_lagged_data AS (\n SELECT\n    MAX(m_visits * m_time_spent_per_visits/1000) / MAX(m_visits) AS summe\nFROM\n    `Piano.total_visits${feverCurveDataset:raw}`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\n  AND tmstp <= \"${comp_fever}\"\n),\ndaily_data AS (SELECT\n    SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS summe\nFROM\n      `Piano.total_visits${dataset_vergleichs_zeitraum:raw}`\nWHERE site_level2 = '${app_name}'\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\n  )\nSELECT summe as past_sum FROM ${dataset_not_fevercurve}), current_value AS (\nSELECT \n   SUM(m_visits * m_time_spent_per_visits/1000) / SUM(m_visits) AS current_sum,\nFROM \n    `Piano.total_visits${dataset_zeitraum:raw}`\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n)\nSELECT ((current_sum-past_sum)/past_sum)*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  { "title": "Top Inhalte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Top 100 App Artikel",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version\nSELECT\n  publishing_date as Datum,\n  content_titel as Artikel,\n  sum(m_visits) as Visits,\n  sum(m_page_loads) as page_views,\n  content_id_sophora,\n  '' as Type\nFROM\n  (\n    SELECT\n      --publishing_date,\n      FIRST_VALUE(publishing_date) OVER (PARTITION BY CASE uuid WHEN \"N/A\" THEN content_id_sophora ELSE uuid END ORDER BY publishing_date DESC) as publishing_date, \n      FIRST_VALUE(content_id_sophora) OVER (PARTITION BY CASE uuid WHEN \"N/A\" THEN content_id_sophora ELSE uuid END ORDER BY publishing_date DESC) as content_id_sophora, \n      m_visits,\n      m_page_loads,\n      FIRST_VALUE(content_titel) OVER (PARTITION BY CASE uuid WHEN \"N/A\" THEN content_id_sophora ELSE uuid END ORDER BY publishing_date DESC) as content_titel\n    FROM\n      $table\n    WHERE\n      site_level2 = '${app_name}'\n      AND content_id_sophora NOT LIKE '%index%'\n      AND content_id_sophora NOT LIKE '%N/A%'\n      AND (\n        CASE \n            WHEN \"$LRA\" = 'NDR' THEN\n                content_titel NOT LIKE '%Video Livestream%'\n            AND content_titel NOT LIKE '%Startteaser%'\n            AND content_titel NOT LIKE '%startteaser%'\n            AND content_titel NOT LIKE '%-Anmelden%'\n            AND content_titel NOT LIKE '%_Start'\n            AND content_titel != 'Anmelden'\n            AND content_titel != 'Jetzt läuft'\n        ELSE\n          TRUE\n        END)\n      AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n  )\nGROUP BY\n  content_id_sophora,\n  content_titel,\n  publishing_date\nORDER BY\n  3 DESC\nLIMIT\n  100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "options": { "content": " " } },
  { "title": "AV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), '')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 3, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaben')), 'Wiedergaben')\r\nFROM(\r\nSELECT 'Wiedergaben' as Wiedergaben\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Wiedergaberate')), 'Wiedergaberate')\r\nFROM(\r\nSELECT 'Wiedergaberate' as Wiedergaberate\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Video')), 'Video')\r\nFROM(\r\nSELECT 'Video' as Video\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton, m_av_playbacks, 0)) as summe\r\nFROM  \r\n  `${dataset_zeitraum_av:raw}`\r\n  WHERE \r\n$av_filter  \r\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND $av_app_condition_video"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton,m_av_playbacks,0)) as summe\r\nFROM \r\n `${dataset_vergleichs_zeitraum_av:raw}` WHERE \r\n$av_filter \r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND $av_app_condition_video"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_value AS (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton,m_av_playbacks,0)) as current_sum\r\nFROM  \r\n `${dataset_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND ($av_app_condition_video)\r\n), past_value AS (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton,m_av_playbacks,0)) as past_sum\r\nFROM \r\n`${dataset_vergleichs_zeitraum_av:raw}`WHERE \r\n$av_filter \r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND ($av_app_condition_video)\r\n)\r\nSELECT (SAFE_DIVIDE((current_sum-past_sum),past_sum))*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ohne Live-Videos",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SAFE_DIVIDE(SUM(m_av_playbacks * m_av_average_playback_completion_rate), SUM(m_av_playbacks)) as summe\r\nFROM \r\n `${dataset_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND ($av_app_condition_video)\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ohne Live-Videos",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\r\n  SAFE_DIVIDE(SUM(m_av_playbacks * m_av_average_playback_completion_rate), SUM(m_av_playbacks)) as summe\r\n  --AVG(m_av_average_playback_completion_rate) as summe\r\n  -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n   `${dataset_vergleichs_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND ($av_app_condition_video)\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ohne Live-Videos",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_value AS (\r\n  SELECT\r\n  SAFE_DIVIDE(SUM(m_av_playbacks * m_av_average_playback_completion_rate), SUM(m_av_playbacks)) as current_sum\r\n  -- AVG(m_av_average_playback_completion_rate) as current_sum\r\n   -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n `${dataset_zeitraum_av:raw}`WHERE \r\n$av_filter \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND ($av_app_condition_video)\r\n), past_value AS (\r\n  SELECT\r\n  SAFE_DIVIDE(SUM(m_av_playbacks * m_av_average_playback_completion_rate), SUM(m_av_playbacks)) as past_sum\r\n  --AVG(m_av_average_playback_completion_rate) as past_sum\r\n   -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  `${dataset_vergleichs_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND ($av_app_condition_video)\r\nAND bi_av_broadcasting_type NOT LIKE '%Live%'\r\nAND bi_av_broadcasting_type NOT LIKE '%live%'\r\n)\r\nSELECT (SAFE_DIVIDE((current_sum-past_sum),past_sum))*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT CONCAT(REPEAT(\" \", $filled_size_headline - CHAR_LENGTH('Audio')), 'Audio')\r\nFROM(\r\nSELECT 'Audio' as Audio\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton,m_av_playbacks,0)) as summe\r\nFROM \r\n   `${dataset_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND ($av_app_condition_audio)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SUM(COALESCE(m_playbutton,m_av_playbacks,0)) as summe\r\nFROM \r\n`${dataset_vergleichs_zeitraum_av:raw}`WHERE \r\n$av_filter \r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND ($av_app_condition_audio)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_value AS (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton,m_av_playbacks,0)) as current_sum\r\nFROM \r\n   `${dataset_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND ($av_app_condition_audio)\r\n), past_value AS (\r\n  SELECT \r\n  SUM(COALESCE(m_playbutton,m_av_playbacks,0)) as past_sum\r\nFROM \r\n   `${dataset_vergleichs_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio)\r\n)\r\nSELECT (SAFE_DIVIDE((current_sum-past_sum),past_sum))*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  --AVG(m_av_average_playback_completion_rate) as summe\r\n  SAFE_DIVIDE(SUM(m_av_playbacks * m_av_average_playback_completion_rate), SUM(m_av_playbacks)) as summe\r\nFROM \r\n `${dataset_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND ($av_app_condition_audio)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\n  SAFE_DIVIDE(SUM(m_av_playbacks * m_av_average_playback_completion_rate), SUM(m_av_playbacks)) as summe\r\nFROM \r\n`${dataset_vergleichs_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote}\r\nAND ($av_app_condition_audio)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH current_value AS (\r\n  SELECT\r\n  SAFE_DIVIDE(SUM(m_av_playbacks * m_av_average_playback_completion_rate), SUM(m_av_playbacks)) as current_sum\r\n  -- AVG(m_av_average_playback_completion_rate) as current_sum\r\n   -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  `${dataset_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\r\nAND ($av_app_condition_audio)\r\n), past_value AS (\r\n  SELECT\r\n  SAFE_DIVIDE(SUM(m_av_playbacks * m_av_average_playback_completion_rate), SUM(m_av_playbacks)) as past_sum\r\n  --AVG(m_av_average_playback_completion_rate) as past_sum\r\n   -- AVG(m_av_playbacks)/AVG(av_content_duration) as summe\r\n  --SUM(COALESCE(m_av_playbacks,0))/SUM(COALESCE(av_content_duration,0)) as summe\r\nFROM \r\n  `${dataset_vergleichs_zeitraum_av:raw}`\r\nWHERE \r\n$av_filter \r\nAND date >= ${bq_comp_timeframe_start:doublequote} AND date <= ${bq_comp_timeframe_end:doublequote} \r\nAND ($av_app_condition_audio)\r\n)\r\nSELECT (SAFE_DIVIDE((current_sum-past_sum),past_sum))*100 FROM current_value,past_value as relative_difference"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }, "options": { "content": " " } },
  {
   "title": "Top 100 Web Audios & Videos on Demand",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe, \r\nCONCAT(CONCAT(\r\n\r\n  CASE WHEN LENGTH(CAST(DIV(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(DIV(av_content_duration,60) AS String)) ELSE CAST(DIV(av_content_duration,60) AS String)  END ,\r\n\r\n  \":\",CASE WHEN LENGTH(CAST(MOD(av_content_duration,60) AS String))<2 THEN CONCAT(\"0\",CAST(MOD(av_content_duration,60) AS String)) ELSE CAST(MOD(av_content_duration,60) AS String)  END),\" Min\") as av_content_duration,\r\nCASE \"$LRA\"\r\nWHEN \"NDR\" THEN NULL\r\nELSE 100*SUM(m_av_playbacks * m_av_average_playback_completion_rate) / SUM(m_av_playbacks) END as wiedergaberate,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\n--device_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE($av_pub_date) OVER (PARTITION BY bi_av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_publication_date,  \r\nCOALESCE(m_playbutton,m_av_playbacks) as m_av_playbacks, \r\nCASE  \r\n      WHEN av_content_duration is NULL THEN NULL\r\n      ELSE CAST((av_content_duration/1000) AS INT) END av_content_duration,\r\n--CAST((av_content_duration/1000) AS INT) as av_content_duration,  \r\nm_av_average_playback_completion_rate, \r\nCOALESCE(content_typ, av_content_type) as av_content_type, COALESCE(content_id_sophora, bi_av_content_id) as bi_av_content_id,  \r\nCOALESCE(objekt_typ ,bi_av_broadcasting_type) as bi_av_broadcasting_type ,  \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_url,  \r\n\r\n--device_type,\r\nFIRST_VALUE($av_content) OVER (PARTITION BY COALESCE(content_id_sophora,bi_av_content_id) ORDER BY COALESCE(m_playbutton,m_av_playbacks) DESC) as bi_av_content  \r\nFROM \r\n`${dataset_zeitraum_av:raw}`--`Piano.av${dataset_zeitraum:raw}` \r\nWHERE $av_filter \r\nAND COALESCE(content_id_sophora, bi_av_content_id) NOT LIKE '%index%'  \r\nAND COALESCE(objekt_typ, bi_av_broadcasting_type) IN $av_on_demand_filter  \r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})  \r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,av_content_duration,av_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  {
   "title": "Top 100 Web Audios & Videos Livestreams",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\nbi_av_publication_date,\r\nbi_av_content, bi_av_content_id,\r\nbi_av_url as url,\r\nsum(m_av_playbacks) as wiedergabe,\r\nav_content_type,\r\nbi_av_broadcasting_type,\r\nFROM\r\n(\r\nSELECT\r\nFIRST_VALUE($av_pub_date) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_publication_date, \r\nCOALESCE(m_playbutton,m_av_playbacks) as m_av_playbacks,\r\nCOALESCE(content_typ, av_content_type) as av_content_type, $av_content_id as bi_av_content_id,\r\nbi_av_broadcasting_type, \r\nFIRST_VALUE(bi_av_url) OVER (PARTITION BY $av_content ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_url, \r\n\r\n--device_type,\r\nFIRST_VALUE($av_content) OVER (PARTITION BY $av_content_id ORDER BY COALESCE(m_playbutton, m_av_playbacks) DESC) as bi_av_content, \r\nFROM \r\n`${dataset_zeitraum_av:raw}`--`Piano.av${dataset_zeitraum:raw}`\r\nWHERE $av_filter \r\nAND $av_content_id NOT LIKE '%index%'\r\nAND COALESCE(objekt_typ, bi_av_broadcasting_type) IN $av_live_stream_filter\r\nAND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote})\r\nWHERE m_av_playbacks > 0\r\nGROUP BY bi_av_publication_date,bi_av_content,\r\nav_content_type,bi_av_content_id, bi_av_broadcasting_type, bi_av_url\r\n--,device_type \r\nORDER BY 5 DESC\r\nLimit 100"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }, "options": { "content": " " } },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "App | Distribution | $Zeitraumlabels",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "-- cache version\nSELECT \n  SUM(m_visits), os_group \nFROM \n  ${distro_table:raw}\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote}\n  AND device_type NOT LIKE '%N/A%'\nGROUP BY os_group\nORDER BY 1 DESC\n"
    }
   ]
  },
  {
   "title": "App | Devices | $Zeitraumlabels",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\ndevice_type,\nSUM(m_visits) as visits\nFROM\n  ${distro_table:raw}\nWHERE site_level2 = \"${app_name}\"\n  AND page_chapter1 = \"Alle Kapitel 1\"\n  AND page_chapter2 = \"Alle Kapitel 2\"\n  AND sendungs_id = \"Alle Sendungs-ID\"\n  AND date >= ${bq_timeframe_start:doublequote} AND date <= ${bq_timeframe_end:doublequote} \n  AND device_type NOT LIKE '%N/A%'\nGROUP BY device_type \nORDER BY visits DESC \nLIMIT 10"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }, "options": { "content": " " } }
 ]
}