{
 "title": "ML-Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Profil",
    "query": {}
   },
   {
    "name": "Posts",
    "query": {}
   },
   {
    "name": "Vorhersagezeitraum",
    "query": "Eine Woche : 7, Zwei Wochen : 14, Drei Wochen : 21, Ein Monat : 30, Zwei Monate : 60"
   },
   {
    "name": "heute",
    "query": {}
   },
   {
    "name": "Plattform",
    "query": {}
   },
   {
    "name": "Vergleichsplattform",
    "query": {}
   },
   {
    "name": "FBprofileID",
    "query": {}
   },
   {
    "name": "InprofileID",
    "query": {}
   },
   {
    "name": "YTprofileID",
    "query": {}
   },
   {
    "name": "TTprofileID",
    "query": {}
   },
   {
    "name": "profileID",
    "query": {}
   },
   {
    "name": "VergleichsprofileID",
    "query": {}
   },
   {
    "name": "Vorhersagemodel",
    "query": {}
   },
   {
    "name": "Vorhersagevergleichsplattform",
    "query": {}
   },
   {
    "name": "PlattformFollowersVorhersageExceptList",
    "query": {}
   },
   {
    "name": "FBExcept",
    "query": "\"last_update\\, uniqueId\\, lra\\, profileId\\, importTime\""
   },
   {
    "name": "InExcept",
    "query": "\"last_update\\, uniqueId\\, lra\\, profileId\""
   },
   {
    "name": "YTExcept",
    "query": "\"last_update\\, uniqueId\\, lra\\, profileId\\, importTime\\, viewsByAgeAndGender\\, viewsBySubscribedStatus\""
   },
   {
    "name": "TTExcept",
    "query": "\"last_update\\, uniqueId\\, lra\\, profileId\\, followersChange\\, followersBefore\""
   },
   {
    "name": "VergleichsPlattformFollowersVorhersageExceptList",
    "query": {}
   },
   {
    "name": "PlattformFollowersField",
    "query": {}
   },
   {
    "name": "VergleichsPlattformFollowersField",
    "query": {}
   },
   {
    "name": "Zeitraum",
    "query": {}
   },
   {
    "name": "VergleichsPlattformZeitraum",
    "query": {}
   },
   {
    "name": "PlattformAnzahlPosts",
    "query": {}
   },
   {
    "name": "VergleichsPlattformAnzahlPosts",
    "query": {}
   },
   {
    "name": "VorhersageVergleichsprofileID",
    "query": {}
   },
   {
    "name": "VorhersageVergleichsPlattformZeitraum",
    "query": {}
   },
   {
    "name": "PlattformInteraktionen",
    "query": {}
   },
   {
    "name": "VergleicsplattformInteraktionen",
    "query": {}
   },
   {
    "name": "NumberOfWeeks",
    "query": {}
   },
   {
    "name": "PlattformPostField",
    "query": {}
   },
   {
    "name": "VergleichsplattformPostField",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "DECLARE system_time ARRAY<TIMESTAMP>;\nDECLARE i INT64 DEFAULT 0;\n\nSET system_time = ARRAY(\n  SELECT TIMESTAMP_ADD(TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL x DAY), INTERVAL 23 HOUR) \n  FROM UNNEST(GENERATE_ARRAY(0, 5)) as x\n);\n\nLOOP\n  IF i >= ARRAY_LENGTH(system_time) THEN \n    LEAVE;\n  END IF;\n\n  -- Replace this SELECT statement with your actual query, using system_time[OFFSET(i)]\n  SELECT system_time[OFFSET(i)];\n\n  SET i = i + 1;\nEND LOOP;"
    }
   ]
  },
  { "title": "Interaktion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Clustering",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Anzahl der Posts pro Stunde",
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "WITH selected_platform AS(\r\nWITH all_hours AS(\r\n  SELECT CAST(stunde AS STRING) as stunde FROM UNNEST(GENERATE_ARRAY(0,23)) AS stunde\r\n),\r\nexisting_hours AS(\r\nSELECT CAST(EXTRACT(HOUR from time) AS STRING) as stunde, COUNT(DISTINCT externalId) as anzahlPosts FROM ${PlattformAnzahlPosts}\r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND  profileId = $profileID\r\nGROUP BY stunde\r\nORDER BY stunde ASC),\r\nnot_exisiting_hours AS(\r\n   SELECT all_hours.stunde as stunde, 0 as anzahlPosts\r\n  FROM all_hours\r\n  LEFT JOIN existing_hours ON all_hours.stunde = existing_hours.stunde\r\n  WHERE existing_hours.stunde IS NULL\r\n)\r\nSELECT * FROM existing_hours UNION ALL SELECT * FROM not_exisiting_hours\r\nORDER by CAST(stunde AS INT)),\r\n\r\nselected_comparison_platform AS(\r\nWITH all_hours AS(\r\n  SELECT CAST(stunde AS STRING) as stunde, 0 as anzahlPosts FROM UNNEST(GENERATE_ARRAY(0,23)) AS stunde\r\n),\r\nexisting_hours AS(\r\nSELECT CAST(EXTRACT(HOUR from time) AS STRING) as stunde, COUNT(DISTINCT externalId) as anzahlPosts FROM ${VergleichsPlattformAnzahlPosts}\r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND profileId = $VergleichsprofileID\r\nGROUP BY stunde\r\nORDER BY stunde ASC),\r\nnot_exisiting_hours AS(\r\n   SELECT all_hours.stunde as stunde, 0 as anzahlPosts\r\n  FROM all_hours\r\n  LEFT JOIN existing_hours ON all_hours.stunde = existing_hours.stunde\r\n  WHERE existing_hours.stunde IS NULL\r\n)\r\nSELECT * FROM existing_hours UNION ALL SELECT * FROM not_exisiting_hours\r\nORDER by CAST(stunde AS INT))\r\n\r\nSELECT selected_platform.stunde, anzahlPosts,COALESCE(VergleichsAnzahlposts,0)  as VergleichsAnzahlPosts,\r\n\"${Vergleichsplattform}\" as Vergleichsplatform, \"${Plattform}\" as platform FROM selected_platform\r\nLEFT JOIN (SELECT stunde, anzahlPosts as VergleichsAnzahlPosts FROM selected_comparison_platform) AS selected_comparison_platform\r\nON selected_platform.stunde = selected_comparison_platform.stunde\r\nORDER BY CAST(stunde AS INT)"
      }
     ]
    },
    {
     "title": "Anzahl der Posts pro Wochentag",
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "CREATE TEMP FUNCTION getDayByDate(datum DATE)\r\nRETURNS STRING\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nvar jsDatum = new Date(datum);\r\nvar day = jsDatum.getUTCDay();\r\nvar days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];\r\nreturn days[day];\r\n\"\"\";\r\n\r\nCREATE TEMP FUNCTION getDayAsNumber(tag STRING)\r\nRETURNS INT64\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nvar days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];\r\nreturn days.indexOf(tag)\r\n\"\"\";\r\n\r\nCREATE TEMP FUNCTION getDayInGerman(tag STRING)\r\nRETURNS STRING\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nconst dayMap = {\r\n        'Sunday': 'Sonntag',\r\n        'Monday': 'Montag',\r\n        'Tuesday': 'Dienstag',\r\n        'Wednesday': 'Mittwoch',\r\n        'Thursday': 'Donnerstag',\r\n        'Friday': 'Freitag',\r\n        'Saturday': 'Samstag'};\r\nreturn dayMap[tag]\r\n\"\"\";\r\n\r\nWITH selected_platform AS(\r\nWITH all_days AS(\r\n  SELECT tag FROM UNNEST(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']) AS tag\r\n),\r\nexisting_days AS(\r\nSELECT getDayByDate(EXTRACT(DATE from time)) as tag, COUNT(DISTINCT externalId) as anzahlPosts FROM ${PlattformAnzahlPosts}\r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND  profileId = $profileID\r\nGROUP BY tag\r\nORDER BY tag ASC),\r\nnot_exisiting_days AS(\r\n   SELECT all_days.tag as tag, 0 as anzahlPosts\r\n  FROM all_days\r\n  LEFT JOIN existing_days ON all_days.tag = existing_days.tag\r\n  WHERE existing_days.tag IS NULL\r\n)\r\nSELECT * FROM existing_days UNION ALL SELECT * FROM not_exisiting_days\r\nORDER by tag),\r\n\r\nselected_comparison_platform AS(\r\nWITH all_days AS(\r\n  SELECT tag FROM UNNEST(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']) AS tag\r\n),\r\nexisting_days AS(\r\nSELECT getDayByDate(EXTRACT(DATE from time)) as tag, COUNT(DISTINCT externalId) as anzahlPosts FROM ${VergleichsPlattformAnzahlPosts}\r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND profileId = $VergleichsprofileID\r\nGROUP BY tag\r\nORDER BY tag ASC),\r\nnot_exisiting_days AS(\r\n   SELECT all_days.tag as tag, 0 as anzahlPosts\r\n  FROM all_days\r\n  LEFT JOIN existing_days ON all_days.tag = existing_days.tag\r\n  WHERE existing_days.tag IS NULL\r\n)\r\nSELECT * FROM existing_days UNION ALL SELECT * FROM not_exisiting_days\r\nORDER by tag)\r\n\r\nSELECT getDayInGerman(selected_platform.tag) as tag, anzahlPosts,COALESCE(VergleichsAnzahlposts,0)  as VergleichsAnzahlPosts,\r\n\"${Vergleichsplattform}\" as Vergleichsplatform, \"${Plattform}\" as platform FROM selected_platform\r\nLEFT JOIN (SELECT tag, anzahlPosts as VergleichsAnzahlPosts FROM selected_comparison_platform) AS selected_comparison_platform\r\nON selected_platform.tag = selected_comparison_platform.tag\r\nORDER BY getDayAsNumber(selected_comparison_platform.tag)"
      }
     ]
    },
    {
     "title": "Interaktionen pro Wochentag",
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "CREATE TEMP FUNCTION getDayByDate(datum DATE)\r\nRETURNS STRING\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nvar jsDatum = new Date(datum);\r\nvar day = jsDatum.getUTCDay();\r\nvar days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];\r\nreturn days[day];\r\n\"\"\";\r\n\r\nCREATE TEMP FUNCTION getDayAsNumber(tag STRING)\r\nRETURNS INT64\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nvar days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];\r\nreturn days.indexOf(tag)\r\n\"\"\";\r\n\r\nCREATE TEMP FUNCTION getDayInGerman(tag STRING)\r\nRETURNS STRING\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nconst dayMap = {\r\n        'Sunday': 'Sonntag',\r\n        'Monday': 'Montag',\r\n        'Tuesday': 'Dienstag',\r\n        'Wednesday': 'Mittwoch',\r\n        'Thursday': 'Donnerstag',\r\n        'Friday': 'Freitag',\r\n        'Saturday': 'Samstag'};\r\nreturn dayMap[tag]\r\n\"\"\";\r\n\r\nWITH selected_platform AS(\r\nWITH all_days AS(\r\n  SELECT tag FROM UNNEST(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']) AS tag\r\n),\r\nexisting_days AS(\r\nSELECT getDayByDate(EXTRACT(DATE from time)) as tag, $PlattformInteraktionen as Interaktionen FROM Quintly.${Vorhersagemodel}\r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND  profileId = $profileID\r\nGROUP BY tag\r\nORDER BY tag ASC),\r\nnot_exisiting_days AS(\r\n   SELECT all_days.tag as tag, 0 as Interaktionen\r\n  FROM all_days\r\n  LEFT JOIN existing_days ON all_days.tag = existing_days.tag\r\n  WHERE existing_days.tag IS NULL\r\n)\r\nSELECT * FROM existing_days UNION ALL SELECT * FROM not_exisiting_days\r\nORDER by tag),\r\n\r\nselected_comparison_platform AS(\r\nWITH all_days AS(\r\n  SELECT tag FROM UNNEST(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']) AS tag\r\n),\r\nexisting_days AS(\r\nSELECT getDayByDate(EXTRACT(DATE from time)) as tag, $VergleicsplattformInteraktionen as Interaktionen FROM Quintly.${Vorhersagevergleichsplattform}\r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND profileId = $VergleichsprofileID\r\nGROUP BY tag\r\nORDER BY tag ASC),\r\nnot_exisiting_days AS(\r\n   SELECT all_days.tag as tag, 0 as Interaktionen\r\n  FROM all_days\r\n  LEFT JOIN existing_days ON all_days.tag = existing_days.tag\r\n  WHERE existing_days.tag IS NULL\r\n)\r\nSELECT * FROM existing_days UNION ALL SELECT * FROM not_exisiting_days\r\nORDER by tag)\r\n\r\n\r\nSELECT getDayInGerman(selected_platform.tag) as tag, Interaktionen,COALESCE(VergleichsInteraktionen,0)  as VergleichsInteraktionen,\r\n\"${Vergleichsplattform}\" as Vergleichsplatform, \"${Plattform}\" as platform FROM selected_platform\r\nLEFT JOIN (SELECT tag, Interaktionen as VergleichsInteraktionen FROM selected_comparison_platform) AS selected_comparison_platform\r\nON selected_platform.tag = selected_comparison_platform.tag\r\nORDER BY getDayAsNumber(selected_comparison_platform.tag)"
      }
     ]
    },
    {
     "title": "Durchschnettliche Interaktionen pro Wochentag | ${Plattform}",
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 9, "w": 10, "x": 2, "y": 36 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "CREATE TEMP FUNCTION getDayByDate(datum DATE)\r\nRETURNS STRING\r\nDETERMINISTIC\r\nLANGUAGE js\r\nAS r\"\"\"\r\nvar jsDatum = new Date(datum);\r\nvar day = jsDatum.getUTCDay();\r\nvar days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];\r\nreturn days[day];\r\n\"\"\";\r\n\r\nCREATE TEMP FUNCTION getDayAsNumber(tag STRING)\r\nRETURNS INT64\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nvar days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];\r\nreturn days.indexOf(tag)\r\n\"\"\";\r\n\r\nCREATE TEMP FUNCTION getDayInGerman(tag STRING)\r\nRETURNS STRING\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nconst dayMap = {\r\n        'Sunday': 'Sonntag',\r\n        'Monday': 'Montag',\r\n        'Tuesday': 'Dienstag',\r\n        'Wednesday': 'Mittwoch',\r\n        'Thursday': 'Donnerstag',\r\n        'Friday': 'Freitag',\r\n        'Saturday': 'Samstag'};\r\nreturn dayMap[tag]\r\n\"\"\";\r\n\r\nWITH selected_platform AS(\r\nWITH all_days AS(\r\n  SELECT tag FROM UNNEST(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']) AS tag\r\n),\r\nexisting_days AS(\r\nSELECT getDayByDate(EXTRACT(DATE from time)) as tag, ROUND($PlattformInteraktionen/$NumberOfWeeks) as Interaktionen FROM Quintly.${Vorhersagemodel}\r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND  profileId = $profileID\r\nGROUP BY tag\r\nORDER BY tag ASC),\r\nnot_exisiting_days AS(\r\n   SELECT all_days.tag as tag, 0 as Interaktionen\r\n  FROM all_days\r\n  LEFT JOIN existing_days ON all_days.tag = existing_days.tag\r\n  WHERE existing_days.tag IS NULL\r\n)\r\nSELECT * FROM existing_days UNION ALL SELECT * FROM not_exisiting_days\r\nORDER by tag)\r\nSELECT getDayInGerman(selected_platform.tag) as tag, Interaktionen FROM selected_platform\r\nORDER BY getDayAsNumber(selected_platform.tag) ASC"
      }
     ]
    },
    {
     "title": "Durchschnettliche Interaktionen pro Wochentag | ${Vergleichsplattform}",
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 9, "w": 10, "x": 12, "y": 36 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "CREATE TEMP FUNCTION getDayByDate(datum DATE)\r\nRETURNS STRING\r\nDETERMINISTIC\r\nLANGUAGE js\r\nAS r\"\"\"\r\nvar jsDatum = new Date(datum);\r\nvar day = jsDatum.getUTCDay();\r\nvar days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];\r\nreturn days[day];\r\n\"\"\";\r\n\r\nCREATE TEMP FUNCTION getDayAsNumber(tag STRING)\r\nRETURNS INT64\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nvar days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];\r\nreturn days.indexOf(tag)\r\n\"\"\";\r\n\r\nCREATE TEMP FUNCTION getDayInGerman(tag STRING)\r\nRETURNS STRING\r\nDETERMINISTIC \r\nLANGUAGE js\r\nAS r\"\"\"\r\nconst dayMap = {\r\n        'Sunday': 'Sonntag',\r\n        'Monday': 'Montag',\r\n        'Tuesday': 'Dienstag',\r\n        'Wednesday': 'Mittwoch',\r\n        'Thursday': 'Donnerstag',\r\n        'Friday': 'Freitag',\r\n        'Saturday': 'Samstag'};\r\nreturn dayMap[tag]\r\n\"\"\";\r\n\r\nWITH selected_platform AS(\r\nWITH all_days AS(\r\n  SELECT tag FROM UNNEST(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']) AS tag\r\n),\r\nexisting_days AS(\r\nSELECT getDayByDate(EXTRACT(DATE from time)) as tag, ROUND($VergleicsplattformInteraktionen/$NumberOfWeeks) as Interaktionen FROM Quintly.${Vorhersagevergleichsplattform}\r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND  profileId = $VergleichsprofileID\r\nGROUP BY tag\r\nORDER BY tag ASC),\r\nnot_exisiting_days AS(\r\n   SELECT all_days.tag as tag, \r\n   CASE \"${Vergleichsplattform}\"\r\n   WHEN \"\" THEN CAST(NULL as INT64)\r\n   ELSE 0 END as Interaktionen\r\n  FROM all_days\r\n  LEFT JOIN existing_days ON all_days.tag = existing_days.tag\r\n  WHERE existing_days.tag IS NULL\r\n)\r\nSELECT * FROM existing_days UNION ALL SELECT * FROM not_exisiting_days\r\nORDER by tag)\r\nSELECT getDayInGerman(selected_platform.tag) as tag, Interaktionen FROM selected_platform\r\nORDER BY getDayAsNumber(selected_platform.tag) ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Vorhersage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Followers Vorhersage | $Plattform",
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "SELECT * FROM\r\n(SELECT DATE(forecast_timestamp) as Datum, forecast_value as Vorhersage, prediction_interval_lower_bound as Unterschranke\r\n, prediction_interval_upper_bound as Oberschranke  FROM ML.FORECAST(MODEL `ndr-code-bi-dashboard.Quintly.arimaModel_${Vorhersagemodel}_${profileID}`,STRUCT($Vorhersagezeitraum AS horizon),\r\n(  SELECT\r\n      EXTRACT(DATE from time) as datum, * EXCEPT(`time`)\r\n    FROM (\r\n    SELECT * EXCEPT($PlattformFollowersVorhersageExceptList) FROM `Quintly.${Vorhersagemodel}`\r\n     WHERE EXTRACT(date from time) < \"$heute\"\r\n    AND profileId = $profileID\r\n)))) AS predicted_data\r\nLEFT JOIN (SELECT DATE_ADD(EXTRACT(date from time), INTERVAL $Vorhersagezeitraum DAY) as Datum, $PlattformFollowersField as page_follows, EXTRACT(date from time) as EchtesDatum\r\nFROM `Quintly.${Vorhersagemodel}` \r\nWHERE EXTRACT(date from time) > \"$Zeitraum\" AND profileId = $profileID AND $PlattformFollowersField IS NOT NULL\r\nORDER BY datum DESC) AS real_data\r\nON real_data.datum = predicted_data.datum"
      }
     ]
    },
    {
     "title": "Followers Vorhersage | $Vergleichsplattform",
     "type": "volkovlabs-echarts-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "location": "europe-west3",
       "project": "ndr-code-bi-dashboard",
       "rawSql": "WITH available_vergleichsplattform AS (\r\nSELECT predicted_data.Datum, Vorhersage, Unterschranke, Oberschranke, page_follows, EchtesDatum FROM\r\n(SELECT DATE(forecast_timestamp) as Datum, forecast_value as Vorhersage, prediction_interval_lower_bound as Unterschranke\r\n, prediction_interval_upper_bound as Oberschranke  FROM ML.FORECAST(MODEL `ndr-code-bi-dashboard.Quintly.arimaModel_${Vorhersagevergleichsplattform}_${VorhersageVergleichsprofileID}`,STRUCT($Vorhersagezeitraum AS horizon),\r\n(  SELECT\r\n      EXTRACT(DATE from time) as datum, * EXCEPT(`time`)\r\n    FROM (\r\n    SELECT * EXCEPT($VergleichsPlattformFollowersVorhersageExceptList) FROM `Quintly.${Vorhersagevergleichsplattform}`\r\n     WHERE EXTRACT(date from time) < \"$heute\"\r\n    AND profileId = $VorhersageVergleichsprofileID\r\n)))) AS predicted_data\r\nLEFT JOIN (SELECT DATE_ADD(EXTRACT(date from time), INTERVAL $Vorhersagezeitraum DAY) as Datum, $VergleichsPlattformFollowersField as page_follows, EXTRACT(date from time) as EchtesDatum\r\nFROM `Quintly.${Vorhersagevergleichsplattform}` \r\nWHERE EXTRACT(date from time) > \"$VorhersageVergleichsPlattformZeitraum\" AND profileId = $VorhersageVergleichsprofileID AND $VergleichsPlattformFollowersField IS NOT NULL\r\nORDER BY datum DESC) AS real_data\r\nON real_data.datum = predicted_data.datum),\r\nnone_data AS(\r\n   SELECT \r\n    CAST(NULL AS DATE) AS Datum,\r\n    CAST(NULL AS FLOAT64) AS Vorhersage,\r\n    CAST(NULL AS FLOAT64) AS Unterschranke,\r\n    CAST(NULL AS FLOAT64) AS Oberschranke,\r\n    CAST(NULL AS INT64) AS page_follows,\r\n    CAST(NULL AS DATE) AS EchtesDatum\r\n)\r\nSELECT\r\nCASE \r\n    WHEN \"${Vergleichsplattform}\" = \"\" THEN nd.Datum\r\n    ELSE av.Datum\r\nEND AS Datum,\r\nCASE \r\n    WHEN \"${Vergleichsplattform}\" = \"\" THEN nd.Vorhersage\r\n    ELSE av.Vorhersage\r\nEND AS Vorhersage,\r\nCASE \r\n    WHEN \"${Vergleichsplattform}\" = \"\" THEN nd.Unterschranke\r\n    ELSE av.Unterschranke\r\nEND AS Unterschranke,\r\nCASE \r\n    WHEN \"${Vergleichsplattform}\" = \"\" THEN nd.Oberschranke\r\n    ELSE av.Oberschranke\r\nEND AS Oberschranke,\r\nCASE \r\n    WHEN \"${Vergleichsplattform}\" = \"\" THEN nd.page_follows\r\n    ELSE av.page_follows\r\nEND AS page_follows,\r\nCASE \r\n    WHEN \"${Vergleichsplattform}\" = \"\" THEN nd.EchtesDatum\r\n    ELSE av.EchtesDatum\r\nEND AS EchtesDatum,\r\nFROM available_vergleichsplattform av, none_data nd\r\n"
      }
     ]
    }
   ]
  }
 ]
}