{
 "title": "Operations Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "NDR Articles Row Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Timestamp(date), COUNT(*) FROM `ndr-code-bi-dashboard.Piano.NDR_articles` GROUP BY date "
    }
   ]
  },
  {
   "title": "NDR Total Visits Row Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Timestamp(date), COUNT(*) FROM `ndr-code-bi-dashboard.Piano.NDR_total_visits` GROUP BY date "
    }
   ]
  },
  {
   "title": "NDR Articles Row Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Timestamp(date), COUNT(*) FROM `ndr-code-bi-dashboard.Piano.MDR_articles` GROUP BY date "
    }
   ]
  },
  {
   "title": "MDR Total Visits Row Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "Piano",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT Timestamp(date), COUNT(*) FROM `ndr-code-bi-dashboard.Piano.MDR_total_visits` GROUP BY date "
    }
   ]
  }
 ]
}