{
 "title": "Google Trends All Sections",
 "tags": [ "Google Trends" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": "<font size=\"8\" style=\"color:rgb(255, 0, 0);\">Google Trends</font><font size=\"8\"></font>"
   }
  },
  {
   "title": "Google Trends | Echtzeit | Schlagzeilen",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Suchtrends des Tages | gestern",
   "type": "table",
   "gridPos": { "h": 30, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT\n  *\nFROM\n  `ndr-code-bi-dashboard.GoogleTrends.search_trends_daily`\n\n--timestamp = DATE_SUB(CURRENT_DATE(), INTERVAL 0 DAY) \nWHERE CAST(timestamp as date) = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) \n--DATE_SUB(CURRENT_DATE()\\, INTERVAL  1 DAY),\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Business",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Sport",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Unterhaltung",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trend | Echtzeit | Wissen & Technik",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 47 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n--  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  },
  {
   "title": "Google Trends | Echtzeit | Gesundheit",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 58 },
   "targets": [
    {
     "dataset": "GoogleTrends",
     "location": "EU",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT * \nFROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean` \nWHERE \n--  category ='Business'\n--  category = 'Headlines'\n--  category = 'Science_Tech'\n--  category = 'Sport'\n--  category = 'Entertainment'\n  category = 'Health'\nAND tmstp = \n  (SELECT MAX(tmstp) \n  FROM `ndr-code-bi-dashboard.GoogleTrends.realtime_trends_clean`)\nORDER BY rank"
    }
   ]
  }
 ]
}