{
 "title": "Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LRA",
    "query": {}
   },
   {
    "name": "Kategorie",
    "query": {}
   },
   { "name": "filled_size", "query": "20" },
   {
    "name": "lastUpdate",
    "query": {}
   },
   {
    "name": "Image",
    "query": {}
   },
   {
    "name": "zeitfilter",
    "query": {}
   },
   {
    "name": "lastUpdate_tenth_minute",
    "query": {}
   },
   {
    "name": "zeitfilter_tenth_minute_piano",
    "query": {}
   },
   {
    "name": "date_from_tmstp",
    "query": {}
   },
   {
    "name": "zeitfilter_tenth_minute_telemedienampel",
    "query": {}
   },
   {
    "name": "second_zeitfilter_tenth_minute_telemedienampel",
    "query": {}
   },
   {
    "name": "telemedienampel_correct",
    "query": {}
   },
   {
    "name": "second_telemedienampel_correct",
    "query": {}
   },
   {
    "name": "telemedienampel_wrong",
    "query": {}
   },
   {
    "name": "second_telemedienampel_wrong",
    "query": {}
   },
   {
    "name": "Zehn_Minuten_Kategorie",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "\n\n<img width=\"160\" height=\"auto\" src=\"$Image\n\" />\n\n<!-- src=${Image} />"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "options": {
    "content": "### Letztes Update:\r\n###### Datumsbasierter Vergleich - ${lastUpdate}\r\n###### Intervallbasierter Vergleich - ${lastUpdate_tenth_minute}"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  post_video_view_time\nFROM facebookinsightsownposts\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Übersicht - Datumsbasierter Vergleich  | ${LRA} - ${Kategorie}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \nCOUNT(*) AS summe\nFROM Monitoring.monitoring_bigquery_tables_daily\nWHERE\n\"$LRA\" = LRA\nAND DATETIME(tmstp) = \"$zeitfilter\"\nAND\nCASE\nWHEN REPLACE(\"$Kategorie\",\"'\", \"\") IN (\"Alle Kategorien\") THEN TRUE\nELSE  category IN ($Kategorie) END\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \nCOUNT(*) AS summe\nFROM Monitoring.monitoring_bigquery_tables_daily\nWHERE\n\"$LRA\" = LRA\nAND\nDATETIME(tmstp) = \"$zeitfilter\"\nAND\nCASE\nWHEN REPLACE(\"$Kategorie\",\"'\", \"\") IN (\"Alle Kategorien\") THEN TRUE\nELSE  category IN ($Kategorie)  END\nAND\nCASE\nWHEN \"Social Media\" = category THEN max_date < expected_date\nWHEN \"Telemedienampel\" = category THEN max_date < expected_date\nELSE max_date != expected_date END\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \nCOUNT(*) AS summe\nFROM Monitoring.monitoring_bigquery_tables_daily\nWHERE\n\"$LRA\" = LRA\nAND\nDATETIME(tmstp) = \"$zeitfilter\"\nAND\nCASE\nWHEN REPLACE(\"$Kategorie\",\"'\", \"\") IN (\"Alle Kategorien\") THEN TRUE\nELSE  category IN ($Kategorie)  END\nAND\nCASE\nWHEN \"Social Media\" = category THEN max_date >= expected_date\nWHEN \"Telemedienampel\" = category THEN max_date >= expected_date\nELSE max_date = expected_date END\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH correct AS (\n  SELECT \nCOUNT(*) AS correct_sum\nFROM Monitoring.monitoring_bigquery_tables_daily\nWHERE\n\"$LRA\" = LRA\nAND\nCASE\nWHEN REPLACE(\"$Kategorie\",\"'\", \"\") IN (\"Alle Kategorien\") THEN TRUE\nELSE  category IN ($Kategorie)  END\nAND\nDATETIME(tmstp) = \"$zeitfilter\"\nAND\nCASE\nWHEN \"Social Media\" = category THEN max_date >= expected_date\nWHEN \"Telemedienampel\" = category THEN max_date >= expected_date\nELSE max_date = expected_date END\n), wrong AS(\n  SELECT \nCOUNT(*) AS wrong_sum\nFROM Monitoring.monitoring_bigquery_tables_daily\nWHERE\n\"$LRA\" = LRA\nAND\nDATETIME(tmstp) = \"$zeitfilter\"\nAND\nCASE\nWHEN REPLACE(\"$Kategorie\",\"'\", \"\") IN (\"Alle Kategorien\") THEN TRUE\nELSE  category IN ($Kategorie)  END\nAND\nCASE\nWHEN \"Social Media\" = category THEN max_date < expected_date\nWHEN \"Telemedienampel\" = category THEN max_date < expected_date\nELSE max_date != expected_date END\n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT 100 * (correct_sum / (correct_sum + wrong_sum)) AS summe FROM correct, wrong\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "title": "Heatmap Verlauf | ${LRA} - ${Kategorie}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 17 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH correct AS (\r\n  SELECT \r\n    COUNT(*) AS correct_sum,\r\n    DATE(tmstp) AS date,\r\n    EXTRACT(HOUR FROM tmstp) AS hour\r\n  FROM Monitoring.monitoring_bigquery_tables_daily\r\n  WHERE\r\n    \"$LRA\" = LRA\r\n    AND\r\n    CASE\r\n      WHEN REPLACE(\"$Kategorie\",\"'\", \"\") IN (\"Alle Kategorien\") THEN TRUE\r\n      ELSE category IN ($Kategorie)\r\n    END\r\n    AND\r\n    CASE\r\n      WHEN \"Social Media\" = category THEN max_date >= expected_date\r\n      WHEN \"Telemedienampel\" = category THEN max_date >= expected_date\r\n      ELSE max_date = expected_date \r\n    END\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY) AND CURRENT_DATE\r\n  GROUP BY date, hour\r\n), wrong AS (\r\n  SELECT \r\n    COUNT(*) AS wrong_sum,\r\n    DATE(tmstp) AS date,\r\n    EXTRACT(HOUR FROM tmstp) AS hour\r\n  FROM Monitoring.monitoring_bigquery_tables_daily\r\n  WHERE\r\n    \"$LRA\" = LRA\r\n    AND\r\n    CASE\r\n      WHEN REPLACE(\"$Kategorie\",\"'\", \"\") IN (\"Alle Kategorien\") THEN TRUE\r\n      ELSE category IN ($Kategorie)\r\n    END\r\n    AND\r\n    CASE\r\n      WHEN \"Social Media\" = category THEN max_date < expected_date\r\n      WHEN \"Telemedienampel\" = category THEN max_date < expected_date\r\n      ELSE max_date != expected_date \r\n    END\r\n    AND DATE(tmstp) BETWEEN DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY) AND CURRENT_DATE\r\n  GROUP BY date, hour\r\n)\r\nSELECT \r\n  date,\r\n  hour,\r\n  IFNULL(correct_sum, 0) AS correct_sum,\r\n  IFNULL(wrong_sum, 0) AS wrong_sum\r\nFROM correct\r\nFULL JOIN wrong\r\nUSING (date, hour)\r\nORDER BY date, hour ASC;\r\n"
    }
   ]
  },
  {
   "title": "Übersicht aller Tabellen | ${LRA} - ${Kategorie}",
   "type": "table",
   "gridPos": { "h": 19, "w": 19, "x": 0, "y": 30 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\ntable_name,\r\ncategory,\r\nCASE \r\nWHEN EXTRACT(YEAR FROM max_date) = 1900 THEN \"Datum ist älter als 5 Tage\"\r\nELSE FORMAT_DATE(\"%d.%m.%y\",DATE(max_date)) END AS max_date, \r\nFORMAT_DATE(\"%d.%m.%y\",DATE(expected_date)) as expected_date,\r\nCASE\r\nWHEN \"Social Media\" = category OR category = \"Telemedienampel\" THEN\r\nCASE\r\nWHEN max_date >= expected_date THEN TRUE\r\nELSE FALSE END \r\nELSE\r\nCASE\r\nWHEN max_date = expected_date THEN TRUE\r\nELSE FALSE END\r\nEND as vergleich\r\nFROM Monitoring.monitoring_bigquery_tables_daily\r\nWHERE \r\n\"$LRA\" = LRA \r\nAND \r\nDATETIME(tmstp) = \"$zeitfilter\"\r\nAND\r\nCASE\r\nWHEN REPLACE(\"$Kategorie\",\"'\", \"\") IN (\"Alle Kategorien\") THEN TRUE\r\nELSE  category IN ($Kategorie)  END\r\nORDER BY table_name ASC"
    }
   ]
  },
  {
   "title": "Übersicht - Intervallbasierter Vergleich | ${LRA}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \nCOUNT(*) AS summe\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\nWHERE\n\"$LRA\" = LRA\nAND\nCASE category\nWHEN \"ATI\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_piano\"\nWHEN \"Telemedienampel\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_telemedienampel\"\nEND\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \nCOUNT(*) AS summe\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\nWHERE\n\"$LRA\" = LRA\nAND\nCASE category\nWHEN \"ATI\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_piano\"\nWHEN \"Telemedienampel\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_telemedienampel\"\nEND\nAND\nNOT (max_date BETWEEN lower_bound_date AND upper_bound_date) \n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\nSELECT \nCOUNT(*) AS summe\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\nWHERE\n\"$LRA\" = LRA\nAND\nCASE category\nWHEN \"ATI\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_piano\"\nWHEN \"Telemedienampel\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_telemedienampel\"\nEND\nAND\nmax_date BETWEEN lower_bound_date AND upper_bound_date\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH correct AS (\n  SELECT \nCOUNT(*) AS correct_sum\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\nWHERE\n\"$LRA\" = LRA\nAND\nCASE category\nWHEN \"ATI\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_piano\"\nWHEN \"Telemedienampel\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_telemedienampel\"\nEND\nAND\nmax_date BETWEEN lower_bound_date AND upper_bound_date\n), wrong AS(\n  SELECT \nCOUNT(*) AS wrong_sum\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\nWHERE\n\"$LRA\" = LRA\nAND\nCASE category\nWHEN \"ATI\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_piano\"\nWHEN \"Telemedienampel\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_telemedienampel\"\nEND\nAND\nNOT (max_date BETWEEN lower_bound_date AND upper_bound_date) \n)\nSELECT  CONCAT(REPEAT(\" \", $filled_size - CHAR_LENGTH(CAST(summe as STRING))), REPLACE(CAST(FORMAT(\"%'.0f\", CAST(ROUND(summe) as NUMERIC)) AS STRING), \",\", \".\"))FROM\n(\n  SELECT 100 * (correct_sum / (correct_sum + wrong_sum)) AS summe FROM correct, wrong\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "Quintly",
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \"\""
    }
   ]
  },
  {
   "title": "Heatmap Verlauf | ${LRA} | ${date_from_tmstp}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 58 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH piano_correct AS (\r\n  SELECT\r\nDATETIME(tmstp, \"Europe/Berlin\") as tmstp_dt, \r\nCOUNT(*) AS correct_sum\r\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\r\nWHERE\r\n\"$LRA\" = LRA\r\nAND\r\ntmstp BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 70 MINUTE) AND CURRENT_TIMESTAMP()\r\nAND\r\nmax_date BETWEEN lower_bound_date AND upper_bound_date\r\nGROUP BY tmstp_dt\r\n), piano_wrong AS (\r\n  SELECT\r\nDATETIME(tmstp, \"Europe/Berlin\") as tmstp_dt, \r\nCOUNT(*) AS wrong_sum\r\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\r\nWHERE\r\n\"$LRA\" = LRA\r\nAND\r\ntmstp BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 70 MINUTE) AND CURRENT_TIMESTAMP()\r\nAND\r\nNOT (max_date BETWEEN lower_bound_date AND upper_bound_date)\r\nGROUP BY tmstp_dt\r\n)\r\nSELECT \r\n  FORMAT_TIMESTAMP('%H:%M',tmstp_dt) as date, --%d.%m.%y \r\n  CASE\r\n  WHEN EXTRACT(MINUTE from tmstp_dt) = 8 THEN IFNULL(correct_sum,0)\r\n  WHEN tmstp_dt > DATETIME(\"$zeitfilter_tenth_minute_telemedienampel\",\"Europe/Berlin\") THEN IFNULL(correct_sum, 0) + $telemedienampel_correct\r\n  WHEN tmstp_dt < DATETIME(\"$zeitfilter_tenth_minute_telemedienampel\",\"Europe/Berlin\") THEN IFNULL(correct_sum,0) + $second_telemedienampel_correct END AS correct_sum,\r\n  CASE\r\n  WHEN EXTRACT(MINUTE from tmstp_dt) = 8 THEN IFNULL(wrong_sum,0)\r\n  WHEN tmstp_dt > DATETIME(\"$zeitfilter_tenth_minute_telemedienampel\",\"Europe/Berlin\") THEN IFNULL(wrong_sum, 0) + $telemedienampel_wrong\r\n  WHEN tmstp_dt < DATETIME(\"$zeitfilter_tenth_minute_telemedienampel\",\"Europe/Berlin\") THEN IFNULL(wrong_sum,0) + $second_telemedienampel_wrong END AS wrong_sum\r\nFROM piano_correct\r\nFULL JOIN piano_wrong\r\nUSING (tmstp_dt)\r\nORDER BY tmstp_dt ASC;\r\n"
    }
   ]
  },
  {
   "title": "Übersicht aller fehlerhaften Tabellen im Heatmap | ${LRA} | ${date_from_tmstp}",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 58 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT table_name, tmstp_dt FROM(\r\nSELECT\r\nFORMAT_TIMESTAMP('%d.%m.%y %H:%M',DATETIME(tmstp, \"Europe/Berlin\")) as tmstp_dt,\r\ntable_name, \r\nCOUNT(*) AS wrong_sum\r\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\r\nWHERE\r\n\"$LRA\" = LRA\r\nAND\r\ntmstp BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 70 MINUTE) AND CURRENT_TIMESTAMP()\r\nAND\r\nNOT (max_date BETWEEN lower_bound_date AND upper_bound_date)\r\nGROUP BY tmstp_dt, table_name)\r\nWHERE wrong_sum != 0\r\nORDER BY tmstp_dt ASC"
    }
   ]
  },
  {
   "title": "Übersicht aller Tabellen | ${LRA}",
   "type": "table",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 71 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "SELECT \r\ntable_name,\r\ncategory,\r\nFORMAT_TIMESTAMP('%d.%m.%y %H:%M',DATETIME(max_date, \"Europe/Berlin\")) as max_date,\r\nFORMAT_TIMESTAMP('%d.%m.%y %H:%M',DATETIME(lower_bound_date, \"Europe/Berlin\")) as lower_bound_date,\r\nFORMAT_TIMESTAMP('%d.%m.%y %H:%M',DATETIME(upper_bound_date, \"Europe/Berlin\")) as upper_bound_date,\r\nCASE \r\nWHEN max_date BETWEEN lower_bound_date AND upper_bound_date THEN TRUE\r\nELSE FALSE END as Vergleich\r\nFROM Monitoring.monitoring_bigquery_tables_tenth_minute\r\nWHERE\r\n\"$LRA\" = LRA\r\nAND\r\nCASE category\r\nWHEN \"ATI\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_piano\"\r\nWHEN \"Telemedienampel\" THEN DATETIME(tmstp) = \"$zeitfilter_tenth_minute_telemedienampel\"\r\nEND\r\nORDER BY table_name ASC"
    }
   ]
  },
  {
   "title": "Übersicht alle Kategorien  | ${LRA} ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }
  },
  {
   "title": "${LRA}  | Übersicht aller korrekter und fehlerhafter Tabellen unterteilt nach den Kategorien",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 9, "x": 8, "y": 86 },
   "targets": [
    {
     "location": "europe-west3",
     "project": "ndr-code-bi-dashboard",
     "rawSql": "WITH correct AS(\r\n  SELECT \r\n  category,\r\nCOUNT(*) AS correct_sum\r\nFROM Monitoring.monitoring_bigquery_tables_daily\r\nWHERE\r\n\"$LRA\" = LRA\r\nAND\r\nDATETIME(tmstp) = \"$zeitfilter\"\r\nAND\r\nCASE\r\nWHEN \"Social Media\" = category THEN max_date >= expected_date\r\nWHEN \"Telemedienampel\" = category THEN max_date >= expected_date\r\nELSE max_date = expected_date END\r\nGROUP BY category\r\n),\r\nwrong AS(\r\n  SELECT \r\n  category,\r\nCOUNT(*) AS wrong_sum\r\nFROM Monitoring.monitoring_bigquery_tables_daily\r\nWHERE\r\n\"$LRA\" = LRA\r\nAND\r\nDATETIME(tmstp) = \"$zeitfilter\"\r\nAND\r\nCASE\r\nWHEN \"Social Media\" = category THEN max_date < expected_date\r\nWHEN \"Telemedienampel\" = category THEN max_date < expected_date\r\nELSE max_date != expected_date END\r\nGROUP BY category\r\n)\r\nSELECT category, IFNULL(correct_sum,0) + IFNULL(wrong_sum,0) AS summe, IFNULL(correct_sum,0) AS correct_sum, IFNULL(wrong_sum,0) AS wrong_sum\r\nFROM correct\r\nFULL JOIN wrong\r\nUSING (category)\r\nORDER BY category ASC"
    }
   ]
  },
  { "title": "APIs Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Piano API-Status",
   "type": "text",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 103 },
   "options": {
    "content": "<iframe id=\"embeddedFrame\" src=\"https://piano.statuspage.io/\" width=\"100%\"> </iframe>\n<script>\nvar iframe = document.getElementById(\"embeddedFrame\");\n\n    function setIframeHeight() {\n        iframe.style.height = iframe.parentElement.offsetHeight-5 + \"px\";\n    }\n\n    // Call setIframeHeight when the iframe content is loaded\n    iframe.onload = setIframeHeight;\n\n    // Also, call setIframeHeight when the window is resized\n    window.addEventListener(\"resize\", setIframeHeight);\n</script>"
   }
  },
  {
   "title": "Quintly API-Status",
   "type": "text",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 103 },
   "options": {
    "content": "<script>\n// Define the iframe element\nvar iframe = document.getElementById(\"embeddedFrame\");\n\nfunction setIframeHeight() {\n    // Check if iframe and parent element exist\n    if (iframe && iframe.parentElement) {\n        // Set the iframe height to the parent's height\n        iframe.style.height = iframe.parentElement.offsetHeight + \"px\";\n    }\n}\n\n// Set iframe height when content is loaded and when window is resized\niframe.onload = setIframeHeight;\nwindow.addEventListener(\"resize\", setIframeHeight);\n</script>\n\n<iframe id=\"embeddedFrame\" src=\"https://status.quintly.com/\" width=\"100%\"></iframe>\n\n<style>\n#embeddedFrame {\n    border: none;\n    display: block;\n    width: 100%;\n    height: 100%;\n}\n</style>\n"
   }
  },
  {
   "title": "Elastic API-Status",
   "type": "text",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 103 },
   "options": {
    "content": "<iframe id=\"embeddedFrame\" src=\"https://status.elastic.co/\" width=\"100%\"> </iframe>\n<script>\nvar iframe = document.getElementById(\"embeddedFrame\");\n\n    function setIframeHeight() {\n        iframe.style.height = iframe.parentElement.offsetHeight-5 + \"px\";\n    }\n\n    // Call setIframeHeight when the iframe content is loaded\n    iframe.onload = setIframeHeight;\n\n    // Also, call setIframeHeight when the window is resized\n    window.addEventListener(\"resize\", setIframeHeight);\n</script>\n\n<style>\n#embeddedFrame {\n    border: none;\n    display: block;\n    width: 100%;\n    height: 100%;\n}\n</style>"
   }
  }
 ]
}